superseriousbusiness/gotosocial

- internal/apimodule/account/accountcreate_test.go
- internal/apimodule/account/accountupdate_test.go
- internal/apimodule/account/accountverify_test.go
- internal/apimodule/admin/admin.go
- internal/apimodule/app/app_test.go
- internal/apimodule/auth/auth.go
- internal/apimodule/auth/auth_test.go
- internal/apimodule/fileserver/fileserver.go
- internal/apimodule/fileserver/servefile_test.go
- internal/apimodule/media/mediacreate_test.go
- internal/apimodule/status/status.go
- internal/apimodule/status/statuscreate_test.go
- internal/apimodule/status/statusfave_test.go
- internal/apimodule/status/statusfavedby_test.go
- internal/apimodule/status/statusget_test.go
- internal/apimodule/status/statusreblog.go
- internal/apimodule/status/statusreblog_test.go
- internal/apimodule/status/statusunfave_test.go
- internal/db/gtsmodel/status.go
- internal/mastotypes/converter.go
- testrig/testmodels.go
This PR adds
* Boosting/reblogging statuses
* Tests for the above
> Status Boost

- cmd/gotosocial/main.go
- internal/config/config.go
- internal/config/default.go
- internal/config/letsencrypt.go
- internal/gotosocial/actions.go
- internal/router/router.go
Add letsencrypt support for automatic https certificate generation.
Tested and working.
> Letsencrypt

- internal/api/client/auth/middleware.go
- internal/api/client/timeline/home.go
- internal/api/client/timeline/timeline.go
- internal/db/db.go
- internal/db/pg/pg.go
- internal/gotosocial/actions.go
- internal/message/fediprocess.go
- internal/message/fromcommonprocess.go
- internal/message/frprocess.go
- internal/message/processor.go
- internal/message/timelineprocess.go
- internal/typeutils/astointernal.go
- internal/typeutils/internaltoas.go
- internal/typeutils/internaltofrontend.go
Add a very basic implementation of a home timeline so we stop 404-ing when doing /api/v1/timelines/home
> Home timeline

- internal/api/client/instance/instance.go
- internal/api/client/instance/instancepatch.go
- internal/api/model/admin.go
- internal/api/model/instance.go
- internal/db/db.go
- internal/db/pg/instancestats.go
- internal/gtsmodel/instance.go
- internal/processing/instance.go
- internal/processing/processor.go
- internal/typeutils/internaltofrontend.go
- internal/util/regexes.go
- internal/util/validation.go
- web/template/footer.tmpl
- web/template/index.tmpl
Allow admins to set instance settings through a PATCH to /api/v1/instance
Update templates to reflect some of the new fields
> Instance settings updates

- internal/api/client/status/statuscreate_test.go
- internal/text/common.go
- internal/text/formatter.go
- internal/text/formatter_test.go
- internal/text/link.go
- internal/text/link_test.go
- internal/text/markdown.go
- internal/text/plain.go
- internal/text/plain_test.go
- internal/text/sanitize.go
- internal/util/regexes.go
- internal/util/statustools.go
- internal/util/statustools_test.go
- internal/util/validation_test.go
- testrig/testmodels.go
This PR fixes up a couple of bugs in the text parsing regular expressions, and also fixes up some behavior where link parsing and tag parsing were clashing, leading to nested hrefs
> Link hashtag bug

- internal/federation/dereference.go
- internal/federation/dereferencing/account.go
- internal/federation/federator.go
- internal/processing/account/get.go
- internal/timeline/get.go
- internal/timeline/index.go
- internal/timeline/timeline.go
Fix two annoying bugs:
1. Fix a bug where avatar + header were not showing when viewing an account, by adding some last-minute dereferencing in the account get handler.
2. Fix a bug where the database was getting stuck in a loop and eating loads of cpu, by adding some maximum retries behavior in the recursive loops in the timeline functionality.
> Bugfixerino

- go.mod
- go.sum
- vendor/github.com/uptrace/bun/CHANGELOG.md
- vendor/github.com/uptrace/bun/commitlint.config.js
- vendor/github.com/uptrace/bun/package.json
- vendor/github.com/uptrace/bun/query_table_create.go
- vendor/github.com/uptrace/bun/schema/table.go
- vendor/github.com/uptrace/bun/schema/zerochecker.go
- vendor/github.com/uptrace/bun/version.go
- vendor/modules.txt
Fixes our status.URI + status.ID uniqueness issue
this will probably need a database migration / wipe...
> update bun library to latest commit

- .drone.yml
- Dockerfile
go => `1.17.1-alpine3.14`
alpine => `3.14`
node => `16.9.0-alpine3.14`
> update container versions

- internal/ap/extract_test.go
- internal/ap/extractattachments_test.go
- internal/ap/extractmentions_test.go
- internal/federation/dereference.go
- internal/federation/dereferencing/announce.go
- internal/federation/dereferencing/dereferencer.go
- internal/federation/dereferencing/status.go
- internal/federation/dereferencing/status_test.go
- internal/federation/dereferencing/thread.go
- internal/federation/federator.go
- internal/processing/fromfederator.go
- internal/processing/fromfederator_test.go
- internal/processing/search.go
- internal/typeutils/astointernal_test.go
- internal/typeutils/converter_test.go
This PR fixes a little bug where notifications were not being created for new mentions, and also adds some tests for parsing mentions and creating notifications.
Closes https://github.com/superseriousbusiness/gotosocial/issues/215
> Fix mentions not notifying

- internal/api/security/useragentblock.go
This PR removes the hardcoded friendica user agent block.
See https://github.com/superseriousbusiness/gotosocial/issues/169
> remove hardcoded friendica user agent block

- go.mod
- go.sum
- vendor/github.com/uptrace/bun/CHANGELOG.md
- vendor/github.com/uptrace/bun/Makefile
- vendor/github.com/uptrace/bun/README.md
- vendor/github.com/uptrace/bun/db.go
- vendor/github.com/uptrace/bun/dialect/append.go
- vendor/github.com/uptrace/bun/hook.go
- vendor/github.com/uptrace/bun/migrate/migration.go
- vendor/github.com/uptrace/bun/model_table_struct.go
- vendor/github.com/uptrace/bun/package.json
- vendor/github.com/uptrace/bun/query_delete.go
- vendor/github.com/uptrace/bun/query_insert.go
- vendor/github.com/uptrace/bun/query_select.go
- vendor/github.com/uptrace/bun/query_update.go
- vendor/github.com/uptrace/bun/schema/append.go
- vendor/github.com/uptrace/bun/schema/append_value.go
- vendor/github.com/uptrace/bun/schema/field.go
- vendor/github.com/uptrace/bun/schema/scan.go
- vendor/github.com/uptrace/bun/schema/sqltype.go
- vendor/github.com/uptrace/bun/schema/table.go
- vendor/github.com/uptrace/bun/version.go
- vendor/modules.txt
This PR upsteps Bun to the latest commit on main, to include the fix for 32-bit ARM architecture.
> upstep bun version

- internal/federation/dereferencing/account.go
- internal/federation/dereferencing/account_test.go
- internal/federation/dereferencing/dereferencer_test.go
- testrig/testmodels.go
closes https://github.com/superseriousbusiness/gotosocial/issues/231
> allow dereferencing of groups

- internal/api/client/auth/auth_test.go
- internal/cliactions/admin/trans/import.go
- internal/cliactions/server/server.go
- internal/db/bundb/basic.go
- internal/db/bundb/migrations/20211113114307_init.go
- internal/db/bundb/migrations/20211113114307_init/README.md
- internal/db/bundb/migrations/20211113114307_init/account.go
- internal/db/bundb/migrations/20211113114307_init/application.go
- internal/db/bundb/migrations/20211113114307_init/block.go
- internal/db/bundb/migrations/20211113114307_init/client.go
- internal/db/bundb/migrations/20211113114307_init/domainblock.go
- internal/db/bundb/migrations/20211113114307_init/emaildomainblock.go
- internal/db/bundb/migrations/20211113114307_init/emoji.go
- internal/db/bundb/migrations/20211113114307_init/follow.go
- internal/db/bundb/migrations/20211113114307_init/followrequest.go
- internal/db/bundb/migrations/20211113114307_init/instance.go
- internal/db/bundb/migrations/20211113114307_init/mediaattachment.go
- internal/db/bundb/migrations/20211113114307_init/mention.go
- internal/db/bundb/migrations/20211113114307_init/notification.go
- internal/db/bundb/migrations/20211113114307_init/routersession.go
- internal/db/bundb/migrations/20211113114307_init/status.go
- internal/db/bundb/migrations/20211113114307_init/statusbookmark.go
- internal/db/bundb/migrations/20211113114307_init/statusfave.go
- internal/db/bundb/migrations/20211113114307_init/statusmute.go
- internal/db/bundb/migrations/20211113114307_init/tag.go
- internal/db/bundb/migrations/20211113114307_init/token.go
- internal/db/bundb/migrations/20211113114307_init/user.go
- internal/db/bundb/migrations/README.md
This PR defines the first iteration of the gtsmodel structs for entry into the database on startup as a bun migration.
From now on, any changes to the database schema should be accompanied by an sql or go migration in the migrations folder.
closes https://github.com/superseriousbusiness/gotosocial/issues/189
> First db migration

- .drone.yml
Fetch git tags in drone pipeline
> update drone file

- internal/db/bundb/bundb.go
This PR tidies up some of the database creation logic. Most notably, it uses the error code lookup map here: https://gitlab.com/cznic/sqlite/-/blob/master/sqlite.go#L70 in order to try to return more sensible & helpful sqlite error strings when something goes wrong creating or pinging the sqlite database.
> tidy up database creation

- .drone.yml
go => 1.17.5
gotosocial-drone-build => 0.0.1 (first release version)
> upstep build dependencies

- example/gotosocial.service
added systemd service in example folder
> add example systemd service

- docs/admin/cli.md
- docs/configuration/index.md
- docs/installation_guide/binary.md
The current instruction gets rejected as an unknown argument.
> Fix documentation to show --config-path in the right position.

- .gitignore
- docs/installation_guide/docker.md
- example/docker-compose/docker-compose.yaml
This is the first Version of a Docker Documentation. Suggestions for improvement and questions are welcome. :)
Fixes #190
> Creates Docker documentation and docker-compose.yaml

- go.mod
- go.sum
- vendor/codeberg.org/gruf/go-fastcopy/README.md
- vendor/codeberg.org/gruf/go-fastcopy/copy.go
- vendor/codeberg.org/gruf/go-mutexes/debug.go
- vendor/codeberg.org/gruf/go-mutexes/map.go
- vendor/codeberg.org/gruf/go-mutexes/mutex.go
- vendor/codeberg.org/gruf/go-mutexes/mutex_safe.go
- vendor/codeberg.org/gruf/go-mutexes/mutex_timeout.go
- vendor/codeberg.org/gruf/go-mutexes/pool.go
- vendor/codeberg.org/gruf/go-store/kv/store.go
- vendor/codeberg.org/gruf/go-store/storage/disk.go
- vendor/modules.txt
> update go-store, go-mutexes

- internal/media/processingmedia.go
This PR adjusts some of the logic for opening/closing store entries in the media package, to avoid situations where (for example) a user tries to upload 4 images, one fails, and then the others hang indefinitely and future uploads also block. The issue was that the store wasn't being closed properly in case of failure, so the other images couldn't obtain a lock.
> [bugfix] Fix media uploads blocking after a failed upload

- example/gotosocial.service
Hi!
The systemd service file was a little simplistic 
I edited it to harden security with basic sandboxing options
And I added a StandardOutput for logging
> Added sandboxing options to harden security

- go.mod
- go.sum
- internal/api/client/account/account_test.go
- internal/api/client/account/statuses.go
- internal/api/client/account/statuses_test.go
- internal/db/bundb/account.go
- internal/federation/federatingdb/inbox.go
- vendor/github.com/superseriousbusiness/activity/pub/database.go
- vendor/github.com/superseriousbusiness/activity/pub/side_effect_actor.go
- vendor/modules.txt
This endpoint wasn't working properly! Now it is, and tests have been added to prove it ;)
Closes #359
> [bugfix] Fix broken only_media and only_public flags on /api/v1/accounts/:id/statuses

- internal/processing/admin/createdomainblock.go
> [bugfix] Use background ctx for domain block side effects

- internal/db/bundb/instance.go
This fixes an issue where the domain block logic would go into an infinite loop.
> [bugfix] Fix infinite domain block database loop

- docs/installation_guide/docker.md
- example/docker-compose/docker-compose.yaml
This PR simplifies the docker-compose documentation and the example docker-compose.yaml file to make it more approachable for beginners.
> [Documentation] Simplify docker-compose documentation + example

- internal/federation/federatingdb/lock.go
This PR just does some small changes for consistency on the federating db lock implementation.
> [chore] Tidy up federating db locks a tiny bit

- docs/installation_guide/nginx.md
Some updates to the NGINX documentation.
* Add websockets options.
* Replace explicit security hardening with a recommendation.
* Stop GoToSocial while the procedure is happening.
> [documentation] NGINX docs updates

- internal/federation/federatingdb/lock.go
This reverts commit 31c1067a548039e7d95f131b3972ecfe1f57f835.
> Revert "[chore] Tidy up federating db locks a tiny bit (#472)"

- go.mod
- go.sum
- internal/federation/federatingdb/db.go
- internal/federation/federatingdb/lock.go
- vendor/github.com/superseriousbusiness/activity/pub/database.go
- vendor/github.com/superseriousbusiness/activity/pub/federating_wrapped_callbacks.go
- vendor/github.com/superseriousbusiness/activity/pub/handlers.go
- vendor/github.com/superseriousbusiness/activity/pub/side_effect_actor.go
- vendor/github.com/superseriousbusiness/activity/pub/social_wrapped_callbacks.go
- vendor/github.com/superseriousbusiness/activity/pub/util.go
- vendor/modules.txt
use MutexMap for federatingdb locks, update activitypub lib to support this
> Fix possible race condition in federatingdb

- internal/worker/workers.go
- scripts/build.sh
Adds startup, shutdown and init logging with type so you know which worker type this is referring to.
> Add logging to the new generic worker package

- internal/router/template.go
Fixes a regression from https://github.com/superseriousbusiness/gotosocial/pull/507
> [bugfix] Fix panic when relative tmpl path given to router

- internal/media/manager.go
A very small change :). Also updated the cron init log message to match the other media-manager messages in prefix / style
> run initial cache cleanup on gotosocial start in case max-age changed

- docs/installation_guide/docker.md
Closes https://github.com/superseriousbusiness/gotosocial/issues/476
> [Documentation] Tidy docker-compose docs, add note about uid/gid

- docs/api/swagger.yaml
- internal/api/client/admin/admin.go
- internal/api/client/admin/mediacleanup.go
- internal/api/client/admin/mediacleanup_test.go
- internal/api/model/admin.go
- internal/db/bundb/media_test.go
- internal/media/pruneremote_test.go
- testrig/testmodels.go
Adds an admin endpoint to trigger a remote media cleanup.
Fixed #348
> [feature] Media cleanup endpoint

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.yaml
I don't know if they look as good as they are, but I thought it would be cool to have such templates.
> Adds Issue templates

- internal/db/bundb/migrations/20220511165212_add_account_raw_note_fix.go
As mentioned in the comment below #651, here is the fix for the second migration
> fix for the second accounts.note_raw migration

- internal/api/client/account/block_test.go
- internal/api/client/account/follow_test.go
- internal/processing/account/createblock.go
- internal/processing/account/createfollow.go
My first Go patch.
If you can tell me where to add/update tests I can see if it works too. :D
> [bugfix] disallow following or blocking yourself (#664)

- internal/regexes/regexes.go
- internal/util/statustools_test.go
closes https://github.com/superseriousbusiness/gotosocial/issues/681
thanks @illfygli !!
> [bugfix] Make hashtag regex work with non-ascii characters

- internal/media/pruneunusedlocal.go
- internal/media/pruneunusedlocal_test.go
Update prune one local storage calls to use new interface from https://github.com/superseriousbusiness/gotosocial/pull/674
> [chore] Update pruneOneLocal to use ctx

- docs/installation_guide/binary.md
- docs/installation_guide/caddy.md
- web/source/css/base.css
This PR covers various fixes (which I accidentally put into the same PR, oops).
The docs should now reference v0.3.7 instead of v0.3.1, an outdated release.
Caddy [automatically upgrades to HTTPS](https://caddyserver.com/docs/automatic-https) and as such the HTTPS upgrading part of the example Caddyfile is redundant, and I removed it.
I noticed on the Admin panel that GoToSocial uses the `system-ui` font for inputs and buttons (pictured below).
This PR fixes this incompatibility, and sets the font to Noto Sans, to provide a smoother experience (pictured below).
I also added `text-align: center;` to `.button` to remove a styling incompatibility between `<button>` and `.button`.
That's it from me, contact me if you need anything else. Have a cheerful day! :)
> [bugfix] Various fixes

- docs/configuration/storage.md
Migrated my instance to the new backend and documented the process. Hope it's in the right place - if not, I'm happy to move it.
> docs: document the migration between local and s3

- web/source/css/status.css
- web/template/status.tmpl
> [bugfix] Fix display names in thread view causing wrapping issues on small screens

- internal/db/bundb/migrations/20220710153020_fix_slow_web_profile_queries.go
This PR adds an index specifically for serving public statuses of accounts via the web view, which was becoming very slow.
> [performance] Add new index to fix slow web profile queries

- web/source/css/base.css
Adjust footer a bit so it looks less wonky when it's wrapping (basically take up 100% width and text-align left when < 600px wide).
> [frontend] Footer styling adjustments

- ROADMAP.md
Shift everything back a quarter, since we had to take time to fix up bugs + performance.
> [docs] update roadmap

- internal/api/client/notification/notification.go
- internal/api/client/notification/notificationsclear.go
- internal/db/bundb/notification.go
- internal/db/bundb/notification_test.go
- internal/db/notification.go
- internal/processing/notification.go
- internal/processing/processor.go
> Implemented notification clear

- web/source/css/status.css
- web/source/frontend/index.js
- web/source/index.js
- web/source/package.json
- web/source/yarn.lock
- web/template/status.tmpl
implements a nice lightbox for media galleries in thread (and profile) pages
> [feature] Photoswipe gallery

- web/source/css/base.css
- web/source/css/status.css
This only works on Firefox so far but hey, it looks pretty cool!
> [frontend] Style scrollbars site-wide (not just in code)

- web/source/css/_colors.css
- web/source/css/status.css
- web/template/status.tmpl
still in draft, need to figure out accessibility aspects, and maybe blurhashes?
> [frontend] Sensitive media spoilers

- CONTRIBUTING.md
- README.md
- ROADMAP.md
Does some updates to (a very little number of) typo's, fixes some punctuation and grammar on the root Markdown files.
> Textual updates on markdown files

- internal/processing/fromcommon.go
> Do not generate a notification when favouriting your own post

- web/source/panels/admin/settings.js
> [Admin panel] Make Description boxes multi-line

- docs/api/swagger.yaml
- docs/swagger.go
- internal/api/client/notification/notification.go
- internal/api/client/notification/notificationsget.go
- internal/api/model/notification.go
- internal/db/bundb/notification.go
- internal/db/bundb/notification_test.go
- internal/db/notification.go
- internal/processing/notification.go
- internal/processing/notification_test.go
- internal/processing/processor.go
this makes it so the "mentions" tab on pinafore works
> Add support for the exclude_types[] parameter on the notifications endpoint

- web/template/status.tmpl
See: https://photoswipe.com/opening-or-closing-transition/#animating-from-cropped-thumbnail
> [frontend] Transition neatly from cropped photos

- .gitignore
- internal/router/template.go
- internal/web/base.go
- internal/web/opengraph.go
- internal/web/profile.go
- internal/web/thread.go
- web/template/header.tmpl
Improves on OpenGraph meta tags served by various pages, to generate better URL previews actually showing useful content.
There's some weird behavior with |noescape inside quoted HTML properties that could use some investigating
> [feature] opengraph meta tags

- internal/api/errorhandling.go
- internal/db/bundb/domain.go
- internal/router/logger.go
we were getting an error doing domain unblocks but it was being swallowed
now, errors are logged, and the domain block delete issue is fixed (we were selecting into a nil model basically).
closes https://github.com/superseriousbusiness/gotosocial/issues/832
> [bugfix] Fix domains not being unblockable, log internal server errors from API

- internal/federation/dereferencing/thread.go
- actually start at top of stack loop on finding a remote child
- fix iteration indexing
> [bugfix] panic during child thread iteration

- internal/db/bundb/account_test.go
- internal/db/bundb/migrations/20220926115233_indexes.go
Also add an unrelated test :')
> [performance] Update indexes that were causing slow db queries

- internal/processing/status/create_test.go
- internal/processing/status/util.go
Closes https://github.com/superseriousbusiness/gotosocial/issues/830, since everything else in that issue is also now completed.
> [bugfix] Fix emojis not showing in spoiler text

- web/source/css/status.css
This PR adds some v. simple css for enlarging emojis on hover (long-press on mobile), when they're inside statuses.
This lets users get a good look at custom emojis!
https://user-images.githubusercontent.com/31960611/193449997-f8d32256-a093-47eb-a00b-b7cb06f182d5.mp4
> [feature] Enlarge active/hovered custom emojis in statuses

- web/source/css/status.css
fixes https://github.com/superseriousbusiness/gotosocial/issues/876
> [frontend] change spacing of status, text always on it's own line, move status date on mobile

- web/source/css/_colors.css
- web/source/frontend/index.js
- web/template/thread.tmpl
Scrolls to highlighted toot on page load, as long as it's not the first one (because then it's not really needed). Also makes unfocused toots one shade darker
> [frontend] Scroll to highlighted toot, improve highlight

- web/source/package.json
- web/source/settings/components/languages.jsx
- web/source/yarn.lock
Now with 184 languages!
Fixes https://github.com/superseriousbusiness/gotosocial/issues/906
> [frontend] Use ISO639 library for language selection

- internal/db/bundb/timeline.go
- internal/db/bundb/timeline_test.go
> [bugfix] Prevent future statuses showing in timelines

- internal/api/client/app/appcreate.go
- internal/api/client/media/mediacreate.go
- internal/api/client/media/mediaupdate.go
- internal/api/client/status/statuscreate.go
- internal/validate/formvalidation.go
- internal/validate/formvalidation_test.go
Fixes https://github.com/superseriousbusiness/gotosocial/issues/946
> [bugfix] Use `[]rune` to check length of user-submitted text

- README.md
> [docs] Add matrix space to readme

- internal/api/client/app/appcreate.go
closes https://github.com/superseriousbusiness/gotosocial/issues/957
> [bugfix] Increase field size limits when registering apps

- internal/processing/status/create.go
- internal/processing/status/create_test.go
- internal/processing/status/status.go
- internal/processing/status/util.go
Closes https://github.com/superseriousbusiness/gotosocial/issues/899
> [bugfix] Check `media-description-min-chars` on submission of new status

- cmd/gotosocial/action/server/server.go
- go.mod
- go.sum
- internal/storage/local.go
- internal/storage/storage.go
- vendor/codeberg.org/gruf/go-store/v2/kv/store.go
- vendor/modules.txt
- bump go-store version to v2.0.5
- init kv.KVStore without initial clean as we are using for storage, not as a key-value store
> [bugfix] KVStore doesn't like lost+found directory

- internal/text/sanitize.go
Resolves https://github.com/superseriousbusiness/gotosocial/issues/990
> Fix rel="nofollow" so that it only applies to external links

- README.md
> [docs] Use correct Friendica link in README

- docs/user_guide/posts.md
- docs/user_guide/user_panel.md
- internal/processing/account/update.go
- internal/processing/account/update_test.go
- web/source/settings/user/profile.js
- web/source/settings/user/settings.js
Implements https://github.com/superseriousbusiness/gotosocial/issues/1032
> Support markdown format for Account bio/note

- internal/db/bundb/account.go
- internal/db/bundb/status.go
Makes it easier diagnosing issues.
> [chore] improve errors returned fetching account/statues from DB

- README.md
- docs/faq.md
- docs/index.md
- mkdocs.yml
As discussed on the Matrix channel, I've added an FAQ for potential users so that we can try to set expectations to a little more realistic level. I feel that this should help reduce the amount of questions in the help channel around things which simply don't exist yet. When I was first setting up my server, I had some difficulty understanding which things I should expect to work, so I hope this helps.
If you have suggestions for further topics to cover, I can do my best to add them.
I know that debugging federation issues can be confusing; I had a friend who ran into this when he was setting up his GtS behind nginx, but I don't know the details, so I left it as a TODO.
Also I clarified some language about algorithms in the readme/index but if you feel that is too pedantic I can remove …
> [docs] Add first draft of FAQ

- internal/text/markdown.go
- internal/text/markdown_test.go
> [enhancement] markdown: disable Smartypants rendering

- web/source/css/profile.css
- web/source/settings/components/fake-profile.jsx
- web/source/settings/lib/api/oauth.js
- web/source/settings/style.css
- web/source/settings/user/profile.js
fixes https://github.com/superseriousbusiness/gotosocial/issues/1129
> [frogend] fix profile preview css, use role info

- internal/api/client/status/statusboostedby.go
- internal/api/client/status/statusboostedby_test.go
- internal/processing/status/boostedby.go
We broke this at some point recently, and i'm not sure when.
In any case, i updated some of the logic in there + added a test for it.
> [bugfix] Fix status boosts giving 404

- web/source/css/_colors.css
- web/source/css/base.css
- web/source/index.js
- web/source/settings/admin/emoji/category-select.jsx
- web/source/settings/admin/emoji/detail.js
- web/source/settings/admin/emoji/new-emoji.js
- web/source/settings/admin/emoji/overview.js
- web/source/settings/components/combo-box.jsx
- web/source/settings/components/form/combobox.jsx
- web/source/settings/lib/query/custom-emoji.js
- web/source/settings/style.css
https://user-images.githubusercontent.com/23422690/203981633-57d503f6-da99-497f-a8ab-ff148a1f645f.mp4
> [frogend] modify local emoji

- web/source/settings/admin/emoji/detail.js
- web/source/settings/components/fake-profile.jsx
- web/source/settings/style.css
fixes a logic error that made it impossible to set a category on new emoji that had no category yet
> [chore] Fix frogend admin emoji patch

- internal/typeutils/internaltofrontend.go
Refactors some of the internaltofrontend.go functions for readability and to consolidate reused code into separate functions
> [bugfix] don't return error during account serialize on deleted emoji

- web/source/settings/lib/api/admin.js
Closes https://github.com/superseriousbusiness/gotosocial/issues/931
> [bugfix] use correct key for PATCHing admin email

- web/source/settings/style.css
fixes https://github.com/superseriousbusiness/gotosocial/issues/1175
> [bugfix] Profile grid scaling in webkit based browsers

- internal/db/bundb/emoji.go
closes https://github.com/superseriousbusiness/gotosocial/issues/1192
> [bugfix] Add missing continues in emoji get funcs

- .github/PULL_REQUEST_TEMPLATE/bugfix.md
- .github/PULL_REQUEST_TEMPLATE/documentation.md
- .github/PULL_REQUEST_TEMPLATE/feature.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/index.md
Update contributing.md:
- Add pull request processes. These just codify what we already did anyway.
- Add guidelines for opening feature requests + bug reports.
- Move stub CoC to its own separate document, where it can more easily be updated later.
- Add a section to help new contributors find their way around the code.
Add pull request templates, which reference the updated contributing.md.
> [docs] Update `CONTRIBUTING.md`, add pull request templates

- internal/config/gen/gen.go
This pull request fixes up a couple of issues we had in the config generation stuff.
- remove duplicate config struct in `internal/config/gen`
- update `internal/config/gen` to import `time`, since it's now needed by cache stuff
> [chore] fix some little config whoopsies

- CONTRIBUTING.md
>
This PR just notes in the contributing doc that go v1.19.4 doesn't work properly, and recommends using a lower or higher version (future proof!).
relates to https://github.com/superseriousbusiness/gotosocial/issues/1249
> [chore] note broken go v1.19.4 in contributing.md

- docs/installation_guide/apache-httpd.md
Added a troubleshooting section to help others deal with the issues I had because I didn't start with a clean Apache setup so it was hard to figure out what to remove.
> Add troubleshooting section for Apache

- docs/configuration/storage.md
It was interesting to note that since presigned urls are used buckets dont need to be exposed publically. this was an interesting change compared to other mastodon specific s3 bucket guides hence documented here for correct directions.
> AWS S3 config details added

- web/source/css/status.css
>
Current blockquote margin + padding values were causing issues on small screens. This PR updates these values to use horizontal space a bit better!
Before:
After:
> [chore/frogend] update status blockquote css

- internal/processing/account/delete.go
> [bugfix] fix panic during account delete

- docs/configuration/storage.md
- example/config.yaml
>
This pull request adds an item in the storage documentation to explain how to disable ssl for s3 connections.
closes #1293 
> update storage docs

- README.md
- docs/index.md
>
This PR updates some of our documentation to acknowledge our successful NLnet funding application :)
> [docs] Rewrite sponsorship + funding section, add NLnet

- docs/federation/behaviors/request_throttling.md
- docs/federation/federating_with_gotosocial/access_control.md
- docs/federation/federating_with_gotosocial/conversation_threads.md
- docs/federation/federating_with_gotosocial/http_signatures.md
- docs/federation/federating_with_gotosocial/outbox.md
- docs/federation/federating_with_gotosocial/request_throttling.md
- docs/federation/security.md
- mkdocs.yml
>
This pull request tidies up some of our federation documentation, adds details of our sicko http signature stuff, and prepares the way for writing more detailed docs on what else remote instances need to know in order to federate nicely with GoToSocial.
> [docs] Tidy up federation docs into 'federating with gotosocial' section

- internal/cache/util.go
> [bugfix] fix cache startup

- web/source/settings/user/settings.js
>
Fix an issue where password couldn't be changed via the settings panel because of incorrect keys.
> [bugfix] Fix password change keys

- web/source/.eslintrc.js
- web/source/package.json
- web/source/settings/admin/emoji/local/detail.js
- web/source/settings/admin/federation/detail.js
- web/source/settings/admin/federation/import-export/form.jsx
- web/source/settings/admin/federation/import-export/index.jsx
- web/source/settings/admin/federation/import-export/process.jsx
- web/source/settings/admin/settings.js
- web/source/settings/components/form/inputs.jsx
- web/source/settings/lib/form/bool.jsx
- web/source/settings/lib/form/check-list.jsx
- web/source/settings/lib/form/combo-box.jsx
- web/source/settings/lib/form/index.js
- web/source/settings/lib/form/radio.jsx
- web/source/settings/lib/form/submit.js
- web/source/settings/lib/form/text.jsx
- web/source/settings/user/profile.js
- web/source/settings/user/settings.js
- web/source/yarn.lock
Changes the way the form field hooks work so they take data from, and update as expected after queries.
> [frogend] Restructure form data default values / update from Query data

- web/source/settings/admin/reports/detail.jsx
- web/source/settings/admin/reports/index.jsx
- web/source/settings/admin/reports/username.jsx
- web/source/settings/index.js
- web/source/settings/lib/query/admin/index.js
- web/source/settings/lib/query/admin/reports.js
- web/source/settings/lib/query/base.js
- web/source/settings/style.css
Implements basic listing and resolving of reports. Not the final implementation by a long shot, but wanted to get the very basics in before the v0.7.0 release.
PR depends on https://github.com/superseriousbusiness/gotosocial/pull/1422, can be rebased afterwards.
> [Frogend] basic report admin interface

- web/source/css/base.css
- web/source/css/profile.css
- web/source/settings/style.css
As reported:
1. There is a horizontal scrollbar when a vertical scrollbar is needed (firefox and safari on osx)
2. also in safari mobile the pofile card is unnecessarily wide and hides all the inputs:
This fix should address 2, as tested in Epiphany (Webkit), and might fix 1 too, but can't reproduce it here in the first place.
> [chore] Webkit frontend fixes

- internal/federation/federatingprotocol.go
This handles a case where a 410 Gone could occur at an unexpected place in the processing of account deletion requests for accounts we were previously unaware of.
This is currently running on my live GTS instance, though the actual race hasn't yet happened so I can't strictly prove it's working yet.
closes #1313 for real
> Fix 410 Gone race on account deletes

- README.md
also groups them into a single block to improve readability
> [chore] update gruf's libs on readme

- internal/db/bundb/migrations/20220905150505_custom_emoji_updates.go
… 
>
This pull request fixes an issue where brand new postgres instances were failing to be created during the migration steps.
> [bugfix] In Postgres, drop shortcodedomain constraint before creating new emoji table

- go.mod
- go.sum
- vendor/codeberg.org/gruf/go-kv/field.go
- vendor/codeberg.org/gruf/go-kv/field_fmt.go
- vendor/codeberg.org/gruf/go-kv/field_format.go
- vendor/codeberg.org/gruf/go-kv/format/format.go
- vendor/codeberg.org/gruf/go-kv/format/util.go
- vendor/codeberg.org/gruf/go-kv/util.go
- vendor/codeberg.org/gruf/go-mangler/LICENSE
- vendor/codeberg.org/gruf/go-mangler/README.md
- vendor/codeberg.org/gruf/go-mangler/helpers.go
- vendor/codeberg.org/gruf/go-mangler/init.go
- vendor/codeberg.org/gruf/go-mangler/load.go
- vendor/codeberg.org/gruf/go-mangler/mangle.go
- vendor/codeberg.org/gruf/go-mangler/manglers.go
- vendor/modules.txt
> [chore] pull in latest go-kv, go-cache

- docs/api/swagger.yaml
- internal/api/client/admin/reportsget_test.go
- internal/api/client/instance/instancepatch_test.go
- internal/api/model/account.go
- internal/api/model/admin.go
- internal/typeutils/internaltofrontend.go
- internal/typeutils/internaltofrontend_test.go
- web/source/settings/index.js
- web/source/settings/user/profile.js
- web/template/profile.tmpl
This is just https://github.com/superseriousbusiness/gotosocial/pull/1521 with a few small tweaks and swagger docs updates :)
> [bugfix] Fix account roles

- test/envparsing.sh
I've struggled a lot with finding what I did wrong whenever I added a config value but forgot to update something related to the envparsing test.
This checks if [jd](https://github.com/josephburnett/jd/releases/) is available and if so uses that to create the diff instead. `jd` can tell you at which (nested) key the values are differing which makes for more human friendly output.
~~I wasn't quite sure how to add this to CI so we get a cleaner diff there so for now I've jacked in a `go install`. That feels a bit nasty though. I'm not entirely sure the resulting binary is actually in $PATH on CI either.~~
Now, if I change the value of `GTS_REQUEST_ID_HEADER='X-Trace-Id'` to `GTS_REQUEST_ID_HEADER='X-Trace-Idd'` instead and run the test.
Before: 
```
OUTPUT not equal EXPECTED
1c1
< …
```
> [chore] Better diff for envparsing test

- .drone.yml
- CONTRIBUTING.md
- go.mod
>
- bump go from 1.19.5 -> 1.20.1
- bump golangci-lint from 1.50.1 -> 1.51.2
- bump gotosocial-drone-build from 0.0.8 -> 0.1.0 (https://github.com/superseriousbusiness/gotosocial-drone-build/releases/tag/v0.1.0)
> [chore] bump go, build, and lint version

- internal/oauth/server.go
This attempts to provide a slightly more comprehensive error message for the end user when an incorrect grant type is used. This is not something the user can typically resolve but should hopefully be informative for the (client) developer.
Slight additional improvement for #1546.
The error message now reads:
```
{"error":"unsupported_grant_type","error_description":"Bad Request: could not validate token request: unsupported_grant_type: If you arrived at this error during a login/oauth flow, your client is trying to use an unsupported OAuth grant type. Supported grant types are: authorization_code, client_credentials; please reach out to developer of your client"}
```
If this is a …
> [chore] Improve unsupported_grant_type error

- internal/federation/dereferencing/account.go
> [bugfix] on deref new account, check db again for account on ErrAlreadyExists

- docs/api/swagger.yaml
- internal/api/client/admin/reportsget.go
- internal/api/client/admin/reportsget_test.go
>
closes https://github.com/superseriousbusiness/gotosocial/issues/1425
> [bugfix] Clamp admin report limit <1 to 100

- internal/processing/media/update.go
> [bugfix] use updateattachment when updating media to ensure cache is invalidated

- internal/federation/dereferencing/account.go
> [chore] improved enrichAccount() logging

- web/source/css/base.css
- web/source/settings/admin/federation/import-export/export-format-table.jsx
- web/source/settings/admin/federation/import-export/form.jsx
- web/source/settings/admin/federation/import-export/process.jsx
- web/source/settings/components/form/mutation-button.jsx
- web/source/settings/style.css
Bunch of small css tweaks, mostly relating to the bulk federation import/export, making things a bit more usable on small screens.
closes https://github.com/superseriousbusiness/gotosocial/issues/1438
> [frontend/fix] Mobile css tweaks

- internal/web/opengraph.go
- web/template/header.tmpl
>
This pull request updates some of our opengraph (og) tags:
1. Use correct `property` instead of `name`.
2. Provide image alt if image description set.
3. Provide profile:username tag.
> [chore] Fix opengraph tags; add image alt, profile username

- docs/api/swagger.yaml
- internal/api/model/instancev2.go
>
This PR fixes a small issue with the swagger docs, and also regenerates them to make sure everything is up to date.
Swagger version (installed with `go install`:
```
version: v0.30.4
commit: (unknown, mod sum: "h1:cPrWLSXY6ZdcgfRicOj0lANg72TkTHz6uv/OlUdzO5U=")
```
> [chore] fix + update swagger docs

- docs/installation_guide/advanced.md
This adds a section to the docs instructing how to ensure apps will be able to successfully login to an instance when host- and account-domain differ.
Resolves #1609
> [chore] Update docs on how to login

- internal/federation/dereferencing/account.go
>
This pull request updates some of our account dereferencing logic to use the ActivityPub URI host as the accountDomain if the second webfinger lookup attempt fails.
This should prevent cases where we accidentally use completely the wrong domain for an account when it's been looked up via a redirect.
closes https://github.com/superseriousbusiness/gotosocial/issues/1627
> [bugfix] Use account ID host as accDomain if 2nd webfinger lookup fails

- cmd/gotosocial/action/admin/account/account.go
- cmd/gotosocial/admin.go
- internal/db/bundb/user.go
- internal/db/bundb/user_test.go
- internal/db/user.go
>
A first pass at #388. Doesn't implement the filtering that was suggested there. I'm inclined to say we shouldn't have filter flags as that's a potentially never ending story. I'm thinking we might want to add a `--format=json` flag there instead and dump the object, so folks can slice, dice and filter with `jq` to their heart's content.
> [feature] Add list command to admin account

- web/template/header.tmpl
>
This pull request implements [preloading](https://devdocs.io/html/link_types/preload) for css in our header template. Should hopefully reduce instances of [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content).
> [bugfix/frontend] Preload css styles

- web/template/404.tmpl
- web/template/about.tmpl
- web/template/authorize.tmpl
- web/template/confirmed.tmpl
- web/template/domain-blocklist.tmpl
- web/template/error.tmpl
- web/template/finalize.tmpl
- web/template/footer.tmpl
- web/template/frontend.tmpl
- web/template/header.tmpl
- web/template/index.tmpl
- web/template/oob.tmpl
- web/template/profile.tmpl
- web/template/sign-in.tmpl
- web/template/status.tmpl
- web/template/thread.tmpl
bring some pesky license headers in line with what we already have elsewhere
> [chore] Update templates license headers

- cmd/gotosocial/action/server/server.go
>
closes https://github.com/superseriousbusiness/gotosocial/issues/1677 by just logging a descriptive (and reassuring) warning if cgroup setting doesn't work, instead of failing entirely 
> [bugfix] warn on maxprocs error instead of failing

- internal/db/bundb/statusbookmark.go
This pull request fixes user's bookmark list appearing empty.
> [bugfix] Fix the bookmarks list API endpoint returning an empty array

- example/config.yaml
>
This pull request fixes some v. small config file typos which may have caused issues.
closes https://github.com/superseriousbusiness/gotosocial/issues/1704
> [bugfix] fix small config typos

- README.md
>
I am in the process of migrating the Helm Charts to a new Github organization, so the paths and URLs are changing as well. I would like to post the current status here.
The old url was https://maxxblow.de/charts the new one is https://charts.fsociety.social .
closes #(issue)
closes #(another issue)
- [x ] I/we have read the [GoToSocial contribution …
> Migrates GoToSocial Helm Chart Location to another repository.

- go.mod
- go.sum
- internal/cache/cache.go
- internal/cache/visibility.go
- internal/db/bundb/relationship_follow_req.go
- vendor/codeberg.org/gruf/go-cache/v3/result/cache.go
- vendor/codeberg.org/gruf/go-cache/v3/result/key.go
- vendor/modules.txt
> [bugfix] update go-cache version to support multi-keying

- archive/design/reports.md
>
This pull request adds some notes for report / Flag implementation, describing what some other implementations do, and what GtS should do.
Relates to https://github.com/superseriousbusiness/gotosocial/issues/1309
> [docs] Add implementation notes for report (Flag) functionality

- docs/api/swagger.yaml
- internal/api/client/notifications/notificationsclear.go
>
The handler is already hooked to the right path, it's just the docs that were missing the path.
> [bugfix] Fix clear notifications API docs

- README.md
- ROADMAP.md
- docs/index.md
>
This PR updates our roadmap document + beta estimates.
> [docs] Update + simplify roadmap, revise beta estimate

- README.md
>
Small update to the readme to clarify that other federation modes are not yet implemented.
closes https://github.com/superseriousbusiness/gotosocial/issues/1846
> [docs] clarify other federation modes not yet implemented

- go.mod
- go.sum
- internal/httpclient/client.go
- vendor/codeberg.org/gruf/go-iotools/close.go
- vendor/modules.txt
> [bugfix] allow httpclient connection reuse

- .drone.yml
- .golangci.yml
- .vscode/settings.json
- cmd/gotosocial/action/admin/account/account.go
- internal/api/client/accounts/accountcreate.go
- internal/api/util/errorhandling.go
- internal/cache/util.go
- internal/db/bundb/basic.go
- internal/federation/federatingdb/reject.go
- internal/gotosocial/gotosocial.go
- internal/processing/fromcommon.go
- internal/processing/fromfederator.go
Update build + container versions, and fix some linting warnings -- including some actual errors!
> [chore] Update versions, fix lint errors

- README.md
- docs/installation_guide/third_party.md
Instead of a manually curated list of distribution packages, this adds the Repology[1] widget instead.
This also separates out the distribution packages from the self-hosting/deployment options into their own sections.
[1]: https://repology.org/project/gotosocial/versions
> [docs] Add Repology stats

- internal/db/bundb/timeline.go
>
This pr fixes a slow old join query which was causing severely slow (60s) SELECT queries for a new user on an already well populated instance.
> [bugfix] Fix slow joined home timeline query

- internal/processing/fromcommon.go
>
This PR does a minor fix on lists: previously we weren't deleting statuses properly from list timelines, so the timelines ended up with stub entries that didn't correspond to an existing status anymore.
> [bugfix] Delete from list timeline on status deletion

- internal/api/client/instance/instancepatch_test.go
- internal/api/model/instance.go
- internal/typeutils/internaltofrontend.go
- internal/typeutils/internaltofrontend_test.go
- web/source/package.json
- web/source/settings/admin/emoji/local/new-emoji.js
- web/source/settings/lib/form/context.jsx
- web/source/settings/lib/form/field-array.jsx
- web/source/settings/lib/form/get-form-mutations.js
- web/source/settings/lib/form/index.js
- web/source/settings/lib/form/submit.js
- web/source/settings/lib/query/base.js
- web/source/settings/style.css
- web/source/settings/user/profile.js
- web/source/yarn.lock
Adds GUI to the user settings interface for setting the new profile fields.
Also exposes the allowed amount of form fields through the instance API, though currently hard-coded to 6 pending https://github.com/superseriousbusiness/gotosocial/issues/1876
> [Frontend] Settings for profile fields

- internal/api/client/lists/listaccountsremove.go
This pull request fixes form parsing in the list member removal endpoint. This fixes removing accounts from lists in Mastodon clients like [Tusky](https://tusky.app) and [Mona](https://apps.apple.com/app/id1659154653) which send the account IDs as an `application/x-www-form-urlencoded` form with a DELETE method, not in query params. 
> [bugfix] Parse POST-style forms in the list member removal endpoint

- docs/getting_started/installation/container.md
>
Addresses some issues with docs brought up in https://github.com/superseriousbusiness/gotosocial/issues/1911
> [docs] Disambiguate docker version, don't recommend opening localhost

- CONTRIBUTING.md
* Add instructions on how to make a new page show up in the sidebar / navigation
* Explain how to create a virtual env to install the dependencies in if you're not using Conda
> [docs] Clarify how to add a page

- internal/processing/fromfederator.go
>
Fixes a mistake in https://github.com/superseriousbusiness/gotosocial/pull/1960 
> [bugfix] Fix delete follow req instead of follow

- docs/admin/cli.md
- internal/validate/formvalidation.go
> [chore] Fix password typos

- internal/federation/dereferencing/account.go
- internal/federation/federatingdb/update.go
- internal/processing/fromfederator.go
>
This pull request updates account Update logic in the following ways:
1. Don't pass partial updated account model to processor for updating, just pass old model + new AP Accountable. What we were doing previously was a bit silly: transferring some fields from the old account model onto the new account model, but then allowing some other fields to be different. Confusing!
2. Remove `*media.Cached` check for updating account avatars + headers, since it's not really relevant to whether or not the Avatar + Header are up to date, and may cause multiple fetches of the same media file …
> [bugfix] Update account `Update` logic

- docs/advanced/caching/assets-media.md
I’ve ported the 「Caching assets and media」 section to Apache 2, for those of us who’ve so far ignored nginx.
There’s one change, to the expiry for `/fileserver/**`, which I’ve taken from the prod setup of the person who originally submitted the nginx section. [Discussion thread on Fedi](https://toot.mirbsd.org/@mirabilos/statuses/01H5RJM7GE9NBM5XYRVHXGYC5N)
> [docs] Apache setup for Caching assets and media

- internal/validate/formvalidation.go
- internal/validate/formvalidation_test.go
>
This PR implements just the password length changes from https://github.com/superseriousbusiness/gotosocial/pull/2008
> [bugfix] Change maximumPasswordLength to 72 bytes

- internal/transport/finger_test.go
We don't talk about 8868889 / #1983.
> [chore] Disable the right webfinger test

- internal/db/bundb/relationship_note.go
Fixes a merge issue from me being too cavalier
> [chore] fix merge issue

- web/source/settings/admin/federation/detail.js
>
This pull request updates domain defederation view in the settings panel to decode URL-encoded domains before showing them to the user. This is particularly useful for unicode domain names, which otherwise rendered as a URL-encoded string that looked nothing like the domain... unless you're capable of decoding URL-encoded strings on the fly in your head, in which case, props to you.
Before:
After:
Closes https://github.com/superseriousbusiness/gotosocial/issues/2035
If this is a …
> [bugfix/frontend] Decode URI component domain before showing on frontend

- internal/db/bundb/account.go
- internal/db/bundb/emoji.go
- internal/db/bundb/status.go
Updates emoji delete, and get statuses / accounts using emoji functions to use their appropriate relational tables for faster lookups.
closes #2015
> [bugfix] fix slow accounts / statuses using emojis lookups

- internal/web/robots.go
Update our robots.txt to:
1. Give chat gpt the middle finger.
2. Make the thing a bit more human-readable.
> [chore] Update robots.txt, give chatgpt the middle finger

- internal/processing/workers/fromclientapi_test.go
>
This mercifully small PR (you're welcome @NyaaaWhatsUpDoc) just adds a couple tests to ensure that show_reblogs works as it should on follows.
closes https://github.com/superseriousbusiness/gotosocial/issues/999
> [chore] Add test to ensure `show_reblogs` on follow works as expected

- internal/federation/federatingactor.go
>
Just a little fix for annoying ErrNoEntries warnings on that damn InboxForwarding function that doesn't work properly -_-
> [bugfix] Suppress 'errNoEntries' warnings from InboxForwarding function call

- internal/gtscontext/wrap.go
- internal/middleware/requestid.go
- internal/processing/workers/fromclientapi.go
- internal/processing/workers/fromfediapi.go
- internal/processing/workers/util.go
Ensures that worker contexts have request ID fields set.
> [chore] ensure worker contexts have request ID

- internal/db/bundb/timeline.go
- internal/db/bundb/timeline_test.go
>
This pr further optimizes our home timeline db function to use the cache a bit more, and produce a simpler query plan overall.
It does this by passing an IN statement to the database with a list of all the account IDs that the requesting account follows.
While this does produce some pretty preposterous looking queries when an account has 100+ followers, it is still much faster than the subquery we were using previously (at least on SQLite).
Previous query plan:
Previous rough measurements of total time spent inside HomeTimeline:
```
42.03077ms
4.483957ms
1.442441078s …
```
> [performance] Rework home timeline query to use cache more

- docs/admin/backup_and_restore.md
- example/borgmatic/media-to-borg-patterns.py
>
We forgot to update these as part of #2121.
* Update the commands to their new names
* Mention how to do emoji too
> [docs] Update backup docs

- docs/getting_started/index.md
- docs/index.md
* Mention the lack of multi-node/clustering support in the docs
* Add myself as a developer :pleading_face: 
> [docs] Add a note on cluster support

- internal/cache/slice.go
> fix typo in slice.go

- internal/oauth/server.go
>
For some reason we only had plain enabled. This adds S256.
> [chore] Enable S256 code challenge

- internal/web/robots.go
> [feature] Block a bunch of "AI" crawlers

- internal/ap/activitystreams.go
- internal/ap/extract.go
- internal/ap/interfaces.go
- internal/ap/normalize.go
- internal/ap/normalize_test.go
- internal/ap/resolve.go
- internal/ap/resolve_test.go
- internal/api/activitypub/users/inboxpost_test.go
- internal/federation/federatingactor.go
> [chore] internal/ap: add pollable AS types, code reformatting, general niceties

- internal/text/markdown.go
> [performance] updates markdown parsing to reduce allocations

- web/source/settings/admin/domain-permissions/overview.tsx
>
Fix the import/export link, which broke (my bad!).
Closes https://github.com/superseriousbusiness/gotosocial/issues/2274
> [frontend/bugfix] Fix bulk import export link

- internal/api/model/instancev1.go
- internal/api/model/instancev2.go
- internal/typeutils/internaltofrontend.go
>
Previously we were letting admins set terms and conditions for their instance, but we weren't serializing those T&Cs back to them via the API, so it looked like their update was being swallowed.
This PR fixes this by ensuring that terms and conditions are serialized properly on the instance model so that they're sticky in the admin panel + don't seem to disappear after a refresh.
Ofc, we still don't do much with these terms and conditions, but that's out of the scope of this PR really.
Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> …
> [bugfix] serialize instance terms via API

- internal/db/bundb/migrations/20231029143819_remove_suspended_at_index.go
closes #2309
Resolve issue by removing index, as discussed in issue.
> Remove account_suspended_at_idx to resolve slow query issues

- docs/api/swagger.md
>
closes https://github.com/superseriousbusiness/gotosocial/issues/2332
> [docs/bugfix] fix link to swagger yaml

- internal/config/flags.go
> [chore/whoops] re-add missing languages flag

- docs/advanced/host-account-domain.md
Small docs improvement that annotate each line with which config option the value needs to match.
> [docs] Annotate split-domain setup

- internal/api/model/poll.go
- internal/typeutils/internaltofrontend.go
- web/template/poll.tmpl
Tiny tweak to make sure poll option IDs are unique.
> [bugfix/chore] id poll options properly

- docs/configuration/database.md
- example/config.yaml
People keep tweaking this and running into performance issues as a consequence.
> [docs] Add a warning about SQLite cache sizes

- docs/federation/federating_with_gotosocial.md
> [documentation] add poll and poll vote details to gotosocial federating doc

- docs/advanced/metrics.md
- docs/configuration/observability.md
> [docs] Explain how to secure metrics endpoints

- docs/federation/federating_with_gotosocial.md
- internal/processing/workers/federate.go
- internal/typeutils/converter_test.go
- internal/typeutils/internaltoas.go
- internal/typeutils/internaltoas_test.go
- internal/typeutils/wrap.go
- internal/typeutils/wrap_test.go
>
Few small fixes to poll federation.
- Poll vote from one GtS instance was being rejected by another, because the Actor property wasn't populated on the outgoing Create. So make sure actor is set properly on Create.
- Use poll vote creation time as published time.
- Reorder poll vote ID creation.
- Add test for above, update docs with example Create.
> [bugfix] Add Actor to outgoing poll vote Create; other fixes

- internal/processing/workers/fromfediapi.go
This should stop the issue that a few of us have noticed with multiple notifications being created for a mention.
> [bugfix] in fedi API CreateStatus(), handle case of data-race and return early

- internal/ap/extract.go
- internal/api/model/poll.go
- internal/router/template.go
- internal/typeutils/internaltofrontend.go
- web/template/status_poll.tmpl
- only sets the `voters_count` frontend field when the poll is multiple choice (changed to ptr to accomodate this)
- slightly more robust ActivityStreams poll data extraction
> [bugfix] poll vote count fixes

- docs/advanced/security/firewall.md
This adds some documentation on how to block one, multiple or whole IP ranges using the firewall. This can be helpful to protect from DDoS attacks or block certain parties from being able to communicate with your instance at all.
> [docs] Describe how to block IPs using a firewall

- internal/middleware/logger.go
>
Add `pubKeyID` to logging of responses to incoming HTTP requests (when the request was signed).
Closes https://github.com/superseriousbusiness/gotosocial/issues/2499
> [feature] Log pubKeyID for incoming http-signed requests

- ROADMAP.md
As the title says :) This updates our roadmap to shuffle the things we didn't finish in 2023 into early 2024, and also add some more items for the BETA period of development.
> [docs] Update roadmap for 2024 onwards

- internal/processing/admin/domainblock.go
- internal/processing/admin/domainpermission_test.go
>
This pull request implements some logic to check whether a domain allow exists when a domain block is processed, and the instance is running in blocklist mode. If so, domain block side effects will be skipped, "shielding" the domain from blocking as promised in the docs.
I thought we already had this in there, but must have overlooked it. Added some tests too to prove it works.
There might still be some additional complications around combining blocks and allows with more or less explicit domains, in different federation modes. We should work out all of the combinations at some …
> [bugfix] Ensure domain block side effects skipped if allow in place (blocklist mode)

- internal/processing/account/alias.go
- internal/processing/account/alias_test.go
- internal/typeutils/astointernal_test.go
>
That's all, just fixes an oversight from a previous PR. Credit to leah for finding the bug.
> [bugfix] Prevent URL + URI for same account being used as alias target

- docs/getting_started/index.md
- docs/getting_started/reverse_proxy/nginx.md
* Mention tuning swappiness
* Warn about database performance issues with network storage
* Mention enabling HTTP/2 on nginx
> [docs] Updates for DB, swap and HTTP/2 on nginx

- web/source/css/profile.css
Closes https://github.com/superseriousbusiness/gotosocial/issues/2528
> [bugfix/frontend] Break word on profile field names and values

- internal/gtsmodel/account.go
Closes https://github.com/superseriousbusiness/gotosocial/issues/2552
> [bugfix] fix array type for also_known_as_uris

- docs/configuration/general.md
- example/config.yaml
Same as #2556, but with just the timestamp format fix.
Closes: #2455
> [docs] Fix log-timestamp-format

- docs/configuration/storage.md
* Some slightly nicer sections
* More links to authoritative documentation on the AWS side
* Mention the avatars and headers thing, in relation to #2328
> [docs] Revamp storage migration

- internal/api/client/lists/listaccountsadd_test.go
- internal/api/client/lists/lists_test.go
>
Repenting for my sins by writing a couple of tests for updating list entries, including one that ensures we get back an empty json object when a POST to update list entries is OK.
> [chore] Add a couple tests for updating list entries

- cmd/gotosocial/action/admin/media/list.go
- internal/cleaner/emoji.go
- internal/cleaner/media.go
- internal/db/bundb/emoji.go
- internal/db/bundb/media.go
- internal/db/emoji.go
- internal/db/media.go
- internal/util/slices.go
> [bugfix] fix possible infinite loops in media / emoji cleanup

- docs/configuration/index.md
This adds a small section clarifying how to mount a config.yaml in a container.
> [docs] Mounting config file in container

- .github/pull_request_template.md
> [chore] Add AI check in PR template

- CONTRIBUTING.md
- docs/advanced/caching/api.md
- docs/advanced/caching/assets-media.md
- docs/environment.yml
- docs/getting_started/reverse_proxy/apache-httpd.md
- mkdocs.yml
* Enables a bunch of additional plugins. See the commit for explanations of what they all do
* Update a few pages to use the new tabbed layout
* Upgrade all the dependencies to latest
> [docs] Enable some new features

- docs/getting_started/installation/metal.md
> [docs] Fix a few things in the bare metal install

- CONTRIBUTING.md
Adds two lines describing how to avoid an error `fatal: No names found, cannot describe anything.` that I faced when initially setting up the repo on my machine.
This error happens because, when using the given instructions, `git` doesn't know about any tags.
> [docs] Inform new contributors to `git fetch`

- internal/db/bundb/status_test.go
>
Comments out that annoying TestGetStatusTwice test, which was a) not necessary and b) failing unpredictably on CI/CD and causing headaches.
> [chore] Comment out silly, frequently-failing `GetStatusTwice` test

- internal/processing/status/create.go
- internal/processing/status/create_test.go
>
I noticed that when making a popular reply to a top-level remote status, I couldn't mute the thread from my reply onwards, because it had no threadID.
This PR adds a check to make sure that when creating a local status, it always gets a thread ID even if the parent is remote and not given a threadID. This ensures that you can always mute your own thread.
> [bugfix] Ensure local statuses always get a threadID so they can be muted

- web/source/css/base.css
> [chore/frontend] Use different background color for block quotes

- internal/web/robots.go
>
Blocks the Amazon crawler bot.
Closes: #2686
> [feature] Block Amazonbot

- internal/db/bundb/drivers.go
closes https://github.com/superseriousbusiness/gotosocial/issues/2709
> [bugfix] update postgresqlstmt to correctly use postgres err hook

- docs/federation/federating_with_gotosocial.md
Just updates our "Federating with GoToSocial" docs to clarify some things around HTTP signatures. See https://github.com/superseriousbusiness/gotosocial/issues/1186#issuecomment-1976112180.
> [docs] Update HTTP signature docs a bit

- internal/db/bundb/account.go
- internal/db/bundb/relationship_follow_req.go
Just fixes a few little errors I noticed while working on something else.
> [chore/bugfix] Little DB fixes

- docs/getting_started/installation/metal.md
>
Update the docs to make explicit that admins have to uncomment the `CAP_NET_BIND_SERVICE` line.
See https://github.com/superseriousbusiness/gotosocial/issues/2734
> [docs] Add note about privileged ports

- docs/federation/federating_with_gotosocial.md
- internal/federation/dereferencing/account.go
- internal/federation/dereferencing/dereferencer.go
- internal/federation/federatingdb/accept.go
- internal/federation/federatingdb/announce.go
- internal/federation/federatingdb/create.go
- internal/federation/federatingdb/db.go
- internal/federation/federatingdb/move.go
- internal/federation/federatingdb/move_test.go
- internal/federation/federatingprotocol.go
- internal/gtsmodel/account.go
- internal/messages/messages.go
- internal/processing/workers/fromfediapi.go
- internal/processing/workers/fromfediapi_move.go
- internal/processing/workers/fromfediapi_test.go
- internal/state/state.go
>
This pull request implements processing of incoming Move activities (ie., remote accounts moving from one account to another).
Part of https://github.com/superseriousbusiness/gotosocial/issues/130
~~Still a draft while I write tests.~~
> [feature] Process incoming `Move` activity

- internal/federation/dereferencing/status.go
> [bugfix] only check replyTo visibility during permission checks IF status is local

- internal/db/bundb/errors.go
See (both issue and this specific reply): https://github.com/superseriousbusiness/gotosocial/issues/2774#issuecomment-2014932907
> [bugfix] add all possible busy result codes to the sqlite errBusy catching check

- web/assets/themes/blurple-dark.css
- web/assets/themes/blurple-light.css
- web/assets/themes/midnight-trip.css
- web/assets/themes/sunset-light.css
>
This PR mutes the blurple themes a little bit (especially dark blurple) and ensures the other themes have good contrast. I looked at the previous dark blurple on an oled screen and my retinas still hurt :')
> [chore/frontend] Adjust contrast, mute blurple a bit (meta update: blurple nerfed)

- cmd/gotosocial/action/admin/account/account.go
- cmd/gotosocial/admin.go
- docs/admin/cli.md
- docs/getting_started/user_creation.md
>
This pull request adds an `enable` command to mark `disabled` on a user to `false`. This can be used to undo a previous `disable` command.
Also updates the docs for the new command, and does a little bit of refactoring to highlight which CLI commands require a restart in order for the command to "take". 
> [feature] Add `enable` command to mirror existing `disable` command; update docs

- internal/gtscontext/context.go
- internal/httpclient/client.go
- internal/httpclient/sign.go
- internal/transport/controller.go
- internal/transport/transport.go
- testrig/transportcontroller.go
> [bugfix] httpclient not signing subsequent redirect requests

- internal/httpclient/sign.go
- internal/processing/admin/debug_apurl.go
- internal/transport/deliver.go
- internal/transport/dereference.go
- internal/transport/derefinstance.go
- internal/transport/derefmedia.go
- internal/transport/finger.go
> [bugfix] set the host header within the signing transport

- internal/db/bundb/account.go
> [performance] update GetAccountsByIDs() to use the new multi cache loader endpoint

- web/template/index_what_is_this.tmpl
>
This commit fixed a small error in the "What's This" template page on the site's homepage, which caused the `http://example.com/signup` page that should have been loaded to become the non-functional `http://example.com/#signup` page.
I'm sorry, because I'm not familiar with Git, I had to close a pull request and then reopen it.🤦‍♀️
> [chore] Delete the unnecessary #, because this # lead to the wrong URL.

- internal/db/bundb/application.go
- internal/db/bundb/application_test.go
>
Correct kimbe's grievous and unforgivable error :pray: 
> [bugfix] fix get all tokens

- docs/api/swagger.yaml
- internal/api/client/statuses/status.go
- internal/api/client/statuses/statussource.go
- internal/api/client/statuses/statussource_test.go
- internal/api/model/status.go
- internal/processing/status/get.go
- internal/typeutils/internaltofrontend.go
>
Implement status source endpoint. See https://docs.joinmastodon.org/entities/StatusSource/ and https://docs.joinmastodon.org/methods/statuses/#source
> [feature] Status source endpoint

- docs/admin/robots.md
- internal/web/robots.go
- mkdocs.yml
This updates the robots.txt based on the list of the ai.robots.txt repository. We can look at automating that at some point.
It's worth pointing out that some robots, namely the ones by Bytedance, are known to ignore robots.txt entirely.
> [chore] Update robots.txt

- go.mod
- go.sum
- vendor/modernc.org/sqlite/doc.go
- vendor/modules.txt
underlying SQLite version change is v3.45.2 -> v3.45.3
> [chore] bump modernc.org/sqlite to v1.29.8 (with our concurrency workaround)

- internal/paging/page_test.go
Also replaces the randomly generated IDs with just integer strings, in order, which makes debugging failing tests much easier!
closes #2651
> [bugfix] flaky paging test

- internal/queue/simple.go
It's not quite a memory leak, as all the memory can still get used, it just currently grows during peak times and never shrinks again. This updates it to follow the logic i've used previously in https://codeberg.org/gruf/go-mutexes/src/commit/130931bd8926f053baaaefa7e51ff0a88fe79a60/map.go#L99, so every `const gcfreq = 1024` pops from the queue, it will sweep out the memory pool of list elements.
> [bugfix] function queue memory pools limitlessly grow

- cmd/gotosocial/action/testrig/testrig.go
- docs/admin/request_filtering_modes.md
- docs/configuration/advanced.md
- example/config.yaml
- internal/api/client/admin/headerfilter.go
- internal/api/client/admin/headerfilter_delete.go
- mkdocs.yml
- testrig/config.go
- web/source/settings/components/authorization/index.tsx
- web/source/settings/components/form/inputs.tsx
- web/source/settings/components/pageable-list.tsx
- web/source/settings/lib/query/admin/http-header-permissions/index.ts
- web/source/settings/lib/query/admin/index.ts
- web/source/settings/lib/query/gts-api.ts
- web/source/settings/lib/types/domain-permission.ts
- web/source/settings/lib/types/http-header-permissions.ts
- web/source/settings/lib/types/perm.ts
- web/source/settings/style.css
- web/source/settings/views/admin/http-header-permissions/create.tsx
- web/source/settings/views/admin/http-header-permissions/detail.tsx
- web/source/settings/views/admin/http-header-permissions/overview.tsx
- web/source/settings/views/admin/menu.tsx
- web/source/settings/views/admin/router.tsx
- web/source/settings/views/moderation/accounts/pending/index.tsx
- web/source/settings/views/moderation/accounts/search/index.tsx
- web/source/settings/views/moderation/domain-permissions/detail.tsx
- web/source/settings/views/moderation/domain-permissions/overview.tsx
>
This pull request adds a header permission management section to the settings panel, which allows admins to use the existing header API endpoints to create, view, and delete HTTP header permissions.
closes https://github.com/superseriousbusiness/gotosocial/issues/1296
> [feature] Add HTTP header permission section to frontend

- web/source/settings/components/error.tsx
- web/source/settings/components/form/inputs.tsx
- web/source/settings/components/form/mutation-button.tsx
- web/source/settings/lib/form/file.tsx
- web/source/settings/style.css
- web/source/settings/views/admin/emoji/local/new-emoji.tsx
>
closes https://github.com/superseriousbusiness/gotosocial/issues/2868 by resetting emoji shortcode + category on upload (success or failure)
as a sneaky extra, make it possible to dismiss errors with a little button
> [bugfix/frontend] Fix emoji values not resetting on upload

- web/source/settings/style.css
- web/source/settings/views/moderation/domain-permissions/overview.tsx
Fix small styling issue in frontend, and ensure correct link to import/export page.
> [chore] Small styling + link issues

- docs/configuration/general.md
This PR fixes a 404 URL link in general configuration.
> [docs] Fix link in general configuration

- cmd/gotosocial/action/server/server.go
- cmd/gotosocial/action/testrig/testrig.go
>
Just a few little tweaks to startup:
- Just get state pointer once (everything state is passed to wants a pointer).
- Return error if cache sweep can't be scheduled.
> [chore] little startup tweaks

- .drone.yml
- internal/db/bundb/notification_test.go
>
This pull request updates our CI test runs to:
- increase the timeout
- use the same build flags that we use when compiling the binary for real
- have drone steps run sequentially so one step doesn't get slowed down by another
- use wasmsqlite3 for tests (it's about twice as fast in this scenario)
Also removes some of the fmt.Printf lines from the notifs test, which was misleading.
If this is a documentation change, only the first checkbox must be filled (you can delete the others …
> [chore] Fiddle with CI tests; use wasmsqlite3

- docs/api/swagger.yaml
- internal/api/client/filters/v1/filterpost.go
- internal/api/client/filters/v1/filterput.go
- internal/api/client/filters/v2/filterkeyworddelete.go
- internal/api/client/filters/v2/filterkeywordpost.go
- internal/api/client/filters/v2/filterkeywordput.go
- internal/api/client/filters/v2/filterpost.go
- internal/api/client/filters/v2/filterput.go
- internal/api/client/filters/v2/filterstatusdelete.go
- internal/api/client/filters/v2/filterstatuspost.go
- internal/gtsmodel/filter.go
- internal/typeutils/internaltofrontend.go
This pull request:
- adds and uses a `Filter.Expired` method for consistency with `UserMute.Expired`
- adds missing Swagger docs for filter keyword and status DELETE operations
- documents filter PUT/POST operations that will 403 when the account has moved
> [bugfix] Filter fixes

- docs/api/swagger.yaml
- docs/user_guide/settings.md
- internal/api/client/user/passwordchange.go
- internal/api/model/instancev1.go
- internal/api/model/instancev2.go
- internal/config/helpers.gen.go
- internal/typeutils/internaltofrontend.go
- web/source/settings/lib/types/instance.ts
- web/source/settings/views/user/settings.tsx
>
Adds `oidc_enabled` to instance configuration api model, and warns in settings panel when OIDC is enabled that the user won't be able to change their password via the panel. Also adds a line about email address.
> [chore] Warn about email/password change when using OIDC

- docs/api/swagger.yaml
- internal/api/client/polls/polls_vote.go
Updates the Swagger spec to match the router.
Fixes #2994
> [bugfix] Correct Swagger path for poll voting

- internal/processing/account/follow.go
- internal/processing/workers/fromclientapi.go
>
This pull request moves the `targetAccount.IsLocal() && !*targetAccount.Locked` check back to the client API worker, to ensure that side effects for following local unlocked accounts are still processed (notif created, stats incremented, etc).
Previously, for local unlocked accounts we were just immediately accepting the follow request and passing nothing back to the clientAPI, which meant no side effects.
Closes https://github.com/superseriousbusiness/gotosocial/issues/2993
Closes https://github.com/superseriousbusiness/gotosocial/issues/2813
Please put an x inside each …
> [bugfix] Ensure side effects handled for local unlocked follows

- internal/db/bundb/notification.go
- internal/db/bundb/notification_test.go
>
This pull request fixes an issue where, when clearing notifications for an account with a lot of notifications, GtS would send an absolutely enormous query to the database driver with a list of every ID to be deleted. This was preventing notifications from being cleared successfully. Instead, it now does a simpler delete that returns IDs, and uses that to do cache invalidation. Also avoids doing a bunch of unnecessary SELECTs of notifications, since we have no invalidate callbacks for notifications (I think, unless I'm missing something!).
Please put an x inside each checkbox to …
> [bugfix] avoid v. long notification clear query

- internal/web/robots.go
This syncs our copy with the current state of the ai.robots.txt repository. Upstream has tightened their scope to be AI-only, whereas before it included a bunch of SEO and "web intelligence" marketing stuff. I've kept those but moved them into their own section.
> [chore] Update our robots.txt

- docs/api/authentication.md
Just does a little tidying of the API auth docs, and also adds a bit about `scope`.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3048
Closes https://github.com/superseriousbusiness/gotosocial/issues/3049
> [docs] Tidy up API auth docs a little bit

- internal/processing/workers/surfaceemail.go
This pull request updates the routing endpoint of SignupURL in the sign up email template.
closes #3054
> [bugfix] update SignupURL routing in email template

- web/source/settings/views/admin/actions/keys/expireremote.tsx
- web/source/settings/views/admin/debug/apurl/index.tsx
- web/source/settings/views/admin/emoji/category-select.tsx
- web/source/settings/views/admin/emoji/local/new-emoji.tsx
- web/source/settings/views/admin/emoji/local/overview.tsx
- web/source/settings/views/admin/emoji/remote/steal-this-look.tsx
- web/source/settings/views/admin/http-header-permissions/create.tsx
- web/source/settings/views/admin/http-header-permissions/detail.tsx
- web/source/settings/views/admin/instance/settings.tsx
- web/source/settings/views/moderation/accounts/detail/actions.tsx
- web/source/settings/views/moderation/accounts/index.tsx
- web/source/settings/views/moderation/accounts/pending/index.tsx
- web/source/settings/views/moderation/accounts/search/index.tsx
- web/source/settings/views/moderation/domain-permissions/detail.tsx
- web/source/settings/views/moderation/domain-permissions/form.tsx
- web/source/settings/views/moderation/domain-permissions/overview.tsx
- web/source/settings/views/moderation/reports/detail.tsx
- web/source/settings/views/user/migration.tsx
- web/source/settings/views/user/profile.tsx
- web/template/sign-up.tmpl
>
This PR does some usability tweaks on the frontend:
- Use autocapitalize/spellcheck more appropriately for different form fields.
- Use `type="url"` where appropriate.
- Do domain name validation in form fields that require a domain name.
- Use monospace for more "codelike" fields.
closes https://github.com/superseriousbusiness/gotosocial/issues/3073
> [frontend] Better autocapitalize/spellcheck settings on forms

- go.mod
- go.sum
- vendor/github.com/ncruces/go-sqlite3/conn.go
- vendor/github.com/ncruces/go-sqlite3/func.go
- vendor/github.com/ncruces/go-sqlite3/internal/util/error.go
- vendor/github.com/ncruces/go-sqlite3/registry.go
- vendor/modules.txt
> [chore] Bump ncruces/go-sqlite3 to 0.17.1

- internal/web/robots.go
Recategorises a pair of scrapers according to their use.
> [choore] Update robots.txt

- internal/filter/visibility/home_timeline.go
>
Quick little nil pointer dereference fix.
closes https://github.com/superseriousbusiness/gotosocial/issues/3095
> [bugfix] Fix panic in `isStatusHomeTimelineable`

- internal/api/model/status.go
- internal/api/model/statuscontext.go
- internal/processing/status/context.go
- internal/typeutils/internaltofrontend_test.go
- web/source/css/thread.css
- web/template/thread.tmpl
Just a couple small tweaks and fixes to https://github.com/superseriousbusiness/gotosocial/pull/3093
> [chore/frontend] Tweak threading a bit, inform about hidden replies

- internal/processing/status/create.go
> [chore] Fix typo

- web/assets/themes/soft.css
- web/assets/themes/sunset-light.css
- web/source/css/profile.css
- web/source/settings/components/profile.tsx
- web/source/settings/style.css
- web/source/settings/views/user/profile.tsx
- web/template/profile.tmpl
>
This pull request adds a "bot" checkbox to the settings panel, and shows a "bot" icon on the web view of bot accounts.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3132
> [feature] Allow user to set "bot" flag; show bot icon on profile

- internal/media/ffmpeg.go
> [bugfix] ensure ffmpeg muxer gets set correctly by setting input file extension before clean

- internal/federation/dereferencing/status_permitted.go
- replaces nested if statements with switch cases
- remove defer function getting passed around, instead just call depending on return value
- removes separate inReplyTo / boostOf arguments to ensure it's always from input status (extracts them itself in function first line)
> [chore] small tidying of dereferencer status permissivity

- internal/db/bundb/account.go
- internal/db/bundb/account_test.go
- internal/federation/dereferencing/account.go
- internal/processing/account/rss.go
- internal/processing/fedi/collections.go
- internal/processing/status/pin.go
- internal/processing/workers/util.go
- internal/typeutils/internaltofrontend.go
> [chore] move PopulateAccountStats() nil check often performed into function itself

- go.mod
- go.sum
- vendor/codeberg.org/gruf/go-ffmpreg/wasm/instance.go
- vendor/modules.txt
Updates `go-ffmpreg` to v0.2.4 which encompasses a rebuild with ffmpeg `n5.1.6` and wasi-sdk-24
> [chore] updates our ffmpreg version, heh

- internal/processing/workers/fromclientapi.go
- internal/processing/workers/fromfediapi.go
- internal/processing/workers/util.go
- internal/util/math.go
> [bugfix] updated pinned counts on status delete

- web/source/settings/style.css
- web/source/settings/views/moderation/domain-permissions/overview.tsx
>
Closes https://github.com/superseriousbusiness/gotosocial/issues/3043 by using a submit button instead of a link, and fixing the submit redirect destination.
> [bugfix/frontend] Fix error on submitting domain perm with enter key

- cmd/gotosocial/action/server/server.go
This reduces the amount of memory required on startup as some of the database migrations can end up storing quite a lot of data in memory too. Instead we compile the WebAssembly binaries into usable form later in the server init process.
This also removes the compilation of the sqlite3 binary early on, as by the time we reach this function call it will have already been compiled in order to make database calls.
> [bugfix] move WASM compilation stage much later in server init

- go.mod
- go.sum
- internal/typeutils/internaltoas_test.go
- internal/typeutils/wrap_test.go
- vendor/github.com/superseriousbusiness/activity/streams/util.go
- vendor/modules.txt
>
This pull request updates the activity library to v1.9.0-gts, which brings proper serialization of `@context` entries, and updates tests to include context entries (since they're now determinate so we can test them properly).
closes https://github.com/superseriousbusiness/gotosocial/issues/1947
closes https://github.com/superseriousbusiness/gotosocial/issues/240
> [bugfix] Fix incorrect json-ld `@context` serialization

- web/source/settings/components/error.tsx
>
Fix some of our error parsing logic, we weren't accounting for RTK Query fetch / parse / timeout errors.
closes https://github.com/superseriousbusiness/gotosocial/issues/3221
> [bugfix/frontend] Fix `TypeError: gtsError is undefined`

- internal/db/bundb/filter.go
Add one I missed in https://github.com/superseriousbusiness/gotosocial/pull/3265
> [chore] Don't try to select zero uncached filters

- internal/db/bundb/conversation.go
- internal/db/bundb/filterkeyword.go
- internal/db/bundb/filterstatus.go
- internal/db/bundb/relationship_block.go
- internal/db/bundb/relationship_follow.go
- internal/db/bundb/relationship_follow_req.go
- internal/db/bundb/relationship_mute.go
- internal/db/bundb/timeline.go
Continuation of https://github.com/superseriousbusiness/gotosocial/pull/3266 and https://github.com/superseriousbusiness/gotosocial/pull/3265
> [chore/performance] Further reduce nil uncached queries

- internal/web/robots.go
> [chore] More AI blocking

- web/assets/themes/ecks-pee.css
Just a lil tweak, the font size was way too big (oops).
> [chore] Change ecks pee font size to large

- go.mod
- go.sum
- vendor/modules.txt
we saved 4 whole bytes per WebAssembly binary :D
> [chore] update go-ffmpreg v0.2.5 -> v0.2.6

- web/source/settings/views/user/export-import/export.tsx
- web/source/settings/views/user/export-import/import.tsx
Just fix a couple docs links I buggered up
> [chore] Fix import/export links on settings panel

- web/assets/themes/brutalist-dark.css
Just adds a color-inverted version of the brutalist theme, and tidies up a few little issues with the OG brutalist theme.
> [feature/frontend] Add dark version of brutalist theme

- internal/ap/extract.go
Whoops! Thanks @NyaaaWhatsUpDoc for spotting this.
> [bugfix] Fix incorrect policy value parsing

- internal/federation/federatingdb/accept.go
I'm the silliest person in the entire world.
> [bugfix] Fix pending approval check

- web/assets/themes/ecks-pee.css
Some cheeky tweaks to give more of an ecks pee feel.
> [chore/frontend] Make ecks pee theme even more ecks pee er

- web/source/css/base.css
Just tweak blockquotes to make padding more consistent, and not use the border-radius.
> [chore/frontend] Tweak blockquote formatting

- internal/email/sender.go
>
Same as https://github.com/superseriousbusiness/gotosocial/commit/6783c6057c2dc3d1b27a97487cf1967d3030ba87 but with some formatting fixes.
closes https://github.com/superseriousbusiness/gotosocial/issues/3320
> [bugfix/email] Don't use plainAuth when no smtp username/password provided

- internal/typeutils/converter_test.go
- internal/typeutils/internaltofrontend.go
- internal/typeutils/internaltofrontend_test.go
Fix a lil whoopsie and add a test case for it.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3342
> [bugfix] Fix incorrect reply shown in interaction request

- web/assets/themes/blurple-dark.css
- web/assets/themes/blurple-light.css
- web/assets/themes/ecks-pee.css
- web/assets/themes/midnight-trip.css
- web/assets/themes/rain-forest.css
- web/assets/themes/soft.css
- web/assets/themes/solarized-dark.css
- web/assets/themes/solarized-light.css
- web/assets/themes/sunset-light.css
Gentle theme tweaking to fix some contrast + performance issues.
> [chore] Fix some contrast issues in themes; performance tweaks

- web/assets/themes/solarized-dark.css
- web/assets/themes/solarized-light.css
There were still a couple contrast issues with solarized, it's a right fiddly bugger.
> [chore] final bits of fiddling with solarized

- docs/advanced/index.md
- docs/advanced/sqlite-networked-storage.md
- docs/getting_started/index.md
- mkdocs.yml
This updates our documentation to include warnings against running SQLite on networked storage.
It also slightly reorganises and consolidates some admonitions on the Getting Started page because it was getting a bit too busy with repeated information.
Relates to: #3360
> [docs] Don't run SQLite on networked storage

- internal/processing/common/status.go
Closes https://github.com/superseriousbusiness/gotosocial/issues/3379
> [bugfix] Don't try to add nil filtered statuses to context

- internal/db/bundb/interaction.go
- internal/db/bundb/migrations/20241005100438_interaction_requests_pending_tweak.go
>
URIs on interaction requests can be nil now if they're implicit rejections, so this PR just updates the way pending interaction requests are selected to account for this.
> [bugfix] Update select of pending interaction requests to account for potential nil URI

- web/assets/themes/moonlight-hunt.css
- web/assets/themes/solarized-dark.css
Just a few tweaks to bring solarized dark in line with the way it's usually used, and also make the ombre on buttons in moonlight hunt a bit less elaborate.
> [chore/themes] Tweak colors on new themes

- internal/federation/dereferencing/status_permitted.go
I just missed a case in https://github.com/superseriousbusiness/gotosocial/pull/3404 where statuses should be stored pending approval. This fixes that. I wrote a butt-load of comments to try to make it as clear as possible what's happening and in what order!
> [bugfix] Fix replies not being stored pending approval

- internal/processing/status/context.go
>
Just some tweaks for visibility of web threads!
Closes https://github.com/superseriousbusiness/gotosocial/issues/3341
> [bugfix/frontend] Don't show replies to hidden parents; return 404 if no "main" thread

- .drone.yml
- .goreleaser.yml
> [chore] Create modernc sqlite builds alongside default wasm; add openbsd builds

- cmd/gotosocial/action/server/server.go
- internal/federation/federatingdb/create.go
- internal/federation/federatingdb/db.go
- testrig/federatingdb.go
Check interaction policy properly for incoming Likes, I totally forgot to do this :facepalm:
> [bugfix] Check interaction policies properly on incoming Likes

- README.md
- docs/advanced/builds/nowasm.md
- docs/advanced/index.md
- mkdocs.yml
Document `nowasm` with some big red warning signs that we don't support it officially.
> [docs] Document experimental, unsupported `nowasm` tag

- internal/api/client/streaming/stream.go
>
Jiggle websocket logic to make sure we're only sending a message down the wire if we actually have one to send. Previously we were sending empty messages immediately after pings.
This might be what was causing issues with ice cubes client but I'm not entirely sure yet.
closes https://github.com/superseriousbusiness/gotosocial/issues/3455
> [bugfix] Fix occasionally streaming empty messages

- web/template/about.tmpl
>
This fixes a minor typo in the moderation section of the about page.
> Fix minor typo in About template

- docs/getting_started/reverse_proxy/caddy.md
Copy editing of the Caddy reverse proxy doc
> [docs] Fix typos

- README.md
- docs/locales/zh/repo/README.md
Updates links in README.md to new assets path.
> [chore] update docs assets path

- docs/configuration/storage.md
>
Clarify what to (not) put in `s3-storage-endpoint`
> [docs] Clarify object store configuration

- .drone.yml
- .goreleaser.yml
> [chore] Sign the bloody thing, fix the other bloody thing

- internal/api/client/notifications/notificationsget.go
- internal/api/client/notifications/notificationsget_test.go
- internal/api/util/parsequery.go
- internal/gtsmodel/notification.go
>
We were being a bit too strict in returning bad request for requests for notification types we don't know about yet. This PR updates our logic to just debug log + ignore unknown notification types when requested via `/api/v1/notifications`, instead of returning 400 Bad Request.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3576
> [bugfix] Log + ignore unknown notification types

- go.mod
- go.sum
- vendor/codeberg.org/superseriousbusiness/exif-terminator/jpeg.go
- vendor/codeberg.org/superseriousbusiness/exif-terminator/webp.go
- vendor/modules.txt
See: https://codeberg.org/superseriousbusiness/exif-terminator/releases/tag/v0.9.1
closes #3579
> [chore] pulls in the latest exif-terminator version with bugfix and performance optimizations

- internal/web/thread.go
> [bugfix] Load instance-wide custom css unconditionally in thread details page

- internal/db/bundb/poll.go
- internal/processing/status/create.go
- internal/typeutils/internaltoas.go
a small little change that justs add support for gotosocial creating unending polls!
> [feature] unending polls

- internal/db/bundb/migrations/20241113151042_remove_mention_updated_at.go
- internal/db/bundb/migrations/20241113152126_add_status_edits.go
- internal/db/bundb/migrations/20241121121623_enum_strings_to_ints.go
- internal/db/bundb/migrations/20241203124608_remove_media_attachment_updated_at.go
Log step-by-step during new migrations so admins know what's going on.
> [chore] Log during potentially long migrations

- internal/cache/db.go
- internal/gtsmodel/status.go
- fixes status edits getting cached in the status object
- fixes slice allocation in status.AllAttachmentIDs()
> [bugfix] more little edit fixes

- internal/web/robots.go
Updates our `robots.txt` to include more AI bots.
> [chore] Update robots.txt with more AI bots

- internal/api/client/admin/domainpermissionsubscriptiontest_test.go
- internal/processing/admin/domainpermissionsubscription.go
- internal/subscriptions/domainperms.go
- internal/subscriptions/subscriptions_test.go
- internal/typeutils/internaltofrontend.go
Fix a few happy little accidents in the previous PR.
> [bugfix] More permissive CSV parsing for perm subs, text parse fix

- internal/federation/federatingdb/undo.go
- internal/processing/workers/fromfediapi.go
- internal/processing/workers/fromfediapi_test.go
>
This pull request process incoming announce undos properly, deleting the boost + invalidating boost + boosted status.
~~Will write a test for it later today.~~
closes https://github.com/superseriousbusiness/gotosocial/issues/3657
> [feature] Process incoming Undo Announce properly

- docs/configuration/trusted_proxies.md
- internal/api/util/template.go
> [chore] Allow suppressing trusted-proxies warning by disabling rate limiting

- internal/db/application.go
- internal/gtsmodel/token.go
- internal/httpclient/client.go
- internal/webpush/realsender.go
- internal/webpush/realsender_test.go
- internal/webpush/sender.go
- adds some missing code comments
- shifts around some interface handling
> [chore] some tidy ups

- internal/federation/dereferencing/account.go
- internal/federation/dereferencing/account_test.go
- internal/federation/dereferencing/dereferencer_test.go
> [bugfix] harden account dereferencing logic

- internal/typeutils/internaltofrontend.go
> [bugfix] fix boost of account ID check

- docs/api/swagger.yaml
- internal/api/client/push/pushsubscriptionpost.go
- internal/api/client/push/pushsubscriptionpost_test.go
- internal/api/client/push/pushsubscriptionput.go
- internal/api/client/push/pushsubscriptionput_test.go
- internal/api/model/webpushsubscription.go
- internal/db/bundb/migrations/20250131184755_add_web_push_subscription_policy.go
- internal/gtsmodel/webpushsubscription.go
- internal/processing/push/create.go
- internal/processing/push/update.go
- internal/typeutils/frontendtointernal.go
- internal/typeutils/internaltoas_test.go
- internal/typeutils/internaltofrontend.go
- internal/webpush/realsender.go
- internal/webpush/realsender_test.go
- testrig/testmodels.go
> [feature] Implement Web Push notification policy

- internal/processing/fedi/wellknown.go
> [bugfix] Fix wrong nodeinfo version

- README.md
Updates our README's support matrix to better reflect state of wazero and WASM sqlite compiler / interpreter support.
> [chore] update readme support matrix

- internal/media/ffmpeg/wasm.go
Thanks to @ncruces for pointing this out and the suggested fix!
> [bugfix] temporary workaround for tetratelabs/wazero#2365 armv8 compiler support bug

- docs/admin/settings.md
- docs/federation/posts.md
While reviewing the documents, I found a broken link and created this separate PR to fix it. 
I'm still looking into other document modifications, so I've marked it as a draft for now.
> [chore] fix typo in docs

- internal/webpush/realsender.go
This change to `webpush-go` options lets us send Web Push notifications that are small enough to fit through the APNS relays used by iOS clients.
I've tested it on `princess.industries` and it fixed my issues with the Feditext APNS relay getting HTTP 413 Content Too Large errors from Apple.
> [bugfix] Reduce Web Push record size

- cmd/gotosocial/action/testrig/testrig.go
- web/source/settings/lib/form/index.ts
Biffed the super simple form hook during a refactor. Fixed!
Closes https://github.com/superseriousbusiness/gotosocial/issues/3748
> [bugfix] Fix missing `hasChanged` func

- internal/processing/status/context.go
>
This pull request fixes a panic when trying to view a public/unlisted reply to a followers-only or otherwise hidden status in the web view. The request will now just return a 404 instead. We might want to change this behavior later, but for now it's better than panicking.
closes https://github.com/superseriousbusiness/gotosocial/issues/3674
> [bugfix] Return 404 when web context target status hidden

- internal/db/bundb/migrations/20241121121623_enum_strings_to_ints.go
- internal/db/bundb/migrations/util.go
Performance fix to drop status visibility index *AFTER* using it to select into the new visibility column.
> [bugfix] Drop status indices AFTER updating visibility

- internal/processing/status/create.go
- internal/processing/workers/fromclientapi.go
simply makes some formatting tweaks (because my brain is *very* **very** normal about how code looks) and adds some more code comments to the recently added backfill status code :). also removed info logging of mentions in backfilled statuses as i'm assuming that was accidental left-in debug logging which could very easily fill up logs when backfilling statuses (even if just mentioning yourself).
> [chore] small formatting tweaks and additions of more code comments

- docs/api/swagger.yaml
- internal/api/client/admin/ruleget.go
- internal/api/client/admin/rulesget.go
> Fix swagger operation descriptions

- docs/user_guide/importing_posts.md
- docs/user_guide/migration.md
- mkdocs.yml
Document the current post import process, including a link to `slurp`.
Fixes #3786
> [docs] Document importing posts

- go.mod
- go.sum
- vendor/modules.txt
Another part of https://github.com/superseriousbusiness/gotosocial/issues/3769
> [chore] go-swagger -> codeberg

- CONTRIBUTING.md
- docs/locales/zh/repo/CONTRIBUTING.md
>
I noticed that some links in CONTRIBUTING.md have changed while reading it, so I went through all the external links and updated the ones that moved.
> [chore] update links in CONTRIBUTING.md

- internal/db/bundb/migrations/util.go
Tested and working with local postgres.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3880
> [bugfix] Fix `length for type varchar must be at least 1` on Postgres

- internal/db/bundb/account.go
Closes https://github.com/superseriousbusiness/gotosocial/issues/3839
> [bugfix] Fix panic when opening instance actor in web view

- go.mod
- go.sum
- vendor/modernc.org/sqlite/lib/mutex.go
- vendor/modules.txt
see: https://gitlab.com/cznic/sqlite/-/tags/v1.36.2
> [chore] bump modernc.org/sqlite to v1.36.2-concurrency-workaround

- internal/api/util/template.go
- internal/processing/account/statuses.go
- internal/web/domain-blocklist.go
- internal/web/profile.go
- internal/web/settings-panel.go
- internal/web/thread.go
- internal/web/web.go
- web/source/blurhash/index.js
- web/source/css/_media-wrapper.css
- web/source/css/_status-media.css
- web/source/css/profile-gallery.css
- web/source/frontend/index.js
- web/source/index.js
- web/source/package.json
- web/source/yarn.lock
- web/template/page.tmpl
- web/template/status_attachment.tmpl
As it says! Adds blurhash functionality in the frontend with javascript enabled, falls back to showing a generic gradient if there's no javascript enabled. Should save us some network requests (don't need to load thumbnail to lay a blur on top of it). Also ups the limit for profile gallery mode web statuses, to present a nice full web view.
Running now at https://goblin.technology/@tobi if anyone wants to poke at it.
> [feature] Use blurhashes in frontend, tidy up gallery view a bit

- archive/nlnet/2025-ngi-zero-commons-fund.md
> [docs] NLnet Grant Application - NGI Zero Commons 2025

- internal/db/bundb/migrations/20250310144102_application_management.go
Add WHERE clause to users migration query to fix postgres complaining.
> [bugfix] Fix update users query in migration

- web/source/settings/lib/query/user/index.ts
- web/source/settings/style.css
- web/source/settings/views/user/profile.tsx
That's it! It's just a small addition to the settings panel.
Closes https://github.com/superseriousbusiness/gotosocial/issues/823
> [feature] Allow deleting avatar + header via settings panel

- cmd/gotosocial/action/server/server.go
- internal/api/util/template.go
- internal/config/config.go
- internal/config/defaults.go
- internal/config/flags.go
- internal/config/gen/gen.go
- internal/config/helpers.gen.go
- internal/config/types.go
- internal/config/validate.go
- test/envparsing.sh
closes https://github.com/superseriousbusiness/gotosocial/issues/3701
> [chore] add IPPrefixes type so we don't need separate rate limit parsed field

- web/source/css/_profile-header.css
Make margin/padding a bit more consistent for headers + avatars.
> [chore/frontend] Fix header insets

- internal/gtsmodel/account.go
- internal/processing/account/update.go
- internal/processing/account/update_test.go
- internal/typeutils/internaltoas.go
- internal/typeutils/internaltoas_test.go
Closes https://github.com/superseriousbusiness/gotosocial/issues/3984
> [bugfix] Fix setting bot on/off

- internal/processing/status/create.go
- internal/typeutils/internaltofrontend.go
closes https://github.com/superseriousbusiness/gotosocial/issues/3992
> [bugfix] ensure 'none' gets included in serializable visibilities

- internal/api/client/streaming/stream.go
Should fix: https://github.com/superseriousbusiness/gotosocial/issues/3996
> [bugfix] websocket header token not always returned

- web/assets/themes/midnight-trip.css
- web/assets/themes/solarized-dark.css
- web/assets/themes/solarized-light.css
- web/source/css/_colors.css
- web/source/css/_media-wrapper.css
- web/source/css/_status-media.css
- web/source/frontend/index.js
- web/source/settings/components/blurhash.tsx
- web/source/settings/components/form/inputs.tsx
- web/source/settings/components/status.tsx
- web/source/settings/views/admin/http-header-permissions/overview.tsx
- web/source/settings/views/moderation/domain-permissions/drafts/index.tsx
- web/source/settings/views/moderation/domain-permissions/excludes/index.tsx
- web/source/settings/views/moderation/domain-permissions/form.tsx
- web/source/settings/views/moderation/domain-permissions/subscriptions/common.tsx
- web/source/settings/views/moderation/reports/search.tsx
- web/source/settings/views/user/applications/search.tsx
- web/source/settings/views/user/interactions/search.tsx
Images weren't being scaled properly on chrome! This fixes that!
Also fixes shortcut keys for buttons and show/hide media not working properly on chrome.
And as a treat, adds blurhash to reports in the settings panel.
> [bugfix/frontend] Fix photoswipe layout issues, keyboard shortcuts

- web/template/profile-gallery.tmpl
- web/template/profile.tmpl
Fixes a little error with recent heading ID.
> [chore/frontend] Fix id on recent posts/media heading

- web/source/settings/views/moderation/domain-permissions/form.tsx
Fix the thing I just broke -_-
> [chore/bugfix] fix import file on click

- internal/api/util/robots.go
Fuck "AI" and death to capitalism.
> [chore] Update robots.txt with latest ai bullshit

- docs/api/swagger.yaml
- internal/api/client/statuses/statushistory.go
- web/source/settings/components/status.tsx
- web/source/settings/lib/types/status.ts
Tweak the settings panel report view a tiny bit; remove "unimplemented" warning from status history.
> [chore] Little settings panel report view tweak

- web/template/2fa.tmpl
- web/template/sign-in.tmpl
As it says! Just tweaks some of the sign in HTML forms a bit to use some handy attributes.
> [feature/frontend] add autocomplete + other helpful attributes to auth html pages

- internal/web/profile.go
- internal/web/thread.go
- internal/web/web.go
- web/source/frontend/index.js
- web/source/frontend_prerender/index.js
- web/source/index.js
Comments in the files prettymuch explain what this PR is about: minimizing visible jumping around when progressive enhancement scripts run.
> [chore/frontend] Reorder JS a little bit to avoid visible text changes

- cmd/gotosocial/action/testrig/testrig.go
- internal/api/client/lists/listaccountsadd_test.go
> [chore] fix testrig build
