superseriousbusiness/gotosocial

internal/api/s2s/user/publickeyget.go, internal/api/s2s/user/user.go, internal/gtsmodel/account.go, internal/processing/federation.go, internal/typeutils/converter.go, internal/typeutils/internaltoas.go, internal/util/regexes.go, internal/util/uri.go
now supports serving bare minimum responses to public key requests, so that servers can bypass normal authentication if they just want to get a public key (for example, if two servers who haven't communicated yet are talking to each other)
This solves a case where two gotosocial servers would get stuck in a handshake loop because they kept asking each other GIMME UR PUBLIC KEY and the other one was like NO GIMME YOURS, due to the way authentication worked before
=> separate public key handler

internal/db/pg/pg.go
Drop regex validation for postgres hostname, because it was breaking when running in a docker-compose stack where hostnames can be just one word.
If necessary this can be added in again later, but it probably won't be necessary because it doesn't actually add anything useful!
=> remove regex postgres hostname parsing

internal/federation/federator.go, internal/federation/handshake.go, internal/federation/util.go, internal/processing/federation.go
This PR fixes the annoying infinite handshake bug between two gotosocial servers:
* Add a 'Handshaking' function to the Federator, so that structs with access to a federator can check whether a handshake is currently in progress with a remote user.
* If a handshake is in progress already (ie., we're already dereferencing a remote user) don't try to dereference them again as part of authorization.
In other words, we short-circuit the broken-ass loop by saying 'okay, if these two servers are trying to dereference each other at the same time, just have them give up their information to each other'.
=> fix the annoying infinite handshake bug (tested)

internal/federation/authenticate.go, internal/federation/commonbehavior.go, internal/federation/dereference.go, internal/federation/federatingprotocol.go, internal/federation/federator.go, internal/federation/transport.go, internal/federation/util.go, internal/gtsmodel/instance.go, internal/transport/deliver.go, internal/transport/dereference.go, internal/transport/derefinstance.go, internal/transport/derefmedia.go, internal/transport/finger.go, internal/transport/transport.go
Remote instances are now dereferenced when they post to an inbox on a GtS instance.
* Dereferencing will be done first by checking the `/api/v1/instance` endpoint of an instance.
* If that doesn't work, `/.well-known/nodeinfo` will be checked.
* If that doesn't work, only a minimal representation of the instance will be stored.
A new field was added to the Instance database model. To create it:
`alter table instances add column contact_account_username text;`
=> Remote instance dereferencing

internal/api/client/auth/authorize.go, internal/cliactions/server/server.go, internal/cliactions/testrig/testrig.go, internal/gtsmodel/routersession.go, internal/router/attach.go, internal/router/cors.go, internal/router/router.go, internal/router/session.go, internal/router/template.go, testrig/db.go
* Clean up some of the cookie/session weirdness that was causing half-done logins to persist across authorize attempts.
* Rearrange some of the router code so it's tidier.
* Persist auth and crypt session keys between restarts by storing the router session in the db.
=> clean up some weirdness in the router

internal/api/client/auth/auth.go, internal/api/client/auth/authorize.go, internal/api/client/auth/signin.go, internal/api/model/oauth.go, internal/router/session.go
This PR fixes the auth flow which I managed to break last time!
Previously, we were setting options on cookies like so:
```
s.Options(sessions.Options{
MaxAge:   120,  // 2 minutes
})
```
and what we actually need to do is set them like so:
```
store.Options(sessions.Options{
Path:     "/",
Domain:   cfg.Host,
MaxAge:   120,  // 2 minutes
Secure:   true, // only use cookie over https
HttpOnly: true, // exclude javascript from inspecting cookie
SameSite: http.SameSiteStrictMode,
})
```
Reason: `Path` defaults to `/` if you set no options at all. However, if you set *any* options then `Path` is overwritten to an empty string. Because we were setting MaxAge and not Path, path ended up empty so the browser wouldn't send cookies during the auth flow!
Now it's fixed up so that cookie settings …
=> Auth flow fixes

README.md, go.mod, go.sum, internal/processing/account/create.go, internal/processing/account/update.go, internal/processing/admin/createdomainblock.go, internal/processing/instance.go, internal/processing/media/create.go, internal/processing/media/update.go, internal/processing/status/create.go, internal/processing/status/util.go, internal/util/sanitize.go
This PR adds input sanitization for user-created statuses, media, and profiles, and admin-updated instance settings and descriptions.
To achieve this, we use the following library: https://github.com/microcosm-cc/bluemonday
We can merge this in for now because it's an important safety feature, but we should make another PR later to also run the following through sanitization:
* Incoming statuses from federation
* Incoming instance descriptions and settings
=> sanitize html for statuses + instance

cmd/gotosocial/main.go, example/config.yaml, internal/api/s2s/webfinger/webfingerget.go, internal/config/config.go, internal/config/default.go, internal/processing/federation.go, internal/typeutils/internaltoas.go
This PR adds a differentiation between a host and an accountDomain. As explained in config.yaml:
```
```
This is comparable to Mastodon's differentiation between `LOCAL_DOMAIN` and `WEB_DOMAIN` (https://docs.joinmastodon.org/admin/config/)
=> allow different host + accountDomain

internal/api/s2s/user/followers.go, internal/api/s2s/user/following.go, internal/api/s2s/user/publickeyget.go, internal/api/s2s/user/statusget.go, internal/api/s2s/user/userget.go, internal/api/s2s/webfinger/webfingerget.go
This allows webfinger requests to be served for both `host` and `accountDomain`.
For example, we have a server with `host` of `gts.superseriousbusiness.org` and `accountDomain` of `superseriousbusiness.org`
The following query:
```bash
curl -L "https://superseriousbusiness.org/.well-known/webfinger?resource=acct:test@superseriousbusiness.org"  | jq
```
returns
```json
{
"subject": "acct:test@superseriousbusiness.org",
"aliases": [
"https://gts.superseriousbusiness.org/users/test",
"https://gts.superseriousbusiness.org/@test"
],
"links": [
{
"rel": "http://webfinger.net/rel/profile-page",
"type": "text/html",
"href": "https://gts.superseriousbusiness.org/@test"
},
{
"rel": "self",
"type": "application/activity+json",
"href": "https://gts.superseriousbusiness.org/users/test"
}
]
}
```
and …
=> lil webfingy fix

GETTINGSTARTED.md, cmd/gotosocial/generalflags.go, cmd/gotosocial/letsencryptflags.go, example/config.yaml, internal/config/config.go, internal/config/default.go, internal/config/letsencrypt.go, internal/router/router.go
This PR allows custom ports to be selected for both the GTS webserver/API, and the letsencrypt certificate challenge.
For LE:
```yaml
letsEncrypt:
[...]
port: 80
```
And for the webserver/api port:
```yaml
port: 8080
```
These values can also be set by the cli flags `--port` and `--letsencrypt-port` or by env vars `GTS_PORT` and `GTS_LETSENCRYPT_PORT`
Closes https://github.com/superseriousbusiness/gotosocial/issues/43
=> allow custom ports for webserver and le

internal/federation/federatingdb/accept.go, internal/federation/federatingdb/announce.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/delete.go, internal/federation/federatingdb/followers.go, internal/federation/federatingdb/following.go, internal/federation/federatingdb/undo.go, internal/federation/federatingdb/update.go
This PR makes logging and code more consistent across the various federating DB functions.
It also fixes the 'account was not set on context' errors which were popping up. Basically, these were caused by requests which were coming from inside GtS itself, and not being pushed through the API. The correct way of dealing with these 'errors' is to just ignore them, because they've already been processed elsewhere and aren't actually errors at all, so that's what this PR does.
In other words: is your code logging lots of errors? Remove the error logging line ;)
=> federating db updates

Dockerfile
This PR alters the Dockerfile to compile + bundle the static web assets inside the final Dockerfile, meaning that the build no longer needs to be triggered manually when updating the web stuff.
It also adds a step to pull and build the admin console (https://github.com/superseriousbusiness/gotosocial-admin), so that it's included in the final container at the path: `https://example.org/admin`.
Closes https://github.com/superseriousbusiness/gotosocial/issues/79
=> build and bundle admin console + web assets

cmd/gotosocial/admincommands.go, docs/admin/cli.md, internal/cliactions/admin/account/account.go
This PR adds the command `gotosocial admin account password` for changing the password of an account.
```
NAME:
gotosocial admin account password - set a new password for the given account
USAGE:
gotosocial admin account password [command options] [arguments...]
OPTIONS:
--username value  the username to create/delete/etc
--password value  the password to set for this account
--help, -h        show help (default: false)
```
It also adds some initial documentation for the various CLI commands, and some usage examples.
=> Password change

internal/processing/status/create.go, internal/processing/status/status.go, internal/processing/status/status_test.go, internal/processing/status/util.go, internal/processing/status/util_test.go, internal/text/common.go, internal/text/common_test.go, internal/text/formatter_test.go, internal/text/plain_test.go, internal/util/statustools.go, internal/util/statustools_test.go, testrig/db.go, testrig/testmodels.go
Closes https://github.com/superseriousbusiness/gotosocial/issues/134
From matrix conversation:
The problem was exactly here: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/text/common.go#L62
Instead of returning `in` if no matching tags are found, it should return `match`.
So basically what happened in that function was that the hashtagfinderregex matched `#Hashtag` in the string, then it started iterating through the list of tags looking for the replacement... HOWEVER, `tag.Name` was automatically lowercased by some of the text parsing functionality from earlier
which means that `strings.TrimSpace(match) == fmt.Sprintf("#%s", tag.Name)` was not true
so the fallback behavior was to return in, which is the whole status
so #Hashtag was being replaced by ALL of in
so …
=> Text duplication fix

.drone.yml, internal/db/pg/timeline.go, internal/processing/processor.go, internal/processing/timeline.go, internal/timeline/get.go, internal/timeline/get_test.go, internal/timeline/index.go, internal/timeline/index_test.go, internal/timeline/manager.go, internal/timeline/manager_test.go, internal/timeline/prepare.go, internal/timeline/timeline.go, internal/timeline/timeline_test.go
This PR:
1. Fixes some bugs in the timeline code where an infinite db-fetching loop was occurring and eating up precious CPU and mem.
2. Removes the pre-caching of timelines on startup -- now they're just cached on first GET to timeline instead.
3. Adds a bunch of tests for timelines where there were 0 before!
4. Modifies the drone.yml to cache some go artifacts between runs.
=> Timeline loop fix

internal/db/bundb/account_test.go, internal/db/bundb/basic_test.go, internal/db/bundb/bundb_test.go, internal/db/bundb/mention_test.go, internal/db/bundb/relationship_test.go, internal/db/bundb/status_test.go, internal/db/bundb/timeline_test.go, internal/processing/fromclientapi.go, internal/processing/fromcommon.go, internal/processing/fromfederator.go, internal/processing/fromfederator_test.go, internal/processing/notification_test.go, internal/processing/processor.go, internal/processing/processor_test.go
This PR fixes a tiny issue with reblog/boost notifications not being created (replacing `==` with `!=` in one file -- https://github.com/superseriousbusiness/gotosocial/pull/193/files#diff-4702c34f947db9e2ac6ce9f82430f5ac32d518f76ba4dc3e9963383a2d2f9499R255), and adds some tests to validate that notifications are created when a boost/reblog is processed.
It also adds a couple of tests elsewhere, and tidies up some existing tests.
closes #170
=> tests + announce notification fix

internal/api/client/account/account_test.go, internal/api/client/account/accountupdate.go, internal/api/client/account/accountupdate_test.go, internal/api/client/account/accountverify_test.go, internal/cliactions/admin/account/account.go, internal/db/basic.go, internal/db/bundb/basic.go, internal/db/bundb/basic_test.go, internal/federation/dereferencing/status.go, internal/processing/account/account_test.go, internal/processing/account/update.go, internal/processing/account/update_test.go, internal/processing/admin/createdomainblock.go, internal/processing/admin/deletedomainblock.go, internal/processing/instance.go, internal/processing/media/update.go
This PR fixes accounts not being updated correctly through the /api/v1/accounts/update_credentials endpoint.
The issue was with the account update processing function calling updateOneByID with a struct with no ID (!!). See https://github.com/superseriousbusiness/gotosocial/compare/update_credentials_fix?expand=1#diff-11c4e2344b724d635e09d01f642aeeb00c9928298caa96746a79e5f19cf55d43R42-R115.
This has been fixed.  The database interface function has also been renamed and changed, to avoid this kind of error in future.
Also tests!
=> fixes + db changes

internal/typeutils/internaltoas.go
Remove the cache for ActivityStreams serialization of Accounts, which are liable to change. Keep the cache for AS statuses, which are less change-prone.
=> only store statuses in the AS cache, not accounts

internal/db/bundb/bundb.go
This PR tweaks some of the bundb database settings following the guidelines described in the bun docs here: https://bun.uptrace.dev/postgres/running-bun-in-production.html#database-sql
=> tweak db settings slightly

internal/processing/fromclientapi.go, internal/processing/fromcommon.go, internal/processing/fromfederator.go, internal/processing/fromfederator_test.go
This PR fixes an issue where notifications were being streamed to a user for faves on statuses owned by other people.
The issue was caused by GtS assuming that any faves that arrived in an inbox should be faves of a status created by the inbox owner. However, other implementations like Misskey seem to federate faves by an account to all followers of that account, regardless of who actually posted the status.
The fix was to check who the fave was directed at before streaming a notification, rather than just assuming that the inbox owner and the status fave target owner are the same.
=> Weird notif issue

internal/federation/federatingdb/followers.go, internal/federation/federatingdb/following.go
This PR allows the following/followers federatedDB functions to continue if there's an error fetching a particular account while selecting an account's followers or following. This can happen in cases where an account has just been deleted, for example.
=> skip account on error instead of returning error

internal/api/s2s/user/inboxpost_test.go, internal/api/s2s/user/user_test.go, internal/federation/federatingdb/delete.go, internal/processing/account/delete.go, internal/processing/fromfederator.go, internal/processing/fromfederator_test.go, internal/processing/processor_test.go
This PR brings federated account deletes in line with the same behavior used when suspending an account or doing a domain block: remove account's statuses, follows, etc, etc, etc, etc, and just leave a stub of the account in the database.
Addresses #253
=> handle remote account deletion more systematically

internal/regexes/regexes.go, internal/util/statustools_test.go
This PR updates our mention finder regex very slightly to avoid finding mentions incorrectly within links. Solution was to add a little bit to the beginning of the regex specifying that we want either a line beginning or some kind of whitespace to precede a mention, otherwise skip it.
Also add a test for this.
See the regex in action here: https://regex101.com/r/G1oGR0/1/
PR also removes a bit of the weirdness in the regex which I don't know why I put there in the first place!
Closes https://github.com/superseriousbusiness/gotosocial/issues/223
=> don't catch mentions within links

internal/text/common.go, internal/text/common_test.go
This PR fixes an issue where if one mentioned oneself, and posted a link to one's own status, the link would be formatted as a mention (!!).
The solution was to rework the mention replacement function in `text` to replace only exact regex matches, in line with the way we replace tags.
=> rework mention replacement func

internal/processing/fromclientapi.go, internal/processing/fromcommon.go, internal/processing/fromfederator.go, internal/processing/fromfederator_test.go, internal/processing/processor_test.go
This PR adds auto-acceptance of follow requests from the federating API, when targeted at a local account that's not locked.
Closes https://github.com/superseriousbusiness/gotosocial/issues/219
=> Follow request auto approval

internal/federation/federatingdb/accept.go, internal/federation/federatingdb/announce.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/undo.go, internal/federation/federatingdb/update.go, internal/federation/federatingdb/util.go
When you create a *logrus.Entry from a *logrus.Logger and then check entry.Level it always shows as 0 (ie., no logging) even when the logger you created it from had something like 5 (debug logging).
This meant that logs where the level is checked first based on the created Entry weren't working properly in the federating db.
This PR fixes that by checking the level from the Logger instead of the Entry created from it.
=> fix logs not working properly

internal/ap/extract.go, internal/ap/extract_test.go, internal/ap/extractvisibility_test.go, internal/ap/interfaces.go, internal/api/s2s/user/inboxpost_test.go, internal/typeutils/astointernal.go, internal/typeutils/converter.go, internal/typeutils/internaltoas.go, internal/typeutils/wrap.go, testrig/testmodels.go
This PR fixes up and tests visibility derivation for messages coming in over the federation API. It consolidates the separate logics for checking visibility of announces and notes, and moves it all to the `ap` package with the other extract functions. Also adds tests for expected visibility behavior.
closes https://github.com/superseriousbusiness/gotosocial/issues/267
=> Derive visibility fixes

internal/db/bundb/admin.go, internal/db/bundb/admin_test.go
This PR updates the instance account creation logic to use the `Exists` function in the db conn wrapper when checking if an instance account has already been created.
Closes https://github.com/superseriousbusiness/gotosocial/issues/217
=> Fix instance account not being created

internal/db/bundb/account.go, internal/db/bundb/admin_test.go
Fix a broken query in the database for pulling the instance account out of the database.
=> fix broken GetInstanceAccount selector

internal/cliactions/server/server.go, internal/cliactions/testrig/testrig.go
This PR properly initializes the user client module for both the testrig and server commands, fixing a total oversight where we were doing all the legwork for the user module, but not actually attaching it to the router -_-
Addresses #https://github.com/superseriousbusiness/gotosocial/issues/318
=> fix 404 on POST to `/api/v1/user/password_change`

cmd/gotosocial/generalflags.go, docs/configuration/general.md, example/config.yaml, internal/config/config.go, internal/config/default.go, internal/router/router.go
This PR adds a configuration option for setting the bind/listen address of the GoToSocial server, for both https and http / letsencrypt. It supports both ipv6 and ipv4 configurations. The default listens on all interfaces; for most users this probably won't be necessary to change.
Closes #307
=> add bindAddress configuration option

internal/processing/media/create.go, internal/processing/media/update.go, internal/text/caption.go, internal/text/caption_test.go, internal/text/common_test.go, internal/text/formatter_test.go, internal/text/link_test.go, internal/text/markdown_test.go, internal/text/plain_test.go
This PR implements a SanitizeCaption function in the text formatter for processing image descriptions. It's similar to other text-formatting functions in that package, but it doesn't format text into html, it just preformats, unescapes, and postformats.
This resolves an issue where characters like `'` were being HTML-escaped in image captions, which led to weird-looking alt-text.
Closes https://github.com/superseriousbusiness/gotosocial/issues/305
=> Fix image description unnecessarily html-escaping innocent characters

cmd/gotosocial/generalflags.go, docs/configuration/general.md, example/config.yaml
IPv6 has a dedicated prefix for documentation and examples, this commit makes use of it for `BindAddress` config flag docs and examples.
=> Use IPv6 doc prefix for docs

cmd/gotosocial/accountsflags.go, cmd/gotosocial/admincommands.go, cmd/gotosocial/commands.go, cmd/gotosocial/main.go, cmd/gotosocial/runaction.go, cmd/gotosocial/servercommands.go, cmd/gotosocial/testrigcommands.go, internal/api/client/auth/auth_test.go, internal/config/config.go, internal/config/default.go
See here for explanation (very tall wall of text  warning ) https://picopublish.sequentialread.com/files/chatlog_2021_11_18.txt
It works like this (NEW) as of commit 4c5fa42565abd1988e1f5297a1ab74784e3885ca
```
forest@thingpad:~/Desktop/git/gotosocial$ GTS_HOST=localhost  GTS_ACCOUNTS_OPEN_REGISTRATION=true go run ./cmd/* server start 
INFO[0000] f.IsSet(fn.AccountsOpenRegistration): true   
time=2021-11-18T20:58:16-06:00 level=fatal msg=error creating dbservice: db connection error: failed to connect to `host=localhost user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
exit status 1
forest@thingpad:~/Desktop/git/gotosocial$ GTS_HOST=localhost   go run ./cmd/* server start 
INFO[0000] f.IsSet(fn.AccountsOpenRegistration): false …
```
=> Fix broken defaults and broken flags

docs/user_guide/posts.md
This PR adds user documentation for the different privacy settings on posts that GoToSocial offers, as well as the extra flags that GtS allows on posts.
Closes #326
=> document post privacy settings and extra post flags

internal/router/router.go
I got a bit confused when trying to start `gotosocial server`, because it was failing to bind to `:80`, when I was asking it to bind to `:8080`. Turns out that's the let's encrypt port!
Since this will fail when running as non-root (without `CAP_NET_ADMIN`, at least), or if something like nginx is already hogging that port, we should probably make the error a bit more obvious, and add some logging for good measure.
(Maybe it's just me, but I like it when software tells me when it's opening ports and stuff.)
=> Log when listening

internal/api/negotiate.go
This PR relaxes the content-negotiation function in the API package, ensuring that *something* will be returned to a caller even if they have no content-type set in their Accept header.
This is achieved by returning the first content-type on offer when no Accept header is set.
This works around an issue where Tusky doesn't present Accept headers when making API requests.
=> Return first content-type when no Accept header is set

internal/api/client/media/mediacreate.go, internal/api/client/media/mediaupdate_test.go
This PR adjusts the checks when first creating POSTing new media to remove the minimum description check.
The description length check when updating media still exists.
This gives users the chance to edit their description before the server gets arsey at them for the description not being long enough.
closes https://github.com/superseriousbusiness/gotosocial/issues/338
=> [bug] Fix minimum description length check

docs/configuration/database.md, example/config.yaml, internal/db/bundb/bundb.go, internal/db/bundb/bundbnew_test.go
This PR updates the docs to better explain what `db-address` means for sqlite, and also adds a check in bun that will fail if no `db-address` has been set, when creating an sqlite connection. This should avoid weird scenarios where it looks like a db has been created, but GoToSocial fails trying to access it.
Closes https://github.com/superseriousbusiness/gotosocial/issues/363
=> [bug] Fix sqlite empty address issue

docs/installation_guide/binary.md
When I tried to start the server using the command `./gotosocial server start --config-file ./config.yaml`, I got the following error:
```
root@gotosocial-experiment:/gotosocial# ./gotosocial server start --config-file ./config.yaml
Incorrect Usage: flag provided but not defined: -config-file
NAME:
gotosocial server start - start the gotosocial server
USAGE:
gotosocial server start [command options] [arguments...]
OPTIONS:
--help, -h  show help (default: false)
FATA[0000] flag provided but not defined: -config-file
```
Putting the flag after the `./gotosocial` but before the `server start` seems to work properly
=> Fix start command invocation

internal/processing/federation/getwebfinger.go, internal/typeutils/internaltoas.go
Due to the config changes introduced a while back, GtS was returning malformed webfinger responses if account-domain wasn't set, causing federation problems with Mastodon. This PR should fix this, by using the value for `host` if the value for `account-domain` is an empty string.
=> [bug] Fix malformed webfinger response

internal/api/s2s/webfinger/webfingerget.go
This PR removes content-negotiation for the webfinger endpoint, since a) it's unnecessary anyway and b) seemed to be causing some issues with remote servers.
=> [bug] don't bother negotiating Accept for webfinger

internal/router/session.go
Fixes cookies not being stored/sent by Safari when serving over plain http
=> [bugfix] Only mark cookies as Secure on https

internal/api/client/fileserver/servefile.go, internal/api/model/content.go, internal/processing/media/getfile.go
This PR switches the fileserver to use an io.reader to stream files directly from storage, rather than getting files as a byte blob, holding them in memory, and converting them into a reader. This should make fileserving less memory intensive.
closes #402
=> [feature] Stream files via reader

README.md, go.mod, go.sum, internal/router/gzip.go, internal/router/router.go, vendor/github.com/gin-contrib/gzip/LICENSE, vendor/github.com/gin-contrib/gzip/README.md, vendor/github.com/gin-contrib/gzip/gzip.go, vendor/github.com/gin-contrib/gzip/handler.go, vendor/github.com/gin-contrib/gzip/options.go, vendor/modules.txt
This PR adds a dependency on the gin-contrib gzip middleware, to enable gzip compression on API responses. Tested and working with the testrig.
=> [feature] Gin enable gzip encoding

internal/api/client/fileserver/servefile_test.go, internal/media/manager_test.go, internal/media/processingmedia.go
We were incorrectly setting the image type of thumbnails to `jpeg` instead of `image/jpeg`, which resulted in the wrong content-type being served to callers when retrieving files. This PR fixes that + adds a test for it.
=> [bugfix] Fix thumbnail image type

internal/federation/dereferencing/account.go, internal/federation/dereferencing/media.go, internal/media/manager.go, internal/media/manager_test.go, internal/media/processingemoji.go, internal/media/processingmedia.go, internal/media/types.go, internal/processing/account/update.go, internal/processing/admin/emoji.go, internal/processing/media/create.go
This PR adds a callback to the media manager that will be executed after the data function has been called. This will allow callers to perform additional cleanup of resources etc.
=> [feature] Add postDataCallbackFunc to allow cleanup

.goreleaser.yml
This should build the containers for Linux (amd64, arm64 & arm), I commented out latest here because I added another step here (docker_manifests), this step wants to push the images into dockerhub and build a manifest from it. So you can just do a docker pull from your architecture and the right version will be selected.
Unfortunately I couldn't test the last step properly locally, so in any case the changes need to be tested again before the merge.
But if you don't want goreleaser to push this manifest, you can simply delete the step "docker_manifests" edit the latest tags to `:latest`, `:latest-arm64` & `:latest-arm` or something like that and uncomment the lines.
EDIT:
Sources:
- https://goreleaser.com/customization/docker/?h=docker
- …
=> goreleaser multi Architecture Images

Dockerfile
This will update the Dockerfile to newer Versions:
- node:16.9.0-alpine3.14 -> node:17.6.0-alpine3.15
- node:17.6.0-alpine3.15 -> node:17.6.0-alpine3.15
The upgrade will also fix some vulnerabilities.
The Build is working with the newer versions, but we have to test if everything is working as expected
=> Updates Docker Images in Dockerfile

.dockerignore, .drone.yml, .goreleaser.yml, Dockerfile
This PR enables [buildx](https://docs.docker.com/buildx/working-with-buildx/) to ease multi-arch builds, and adds separate v6 and v7 ARM builds, as well as changing the drone file to build a manifest of `latest` for all architectures instead of just amd64. 
Credit to @0hlov3
=> [packaging] Use buildx for multi-arch Docker builds

internal/processing/status/create.go, internal/processing/status/create_test.go
This PR updates the status create functionality to use text.SanitizeCaption for sanitizing content-warnings of statuses, to avoid html-escaping quotation marks and special characters in CWs.
Closes https://github.com/superseriousbusiness/gotosocial/issues/421
=> [bugfix] Fix html-escaped characters in content warnings

internal/router/router.go, internal/web/base.go
This PR fixes a bug where the admin panel was not accessible at `/admin` but was accessible at `/admin/`. The fix just adds a 301 redirect from `/admin` to `/admin/`, in a similar style to how admin panel access already worked at `/assets/admin`.
Also tidy up some of the serving logic by using absolute paths where appropriate.
Closes https://github.com/superseriousbusiness/gotosocial/issues/377
=> [bugfix] Fix bug where admin panel could not be accessed at `/admin`

cmd/gotosocial/action/server/server.go, internal/transport/controller.go, internal/transport/deliver.go, internal/transport/dereference.go, internal/transport/transport.go, testrig/testmodels.go, testrig/transportcontroller.go
This PR adds logic within the transport controller + transports to skip 'remote' dereferencing of resources that already exist on our instance, and fetch them from the database instead. It also adds logic to skip delivering messages to inboxes owned by our instance, since by definition we're already aware of whatever message is being sent.
=> Dereference shortcuts

docs/api/swagger.yaml, internal/api/client/admin/accountaction.go, internal/api/client/admin/admin.go, internal/api/client/admin/admin_test.go, internal/api/model/admin.go, internal/db/bundb/migrations/20220315160814_admin_account_actions.go, internal/db/bundb/migrations/20220315160814_admin_account_actions/account.go, internal/db/bundb/migrations/20220315160814_admin_account_actions/admin.go, internal/db/bundb/migrations/20220315160814_admin_account_actions/mediaattachment.go, internal/gtsmodel/admin.go, internal/processing/admin.go, internal/processing/admin/accountaction.go, internal/processing/admin/admin.go, internal/processing/processor.go
This PR adds an endpoint for admins to take actions on accounts (`/api/v1/admin/accounts/:id/action`). Currently only the 'suspend' action is available, which will delete/suspend an account.
If a local account is deleted in this way, the action will be propagated out to other instances (To: the account's followers and CC: public).
This allows instance admins to delete accounts on their instances that aren't being used anymore, and also allows them to do targeted suspensions of accounts from other instances that they don't want their instance to be able to interact with anymore, without blocking the entire domain.
This PR includes a database migration which adds a new table to the database: admin_account_actions. This keeps track of which admin has taken action against which account, and …
=> [feature] Admin account actions

internal/media/processingemoji.go, internal/media/processingmedia.go, internal/processing/media/getfile.go, internal/processing/media/util.go
This PR makes some small changes in the media package to make sure that we're properly closing Readers wherever possible. This *might* help with #420, it's running on goblin.technology for testing.
Update: haven't seen any more issues on goblin.technology. However, it's only been running for two days. Still I'm going to merge this in as it can't hurt having these fixes in main anyway, even if they don't end up resolving the issue.
=> [bugfix] Close ReadClosers properly in the media package

internal/ap/extract.go
This isn't an error! So it shouldn't be treated as such.
Closes https://github.com/superseriousbusiness/gotosocial/issues/433
=> [bugfix] Don't error if status has no content

go.mod, go.sum, internal/federation/federatingdb/inbox.go, vendor/github.com/superseriousbusiness/activity/pub/database.go, vendor/github.com/superseriousbusiness/activity/pub/side_effect_actor.go, vendor/modules.txt
This PR updates the dependency on superseriousbusiness/activity (forked from go-fed) to the latest version.
To make it work with this version, the federatingdb 'InboxForActor' function was reworked into 'InboxesForIRI'.
This allows us to save a lot of bandwidth and time by shortcutting dereferences of accounts that follow x account when x account makes a new post and it needs to be federated outwards. Now instead of making lots of remote calls to other instances to dereference the account, the inboxIRI of each following account can be retrieved directly from the database. This speeds up outgoing federation by a huge amount.
=> [dependency] Update superseriousbusiness/activity dependency

internal/router/session.go, internal/router/session_test.go
This is due to a limitation in the cookie library we use.
Closes https://github.com/superseriousbusiness/gotosocial/issues/450
=> [bugfix] Convert IDNs to punycode before using as session name

internal/transport/deliver.go
We had a code path for this before, but it wasn't being properly used. This PR makes sure it is, which *also* makes sure that we don't do silly things like attempt http delivers to our own addresses, which is a total waste of time.
=> [bugfix] Use our own (Batch)Deliver implementation for federated messages

docs/installation_guide/apache-httpd.md, docs/installation_guide/binary.md, docs/installation_guide/docker.md, docs/installation_guide/nginx.md, mkdocs.yml
there are two places where nginx + certbot is explained, unify that into one place.
Add apache httpd, following the same steps, but using mod_md for LetsEncrypt
add a note about #453 in both guides.
Link to both, and call the section reverse proxy, instead of NGINX
=> docs: unify nginx explainers and add apache httpd

docs/installation_guide/websocket.md, mkdocs.yml
This PR adds a document explaining which port, protocol, and headers are used by GoToSocial for making WebSocket connections.
closes #463
=> [documentation] Add WebSocket protocol documentation

internal/api/client/media/media.go, internal/api/client/media/mediacreate_test.go, internal/api/client/media/mediaupdate_test.go
This PR 'implements' the /api/v2/media endpoints to accommodate their use by Tusky version 17 (see https://github.com/tuskyapp/Tusky/issues/2409). The implementation is really just a copy: the same handlers serve both v1 and v2 of the API because it's prettymuch identical.
Closes #462 (tested and working with tusky 17)
=> [feature] Implement media v2 endpoint to accommodate Tusky 17

internal/api/s2s/user/statusget_test.go, internal/api/s2s/user/user_test.go, internal/db/bundb/status.go, internal/processing/federation/getstatus.go, testrig/testmodels.go
This PR makes the status ID case insensitive when fetching statuses out of the database, which means that the web url for statuses is no longer case sensitive. This also means the federating api can also serve statuses in a case-insensitive manner (however it still requires the case of the dereference signature and the request target to match).
closes https://github.com/superseriousbusiness/gotosocial/issues/469
=> [bug] Fix status API / status web API being case sensitive

internal/ap/extract.go, internal/typeutils/astointernal_test.go, internal/typeutils/converter_test.go
This PR fixes a bug where statuses content warnings were sometimes parsed as an IRI by the Activity library if they contain characters like `:`, but GoToSocial would only try extract them as strings. Now GoToSocial attempts to extract content warnings that are either strings or IRIs (which are then converted into plain strings anyway). A test case is added to validate the parsing.
closes https://github.com/superseriousbusiness/gotosocial/issues/456
=> [bugfix] Status iri summary fix

internal/federation/authenticate.go, internal/federation/federatingprotocol.go, internal/federation/federator.go, internal/processing/federation/getfollowers.go, internal/processing/federation/getfollowing.go, internal/processing/federation/getoutbox.go, internal/processing/federation/getstatus.go, internal/processing/federation/getstatusreplies.go, internal/processing/federation/getuser.go
This PR updates some of the signature checking/authentication functionality in two ways:
1. Make the signature for the authorization function simpler (drop the bool), and have it return an error with code instead so that codes logged and returned to callers are more informative.
2. Change the order in which http signature algorithms are checked, to put the most common -- rsa_sha256 -- first. This should same some time/cpu since it's more likely to pass first without having to check more than one algorithm :muscle:
=> [chore] Signature check updates

internal/db/bundb/migrations/20220214175650_media_cleanup.go
The `database/sql` package in the Go stdlib has two methods that can run
queries against the database driver: `Query` and `Exec`. When the query
returns rows, such as "SELECT", the package expects the use of `Query`,
and returns `*sql.Rows`. When the query does not return rows, the
package expects the use of `Exec`, which returns `sql.Result`.
This changeset corrects the "media_attachments" migration to using
`ExecContext`, as "ALTER TABLE" does not return rows.
=> use Exec to rename media_attachments

README.md, go.mod, go.sum, internal/router/router.go, scripts/build.sh, vendor/codeberg.org/gruf/go-debug/LICENSE, vendor/codeberg.org/gruf/go-debug/README.md, vendor/codeberg.org/gruf/go-debug/debug.go, vendor/codeberg.org/gruf/go-debug/debug_env.go, vendor/codeberg.org/gruf/go-debug/debug_off.go, vendor/codeberg.org/gruf/go-debug/debug_on.go, vendor/codeberg.org/gruf/go-debug/pprof_off.go, vendor/codeberg.org/gruf/go-debug/pprof_on.go, vendor/codeberg.org/gruf/go-debug/run_tests.sh, vendor/modules.txt
wrap root HTTP handler in debug.WithPprof(), rearrange router.Start() to support this
=> Add support for running profiling when debug build-tags provided

internal/email/util.go, internal/router/template.go, testrig/router.go
Only attempt to join the `WebTemplateBaseDir` with the current working
directory if the user has not configured an absolute path to the
template directory.
This changeset also makes a similar change to the testrig, allowing
tests to configure an alternative location for the templates directory.
Fixes #411
Signed-off-by: Terin Stock <terinjokes@gmail.com>
=> [feature] allow absolute path to templates

internal/federation/federatingactor.go, internal/federation/federatingactor_test.go, internal/federation/federatingprotocol_test.go, internal/federation/federator_test.go, testrig/testmodels.go
This PR adds a couple of tests for the FederatingActor's Send() function.
It also adds a logrus.Infof() call when a federating activity is being sent out.
=> [chore] Add Federatingactor.Send() tests

docs/installation_guide/binary.md, docs/installation_guide/docker.md
This PR updates the binary + docker installation guides to recommend that users take the latest stable release of GoToSocial when they're doing their deploys.
This should avoid issues where something has been broken on main and we haven't fixed it yet, and users are deploying with `latest` and running into issues (https://github.com/superseriousbusiness/gotosocial/issues/511)
=> [documentation] Recommend users take latest *stable* release in installation guides

internal/api/s2s/user/statusget.go, internal/db/bundb/account.go, internal/db/bundb/conn.go, internal/db/bundb/domain.go, internal/db/bundb/domain_test.go, internal/db/bundb/relationship.go, internal/db/bundb/relationship_test.go, internal/db/bundb/status.go, internal/db/bundb/trace.go, internal/federation/federatingprotocol.go, internal/processing/admin/createdomainblock.go, internal/processing/federation/getstatus.go, internal/web/thread.go
This PR:
1. Removes use of the `LOWER()` db function where it wasn't necessary (this function prevented the db indexes from working properly).
2. Swaps the db exists function from using `COUNT(*)` to using `EXISTS`, which should be faster.
3. Reworks the blocked function to always present params in the order that's been indexed.
4. Adds a warning level log when db queries take longer than 1s to help debugging.
closes https://github.com/superseriousbusiness/gotosocial/issues/520
=> [performance] Speed up some of the slower db queries

internal/db/bundb/migrations/20220502113806_add_missing_indexes.go
This PR adds indexes on the following tables/rows:
`accounts.url`
`accounts.public_key_uri`
`accounts.suspended_at`
`users.account_id`
`tags.name`
`applications.client_id`
`status_faves.account_id`
`status_mutes.account_id,target_account_id,status_id`
closes #522
=> [performance] Add extra database indexes

README.md
This adds a Kubernetes Helm Chart to the "Third-Party Packaging" of the README.md
=> Adds a Kubernetes Helm Chart to README.md

internal/federation/federatingdb/inbox_test.go
This was causing false negatives in tests because there's no guarantee to the order of the slice of inbox iris returned from the db, nor any need to guarantee the order.
=> [chore] Fix inbox iris test to use 'contains' instead of index

README.md
Sorry, since I migrated the Helm-Charts and added a Pipeline to auto build the HelmCharts the URL has changed. :(
=> Corrects the Helm-Chart URL by 0hlov3

docs/installation_guide/binary.md, docs/installation_guide/docker.md
This should help avoid problems like https://github.com/superseriousbusiness/gotosocial/issues/518 where the command-line is interpreting special characters
=> [documentation] put single-quotes around passwords in install docs

internal/media/manager.go, internal/media/manager_test.go, internal/worker/workers.go
By updating the media manager to use the internal/worker package it allows us to neaten up the enqueuing mechanism. I also added some improved logging to the worker pool so when trace is enabled we get an idea of workers state on each queued message.
=> update media manager to use internal/worker package

internal/log/log.go, internal/log/log_test.go
The previous method of looking for level string in the log bytes would perform a very simplistic search for the string `level=error`. So for a log message with `level=info msg="hello world"` it would index past the `level=info`, and keep looking along the rest all the way until the end. This new code makes the output splitting more customizable (and so now includes error, fatal and panic to stderr), makes it more testable, and improves performance by only checking along the log bytes until the first instance of `level=`.
=> improved logrus output switching performance

internal/db/bundb/migrations/20220506110822_add_account_raw_note.go, internal/db/bundb/migrations/20220511165212_add_account_raw_note_fix.go
This PR fixes the database migration script that may have already been run by some users.
To do this, it both:
1. fixes the previous migration script
2. adds a new migration script that repeats the command, which will be run even in cases where the previous migration script already ran
The two scripts above are now identical.
To make sure the migration is idempotent, the updated/added migration script doesn't error out if the column name already exists.
To avoid panicking even when this error was checked, the migration is not run in a transaction.
=> [bugfix] Add account raw note fix

internal/router/router.go
This PR fixes a bug where we weren't setting the listen address on the letsencrypt server properly, so that it was trying to listen on whatever port was configured for the main server. This was causing the main listener to then fail because the port was already in use.
This fix tested and working both in nginx with certs handled by nginx, and with a raw binary with certs handled by the built in le
=> [bugfix] Fix server trying to listen twice on same address when LE enabled

internal/log/syslog_test.go, testrig/log.go
On some systems these tests will simply hang, this fixes that.
=> update syslog tests to listen/connect specifically to ipv4 loopback

archive/README.md, archive/nlnet/2022-user-operated-internet-fund.md
This PR adds the funding application submitted for the June 2022 NLNet.nl user operated internet fund, in a new 'archive' folder of the repo.
=> [documentation] Nlnet application

example/gotosocial.service
I don't know systemd so it took me a while to figure out how to run on a privileged port as non-root.
I added it to the example service, commented out.
=> Mention `AmbientCapabilities=CAP_NET_BIND_SERVICE` in example systemd service

internal/visibility/statushometimelineable.go, internal/visibility/statushometimelineable_test.go
This PR adds a recursive check upwards through a status's parent statuses to check whether a status really should be put on the home timeline. If one of the statuses in the parent chain is not home timelineable, then the status being checked will also not be put in the home timeline.
Closes https://github.com/superseriousbusiness/gotosocial/issues/501
=> [bugfix] Stop some statuses from being home timelined when they shouldn't be

docs/installation_guide/caddy.md, mkdocs.yml
This PR adds Caddy instructions to the documentation. It borrows some text from the NGINX document for the configuration of GoToSocial. It doesn't require much configuration, so the installation instruction is actually a little bit easier.
=> Add Caddy instructions to the documentation

internal/typeutils/astointernal.go, internal/typeutils/astointernal_test.go, internal/typeutils/converter_test.go
This PR fixes an issue where if no URL was set on the Note Activity, we were logging an error and not setting a URL. This led to instances where in the UI you go to click on a status to see the web representation, but the link is empty. Now, we take the status URI and save it as the URL for the webview when no URL is available, so the user at least has something to click :)
closes #590
=> [bugfix] If status URL is empty, use URI instead and don't log unnecessary error

internal/ap/extract.go, internal/ap/extract_test.go, internal/ap/extractcontent_test.go, internal/typeutils/astointernal.go
This PR closes https://github.com/superseriousbusiness/gotosocial/issues/565 by updating ExtractContent to just return an empty string if no Content is found in an Activity, since this isn't technically an error, it just means that no text content was set and most likely the post contains a poll or media or something. It also updates the extract content function to check if there's an IRI in the content field, because that's a thing that can sometimes happen.
=> [bugfix] Fix `error extracting status content: no content found`

internal/processing/search.go
This fixes an issue in the search logic where we would sometimes try to search (at length) for an account or status with an unrecognized or empty protocol, since the URI parsing in Go is chill enough to accept `acct:whatever@wherever.whatever` or `whatever@wherever.somewhere` as valid URIs. Now, we only perform remote searches by URI if the parsed URI protocol is `http` or `https`, which saves making pointless http calls that just return with 'unsupported protocol' errors.
=> [bugfix] Only search remote if protocol is http(s)

internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
At /api/v1/instance we were serializing an empty instance account if no instance admin account was set. Silly! This PR fixes that.
=> [bugfix] Don't serialize instance account if not set

internal/processing/streaming/notification_test.go, internal/typeutils/internaltofrontend.go, internal/util/time.go, internal/util/time_test.go
We were running into some problems with the Mastodon android app trying to parse our timestamps as utc ISO8601, when we were using RFC3339 with zone offset.
This means that depending on time zone, a time might look like `2021-11-16T09:46:13Z` or like `2021-11-16T11:46:13+02:00`, the latter of which causes the Mastodon android app to shit its pants.
This fixes the issue by converting all time stamps to utc first and then putting them through a time formatter that matches ISO8601 behavior.
=> [chore] Serialize times as UTC ISO8601 instead of RFC3339

internal/router/session.go
Previously we were using `http.SameSiteDefaultMode` on our session cookies, which (in firefox at least) defaults to Lax. This PR switches our session config to use `http.SameSiteStrictMode` instead, which should make us more secure against CSRF attacks (not that these were much of an issue anyway but you never know).
Tested with the testrig and goblin.technology on Pinafore, both chrome and firefox, and it seems to work fine :)
=> [security] Set SameSite to `strict` instead of browser default

go.mod, go.sum, internal/httpclient/client.go, internal/httpclient/request.go, internal/transport/transport.go, vendor/golang.org/x/net/http/httpguts/guts.go, vendor/golang.org/x/net/http/httpguts/httplex.go, vendor/modules.txt
I, tobi, definitely wrote this code. Kim definitely did not write this. Imagine! Laughable.
=> [performance] Don't retry/backoff invalid http requests that will never succeed

internal/processing/search.go
This PR adds a debug call to a failed GetRemoteAccount call via the search API, instead of just swallowing the error and continuing.
=> [chore] Debug failed account get

internal/transport/dereference.go
This PR adds `application/activity+json` to the Accept header on dereference requests, in addition to the `application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"` value that we already had.
This is a workaround for servers that don't understand `application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"` (like the most recent version of Owncast).
closes https://github.com/superseriousbusiness/gotosocial/issues/610 , since with this fix it's possible now to lookup an Owncast account.
=> [bugfix] Add `accept: application/activity+json` to dereferencer

web/assets/base.css, web/gotosocial-styling/templates/base.css
This way the footer doesn't touch on the content on mobile.
Fixes this issue:
=> Add padding to the bottom of main

web/assets/profile.css, web/gotosocial-styling/templates/profile.css, web/template/profile.tmpl
The commit makes the profile image on the profile page reduce in width
if the screen width is less then it's normal width while maintaining
it's 1:1 aspect ration.
Fixes #614
=> Reduce width of profile img with screen width

.gitignore, .vscode/launch.json, .vscode/settings.json
Having this in the repository will allow any dev using vscode (or forks etc) to automatically get the correct linter and debug run target set up.
=> [feature] add vscode workspace config for linting + debugging

internal/db/bundb/account.go, internal/db/bundb/account_test.go, internal/db/bundb/bundbnew_test.go
This PR fixes an issue where postgres couldn't understand the media_only query that was being passed to it. Now, a different query is built depending on whether the db driver is sqlite or postgres, to account for this.
=> [bugfix] Make accounts media_only query also work with pg

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, internal/api/client/auth/auth.go, internal/api/client/auth/auth_test.go, internal/api/client/auth/authorize.go, internal/api/client/auth/authorize_test.go, internal/api/client/auth/token.go, internal/api/client/auth/token_test.go, internal/api/errorhandling.go, internal/oauth/errors.go, internal/oauth/server.go, internal/processing/oauth.go, internal/processing/processor.go, testrig/testmodels.go
This PR adds a 'created_at' unix timestamp to tokens returned by the `oauth/token` endpoint, to ensure mastodon API compatibility (closes #644).
It also does better validation of input to that endpoint, and returns helpful error messages in the `error_description` field, while remaining oauth compliant by only returning one of the mandated oauth errors in the `error` field. This should make life a little easier for users who are trying to fetch a token, and wondering why it's not working.
This is also relevant to https://github.com/superseriousbusiness/gotosocial/issues/83
=> [feature] Add `created_at` and `error_description` to `/oauth/token` endpoint

internal/federation/dereferencing/thread.go
This PR just tidies up the DereferenceThread function a little bit, renames some variables for clarity, and changes most of the logging to trace to avoid clogging up debug logging too much.
this closes #539 since it clarifies that erroring while dereferencing a single status in a thread shouldn't mess up the whole thread.
also opened an issue on github with Mastodon for an issue discovered while doing this investigation: https://github.com/mastodon/mastodon/issues/18638
=> [chore] Refactor thread dereference a bit for clarity

internal/db/bundb/migrations/20220612091800_duplicated_media_cleanup.go, testrig/config.go, testrig/storage.go
This PR adds a database migration for cleaning up duplicated media caused by https://github.com/superseriousbusiness/gotosocial/issues/587
To do this, it needs to instantiate a storage interface so that the stored media files can be removed; for testing, this fails if the default test storage path of `/gotosocial/storage` is taken, because the gts process doesn't have permissions on that path.
To work around this, this value was changed to `/tmp/gotosocial` (or os-equivalent). The testrig doesn't actually use this directory for anything aside from instantiating the store during that one migration.
Closes #599
=> [chore] Duplicated media cleanup

internal/db/bundb/migrations/20220506110822_add_account_raw_note.go
Database migration `20220506110822_add_account_raw_note.go` has [some error
handling code](https://github.com/superseriousbusiness/gotosocial/blob/13e4bbdbfa104a2384834b634285dce2f4dafe2e/internal/db/bundb/migrations/20220506110822_add_account_raw_note.go#L31) to detect some error messages as "ok", but only done for english error messages.
This adds a check for the specific error code, which should be locale agnostic.
=> postgres locale: fix accounts.note_raw migration

.drone.yml, .goreleaser.yml
This PR updates some of our packaging in the following ways:
1. Bump version of golang to 1.18.3.
2. Bump gotosocial-drone-build to 0.0.5 (which includes bumps to GoReleaser and Docker buildx).
3. Remove the bundled source tarball from releases, since it was misleading and unhelpful.
4. Add a release archive that just contains the bundled web/assets and web/templates folders, to make life easier for people doing ports.
Should close https://github.com/superseriousbusiness/gotosocial/issues/654
However, it doesn't really address the 'tarbomb' point raised in that issue, because while you can instruct goreleaser to embed a root directory inside a tar, it would cause our installation instructions to change, and people would have to run different installation commands for different releases. …
=> [packaging] Packaging updates

internal/api/client/admin/mediacleanup_test.go, internal/federation/dereferencing/status_test.go, testrig/testmodels.go
This PR updates the testrig to avoid unnecessary use of time.Now() where possible. This was preventing tests from being cached properly by our CI/CD system, and resulted in almost all tests being run for every PR, even when code pertaining to those tests was not changed. Now, far more tests should be cached, which will save time, processing power, and errors.
=> [chore] Make tests more cacheable by avoiding time.Now()

web/source/lib/oauth.js
This PR adds `Accept: application/json` by default to oauth api requests by the admin panel. If any other value than "json" is provided in the apiRequest call, accept will instead be `*/*`.
=> [frontend] Add Accept header to oauthed api requests

internal/processing/search.go
This PR updates some of the search logic to not attempt to dereference/resolve URLs that belong to the instance the search was performed on. This caused an issue where an account ended up webfingering itself, which caused all sorts of problems since the finger ended up updating the account's domain, so it wasn't recognized as a local account anymore -_-
=> [bugfix] Account self finger fix

internal/web/thread.go, web/source/css/_colors.css, web/source/css/base.css, web/source/css/profile.css, web/source/css/status.css, web/source/yarn.lock, web/template/header.tmpl, web/template/profile.tmpl, web/template/status.tmpl
building upon restructure in #634
=> [:frog:] Profile pages

internal/api/client/instance/instancepatch_test.go, internal/processing/instance.go
This PR updates the instance PATCH logic to allow users to set an empty email address / clear the email address for their instance.
Closes https://github.com/superseriousbusiness/gotosocial/issues/652
=> [bugfix] allow setting empty email via instance patch

docs/api/swagger.yaml, internal/api/client/instance/instancepatch_test.go, internal/api/model/instance.go, internal/media/util.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
This PR closes #345 by adding the mastodon-style 'configuration' object to the /api/v1/instance response. This will allow client applications to parse certain limits and supported features from the instance.
Some of the values added are hardcoded for compatibility, since they aren't checked yet or indeed settable by instance admins. In future, we can (if necessary) move some of these to a more sensible place and allow them to be set and checked.
---
Example api response:
```json
{
"uri": "http://localhost:8080",
"title": "localhost:8080",
"description": "",
"short_description": "",
"email": "",
"version": "",
"registrations": true,
"approval_required": true,
"invites_enabled": false,
"configuration": {
"statuses": {
"max_characters": 5000,
"max_media_attachments": 6, …
```
=> [feature] add configuration to `/api/v1/instance` response

internal/db/bundb/media.go, internal/db/bundb/media_test.go, internal/db/media.go, internal/media/manager.go, internal/media/pruneremote.go, internal/media/pruneunusedlocal.go, internal/media/pruneunusedlocal_test.go, internal/media/util.go, internal/processing/admin/mediaprune.go
This PR closes #666 by adding some logic for cleaning up local media that was uploaded but never used, or media that was attached to a status which was subsequently deleted.
The time limit to keep unattached media around is currently hardcoded at 3 days. This was chosen because it seems very unlikely that someone would upload media, leave it unattached, and then after 3 days return to it and attach it to a status. Most of the time users upload something and then simply never use it, or they delete and redraft so that the media only stays unused for a few minutes at most.
The cleanup is triggered on instance startup, and every night @ midnight along with the other cleaning jobs. It's also triggerable by an admin calling the `/api/v1/admin/media_cleanup` endpoint
=> [feature] Cleanup unattached local media

.goreleaser.yml
closes https://github.com/superseriousbusiness/gotosocial/issues/662 -- since the source tar is being generated again now, the checksums.txt file is also complete
GoReleaser is weird
=> [chore] Re-enable source tar but name it clearly as source

web/source/css/status.css, web/template/status.tmpl
This PR:
- updates the spoiler text / button div to make it a flexbox so items can wrap without splitting the 'show more' button in half
- allows spoiler text to break so that long one-word spoiler texts won't break the display
- sets the z-index of all status text (spoiler text + show more button + content) higher, so that text can be selected/copy pasted, while still allowing the rest of the status to be clickable
=> [frontend] Fix up status 'show more' and z-index

internal/api/model/timeline.go, internal/db/account.go, internal/db/bundb/account.go, internal/processing/account.go, internal/processing/account/account.go, internal/processing/account/getstatuses.go, internal/processing/processor.go, internal/util/timeline.go, internal/web/profile.go, web/source/css/profile.css, web/template/profile.tmpl
This PR adds 'back to top' and 'next page' links to local account profiles, to allow visitors to the profile to page through more than just the most recent 10 public statuses.
The 'back to top' link is not shown on the first page of profiles (since the user is then already at the 'top').
To support this functionality, a new function has been added to the database that *just* selects statuses that are candidates for viewing on a user's profile (public, non-reply, non-boost, federated statuses).
Closes #https://github.com/superseriousbusiness/gotosocial/issues/583
=> [feature] Add back/next buttons to profiles for paging through statuses

internal/api/client/fileserver/servefile.go
This PR adds the header `Cache-Control: max-age=604800` to the fileserver endpoint, to allow clients to cache files. This should lead to significant bandwidth savings and speed improvements.
=> [performance] Add long cache-control max age to fileserver

internal/httpclient/client.go
Fixes the very minor incorrect pointer copying bug we had by just moving instantiation of the dialer inside the New function.
=> [chore] move dialer inside new, use default resolver

internal/text/markdown.go, internal/text/markdown_test.go
This PR updates markdown post formatting to not use the same postprocessing as plaintext posts, since this was causing issues with html being improperly escaped. Instead, it just sanitizes html in outgoing markdown, instead of escaping it + minifying it.
closes https://github.com/superseriousbusiness/gotosocial/issues/679
=> [bugfix] Markdown format fixes

docs/api/swagger.yaml, internal/api/client/status/statuscreate_test.go, internal/api/model/status.go
This PR fixes the issue of the Toot cli not attaching media correctly to new statuses.
The problem was that when it comes to POST form data, the Mastodon API expects clients to use the key `media_ids[]` for their list of media attachment IDs. However, GtS was just accepting `media_ids`, which works great for json, but not so much for clients that use POST forms like Toot does.
This PR implements a simple fix for this by parsing `media_ids[]` in forms, but still using `media_ids` for json and xml. Tested and working with Toot, and therefore should work for other mastodon clients as well.
closes https://github.com/superseriousbusiness/gotosocial/issues/686
=> [bugfix] Fix Toot CLI media attachments not working properly

internal/api/client/auth/auth.go, internal/api/client/auth/authorize.go, internal/api/client/auth/callback.go, internal/api/client/auth/signin.go, internal/api/client/status/statuscreate_test.go, internal/api/model/oauth.go
This PR adds support for the optional oauth2 'state' request parameter, which was missing before.
See https://www.oauth.com/oauth2-servers/authorization/the-authorization-request/
This also introduces a differentiation between 'internal' state during the flow, and 'client' state.
Internal state is generated by the server for every request, and sent along to oidc providers as necessary.
Client state on the other hand is only set by an incoming client request, and the state param is returned to the client at the end of the flow, just like it was submitted.
This should allow GtS to work properly with clients that submit state to mitigate csrf attacks :)
=> [feature] add 'state' oauth2 param to /oauth/authorize

internal/api/client/status/statuscreate_test.go, internal/oauth/server.go
This PR updates the oauth token response to remove the `expires_in` field completely from the response if the value is less than or equal to 0. According to oauth:
> expires_in (recommended) If the access token expires, the server should reply with the duration of time the access token is granted for.
Since we use 0 to indicate a token that doesn't expire, we should not set this in the response in case clients interpret this to mean that the token is *already expired* as soon as they receive it.
Along with https://github.com/superseriousbusiness/gotosocial/pull/730, this should allow liberapay to work with GoToSocial
=> [bugfix] remove <= 0 `expires_in` from oauth token response

internal/api/client/fileserver/fileserver.go, internal/api/client/fileserver/servefile.go
This PR updates the fileserver endpoint to also serve `HEAD` requests, which is functionality supported by the mastodon API. This should allow liberapay (for example) to properly use GtS avatars as avatars for connected accounts.
=> [feature] serve HEAD requests via the fileserver

web/source/css/status.css
=> [frontend] style blockquote nicely within content

go.mod, go.sum, vendor/github.com/superseriousbusiness/exif-terminator/jpeg.go, vendor/github.com/superseriousbusiness/exif-terminator/terminator.go, vendor/modules.txt
This fixes a bug where too many bytes were getting removed during exif-removal, leading to GtS trying to serve files with incorrect `content-size` header
=> [chore] bump `exif-terminator` to v0.4.0

web/source/css/status.css
- Pad top and bottom of statuses a bit so they're more visually separated from the content warning or avatar at top, and stats at bottom.
- Format `hr` as a dotted orange line.
- Format code a bit nicer, make code blocks horizontally scrollable.
=> [frontend] Status styling tweaks

internal/cache/account.go, internal/cache/account_test.go, internal/db/account.go, internal/db/bundb/account.go, internal/db/bundb/account_test.go, internal/federation/dereferencing/account.go, internal/federation/dereferencing/account_test.go, internal/processing/search.go
This PR updates some of the logic in `GetRemoteAccount` to ensure that accounts from our own instance are never webfingered. This has happened before and causes an issue where the domain of the account is set to `AccountDomain` or `Host`, which means that the account in question is no longer picked up correctly by `GetLocalAccountByUsername`, which causes all sorts of knock-on issues.
Rather than trying to track down + add checks for every instance where callers might be passing a local account into this function, it's easier to just add the logic into `GetRemoteAccount` instead.
Callers should still try to avoid passing local accounts into `GetRemoteAccount` because it's confusing, but at least if they do it now it won't break the account that was passed in.
To support this update, this …
=> [bugfix] Fix potential dereference of accounts on own instance

internal/db/bundb/bundb.go, internal/trans/import_test.go, internal/trans/model/account.go, internal/trans/trans_test.go
This PR updates some of the export/import logic to export more fields from accounts, and adds tests to ensure that account data matches across export/import. To support this, the PR updates the sqlite in-memory implementation to use a different random address per in-memory database, to allow easier testing/comparison of multiple databases.
=> [bugfix] Fix loss of account info on export/import, add tests

internal/processing/status/boost.go, internal/processing/status/boost_test.go
This PR fixes an issue where clients could sometimes boost a boost, instead of the intended behavior of boosting the original status. The fix is to just redirect the target of the boost back to the original boosted status, rather than the boost wrapper status.
closes https://github.com/superseriousbusiness/gotosocial/issues/620
=> [bugfix] Fix boost of boost issue

internal/text/markdown.go, internal/text/markdown_test.go
This PR updates the markdown parsing a tiny bit to:
1. Allow footnotes
2. Replace `\n` with `<br>` in markdown-submitted text (though `\n\n` is still parsed as a separate block, which is good)
3. No longer keep whitespace/newlines in minified html derived from markdown (since we shouldn't use newlines to structure text).
=> [feature] Allow footnotes in markdown, use `<br>` instead of `\n`

internal/api/client/status/statuscreate.go
awesome software! just set up a test instance tonight and ran into this snag. It seems that polls aren't really supported yet, but to get it to work eventually this change will probably be necessary.
When sending a post on tusky, it appears that "form.MediaIDs" isn't nil but instead an empty array. If you try to attach a poll, the post is rejected because this code thinks there's both a poll and media on the status.
On pinafore, this doesn't occur (though the post is still rejected because the expires_in field of the payload is a string and not an int. different problem that probably needs to be fixed in pinafore)
=> validateCreateStatus: Check the presence of form.MediaIDs more thoroughly, instead of just checking for null

web/source/css/status.css
This PR fiddles very slightly with the css to try to make spacing more consistent, and also add a bit of padding after spoiler text and before text content
(it's deployed on goblin.technology so can be previewed there)
=> [frontend] gentle css fiddling

internal/typeutils/internaltofrontend.go
pretty minor change to bring the endpoint more in line with mastodon behaviour. the mastodon implementation of this endpoint puts the original, reblogged status in the "status" field of the "reblog" notification, instead of the reblogging user's status that includes the original status in the "reblog" field. to explain better, here's a "reblog" notification from a mastodon instance:
<details>
<summary>long json snippet</summary>
<pre>
{
&quot;id&quot;: &quot;8977162&quot;,
&quot;type&quot;: &quot;reblog&quot;,
&quot;created_at&quot;: &quot;2022-08-29T03:26:10.907Z&quot;,
&quot;account&quot;: {
&quot;id&quot;: &quot;263434&quot;,
&quot;username&quot;: &quot;aphyr&quot;,
&quot;acct&quot;: &quot;aphyr@woof.group&quot;,
&quot;display_name&quot;: &quot;Bear Traffic Control&quot;, …
=> Adjust the notifications endpoint slightly so the status object of a reblog notification is the original, reblogged post

README.md
I presumed that you want to link directly to your actual collective and not to the open collective homepage, hence this PR. Please disregard if I was mistaken.
=> Fix link to open collective

internal/typeutils/internaltofrontend.go
since the requesting account was nil in the call to StatusToAPIStatus, it couldn't set the favourited flag correctly. so if you favourite a post from a notification then reload notifications, the favourite disappears (even though the favourite was successful)
=> Fix issue where the 'favourited' field of a notification's status is always false

internal/processing/search.go
fixes #68
basically the issue is not using limit/offset, but because the code only ever returns one item, we can underhandedly-implement offset to fix this bug
=> Fix tusky search issue by returning empty if offset is greater than zero

internal/text/markdown.go, internal/text/markdown_test.go
fixes #783. blackfriday lets you specify your own renderer, which gives us more control over where we insert the hashtag/mention links. see: https://github.com/russross/blackfriday/blob/v2/html.go#L508
basically, `blackfriday.Text` signals raw text output, and `blackfriday.Code` signals code block output, so we can avoid making the conversion there.
caveat: posting something like:
```
_#hashtag_
```
doesn't turn #hashtag into a hashtag, but
```
_#hashtag #hashtag #hashtag_
```
converts all three, so I think the code that generates the tag list needs some work in the markdown case.
=> Use custom blackfriday renderer to only add mention/hashtag links in normal text

testrig/testmodels.go
We were getting this issue about half the time:
```
--- FAIL: TestFollowingTestSuite (0.30s)
--- FAIL: TestFollowingTestSuite/TestGetFollowing (0.30s)
following_test.go:48: 
Error Trace:	/drone/src/internal/federation/federatingdb/following_test.go:48
Error:      	Not equal: 
expected: "{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"items\":[\"http://localhost:8080/users/admin\",\"http://localhost:8080/users/1happyturtle\"],\"type\":\"Collection\"}"
actual  : "{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"items\":[\"http://localhost:8080/users/1happyturtle\",\"http://localhost:8080/users/admin\"],\"type\":\"Collection\"}"
```
This is because the follows in the test rig all had the same created at and updated at, so the order in which they would be selected from the …
=> [bugfix] Fix occasional federatingdb test fail

internal/router/template.go, web/source/css/base.css, web/template/status.tmpl
fixes #648
funny enough, emojification bugs were one of the first things I worked on for mastodon 5 years ago
probably my most complicated commit so far, the creation of the regex and template can maybe be optimized?
emojify takes a template.HTML parameter for the text because it assumes that everything is already escaped, and its output can't be escaped again or it will destroy the img tags. I noticed that .Content gets sent through noescape, but not .SpoilerText. Should SpoilerText be html escaped?
the "emoji" css class still needs to be made, not sure where to put it
=> Emojify spoiler and content in web templates

cmd/gotosocial/action/admin/account/account.go, internal/db/account.go, internal/db/bundb/account.go, internal/federation/dereferencing/account.go, internal/federation/federatingdb/inbox.go, internal/federation/federatingdb/owns.go, internal/federation/federatingprotocol.go, internal/processing/account/get.go, internal/processing/federation/getfollowers.go, internal/processing/federation/getfollowing.go, internal/processing/federation/getoutbox.go, internal/processing/federation/getstatus.go, internal/processing/federation/getstatusreplies.go, internal/processing/federation/getuser.go, internal/processing/federation/getwebfinger.go, internal/processing/instance.go, internal/processing/search.go, internal/processing/util.go, internal/transport/controller.go
Removes GetLocalAccountByUsername() to instead rely on GetAccountByUsernameDomain()
=> [performance] use cache for local account lookups

internal/typeutils/converter.go, internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go
only the outgoing statuses for now. also adds a test that reads the full status from the DB and then serializes it, so we can compare the "tags" field (just using the raw test suite status doesn't have those fields populated)
I ran gofmt on the internaltoas.go file which is why there are more changes than just my code..
caveat: for some reason, gif emoji don't federate to some mastodon servers, even though the AP objects look basically identical (though we're missing the "updated" field in the emoji object, but static emoji still works in spite of that...)
=> Federate custom emoji (outbound)

internal/cache/domain.go, internal/db/bundb/bundb.go, internal/db/bundb/domain.go, internal/db/bundb/domain_test.go, internal/db/domain.go, internal/processing/admin/createdomainblock.go, internal/processing/admin/deletedomainblock.go
the situation with `nil` sentinel values being handled in the cache isn't ideal (it's a bit messy imo), but i have future plans that should improve this :)
=> [performance] cache recently allowed/denied domains to cut down on db calls

internal/api/client/media/mediaupdate_test.go, internal/db/bundb/migrations/20220903141016_store_gifs_as_image.go, internal/gtsmodel/mediaattachment.go, internal/media/processingmedia.go, testrig/testmodels.go
We made a mistake earlier with our implementation of the media attachment api: instead of storing gifs with type `Image` we stored them with type `Gif`, which isn't part of the Mastodon API (`Gifv` is but that's for short looping soundless video files, not gifs). This meant that frontends like Tusky always showed gifs as unrecognized file types.
This PR corrects this behavior by:
1. Storing and presenting new gifs as type Image
2. Migrating already-stored Gif types to Image.
=> [bugfix] Use 'Image' instead of unrecognized 'Gif' type for media attachments

web/source/panels/lib/oauth.js
This PR just adds a bit of error checking in the panel oauth functionality to check for JSON parsing errors. Now, a human-readable error message will be displayed, which hints at possible issues, instead of a JSON parsing error.
fixes #771
=> [bugfix] Catch json syntax errors in the frontend + display a more helpful message

internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go
There were a couple cases where we weren't selecting attachments, emojis, and mentions properly from the database on statuses serialized via the activitypub API. This PR fixes that. Should resolve an issue where emojis sometimes weren't being seen correctly on remote instances.
=> [bugfix] Fix emojis, attachments, and mentions not being serialized correctly sometimes via AP

internal/api/client/fileserver/servefile.go, internal/media/processingemoji.go, internal/media/processingmedia.go, internal/router/router.go
1. Fix possible unclosed storage streams in the media manager
2. Close http Server more gracefully
3.  Use cobra command context for Server
=> [bugfix] Server and closer bugfixes

docs/admin/cli.md
Previously we had a few examples referring to --config-file (which is not accepted) but most were missing it altogether, so the commands listed did not work.
Also replaced "./example.json" with just "example.json" in the import/export examples because the "./" was unnecessary.
=> Add --config-path to example CLI commands where needed.

internal/processing/status/create_test.go, internal/processing/status/util.go, internal/text/formatter.go, internal/text/markdown.go, internal/text/markdown_test.go
Fix a bug where shortcodes with underscores were being parsed as emphasis by markdown parser.
eg `:_some_emoji:` was being parsed as `:<em>some</em>emoji:`, which is not desired behavior
=> [bugfix] Fix emphasis being added to emoji shortcodes with markdown parsing

internal/api/security/robots.go, internal/web/profile.go, internal/web/robots.go, web/template/header.tmpl, web/template/profile.tmpl, web/template/status.tmpl, web/template/thread.tmpl
This PR adds more granular control over which endpoints robots are allowed to index.
By default, all web pages now have the following tag added to them:
```
<meta name="robots" content="noindex, nofollow">
```
This restricts search engines to not being able to index anything on the page.
However, if a user is Discoverable, then some limited indexing will be allowed of their profile page (but not their statuses or anyone else's statuses either).
In this case, the returned tag will be:
```
<meta name="robots" content="nofollow, noarchive, nositelinkssearchbox, max-image-preview:standard">
```
This allows the user's profile to be indexed, but not archived, and links will not be followed.
Currently, this won't make much difference for users, since by default users are not Discoverable, and …
=> [feature] Add `meta robots` tag; allow robots to index profile card if user is Discoverable

internal/db/bundb/domain.go, internal/db/bundb/domain_test.go
This PR makes it so that domain blocks are always normalized to punycode no matter how you create or check the domain block.
This should make life a bit easier for admins, since now they don't need to worry about whether to block the punycode domain or the unicode domain, both will work.
=> [chore] Normalize domain blocks to punycode

internal/router/template.go, internal/util/time.go, web/source/css/status.css, web/template/profile.tmpl, web/template/status.tmpl
This PR updates some of the timestamp string generation logic in web templates. Now, replies use timestamp strings that are shorter, to avoid obscuring the display name + username as much. These timestamps become more vague the longer ago the status was created. A status created today gets `Today, 15:04`; a status created this year gets `Jan 02, 15:04`, and a status created longer ago than this year gets `Jan 02, 2006`.
examples:
=> [chore] Use shorter timestamps in frontend for replies

cmd/gotosocial/action/admin/account/account.go, internal/api/client/auth/authorize.go, internal/api/client/auth/authorize_test.go, internal/api/client/auth/callback.go, internal/api/client/auth/signin.go, internal/api/security/tokencheck.go, internal/cache/user.go, internal/db/bundb/admin.go, internal/db/bundb/bundb.go, internal/db/bundb/user.go, internal/db/bundb/user_test.go, internal/db/db.go, internal/db/user.go, internal/processing/account/delete.go, internal/processing/fromclientapi.go, internal/processing/fromfederator_test.go, internal/processing/instance.go, internal/processing/streaming/authorize.go, internal/processing/user/emailconfirm.go, internal/typeutils/internaltofrontend_test.go, internal/visibility/statusvisible.go
This PR adds a cache for `*gtsmodel.User` gets, deletes, and updates.
Also adds some more functions to the db interface to use this new cache, and replaces old db.Where calls with these new ones.
This is in preparation for https://github.com/superseriousbusiness/gotosocial/issues/814 and https://github.com/superseriousbusiness/gotosocial/issues/815
=> [performance] add user cache and database

.github/ISSUE_TEMPLATE/bug_report.yaml, web/source/css/base.css, web/source/css/profile.css
Adds fallback css rules for browsers that don't support `min()` and `aspect-ratio`. Not equivalent styling but close enough
fixes https://github.com/superseriousbusiness/gotosocial/issues/803, https://github.com/superseriousbusiness/gotosocial/issues/800
=> [chore] Old browser fixes

internal/processing/admin/createdomainblock.go, internal/processing/admin/mediaprune.go
Fixes an issue where async processing was not completing correctly.
In particular this applies to side effects of domain blocks: while the domain block was being entered and enforced correctly, side effects like deleting accounts and updating the instance entry for the blocked instance were not. This fixes that :)
=> [bugfix] Use background context instead of request context

web/source/css/base.css, web/source/css/status.css
bit larger by default (they still fit fine), and make em scale a bit larger on hover as well
=> [frontend] Make emojis v. slightly larger

internal/db/bundb/domain.go, internal/db/bundb/domain_test.go, internal/db/domain.go, internal/processing/admin/createdomainblock.go
We weren't setting the date correctly on new domain blocks. Or rather we were, but it wasn't being set correctly on the returned domain block. This fixes that :)
closes https://github.com/superseriousbusiness/gotosocial/issues/870
=> [bugfix] Fix new domain block date

internal/api/client/auth/auth.go, internal/api/client/auth/authorize.go, internal/api/client/auth/callback.go, internal/api/client/auth/oob.go, internal/api/client/auth/signin.go, internal/oauth/server.go, internal/processing/oauth.go, internal/processing/processor.go, web/template/oob.tmpl
This PR re-wraps some oauth server logic to provide support for oob tokens.
This will be useful for clients who want to authorize using bots, or using CLI tools like toot.
closes https://github.com/superseriousbusiness/gotosocial/issues/108
=> [feature] `oob` oauth token support

internal/transport/controller.go, internal/transport/transport.go
Max retries are only reached if on HTTP server, DNS resolution or connection type errors. By caching these hostname failures we don't clog up the outoging request queue with likely failing requests.
=> [performance] cache domains after max retries in transport

cmd/gotosocial/action/admin/account/account.go
Check whether username/email address are available when creating accounts via the admin CLI
closes https://github.com/superseriousbusiness/gotosocial/issues/903
=> [bugfix] add in-use checks for admin cli account creation

web/source/settings/admin/emoji.js, web/source/settings/admin/federation.js, web/source/settings/components/back-button.jsx, web/source/settings/lib/api/admin.js, web/source/settings/redux/reducers/admin.js
Fetches custom emoji from `/api/v1/admin/custom_emojis` (https://github.com/superseriousbusiness/gotosocial/pull/902), also enables emoji detail pages although they don't provide any functionality yet (missing api)
=> [frontend] Use new GET custom_emoji admin api

docs/api/swagger.md
See https://github.com/superseriousbusiness/gotosocial/blob/main/internal/api/security/security.go
```go
s.AttachMiddleware(m.RateLimit(RateLimitOptions{
// accept a maximum of 1000 requests in 5 minutes window
Period: 5 * time.Minute,
Limit:  1000,
}))
```
=> fix swagger.md Rate Limit

internal/db/bundb/migrations/20220315160814_admin_account_actions.go
The migration that adds the `admin_account_actions` table did so at the same time as adding indexes onto the new table. This code was ran inside a `RunInTx` function, but the table creation did not use the transaction reference, while the creation of the indexes did. This could cause a race between the table and index creations, depending on the scheduling order. If the table creation did not win the race, then the migration would fail.
This changeset corrects the table creation to also be done inside the same transaction as the index creation.
Signed-off-by: Terin Stock <terinjokes@gmail.com>
=> [bugfix] create admin_account_actions table in tx

CONTRIBUTING.md, web/source/css/profile.css, web/source/css/status.css, web/template/profile.tmpl
Fixing #923 and this issue
I am not entirely sure if the solution for centered imgs (alt needs to contain `!center`) is a good one since it will be read by screen readers.
Although maybe this is even a good solution to indicate that nothing on the same height of the img exists.
=> Fix #923 and markdown css

internal/web/base.go
If set, the landing page user configuration value is used as a Gin context parameter, which seems incorrect, since a normal request isn't going to have a parameter named after an arbitrarily configured user. Instead, the user name should be used directly when building the redirect URL.
=> [bugfix] use the landing page user directly

.gitignore
Hey,
I like to keep GOBIN in the project directories so when switching Go versions (my main Go is still 1.18 because our slower infra ops team) binaries do not fight between projects.
Just for the record, this tool https://direnv.net allows switching Go versions easily:
```
[lzap@nuc gotosocial]$ cat .envrc 
GOVER=1.19.3
export GOROOT="$(go$GOVER env GOROOT)"
PATH_add "$(go$GOVER env GOROOT)/bin"
export GOBIN="$(pwd)/bin"
PATH_add "$(pwd)/bin"
```
Thanks!
=> [chore] gitignore /bin entry

.github/dependabot.yml
We don't really need prs for npm dependencies, this tones down how needy dependabot is a little bit
=> [chore] dependabot: prefix correctly, ignore npm deps

.gitignore, docs/configuration/database.md
Check your Postgres collation for Mastodon instance now. A story about incorrectly ordered toots (long).
I spent three evenings investigating why my instance stopped updating notifications and statuses correctly. I figured out that statuses were not gone, but not ordered correctly. Like if something shaked them a bit, but not much, just a bit.
I was debugging goroutines, learning about Universally Unique Lexicographically Sortable Identifier (ULID) which is the ID that is used in the ActivityPub protocol. No luck. This is how they look like btw:
01GHGAC5EHKSQQ0YRPXNWVZ7EJ
01GHGA78BHHQ8A3T6SFVYXAV4Y
These ULIDs are used as unique identifiers and because they are lexicographically sortable, Mastodon implementations take advantage of that and sort by this database column.
Now it might be …
=> [docs] postgres collation warning

internal/config/helpers.gen.go, internal/federation/dereferencing/account.go, internal/federation/dereferencing/dereferencer.go, internal/federation/dereferencing/emoji.go, internal/federation/dereferencing/emoji_test.go, internal/federation/dereferencing/util.go, internal/media/processingemoji.go, internal/media/processingmedia.go
- Rework logging inside emoji dereferencing stuff so we can get a better idea of which emojis are causing problems.
- Store in-process emoji dereferences inside a locked map in the dereferencer, similar to what we already did for account headers + avatars (why didn't i do this before?? who knows)
- Fix a wild bug where remote emoji fetching could be triggered over and over by refreshing the web view of a profile. 
- Other small fixes for clarity.
Relates to #916 but who knows if it fixes it or not!
=> [chore] Fixes + updates in emoji dereferencing logic

example/gotosocial.service
On some systems (tested on Debian 11) when the `/var/log/gotosocial` directory doesn't exist, it doesn't automatically get created, and the service fails to start with a permission denied error.
Changing the default log path to have no subdirectory means no errors when starting up for the first time.
Fixes #1023
=> Change default log path

go.mod, go.sum, internal/db/bundb/tombstone.go, vendor/codeberg.org/gruf/go-cache/v3/result/cache.go, vendor/codeberg.org/gruf/go-cache/v3/result/key.go, vendor/modules.txt
fixes possible issues with zero value keys (not likely to have appeared in tombstones, but will be important when using in other areas of db)
=> [chore] bump go-cache to v3.1.7

cmd/gotosocial/action/admin/account/account.go, cmd/gotosocial/admin.go, docs/admin/cli.md
It was confusing because it was a no-op and people were trying to use it.
So now it's removed, bam!
Also added the word 'local' into the docs to show that `admin account` commands are for local/this-instance accounts only.
=> [chore] Remove unused `admin account suspend` action

internal/regexes/regexes.go, internal/text/common.go, internal/util/statustools.go, internal/util/statustools_test.go
Go `\b` does not care for Unicode, and without lookahead in the regex engine, the workarounds got very ugly. So I replaced the regex with a parser that uses Go's Unicode functions directly.
The parser runs in O(n) time and performance should be comparable.
Might even be faster since I think this is less work, but I don't know how to benchmark. :)
I'm sure it's all sorts of unidiomatic but maybe it can be salvaged!
Hashtags that wouldn't work before were those ending in non-ASCII characters, like `#blå`, since `\b` would consider `l` followed by `å` to be a word boundary.
=> [bugfix] Fix unicode-unaware word boundary check in hashtags

docs/api/ratelimiting.md
In the case of the clients being treated as the same IP when there is no HTTP proxy, I believe the only fix is to disable rate limiting altogether, since there seems to be no way to get the actual IP.
Also explain specifically that setting the rate limit to zero turns off rate limiting rather than actually setting the limit to zero, since this is not intuitive.
=> [docs] Both HTTP proxies and NAT can cause rate limiting issues

cmd/gotosocial/action/admin/account/account.go, internal/api/client/auth/authorize_test.go, internal/db/bundb/user.go, internal/db/user.go
Prevents trying to set columns to null when doing updates to users via the cli commands
=> [chore] reversion: use specific columns for updating user again

docs/configuration/general.md, docs/installation_guide/advanced.md, docs/installation_guide/index.md, example/config.yaml, mkdocs.yml
Add a document explaining how to set up `fedi.example.org` while pointing to `example.org` as account-domain, including nginx example.
=> [docs] add account domain documentation

docs/installation_guide/third_party.md
The AUR is the Arch unofficial repository, where users can upload PKGBUILD's for Arch Linux users to build a package.
=> docs: Add AUR Reference

docs/installation_guide/nginx.md
The trailing / can break relative URLs.
=> [docs] Remove trailing / from proxy_pass for nginx

docs/installation_guide/binary.md, example/gotosocial.service
Rather than a single access log and no error logging, put the logs in /var/log/gotosocial/, and document creating and owning that directory
=> [docs] Move and document logs

Dockerfile
Explicitly create user, storage dir, and indicate that storage should be mounted from a volume
=> [chore] Little Dockerfile updates

internal/processing/account/delete.go
Refactor federator account statuses delete to better catch errors, ensure next maxID is always set.
=> [bugfix] fix possible infinite loop on federated AP profile delete

CONTRIBUTING.md, Dockerfile
I wanted to document the process I used to build GTS for my ARM-based Single-board-computer  
Yes,  I could have updated docker and installed/configured whatever buildx requires instead, but I chose to do this because we don't technically need buildx as go's cross compilation is 10/10 and needs no `qemu`  :smiling_imp: 
My pet peeve:  When there is an option that does not list all of its possible values. So I wanted to document those:
-  `GOOS`/`GOARCH`  for `./build.sh`
- and the  `--platform` argument in the `Dockerfile`
=> Enable / document non-buildx cross compilation for docker image

go.mod, go.sum, internal/storage/s3.go, internal/storage/storage.go, testrig/storage.go, vendor/codeberg.org/gruf/go-store/v2/storage/s3.go, vendor/modules.txt
This should solve #1105
It replaces our current S3 storage driver with `kv.KVStore` using `storage.S3` under the hood.
In time we can move to remove the now fairly-redundant `storage.Driver` interface.
Shoutout to @theSuess who was also working on this at the same time :grinning:
=> [chore] use kv.KVStore also for S3 storage

CONTRIBUTING.md, Dockerfile
Move the Dockerfile modifications for simpler multi-arch build outside of the actual Dockerfile and add a reminder not to commit them. They were breaking the buildx build we have on CI/CD (presumably because they shadow the global vars): https://drone.superseriousbusiness.org/superseriousbusiness/gotosocial/3564/1/2
=> [chore] fix broken buildx (whoops)

docs/installation_guide/advanced.md
We initialize our http client transport with `http.ProxyFromEnvironment`, so we should document how to use these env vars :)
=> [docs] Document http/s/socks5 proxy use

internal/web/profile.go, internal/web/settings-panel.go, internal/web/thread.go, internal/web/web.go
Since @f0x52 reworked our frontend stuff, we don't use `/assets/dist/bundle.js` anymore, but we still had references to it in some of our static pages, which was causing misleading 404s. This fixes that and also does some other small bits of tidying up.
=> [chore/frontend] remove references to unused bundle.js

docs/installation_guide/apache-httpd.md, docs/installation_guide/caddy.md, docs/installation_guide/docker.md, docs/installation_guide/nginx.md, example/docker-compose/docker-compose.yaml
=> [docs] Clarify that reverse proxy setups need trusted-proxies

internal/federation/authenticate.go, internal/federation/dereferencing/account.go, internal/federation/federatingprotocol.go, internal/httpclient/client.go, internal/processing/account/get.go, internal/processing/federation/getfollowers.go, internal/processing/federation/getfollowing.go, internal/processing/federation/getoutbox.go, internal/processing/federation/getstatus.go, internal/processing/federation/getstatusreplies.go, internal/processing/federation/getuser.go, internal/processing/media/getfile.go, internal/processing/search.go, internal/processing/util.go, internal/transport/context.go, internal/transport/context_test.go, internal/transport/transport.go
Add a `Fastfail` context that can be passed in to external calls made by our httpclient transport.
The idea here is that sometimes we do outbound http requests inside an incoming request context (say when a user is doing a search for an account our instance doesn't know yet). In these cases, the caller should wrap the request passed to the dereferencing functions in a Fastfail context, which indicates to the transport logic that it should fail after the first attempt.
This PR prevents situations where the search fails but the transport keeps retrying, which makes the search request feel very slow and buggy. Now, fails after the first attempt in such situations will return immediately, making things feel a lot snappier for the client (even when the request fails -- at least they can try …
=> [feature/performance] Fail fast when doing remote transport calls inside incoming request contexts

internal/visibility/filter_test.go, internal/visibility/statushometimelineable.go, internal/visibility/statushometimelineable_test.go, internal/visibility/statuspublictimelineable.go, internal/visibility/statusvisible.go
Statuses created more than 5 minutes into the future are now rejected in the visibility package.
=> [bugfix] Prevent future statuses entering timelines

cmd/gotosocial/action/admin/account/account.go, docs/admin/cli.md, docs/installation_guide/binary.md, docs/installation_guide/docker.md
The NewSignup method was already being called with requireApproval=false, but it had emailVerified=false as well, which meant that it was necessary to use the `admin account confirm` command to verify the email before the newly-created user could log in.
I think that was probably an oversight; effectively it did require approval anyway. Changing emailVerified to true allows you to just create the account and log in immediately, streamlining the setup and reducing the opportunity for manual error to sneak in.
Also updated the docs to remove the mention of needing to confirm new accounts. However, I've left the confirmation command alone because I think once we have web signups, it will be needed in that context.
It's possible I've overlooked something about the `admin account confirm` and …
=> [bugfix] Change emailVerified to true for admin account create

docs/installation_guide/binary.md, docs/installation_guide/docker.md
Since the documentation site only shows the latest version of the docs, we need the docs to explain how to use the latest stable release, not just the latest git version.
Without this I think #1140 will cause some confusion.
=> [docs] Explain that before 0.6.0, account confirm was necessary.

internal/netutil/validate.go
The current code considers ff00::/8 valid, but contrary to the comment that's not the global unicast range. ff-prefixes in IPv6 denote multicast.
This adapts the code to take the same approach as IPv4, explicitly blacklisting reserved internal/private ranges.
=> [bugfix]: Fix IPv6 validation

internal/httpclient/client.go, internal/httpclient/sanitizer.go, internal/netutil/validate.go, internal/netutil/validate_test.go
Commits are individually reviewable.
Since I was looking at this code yesterday I decided to take another pass through it:
* Added a check on the network to ensure it's always TCP
* Added IPv4-mapped range to v6 blocklist and add test for it. The behaviour is different between net and netip so it's useful to test and ensure we don't break this at some point
* I've aligned the reserved blocks with the respective IANA Special Purpose registries for v4 and v6
* Added some tests to ensure things are blocked especially for all the magical `/32`'s on v4
=> Additional IP range validations

internal/transport/controller.go
I've tried to tweak the User-Agent a bit to better match my understanding/interpretation of RFC 7231. But in the real world nobody really seems to agree on how these things should be formatted and what they contain so idk if this change is worth it.
This also flips it to use the account domain instead of the host domain, so that when you're looking at the header you can better identify the source of the request.
=> Tweak the User-Agent a bit

internal/transport/deliver.go, internal/transport/dereference.go, internal/transport/derefinstance.go, internal/transport/derefmedia.go, internal/transport/finger.go, internal/transport/transport.go
Currently requests set their own User-Agent. Set it in the transport instead, unless it's been explicitly set on the request. This retains the flexibility of tweaking the UA if necessary, without having to remember to set it.
=> Set User-Agent header in transport

internal/transport/controller.go
Somehow I managed to read the code wrong and swapped Host for AccountDomain in d6f4d196c978d81041ea99a32e2d6f63b0639472, whereas the commit message makes it clear my intent was to use tho Host (so we get the address the server is running on in the header).
This eh, fixes my brainfart. Sorry :sweat:.
=> Use Host domain for UA

docs/installation_guide/advanced.md, docs/installation_guide/binary.md, example/apparmor/gotosocial, mkdocs.yml
This PR adds an AppArmor profile for GoToSocial to `examples/apparmor/gotosocial`. The security guarantees provided by the profile should be roughly comparable to those provided by SELinux, but will work on Debian-family Linux distros (as well as some others, like OpenSUSE). The profile I've provided has been primarily tested and verified to work with the Docker-based deployment for GTS, but should also work for people who use the binary installation method.
I've also updated the security documentation (`Federation > Security`) to include an "application sandboxing" section, which currently has some AppArmor setup instructions that I've included as well as instructions for SELinux (which were previously provided in `Installation Guide > Binary Installation From Release`.
=> Add AppArmor profile for Debian and Ubuntu installations

internal/ap/extract.go
Signed-off-by: Sigrid Solveig Haflínudóttir <sigrid@ftrv.se>
=> ap: add support for PKCS1 "RSA PUBLIC KEY" pem block type

internal/netutil/validate.go
In the previous changes that expanded the IPv4 and IPv6 deny lists based on the IANA registries we inadvertently added a number of duplicates. This is unnecessary as they're already caught by larger prefixes and means there's less entries to scan.
This change removes all prefixes that are subnets of other prefixes.
I solemnly swear this is the last of it.
=> [chore] Remove duplicate prefixes from sanitizer

web/source/settings/admin/federation.js
tracking issue for backend implementation https://github.com/superseriousbusiness/gotosocial/issues/1198
=> [frogend/bugfix] Remove domain block edit functionality until implemented in backend

cmd/gotosocial/action/testrig/testrig.go, internal/storage/storage.go, testrig/storage.go
Implements #864 and should speed up s3 based installations by a lot.
With more static URL, we can then also implement #1026 for even better performance when used in conjunction with CDNs
I hope that I used the cache library correctly - oriented myself on the `eTagCache`
(Also tweaked the testrig to use the actual storage implementation for building the S3 config)
=> [performance]: make s3 urls cacheable

internal/api/client/account/statuses.go, internal/api/client/admin/emojisget.go, internal/api/client/blocks/blocksget.go, internal/api/client/favourites/favouritesget.go, internal/api/client/notification/notificationsget.go, internal/api/client/search/searchget.go, internal/api/client/timeline/home.go, internal/api/client/timeline/public.go, testrig/db.go
Closes: #1204 
This fixes a couple of cases where due to int being platform dependent a value could get truncated if running on 32bits.
=> [chore] Fix a few possible cases of int truncation

docs/installation_guide/binary.md, example/gotosocial.service
I was a bit surprised to see these two lines in our example Systemd unit config.
As far as I know this is a very uncommon default, given Systemd logs to journald by default. Users can then just use journalctl (as expected).
=> [docs] Remove filesystem logging directives from example systemd unit config

internal/db/bundb/timeline.go
This fixes #1151.
This lists favorites in the order they have been created, not by the date of the actual post. E.g. the most recently favored/liked post will be on top.
As this is my first contribution to GoToSocial, please let me know if I missed anything.
=> [bugfix] fix unordered favorites

internal/cache/domain/domain.go, internal/cache/domain/domain_test.go, internal/cache/gts.go, internal/db/bundb/domain.go, internal/db/bundb/domain_test.go
For domain blocks, it would now also block all subdomains under that given domain.
e.g. if you block `example.com` then the following would also be blocked
- `gts.example.com`
- `pleroma.example.com`
- `gts.pleroma.example.com`
=> [feature] domain block wildcarding

internal/api/client/streaming/stream.go, internal/api/client/streaming/streaming.go, internal/api/client/streaming/streaming_test.go
Implements `Sec-Websocket-Protocol` header for streaming.
closes https://github.com/superseriousbusiness/gotosocial/issues/1248
=> [feature] support Sec-Websocket-Protocol in streaming API

docs/installation_guide/apache-httpd.md
Update Apache docs to use 127.0.0.1 instead of localhost as done with Nginx at #1264.
=> Update Apache docs to use 127.0.0.1 instead of localhost

web/source/settings/admin/federation.js
re-uses `match-sorter` instead of a naive `startsWith` for filtering domain blocks in the federation settings
=> [frogend] Use match-sorter for filtering domain blocks

go.mod, go.sum, internal/cache/gts.go, vendor/codeberg.org/gruf/go-cache/v3/result/cache.go, vendor/codeberg.org/gruf/go-cache/v3/result/key.go, vendor/modules.txt
Fixes an issue that @blackle noticed and reported in matrix regarding the database caching context canceled errors. A very nice find, Good sleuthing!.
=> [bugfix] update go-cache to v3.2.0 with support for ignoring errors

internal/api/client/fileserver/fileserver_test.go, internal/api/client/fileserver/servefile.go, internal/api/client/fileserver/servefile_test.go, internal/iotools/io.go, internal/media/manager_test.go, internal/processing/media/getfile.go, internal/processing/media/getfile_test.go, internal/processing/media/util.go
>
This PR implements graceful failure when streaming an image to an API client during a media recache, in cases where the media is no longer present on a remote instance, or some other failure occurs.
Here's the situation before:
1. a client request a piece of media that was cached previously, but needs to be recached now
2. the async Data function is passed back to the worker, with a tee reader pipe jammed into it which the API caller will slurp from as the media is recached into storage
3. the caller waits for data to be blasted into the pipe
4. the Data function fails
5. the …
=> [bugfix] Close reader gracefully when streaming recache of remote media to fileserver api caller

internal/api/client/media/mediacreate.go
>
This PR fixes the errWithCode not being checked while processing media via the client API endpoint, leading to null pointer panics when trying to upload bad media.
=> [bugfix] fix media create error not being checked

cmd/gotosocial/action/server/server.go, internal/api/activitypub.go, internal/api/auth.go, internal/api/client.go, internal/api/fileserver.go, internal/api/nodeinfo.go, internal/api/wellknown.go, internal/middleware/gzip.go, internal/middleware/ratelimit.go, internal/web/web.go
=> [chore] reshuffle rate limit middleware, use single gzip middleware instance

mkdocs.yml
This pull request fixes the "Edit on GitHub" link on the generated documentation.
=> [docs] Fix documentation edit link

internal/api/client.go, internal/api/client/streaming/stream.go, internal/api/client/streaming/streaming.go, internal/api/client/streaming/streaming_test.go
=> [bugfix] return early in websocket upgrade handler

internal/api/activitypub/users/outboxget_test.go, internal/api/client/admin/emojicategoriesget_test.go, internal/api/client/admin/emojidelete_test.go, internal/api/client/admin/emojiget_test.go, internal/api/client/followrequests/authorize_test.go, internal/api/client/followrequests/get_test.go, internal/api/client/followrequests/reject_test.go, internal/api/client/instance/instancepatch_test.go, internal/api/client/instance/instancepeersget_test.go, internal/api/model/source.go, internal/api/wellknown/webfinger/webfingerget_test.go, internal/federation/federatingactor_test.go, internal/federation/federatingdb/followers_test.go, internal/federation/federatingdb/following_test.go, internal/processing/streaming/notification_test.go, internal/typeutils/internaltoas_test.go, internal/typeutils/internaltofrontend_test.go, internal/typeutils/wrap_test.go
>
This pull request updates some of the account serialization logic to remove some omitEmpty annotations that were causing trouble + resulting in missing fields. Tests have been updated for this.
While I was in the code, I also refactored tests elsewhere in the codebase to use prettyprinted json when non-trivial json is being diffed. This lets us more easily see what's failing when tests fail. The actual substance of the tests has not changed at all, it's purely formatting.
closes #1332 
Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` -> …
=> [chore] Remove omitempty on account source; refactor tests to use prettyprint json

internal/api/client/bookmarks/bookmarks.go
>
This pull request fixes an issue where bookmarks were being mounted at `/api/api/v1/bookmarks` instead of `/api/v1/bookmarks`
=> [bugfix] Mount bookmarks endpoint correctly

docs/faq.md
Videos actually work now! Yay. We can stop mentioning them under the section about stuff that hasn't been implemented.
=> Remove videos from the list of missing features in the FAQ.

docs/configuration/database.md, example/config.yaml, internal/config/defaults.go, testrig/config.go
>
Does what it says on the tin! This is to avoid busy timeouts for really long running queries (which we should fix, but OK, this is a workaround for now).
=> [chore] Change default sqlite busy timeout to 5m

web/source/settings/admin/emoji/local/new-emoji.js
Wrongly used `shortcode` (text hook) instead of `shortcode.value` which gave.. some interesting titles
=> [chore] Fix new emoji preview title/alt text

web/source/index.js, web/source/settings/admin/emoji/category-select.jsx, web/source/settings/admin/emoji/local/overview.js, web/source/settings/admin/emoji/local/use-shortcode.js, web/source/settings/admin/emoji/remote/index.js, web/source/settings/components/authorization/index.jsx, web/source/settings/lib/query/admin/custom-emoji.js, web/source/settings/lib/query/base.js, web/source/settings/lib/query/oauth.js, web/source/settings/redux/index.js, web/source/settings/redux/oauth.js
Three small fixes building on `settings-refactor`:
- 'Emoji' RTK Query tag type got lost, re-added and renamed
- Replace 'localhost' with '127.0.0.1' in webdev setup proxy, because GTS doesn't listen on ::1
- Fix issue where login flow quickly flashed "expecting callback" error before redirecting to the instance login flow
=> [chore] Settings refactor fix 2

web/source/settings/components/authorization/login.jsx
Adds back the `name` attribute for the instance field, so you get the same autosuggestions from previous entries
=> [chore] Add name to instance field for autosuggestion

internal/validate/formvalidation.go, internal/validate/formvalidation_test.go
Closes: #1365
extending maximum password limit from 64 to 256 chars.
=> [chore] extending maximumPasswordLength to 256

web/template/header.tmpl
One-line change, implements this feature request:
https://github.com/superseriousbusiness/gotosocial/issues/1358
This adds a <link> element to profiles that have RSS feeds so that browsers and feed readers can automatically discover it.
Tested using the testrig and Vivaldi. As expected, the RSS icon appeared in the URL bar when viewing the profiles for the_mighty_zork and admin, but not 1happyturtle, and not on individual posts or the instance home page.
=> Add RSS autodiscovery on profiles that enable RSS

.drone.yml
1.19.5 is out so we can skip straight to that from 1.19.3 :)
=> [chore] bump go version to 1.19.5

internal/ap/extract.go, internal/ap/interfaces.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/create_test.go, internal/processing/fromfederator.go, internal/regexes/regexes.go, internal/typeutils/astointernal.go, internal/typeutils/astointernal_test.go, internal/typeutils/converter.go, internal/typeutils/util.go, internal/typeutils/util_test.go
>
This pull request allows Flags / reports to be created in GoToSocial via the federated (s2s) interface.
Right now, it doesn't handle any other side effects of flags aside from putting the parsed report in the database.
Works for mastodon-style Flag where `object` can be an array of account URI + one or more status URIs, and also for Misskey-style Flag where status URLs are included in the `content` field of the Flag. 
Relates to https://github.com/superseriousbusiness/gotosocial/issues/1309
Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` …
=> [feature] Accept incoming federated Flag activity

web/source/css/base.css, web/source/settings/admin/emoji/local/overview.js, web/source/settings/admin/federation/overview.js, web/source/settings/style.css
Small quality-of-life improvement to the local emoji list, adding a bit of explanation and a text field to filter the list (similar to the federation domain list).
=> [frogend] Filter local emoji

docs/federation/federating_with_gotosocial/reports.md, mkdocs.yml
>
This pull request adds a 'Federating With GoToSocial' document for user moderation reports / Flags, explaining how GtS sends and receives Flags.
Relates to https://github.com/superseriousbusiness/gotosocial/issues/1309
=> [docs] Add `Flag` documentation to federation docs

docs/installation_guide/apache-httpd.md
since 2.4.47 (released April 22nd 2021), Apache httpd can ProxyPass to websockets on the same URL, without mod_rewrite (and, without mod_proxy_wstunnel).
=> docs: Simplify Apache httpd proxy documentation

docs/installation_guide/advanced.md
There is a section in the documentation that explains how admin can setup a redirect from `example.org` to `fedi.example.org` using Nginx. I wanted to achieve the same through Traefik. It took me about an hour to get it working, so thought of sharing it with others too.
=> Add an example on how to setup redirect with Traefik

cmd/gotosocial/action/server/server.go
This switches the logger to Debug. By default the library logs things internally despite returning errors. Due to the way we had it hooked up this resulted in scary error level logs being emitted for innocuous errors. Now those errors will only be visible in debug mode.
Fixes: #1398
Relates to: #1336
=> [chore] Silence maxprocs logging

docs/configuration/database.md, example/config.yaml, internal/db/bundb/bundb.go
>
This pull request updates sqlite preferences to use 'immediate' locking mode for transactions instead of the default 'deferred' mode. This won't make much of a difference right now, but should be useful in future when we implement proper retry behavior on `SQLITE_BUSY` errors.
Also tidies up some of the sqlite preferences stuff a little bit, and adds some explanatory comments for why we do certain things.
If this is a documentation change, only the first checkbox must be filled (you …
=> [chore] Use 'immediate' lock for sqlite transactions

docs/configuration/database.md, example/config.yaml, internal/db/bundb/bundb.go
>
This PR hard limits the number of sqlite db connections to 1, regardless of CPU and multiplier settings. This is a temporary workaround until we add retry logic for `sqlite_busy` errors. See https://github.com/superseriousbusiness/gotosocial/issues/1407
=> [chore/performance] use only 1 sqlite db connection regardless of multiplier

internal/ap/extract.go, internal/ap/extractattachments_test.go, internal/ap/interfaces.go, internal/typeutils/astointernal.go, internal/typeutils/astointernal_test.go
>
This pull request updates some of our federated Statusable parsing logic:
- Fall back to reading `Name` property into `Status.ContentWarning` when `Summary` property is not set
- Continue to parse `MediaAttachment` from `Attachmentable` even if `MediaType` property is not set, since we don't really use it anyway.
- Make function signature of some ap extract functions simpler since we were swallowing errors from them anyways.
closes https://github.com/superseriousbusiness/gotosocial/issues/1403
Please put an x inside each checkbox to indicate that you've read and followed it: `[ …
=> [bugfix] Fix some AP interface bugs + inconsistencies related to reading articles from Bookwyrm

internal/api/client/instance/instancepatch.go, internal/api/client/instance/instancepatch_test.go, internal/processing/instance.go
>
This pull request fixes an oversight where it was not possible to change just the image description for an instance thumbnail/avatar without also changing the image. Now it is possible, hurray!
Also tidied up some of the instance patch tests a wee bit to cut down on some repetition.
=> [bugfix] Allow instance thumbnail description to be set separately from image

docs/api/swagger.yaml, internal/api/client.go, internal/api/client/featuredtags/featuredtags.go, internal/api/client/featuredtags/get.go
>
This pull request stubs out the featured tags endpoint to always return an empty array, to help soothe some client compatibility issues. We'll be implementing this endpoint later anyways most likely, so stubbing it for now (as we've done with other endpoints in the past) is a-ok.
closes https://github.com/superseriousbusiness/gotosocial/issues/1419
=> [chore] stub /api/v1/featured_tags endpoint

internal/processing/user/changepassword.go
>
This pull request implements updates the password change logic to make sure the old user entry is invalidated in the cache. This wasn't done before, which meant the old password hash was still hanging around.
=> [bugfix] fix old password hash staying in cache

internal/api/fileserver/servefile.go
=> [performance] remove local copying of file for satisfying range headers

internal/processing/media/delete.go
Swallow missing file errors in the media cleanup logic. If the file's not there, it doesn't matter that deleting it failed.
closes #1434
=> Ignore missing files when cleaning up media

internal/api/fileserver/servefile.go, internal/processing/media/delete.go
=> [bugfix] fix file range length calculation being off by 1

internal/processing/account/update.go
Fix emoji being removed from profile fields when other fields are edited.
There's no trivial way of identifying from the list of emoji in the Account object which ones are used in the DisplayName and which in the Note, as both support emoji. Therefore, this change reparses both of these fields for emoji on any change to the profile. If a new version has been submitted, this is parsed and applied to the account; otherwise we use the current version from the account.
closes #1439
closes #(another issue)
=> [bugfix] don't trash emoji in profile fields on edit

.github/ISSUE_TEMPLATE/bug_report.yaml
> Beware. Controversy
There's been a recent increase in new ActivityPub clients. Unfortunately most clients are coded directly against the Mastodon API and make deep rooted assumptions about it in their implementations. This leads to those clients not working with GTS. Though GTS implements a good chunk of the Mastodon API, it's always in catch-up mode. The Mastodon Client API is not part of the ActivityPub spec.
This change aims to add some gentle language to the bug report template to direct folks that are reporting compatibility issues with closed source clients to go talk to those developers instead. GTS developers can reasonably help debug an issue if they have access to the source code on both ends, but when the client is closed source the burden of ensuring compatibility can't be …
=> [chore] Update bug report template

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, internal/web/web.go
>
This pull request ensures that the signature check middleware is mounted for the `/@username` and `/@username/statuses/whatever` endpoints. I forgot to do that during the big middleware refactor. It's necessary because otherwise those endpoints can't check for an http signature in the header and serve the AP representation of an account or status if the Accept header is set to an AP content type.
closes https://github.com/superseriousbusiness/gotosocial/issues/1450
If this is a …
=> [bugfix] Use SignatureCheck middleware for web profile endpoints too

web/source/settings/admin/emoji/remote/parse-from-toot.js, web/source/settings/lib/form/check-list.jsx, web/source/settings/lib/form/submit.js, web/source/settings/lib/query/admin/custom-emoji.js
"Steal this look" interface buttons disabled/enabled based on 'someSelected' property which wasn't implemented properly after previous useCheckList refactoring. Works again now, also involves some changes to unchecking the emoji that *were* properly copied/modified
=> [chore] fix 'steal this look' form, uncheck entries after processing

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, docs/installation_guide/advanced.md, internal/api/activitypub.go, internal/api/activitypub/publickey/publickey.go, internal/api/activitypub/publickey/publickeyget.go, internal/api/activitypub/users/user.go
>
This pull request updates some of our routing code to serve the `/users/:username/main-key` ActivityPub endpoint separately from the other AP endpoints, in order to apply separate throttling + cache policies on it (public cache with lengthy max-age).
The reason for this change is that when a status is federated from GtS to a Mastodon server, Mastodon always makes a request to get the main-key again (https://github.com/mastodon/mastodon/issues/19217). If it can't get the main-key because of throttling or some other issue, the status won't be accepted by that Mastodon server, …
=> [chore/bugfix] Serve + throttle publickey separately from rest of ActivityPub API

web/source/settings/admin/reports/detail.jsx, web/source/settings/admin/reports/index.jsx, web/source/settings/admin/reports/username.jsx, web/source/settings/style.css
closes https://github.com/superseriousbusiness/gotosocial/issues/1456
=> [chore] Fix report username wrapping

internal/federation/dereferencing/account.go, internal/federation/dereferencing/finger.go
>
This pull request updates account dereferencing logic to compare remote header/avatar url before + after latest fetch, and only fetch + store avatars and headers if they've changed since last time we saw them.
Also does a very small performance enhancement to only instantiate a transport once and reuse it for remote calls during enrichAccount.
=> [performance] Don't fetch avatar + header if uri hasn't changed

internal/api/fileserver/servefile.go, internal/processing/media/getfile.go
>
This pull request fixes some logic that got broken in #1250: we were not setting cache control appropriately for presigned s3 links, leading to old links being cached in browsers. Now, cache control is set to 24h when using s3 presigned URLs, to align with the ttl we set for those.
=> [bugfix] Set appropriate cache-control when using presigned s3 links

cmd/gotosocial/action/admin/media/prune/common.go, internal/db/bundb/account.go, internal/db/bundb/bundb.go, internal/db/bundb/media.go, internal/federation/dereferencing/account.go, internal/gtsmodel/mediaattachment.go, internal/media/prune.go
>
This pull request:
1. Fixes a bug where avatars were being set as 'avatar=false' by accident, leading to them being pruned and then later not found.
2. Allows for situations where a remote header/avatar url has changed to empty, and should therefore be unset.
3. Fixes the `admin media prune remote` command to initialize db state and caches properly.
4. Updates media attachment select db logic to select a bunch of IDs and then select attachments from those IDs, rather than doing big ol' queries.
5. Removes some unused db relations that were causing us to make bigger queries than …
=> [bugfix] Fix up `error getting account avatar/header` errors, other small fixes

internal/api/client/search/searchget_test.go, internal/processing/search.go
>
This pull request adds a quick domain block check in the search function of the processor to ensure that items being searched aren't currently domain blocked.
When we do https://github.com/superseriousbusiness/gotosocial/issues/1497 we should consider removing these checks and doing them in the dereferencer instead.
closes https://github.com/superseriousbusiness/gotosocial/issues/1462
If this is a documentation change, only the first checkbox must be filled (you can delete the …
=> [bugfix] Return empty result rather than 500 error when searching for blocked domains

docs/installation_guide/advanced.md
This updates the example to ensure the nginx proxies the request on to GTS if the file is not found on disk. This can happen due to media pruning.
=> [bug] Fix nginx fileserver caching example

docs/faq.md
Having the `Host` config option not match the domain that GTS is exposed on can cause a 400 bad request error on signin.
>
This pull request implements xyz or fixes abc.
closes #(issue)
closes #(another issue)
=> [FAQ] Suggest confirming host option in config

.github/ISSUE_TEMPLATE/bug_frontend.yaml
Based on the idea in https://github.com/superseriousbusiness/gotosocial/issues/1438#issuecomment-1429852161.
Have a separate template for:
* Frontend, with labels bug and frontend and requiring the browser field
* Regular/backend, for other bugs with only the bug label and removal of the browser field
=> [chore] Split the bug template in two

internal/api/fileserver.go, internal/api/fileserver/servefile.go, internal/api/model/content.go, internal/storage/storage.go
>
This PR fixes a case where an s3 url could return a cache-control max age of 24h when the url actually does not have 24h of validity left. Instead, cache-control max-age is now set depending on how long the link has left until expiry.
=> [bugfix] Set cache-control max-age dynamically for s3

cmd/gotosocial/action/server/server.go
We want to set the Logger to nil, but that means we still need to wrap it in `maxprocs.Logger()`.
Fixup from #1476 
=> [bug] maxprocs set logger to nil

internal/middleware/logger.go
This updates the middleware `log.WithField` calls that create new loggers to include the context the first time around. Without it the requestID does not get logged.
Fixup from #1476
=> [bug] Pass context in logging middleware

internal/concurrency/workers.go, internal/federation/federatingdb/accept.go, internal/federation/federatingdb/announce.go, internal/federation/federatingdb/reject.go, internal/federation/federatingdb/undo.go, internal/federation/federatingdb/update.go, internal/federation/federatingdb/util.go, internal/media/manager.go, internal/typeutils/astointernal.go
In #1476 we updated `log.WithFields()` but we forgot about `log.WithField()`. Also updates a few explicit `log.Entry{}` creations.
=> [chore] Update more log calls to include context

internal/oauth/server.go, web/source/css/base.css, web/template/error.tmpl, web/template/oob.tmpl
Our `oob.tmpl` was served on `/oauth/oob` but the flow redirected to `/oob`. Flow now redirects correctly to `/oauth/oob`.
Also took the opportunity to update the layout/style for the oob and error templates.
closes https://github.com/superseriousbusiness/gotosocial/issues/1518
=> [bugfix] Fix oob token route, update templates+css for oob and errors

internal/media/png-stripper.go
>
This pull request implements keeping png files transparency information.
Previous implementations discarded all chunks with names beginning with a lowercase letter.
The simple transparency of the png file is kept by the tRNS chunk, but until now it has been discarded.
This pull request prevent tRNS chunks from being discarded and preserve the simple transparency of the png file.
closes #1295
If this is a documentation change, only the first checkbox must be filled (you can delete …
=> keep png transparency

internal/httpclient/client.go
This moves checking if the request is valid as early as possible in the chain. This should ensure that for an invalid request we never bother acquiring the wait queue and taking up a spot in it.
=> [chore] Move request validation earlier in client

internal/ap/extract.go, internal/processing/account/update.go
Fix a bug where Misskey could send accounts with duplicate emojis, which we would then fail to process.
Also tidies up the local profile edit logic to make sure we don't set duplicate emojis that way, just in case.
closes #1532
=> Fix failure to look up remote profiles with duplicate emojis in some cases

internal/web/about.go, internal/web/web.go, web/source/css/base.css, web/template/about.tmpl
Basic /about page, using the full instance description and generating some more info from various settings. Also links to `/about/suspended` if enabled.
=> [feature] About page

mkdocs.yml
Weird mkdocs/read-the-docs issue for 404 pages, seems setting the site_url might fix the asset links for the 404 pages.
=> [docs] Add site_url for absolute 404 page assets

internal/storage/storage.go
>
This pull request removes the initial disk storage cleanup, which was likely what was causing minutes-long delays for some people when restarting their instance. The cleanup is already part of the nightly media prune cycle, so the startup clean wasn't really needed anymore anyways.
=> [bugfix] Remove initial storage cleanup

internal/web/opengraph.go, internal/web/opengraph_test.go
This changes parseDescription to properly encode things to be safe for usage without removing things like backslashes that may be relevant.
* text.SanitizePlaintext already calls html.UnescapeString so we don't have to do that
* Replace `\n` with space early
* Remove duplicate white-space by splitting on fields and joining
* HTML-escape the string we have
* For extra certainty, encode the backslash as `&bsol;`
Fixes #1549
=> [chore] improve opengraph descripiton tag

internal/api/client/bookmarks/bookmarks_test.go, internal/processing/account/bookmarks.go, internal/processing/fromcommon.go
>
This PR fixes a bug where it was possible for a status to be deleted, but a bookmark to that status to remain, causing a GET to bookmarks to return an internal server error.
Now, bookmarks pointing to a status are deleted when that status is deleted.
The bookmark fetching subprocessor function has also been fine tuned to be a bit neater and more fault tolerant.
=> [bugfix] Fix deleted status causing issues when getting bookmark

.vscode/launch.json
In order to get testrig we have to build with the debugenv tag and run with the DEBUG environment variable. Since this is a Debug build this also updates the launch configuration name to reflect that.
We do not build with `-ldflags="-s -w"` since that strips debug info.
This makes it possible to launch GtS from VS Code in debug mode, set breakpoints in the editor etc.
=> [chore] Update vscode launch configuration

cmd/gotosocial/main.go
This adds a dummy testrig subcommand when we're not building with DEBUG set. Now any invocation of gotosocial testrig, plain or with any kind of subcommands or arguments will result in that error message getting returned.
=> [chore] Inform user on how to get testrig

Dockerfile
This updates the Dockerfile to use the latest image versions for all the containers that are used when building the final GTS container.
=> [chore] Use latest containers when building

internal/api/client/media/mediacreate_test.go, internal/media/manager_test.go, internal/media/prune.go, internal/storage/storage.go, testrig/storage.go
This simplifies our storage driver to directly use the interface type `storage.Storage` instead of the wrapping type `kv.KVStore{}`. We are using this is an adaptable media storage interface, but `kv.KVStore{}` is more intended for use as a key-value store, and as such uses a per-key mutex locking system which we don't need. This PR instead just updates us to use the underlying storage interface type directly, though using `kv.KVStore{}` like wrapper functions to prevent a huge number of required code changes.
=> [chore/performance] simplify storage driver to use storage.Storage directly

internal/db/bundb/status.go, internal/db/bundb/status_test.go
>
This pull request adds some `ON CONFLICT DO NOTHING` clauses to our queries, to prevent postgres transactions from being aborted even though we're catching errors nicely. Postgres considers a transaction in which errors have occurred to be a bad transaction, and will refuse further queries against it with `current transaction is aborted, commands ignored until end of transaction block`. We were running into this in our status update statements specifically, because we create new status_to_emoji and status_to_tag entries in there, but often those exist already.
Also added a test …
=> [bugfix] Add `ON CONFLICT` statements to status updates

internal/api/client/statuses/statusunpin_test.go, internal/processing/status/pin.go
>
And also fix unpinning/pinning potentially leaking the ID of followers-only statuses through returning 422 instead of 404.
Also tests!
=> [bugfix] Fix unpinning statuses not working

docs/federation/federating_with_gotosocial.md, internal/processing/fromclientapi.go, internal/typeutils/converter.go, internal/typeutils/converter_test.go, internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go
>
This pull request updates some of our status delete logic to federate the Delete using only the URI of the status.
It also updates the addressing of the Delete to always include the ActivityPub public URI in the `to` field unless the deleted post was a direct message, and also to always CC the replied-to user (if present) with the delete.
This should help to ensure that Deletes are federated a bit more widely. The trade off is that remote instances might become aware of the URI of now-deleted posts that were not originally addressed to them (but which they might have seen …
=> [bugfix] Federate status Delete using just the URI, update Delete addressing

docs/configuration/general.md, docs/installation_guide/advanced.md, example/config.yaml, internal/api/util/negotiate.go, internal/api/wellknown.go, internal/api/wellknown/hostmeta/hostmeta.go, internal/api/wellknown/hostmeta/hostmetaget.go, internal/processing/fedi/wellknown.go
>
Host-meta is back baby!
So it turns out, when the account and instance domain aren't the same (say pixie.town vs social.pixie.town), the official Mastodon Android client uses the `host-meta` endpoint to discover what the "actual" domain is. Currently this fallback isn't happening for GtS instances because we don't provide `host-meta` making a number of Mastodon apps not work.
The iOS client doesn't do this but (yet) but that's tracked in https://github.com/mastodon/mastodon-ios/issues/967 for now.
I suspect a number of other clients might do this too and having `host-meta` would …
=> [feature] Provide .well-known/host-meta endpoint

internal/api/client/streaming/stream.go, internal/processing/stream/open.go, internal/processing/stream/stream.go, internal/stream/stream.go
I had a go at implementing a fix for #1418. This allows clients to subscribe to multiple event streams on a single [WebSocket connection.](https://docs.joinmastodon.org/methods/streaming/#websocket)
* Clients can now authenticate WebSocket connections using OAuth in addition to the existing token query parameter & `Sec-Websocket-Protocol` header.
* The stream.Stream struct now stores a set of timeline strings, rather than just a single one. Events matching any of these timelines are forwarded to the client over the WebSocket.
* JSON messages received from the client are processed for subscribing and unsubscribing.
I've tested this with Ice Cubes, which now gets live timeline updates. I also checked Pinafore and Metatext, which worked before, and still work.
Note that this is my first time …
=> Support multiple subscriptions on single websocket connection

go.mod, go.sum, vendor/codeberg.org/gruf/go-runners/process.go, vendor/modules.txt
=> bump go-runners version to fix possible race in Processing{Media,Emoji}

internal/cache/cache.go, internal/db/bundb/relationship_follow_req.go, internal/db/bundb/relationship_test.go
>
We introduced a small issue where the follow cache wasn't being invalidated when a follow request was accepted, leading to a case where you could follow someone, have them accept, and still have your relationship show that you aren't following them.
This PR fixes this by just invalidating the follow cache when a follow request is accepted.
=> [bugfix] Fix relationship not updating 'following' on accept follow request

internal/api/client/admin/reportsget_test.go, internal/processing/account/delete.go, internal/processing/account/delete_test.go, internal/typeutils/converter_test.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
>
This pull request updates some of our account deletion logic to no longer delete the *gtsmodel.User entry for local accounts, but rather to stubbify it in a similar way to account stubbification. User's password will now be set to a bcrypt hash of a random uuid, so they'll need to reset their password via email if we ever implement code to reverse local account suspensions.
Also does some slight changes to report serialization to use `null` for `invite_request`, and to show remote accounts as suspended/silenced properly.
closes …
=> [bugfix] Fix report serialization errors caused by user delete

internal/media/prune.go, internal/processing/account_test.go, internal/processing/media/unattach.go
>
This pull request fixes an issue where the column `updated_at` was being passed into media attachment updates as an extra column. This was causing double `updated_at` columns to be used when making db queries. SQLite doesn't mind this, but postgres does.
closes https://github.com/superseriousbusiness/gotosocial/issues/1645
=> [bugfix] Fix multiple "updated_at" columns for media updates

internal/middleware/cors.go
>
Add `Idempotency-Key` to allowed CORS headers. Although we don't currently use this, some clients require this header to be allowed through, and it is in the mastodon API spec so we'd better do it.
closes https://github.com/superseriousbusiness/gotosocial/issues/1664
=> [bugfix] Add idempotency-key to allowed CORS headers

internal/db/bundb/migrations/20230405130021_status_fave_unique_constraints.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/owns.go, internal/federation/federatingdb/undo.go, internal/federation/federatingdb/util.go, internal/gtsmodel/statusfave.go
>
This pull request:
- Introduces proper constraints on status faves -- now, an account can only like a status once.
- Includes a migration to delete duplicate status faves, before adding constraints to status fave table.
- Implements federating undo logic for status likes -- we didn't have this before for some reason???
- Does some v. small tidying up in the bits of the codebase that had to be touched :hand: 
If this is a documentation change, only the first checkbox must be filled …
=> [bugfix] Add proper constraints on status faves, dedupe

docs/federation/federating_with_gotosocial.md, internal/ap/serialize.go, internal/processing/fedi/collections.go, internal/typeutils/internaltoas_test.go
>
This pull request implements a workaround for an issue where orderedItems in a featured/pinned collection would be serialized as a string (instead of a string array) if there was only one entry. This was causing issues with other implementations that assume that orderedItems will always be an array (which is apparently the correct behavior).
See https://github.com/mastodon/mastodon/issues/24225 and https://github.com/go-fed/activity/issues/139
Note: while this code gets us moving for now, it is far from a perfect solution because a) it's confusing and b) it's inefficient. We …
=> [bugfix] Always serialize `orderedItems` as array in `OrderedCollection`

internal/db/bundb/timeline.go, internal/visibility/account.go, internal/visibility/home_timeline.go, internal/visibility/public_timeline.go, internal/visibility/status.go
Changes:
- updates home timeline visibiility to show relevant conversations to timeline owner (i.e. statuses authored by someone they follow and mentioning someone else they follow)
- fixes visibility caching
- small home timeline maxID fix in db query
Checklist:
=> [bugfix] visibility caching and hometimeline

internal/visibility/home_timeline.go, internal/visibility/home_timeline_test.go
>
This pull request fixes an issue where single-author thread replies were not appearing in the home timeline.
We were assuming that threads were not single author, by default, but then never checking that boolean again to possibly set it to true.
Now, instead, we assume single-author threads and only change the boolean once if we see otherwise.
=> [bugfix] Fix single author threads not appearing in home timeline

docs/faq.md, docs/user_guide/posts.md
The current wording explaining the markdown feature seems to imply that the input formatting can be set on a per-post basis, which no client currently supports. It's not clear that you have to go to the user settings page to change it.
Bonus change: a few items in the FAQ were outdated as they referred to missing features which now exist!
=> Explain that markdown is enabled on the user settings page.

web/template/index.tmpl
As Pinafore is now unmaintained: https://nolanlawson.com/2023/01/09/retiring-pinafore/
And that a fork that looks serious is created: https://github.com/NickColley/semaphore
I have changed the mentions of Pirafore to its successor, Semaphore.
This change has been tested and can be seen here: https://gts-test.oniricorpe.eu/
Closes #1343
Also, it maybe be relevant to add this web client too (or replacing Pinafore in place of Semaphore), which seems to be well compatible with GTS: https://github.com/elk-zone/elk
=> Replacing Pinafore with Semaphore

internal/ap/extract.go, internal/ap/interfaces.go, internal/ap/normalize.go, internal/ap/normalize_test.go, internal/ap/resolve.go, internal/processing/fromfederator.go
>
This pull request implements further normalization of the following:
- status summary (used as content warning)
- status name (used as backup content warning)
- status attachment name (used as image description)
- account summary (used as bio)
This should resolve remaining issues with URI strings being parsed and funky escaping happening. 
closes https://github.com/superseriousbusiness/gotosocial/issues/1698
If this is a documentation change, only the first checkbox must be filled …
=> [bugfix] Fix remaining mangled URI escaping issues in statuses + accounts

internal/email/common.go, internal/email/email_test.go, internal/processing/user/email_test.go
This fixes an issue with email headers that prevents sending
closes #1716
=> add From to email header

docs/api/swagger.yaml, internal/api/client/notifications/notificationget.go, internal/api/client/notifications/notifications.go, internal/processing/notification.go
>
Add missing endpoint to GET a single notification by its ID (will return 404 if targeted notification does not belong to authed account). This may fix a small issue with the latest tusky nightly.
=> [feature] Add GET endpoint for single notification

go.mod, go.sum, internal/cache/util.go, internal/httpclient/client.go, internal/media/processingemoji.go, internal/media/processingmedia.go, vendor/codeberg.org/gruf/go-cache/v3/result/cache.go, vendor/codeberg.org/gruf/go-errors/v2/errors.go, vendor/codeberg.org/gruf/go-errors/v2/standard.go, vendor/codeberg.org/gruf/go-errors/v2/value.go, vendor/modules.txt
- improved setting of bad host entries
- update error library for fast multi-checking of errors when you would use `errors.As()`
- catch more x509 errors in httpclient as instant-return
=> [performance] tweak http client error handling

internal/cache/domain/domain.go, internal/cache/domain/domain_test.go, internal/cache/gts.go
Replaces the original domain-block cache, which was an in-memory list backed up by a faster hashmap TTL cache. This replaces that entire complex system with a singular in-memory radix tree, that searches the individual children of a node using a binary search, since we can sort the tree beforehand.
Code and dependency-wise, this is a much simpler solution. It also has the added benefit that it relies only on atomic operations, no mutexes, so it should be a little faster! It may be a bit slower during the procedure of adding new domains, but considering this cache will be 95% of the time read-from, and 5% written-to, this is an acceptable trade-off.
See: https://en.wikipedia.org/wiki/Radix_tree
=> [performance] replace domain block cache with an in-memory radix trie

.gitattributes
>
Linguist already classifies `vendor`/ as vendored files, meaning they don't count towards things like a repo language stat, but are still shows in diffs.
By classifying them as generated instead they're not only excluded from language stats but also hidden in diffs.
=> [chore] Hide vendor from diffs

docs/api/swagger.yaml, internal/api/client/notifications/notifications.go, internal/api/client/notifications/notificationsget.go, internal/db/bundb/notification.go, internal/db/bundb/notification_test.go, internal/db/notification.go, internal/processing/notification.go, internal/processing/notification_test.go
>
This pull request brings our notification serving (using `min_id` to page up) in line with what we do for home + public status timelines.
Also adds filters for notifications so that notifs about accounts or statuses which should not be visible are no longer shown to the requester (though they can still be seen if the id is known).
closes https://github.com/superseriousbusiness/gotosocial/issues/1720
If this is a documentation change, only the first checkbox must be filled (you can …
=> [bugfix] Rework notifs to use `min_id` for paging up

docs/configuration/advanced.md, example/config.yaml, internal/config/config.go, internal/config/defaults.go, internal/config/flags.go, internal/config/helpers.gen.go, internal/transport/controller.go, test/envparsing.sh, testrig/config.go
>
This pull request implements a configuration option for number of senders per CPU, while keeping the default multiplier of 2 * CPU.
=> [chore/performance] Make sender multiplier configurable

internal/api/client/search/searchget_test.go, internal/gtsmodel/account.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
>
This PR updates our typeutils logic to skip trying to fetch a local user when dealing with a local instance account. Not that it's a great idea to interact with the instance account, but at least now it won't return 500 when searching for it.
closes https://github.com/superseriousbusiness/gotosocial/issues/1289
=> [bugfix] Don't try to get user when serializing local instance account

web/source/css/profile.css, web/template/profile.tmpl
Just a tiny tweak after https://tweesecake.social/@weirdwriter/110351055809107669. Uses h1 and h2 for profile column headers as appropriate, but still visually styled the same as before
=> [frontend] Use more semantic headers for profile page

internal/api/util/errorhandling.go, internal/api/util/negotiate.go, internal/web/about.go, internal/web/base.go, internal/web/confirmemail.go, internal/web/customcss.go, internal/web/domain-blocklist.go, internal/web/profile.go, internal/web/rss.go, internal/web/settings-panel.go, internal/web/thread.go
Fixing a point mentioned in https://github.com/superseriousbusiness/gotosocial/issues/1759#issuecomment-1541690096
- Default to JSON over HTML for error handling
- Change the default error display for web endpoints to html
=> Prefer JSON errors in API endpoints

web/source/css/profile.css
Teeny fix to remove break-all on profile fields; it was causing lines to split unpleasantly, making them difficult to read.
=> [frogend/chore] remove break-all on profile fields

web/source/frontend/index.js, web/template/status.tmpl
Another small oversight.. made the dynamic renaming of "show more"/"show less" CW buttons not work, and similar for the media spoiler eye icon label
=> [frogend/chore] fix dynamicSpoiler elements

web/source/css/profile.css
v. small fix to restore previous behavior of back/next links on profiles, so that 'show older' always appears on the right, and 'back to top' always appears on the left
=> [frogend/chore] Update backnextlinks

web/template/profile.tmpl
Fixes the profile templates to include the user's domain (for easy copying), as that's never included in the acct field so didn't work with `acctInstance`
=> [frogend/chore] Fix profile domain

go.mod, go.sum, scripts/build.sh, vendor/codeberg.org/gruf/go-cache/v3/cache.go, vendor/codeberg.org/gruf/go-cache/v3/result/cache.go, vendor/codeberg.org/gruf/go-cache/v3/ttl/ttl.go, vendor/modules.txt
Updates go-cache library to v3.3.2 to fix possible race condition between invalidate hooks holding locks.
=> [bugfix] update go-cache to v3.3.3

internal/processing/account/update.go, internal/processing/account/update_test.go, testrig/testmodels.go
>
This PR fixes fields being duplicated when profile was updated but fields were left untouched. Issue was that we weren't resetting the accounts field's slice. Now we are! Added tests too, booya
=> [bugfix] Fix duplicating fields on profile edit

docs/installation_guide/nginx.md
>
Just bring the 'finished' nginx example in line with the one further up the page; that trailing slash is significant.
=> [docs] remove nginx trailing slash

docs/installation_guide/advanced.md
A proxy_pass in a named location, @name, should not include a trailing slash.
=> [bugfix] Fix proxy_pass in named location

internal/transport/finger_test.go
Every now and then the `TestFingerWithHostMetaCacheStrategy` would fail on a time related error. I suspect `suite.Equal` doesn't quite work as expected when given two `time.Time`'s, so instead explicitly check with the `time.Equal`.
=> [chore] Change time comparison in webfinger test

internal/db/bundb/migrations/20230521105850_emoji_empty_domain_fix.go
>
This pull request adds a database migration to fix a previous bodged migration, where emoji domains were being set to `''` for local emojis, when they should have been `NULL`.
The migration fixes this by updating all emoji domains to NULL where they were empty strings, then moving all emojis into a new table to ensure that the database default is set correctly.
closes https://github.com/superseriousbusiness/gotosocial/issues/1792 …
=> [bugfix] Fix incorrect default for empty emoji domain

cmd/gotosocial/action/admin/media/prune/common.go, cmd/gotosocial/action/testrig/testrig.go
>
- Ensure caches started properly when pruning, so they are also stopped properly.
- Update testrig initialization to avoid initializing caches twice.
closes https://github.com/superseriousbusiness/gotosocial/issues/1713
=> [bugfix] Start + stop caches properly for testrig + pruning

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, example/config.yaml, internal/config/config.go, internal/config/defaults.go, internal/config/helpers.gen.go, internal/gtscontext/log_hooks.go, internal/middleware/logger.go, test/envparsing.sh
Admins can now chose whether client IPs should be present in the logs. By default this is enabled in order to retain the current behaviour and because when running in non-proxied mode this is something admins probably want.
When having an LB in front of GtS this can be disabled as requsets can still be correlated between LB and GtS using the Request ID or the tracing facilities.
Fixes: #1574
=> [feature] Make client IP logging configurable

internal/gtserror/error.go, internal/gtserror/new.go, internal/gtserror/new_test.go, internal/gtserror/util.go, internal/httpclient/client.go, internal/httpclient/validate.go, internal/transport/deliver.go, internal/transport/dereference.go, internal/transport/derefinstance.go, internal/transport/finger.go, testrig/transportcontroller.go
- add back ValidateRequest()
- validate request BEFORE backoff-retry loop
- include response body in 4xx HTTP response errors
=> add back removed ValidateRequest() before backoff-retry loop

mkdocs.yml
From https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
Before:
After:
=> docs: support copy/pasta for code blocks

CONTRIBUTING.md
HOWTO on how to set things up locally for docs hacking.
Alternatively, we could commit a `requirements.txt` to root so that folks can `pip install -r requirements.txt` and maintainers can `pip freeze > requirements.txt` when things get updated / added. Happy to re-work this PR with that change if desired.
> [Rendered](https://github.com/decentral1se/gotosocial/blob/65b328c075c3336e36f3301cc87105a7909087c2/CONTRIBUTING.md)
This is my `requirements.txt` atm:
```
beautifulsoup4==4.12.2
cairocffi==1.5.1
CairoSVG==2.7.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
cssselect2==0.7.0
defusedxml==0.7.1
ghp-import==2.1.0
idna==3.4
importlib-metadata==6.6.0
Jinja2==3.1.2
Markdown==3.3.7
MarkupSafe==2.1.2
mergedeep==1.3.4
mkdocs==1.4.3
mkdocs-material==9.1.14 …
```
=> docs: local docs hacking howto

internal/regexes/regexes.go, internal/validate/formvalidation_test.go
Allows usernames of length 1.
Closes https://github.com/superseriousbusiness/gotosocial/issues/1691.
=> [bugfix] Allow usernames of length 1

docs/configuration/accounts.md, example/config.yaml, internal/config/config.go, internal/config/defaults.go, internal/config/helpers.gen.go, internal/validate/formvalidation.go, internal/validate/formvalidation_test.go, test/envparsing.sh, testrig/config.go
>
This pull request implements a config option for account custom css (10k characters default, up from 5k characters).
closes https://github.com/superseriousbusiness/gotosocial/issues/1806
=> [feature] Configurable custom css length

CONTRIBUTING.md
* Point to semaphore for local testing
* Use `DEBUG=1` when running the testrig
* Use `yarn` to install local dependencies first
* Provide an approach for install yarn
> [Rendered](https://github.com/superseriousbusiness/gotosocial/blob/2fe3f411d3cb7f7693c69bea1030298c4b378f25/CONTRIBUTING.md).
=> [docs]: semaphone ref & DEBUG usage for standalone testing

internal/federation/dereferencing/account.go, internal/federation/dereferencing/status.go
Only populate account / status models in the dereferencer when we *know* it is an *existing* up-to-date model, otherwise errors may be returned for related models not yet dereferenced.
=> [bugfix] only attempt to populate account/statuses from DB if already exist

web/template/header.tmpl
>
This pull request refactors our header template file to use nested templates for repeated values, tidies up some formatting for readability, and updates our use of 'icon' to drop 'shortcut' and add apple values (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#icon)
Closes https://github.com/superseriousbusiness/gotosocial/issues/969 by making it no longer necessary. 
If this is a documentation change, only the first checkbox must be filled (you can delete the others …
=> [chore/frontend] Refactor header templating, add `apple-touch-icon`

internal/api/util/errorhandling.go, internal/gtserror/withcode.go, internal/middleware/logger.go
>
This pull request updates error logging in aputil to check if the error came about because the requester hung up the request before it could be completed. If so, whatever errWithCode was given is replaced with a less alarming error, that indicates that the client already closed the request before we could process it.
Not a standard error code, but then again it doesn't really matter because the client isn't going to see it anyway...
This should make it easier to debug GtS, since the logs won't show so many superfluous error messages.
Please put an x inside each checkbox to …
=> [bugfix] Overwrite API client closed errors with `499 - Client Closed Request`

internal/federation/dereferencing/thread.go
>
This pull request fixes a bug in our thread dereferencing where we were always skipping the first item in replies by calling Begin() on the iter and then calling Next() immediately, skipping to the second item (which is mostly empty).
=> [bugfix] Fix first item of thread dereferencing always being skipped

docs/installation_guide/advanced.md, example/apparmor/gotosocial
Our default configuration places the SQLite DB in /gotosocial/, but the AppArmor profile doesn't allow us to write there. Instead of making the whole directory writable, add a writable area in /gotosocial/db/ instead and advise in the docs to move the DB there.
=> [bugfix] AppArmor profile for SQLite

internal/federation/federatingactor.go
>
Currently, side effect actor inbox forwarding unfortunately handles some of the necessary side effects of creating activities and whatnot (see https://github.com/superseriousbusiness/gotosocial/issues/1891). However, this often causes annoying errors to pop up, especially when doing things like receiving Likes from Misskey instances that target statuses our instance doesn't know about yet. This causes a db error which then results in a 500 being returned to the remote server.
As a temporary workaround before we fix the actual issue, we can at least tone down the error message …
=> [chore/bugfix] Demote 'failed' inbox forwarding to warn log rather than error return

internal/ap/activitystreams.go, internal/ap/extract.go, internal/ap/extractattachments_test.go, internal/federation/dereferencing/status.go, internal/federation/federatingdb/announce.go, internal/federation/federatingprotocol.go, internal/typeutils/astointernal.go, internal/typeutils/astointernal_test.go, internal/typeutils/util.go, internal/typeutils/wrap.go
>
This pull request does some refactoring and enprettification of functions in extract.go file in the `ap` package, to make the naming and commenting more consistent. It also uses the `pub.ToId` function way more liberally in order to ensure that URIs are extracted not just from URI strings, but also from Types that have an ID URI set. This should fix issues where, for example, some remote server Announce's something, and the Object is not an IRI but a whole-ass Note or something, and then GoToSocial fails to process the announce. Now, the URI will be extracted from the note, and …
=> [chore/bugfix] Refactor `ap/extract.go` functions, return URIs more reliably

go.mod, go.sum, internal/transport/finger_test.go, vendor/codeberg.org/gruf/go-cache/v3/result/cache.go, vendor/codeberg.org/gruf/go-cache/v3/ttl/ttl.go, vendor/modules.txt
Updates to latest version of `codeberg.org/gruf/go-cache/v3` which allows for full disabling of TTL checks. I.e. if you set the TTL and sweep to zero then the TTL nature of the cache will be fully disabled.
=> [performance] update go-cache library

docs/configuration/oidc.md
Updates the docs to specify that the claims received from an OIDC provider need to contain a non-zero and unique email address as that's used as part of user creation.
This came up in the support chat on Matrix. Someone was trying to use OIDC but some folks couldn't log in. Turns out they didn't have an email address set.
=> [docs] Clarify email requirement for OIDC

internal/federation/dereferencing/thread.go
>
Fix small mistake introduced in previous PR where statuses were marked as orphans if a call to their parent returned 404. Many implementations use 404 as a spicy 403 for followers-only statuses, so we were orphaning statuses unnecessarily.
=> [bugfix] Only mark status orphaned on 410 Gone

internal/db/bundb/account.go, internal/db/bundb/admin.go, internal/db/bundb/instance.go, internal/db/bundb/media.go, internal/db/bundb/timeline.go, internal/db/bundb/util.go
>
This pull request removes the final `whereEmptyOrNull` function calls (and the functions themselves), which were causing db request latency and causing some indexes to be ignored.
closes https://github.com/superseriousbusiness/gotosocial/issues/1777
=> [chore/performance] Remove remaining 'whereEmptyOrNull' funcs

docs/admin/backup_and_restore.md, docs/getting_started/index.md, example/borgmatic/README.md, example/borgmatic/config.yaml, example/borgmatic/media-to-borg-patterns.py
This changes the existing backup documentation to:
* Push a bit harder on people to perform backups, it's not really just a nice to have
* Removes the language about migrating to/from GoToSocial and a different ActivityPub server since that's really not supported
* Adds a section about using backup software and provides an example on how to do this using Borgmatic
=> [docs] Rework backups a bit

internal/api/util/parsequery.go, internal/federation/dereferencing/dereferencer.go, internal/federation/dereferencing/handshake.go, internal/processing/account/statuses.go, internal/processing/fedi/common.go, internal/processing/fedi/status.go, internal/processing/fedi/user.go, internal/web/profile.go, internal/web/thread.go
>
This pull request updates some of our web view status / account stuff:
- Reorder web view auth logic so that if an AP request comes in on a status URL, the AP representation can be served properly even if it's not a public status (assuming requester has permission to view it). Previously, we only served AP representations of public statuses that were requested using the URL rather than the AP URI, but this is not quite right.
- Serve 404 for local accounts that have been suspended, instead of showing a web view of an empty profile.
- Comment and tidy up for readability.
Please …
=> [bugfix] Reorder web view logic, other small fixes

web/source/css/profile.css
If someone makes a post with a long, uninterrupted piece of text in a code snippet, we would stretch the column to fit it, resulting in the UI going a bit whacky.
By setting min-width: 0% this fixes it, and we now automatically get a scrollbar on overflow instead.
Fixes: #1952
=> [bugfix] Don't stretch on very wide status'es

internal/db/bundb/relationship_follow.go, internal/db/bundb/relationship_follow_req.go, internal/db/bundb/relationship_test.go, internal/db/relationship.go, internal/processing/fromfederator.go
>
This pull request implements behavior to ensure that relationships are properly deleted when a block is received from a remote user via the federating API. Previously, we didn't properly delete follow (requests) in either direction, which lead to annoying and weird behavior.
closes https://github.com/superseriousbusiness/gotosocial/issues/1334
closes https://github.com/superseriousbusiness/gotosocial/issues/920
If this is a documentation change, only the first checkbox must be …
=> [bugfix] Delete mutual follow (requests) when receiving block from remote

mkdocs.yml
We already set edit_uri, but we forgot to enable the feature flag. By turning it on each page now gets an edit button on the right hand side of the page header. This'll open the edit view in GitHub.
Hopefully this makes it easier for folks to make (small) doc changes.
=> [docs] Activate the edit feature

internal/config/gen/gen.go, internal/config/helpers.gen.go, internal/config/state.go
The most common case for GtS is to read config at startup and never call the config.SetXXX methods after that. This means that in almsot all cases when GtS is running, the only thing we'll do is call config.GetXXX. However, since we currently use a Lock(), two config.GetXXX methods will have to wait on each other.
This changes the config state mutex to an RWMutex, allowing many goroutines to read the config at the same time. This should ensure that requests in HTTP handlers aren't blocked on eachother if they happen to call a config.GetXXX method.
The Set methods continue to call Lock() instead of RLock(), as they need to modify the config state, and the same goes for Viper() and Config().
If …
=> [feature] Use Read/Write lock for config

internal/processing/account/rss.go, internal/processing/account/rss_test.go, internal/web/rss.go
>
This PR tidies up some of the very messy rss feed logic and adds comments for clarity.
Also allows RSS feeds to be served even when the account owner hasn't posted anything yet (closes https://github.com/superseriousbusiness/gotosocial/issues/1951). In such a case, the result will be a feed that just doesn't have any items in it.
Example with items:
```xml
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
<title>Posts from @the_mighty_zork@localhost:8080</title> …
```
=> [bugfix] Tidy up rss feed serving; don't error on empty feed

internal/api/fileserver/servefile.go
This makes the serveFileRange function return the entire file if suffix-range is larger than content-length in compliance with RFC9110
closes #1978 
- [ x ] I/we have read the [GoToSocial contribution guidelines](https://github.com/superseriousbusiness/gotosocial/blob/main/CONTRIBUTING.md).
- [ x ] I/we have performed a self-review of added code.
- [ x ] I/we have written code that is legible and maintainable by others.
- [ x ] I/we have commented the added code, particularly in hard-to-understand areas.
- [ x ] I/we have made any necessary changes to documentation.
- [ x ] I/we have added tests that cover new code.
- [ x ] I/we have run tests and they pass locally with the changes.
- [ x ] I/we have run `go fmt ./...` and `golangci-lint run`.
=> [bugfix] Properly handle range > content-length

docs/configuration/advanced.md, docs/configuration/database.md, docs/configuration/general.md, docs/configuration/media.md, docs/configuration/observability.md, docs/configuration/oidc.md, docs/configuration/storage.md, docs/configuration/syslog.md, docs/configuration/tls.md, example/config.yaml, internal/config/defaults.go
>
This pull request aligns default values defined in `example/config.yaml` and in `internal/config/defaults.go` - in most cases changes are done to the config file.
There is one exception where default value is added to `defaults.go` - it is for `AdvancedThrottlingRetryAfter` variable introduced as part of #1466.
Also snippets of `config.yaml` file are updated in the documentation.
Closes #1964
If this is a documentation change, only the first checkbox must be filled (you can delete …
=> [bugfix] Align default values in the configuration file with the code

internal/transport/finger_test.go
This keeps being flaky on CI but we so far have no way to reproduce it locally. To that end, disable this test on CI, but leave it running locally in case we might catch the issue there.
=> [chore] Skip webfinger test on CI

internal/api/activitypub.go, internal/api/activitypub/emoji/emojiget.go, internal/api/activitypub/publickey/publickeyget.go, internal/api/activitypub/users/featured.go, internal/api/activitypub/users/followers.go, internal/api/activitypub/users/following.go, internal/api/activitypub/users/outboxget.go, internal/api/activitypub/users/repliesget.go, internal/api/activitypub/users/statusget.go, internal/api/activitypub/users/userget.go, internal/api/auth.go, internal/api/client.go, internal/api/fileserver.go, internal/api/fileserver/servefile.go, internal/api/nodeinfo.go, internal/api/util/negotiate.go, internal/api/wellknown.go, internal/middleware/cachecontrol.go, internal/web/web.go
>
This PR updates the cache-control middleware to allow callers to the middleware to set the Vary header appropriately. This fixes an issue where it was possible to get nginx to cache a 303 response for the main-key endpoint of a GtS user, because it was cacheing the redirect regardless of the Accept header value.
Also updates AP endpoints to prefer serving ActivityPub.
=> [bugfix] Set Vary header correctly on cache-control

internal/api/util/parsequery.go, internal/cache/cache.go, internal/cache/gts.go, internal/db/bundb/list.go, internal/db/bundb/relationship_follow.go, internal/processing/account/bookmarks.go, internal/processing/account/statuses.go, internal/processing/admin/report.go, internal/processing/list/delete.go, internal/processing/list/get.go, internal/processing/report/get.go, internal/processing/timeline/faved.go, internal/processing/timeline/home.go, internal/processing/timeline/list.go, internal/processing/timeline/public.go
- make list + list-entry cache invalidation more thorough
- allow list entry invalidation by ListID + FollowID
- allow emoji invalidation by CategoryID
- use `defaultValue` when a limit of `0` is provided
- update errors being logged to DEBUG, to log to ERROR
=> [bugfix] more robust list timeline invalidation

docs/api/swagger.yaml, internal/api/client/lists/listaccounts.go, internal/api/client/lists/listaccounts_test.go, internal/api/client/lists/lists_test.go, internal/api/util/parsequery.go, internal/processing/list/get.go
>
This pull request updates our /api/v1/lists/{id}/accounts endpoint, to return all accounts in the given list when limit is explicitly set to 0 (or less). As odd as this behavior may seem, it is in line with Mastodon API expectations, and without it clients like Tusky (which set the 0 limit explicitly) show only one account in a list, regardless of how many are actually present.
closes https://github.com/superseriousbusiness/gotosocial/issues/2006
If this is a documentation change, …
=> [bugfix] Return all accounts when list accounts limit <= 0

docs/configuration/media.md, example/config.yaml, internal/config/defaults.go, testrig/config.go
The old default of 30d can lead to a lot of media getting cached and significant disk usage, even on small or single person instances. A lot of deployments decrease this value, to 15 or even less. This is less of an issue when using object storage, but for local storage which is the more popular deployment option running out of disk space is unpleasant.
With GoToSocial's aim to fit in small places, this changes the default to a much more conservative 7 days. In all likelihood people aren't scrolling that far back in their timeline so this change shouldn't result in any excessive refetching of remote media. Existing deployments will only be affected by this change if the admin hasn't already configured this value, or didn't bootstrap from the example configuration.
closes #(issue)
closes …
=> [feature] Lower remote media cache config duration

example/config.yaml, internal/config/config.go, internal/config/helpers.gen.go, internal/typeutils/internaltofrontend.go, test/envparsing.sh
A number of applications use the version reported by /api/v1/instance as a way to do feature detection for the Mastodon client API. Due to the current GtS versions in 0.x, this often means GtS gets determined to be non-compatible by clients and libraries that only ever test against Mastodon proper.
This adds a configuration value that allows the admin to decide to inject a Mastodon version in that response instead, in order to cajole clients into working correctly with GtS. This is only done for /api/v1/instance as that's the Masto client API, nodeinfo is left as it is as that should not be used by Masto clients for feature detection.
Since the clients we recommend don't need to be tricked this way, this feature defaults to being off. Admins can enable it if so desired, which may be …
=> [feature] Report Masto version in /api/v1/instance

go.mod, go.sum, vendor/github.com/abema/go-mp4/probe.go, vendor/modules.txt
This updates the go mp4 lib to include https://github.com/abema/go-mp4/pull/135 which enables support for probing mp4 files with a co64 box instead of a stco box. This is the case for videos recorded on newer android devices.
=> chore: update go-mp4 to latest commit

Dockerfile, example/docker-compose/docker-compose.yaml
This pull request fixes #2045 ,you can set timezone now.
There is a tested Docker image:
```bash
docker pull eallion/gotosocial:test
```
- https://hub.docker.com/r/eallion/gotosocial/tags
closes #2045 
=> [feature] Configurable timezone in containers

Dockerfile, example/docker-compose/docker-compose.yaml
This reverts commit 96dd0e75f20a1f1f8203f3438ae7a82d260a0ef8 for the reasons given here: https://github.com/superseriousbusiness/gotosocial/pull/2046#issuecomment-1660016251
Essentially, the commit causes our builds to fail because we can't call `apk` or other commands inside build containers with our current setup. We need to find a better way of doing this.
=> [chore] Revert "[feature] Configurable timezone in containers (#2046)"

CONTRIBUTING.md, cmd/gotosocial/action/server/server.go, docs/configuration/httpclient.md, example/config.yaml, internal/config/config.go, internal/config/defaults.go, internal/config/flags.go, internal/config/helpers.gen.go, internal/httpclient/client.go, test/envparsing.sh
>
This pull request implements a configuration flag to set `InsecureSkipVerify` to `true` for the outgoing http client, and warns like hell if this is so set.
Warning looks like this:
`timestamp="01/08/2023 16:18:18.633" func=httpclient.New level=WARN msg="http-client.tls-insecure-skip-verify was set to TRUE. *****THIS SHOULD BE USED FOR TESTING ONLY, IF YOU TURN THIS ON WHILE RUNNING IN PRODUCTION YOU ARE LEAVING YOUR SERVER WIDE OPEN TO ATTACKS! IF IN DOUBT, STOP YOUR SERVER *NOW* AND ADJUST YOUR CONFIGURATION!*****"`
The idea is to make it a bit easier for people to set up …
=> [feature] Allow users to skip http client tls verification for testing purposes (with appropriately loud warnings)

internal/api/client/search/searchget_test.go, internal/processing/search/accounts.go, internal/processing/search/get.go, internal/processing/search/lookup.go, internal/processing/search/util.go, internal/visibility/account.go
>
This pull request makes instance account filtering a bit more granular in search results, to account for cases like https://github.com/superseriousbusiness/gotosocial/issues/2044 where there's a genuine need to search for something that our imprecise heuristics identify as an instance account.
As such, you can now search for an instance account by namestring, or by URL/URI, but they'll still be excluded in text search results.
closes https://github.com/superseriousbusiness/gotosocial/issues/2044
Please put an x inside each checkbox to indicate that you've read and followed it: …
=> [bugfix] Allow instance accounts to be shown in search results in certain circumstances

internal/router/router.go
Updates our HTTP router handle requests with unsupported methods for that route, which means unless it's a HEAD request on a fileserver endpoint it returns a 405 Method Not Allowed.
closes #2016
=> [bugfix] handle HEAD requests more elegantly

docs/configuration/database.md
The current command `create database gotosocial with locale C.UTF-8 template template0;` fails because the locale has to be quoted:
```
postgres=# create database gotosocial with locale C.UTF-8 template template0;
ERROR:  syntax error at or near "."
LINE 1: create database gotosocial with locale C.UTF-8 template temp...
```
Tested manually that it works with the quotes and the official postgres examples also use quotes around the locales: https://www.postgresql.org/docs/current/sql-createdatabase.html
=> [docs] fix postgres create database command

internal/federation/federatingdb/create.go, internal/federation/federatingdb/create_test.go, internal/processing/fromfederator.go, internal/typeutils/astointernal.go, test/run-postgres.sh, test/run-sqlite.sh, testrig/testmodels.go
Updates federatingdb logic to only accept status creation activities if the receiving account is either mentioned, or follows the requesting account.  Also reshuffles the `createStatusable()` logic a little so we check for an existing status with URI in the database before bothering with the deref of forwarded status.
closes #1965
=> [bugfix] don't accept unrelated statuses 

internal/httpclient/client.go
=> [bugfix] only set content-length AFTER rewinding body bytes

internal/db/bundb/list.go, internal/timeline/manager.go
>
These should be per iteration, not per loop. This was caught by running a build with the loopvar experiment: go build -gcflags=-d=loopvar=2.
=> [bugfix] Fix incorrect per-loop variable capture

internal/api/auth/authorize.go, internal/api/auth/callback.go, internal/cache/gts.go, internal/cache/size.go, internal/config/config.go, internal/config/defaults.go, internal/config/helpers.gen.go, internal/db/application.go, internal/db/bundb/application.go, internal/db/bundb/application_test.go, internal/db/bundb/bundb.go, internal/db/bundb/status.go, internal/db/bundb/user.go, internal/middleware/tokencheck.go, internal/processing/account/delete.go, internal/processing/app.go, internal/typeutils/internaltofrontend.go, test/envparsing.sh
- Removes relational part of queries for status selects and user selects
- Adds new separate `applicationDB{}` with its own caching
closes https://github.com/superseriousbusiness/gotosocial/issues/1094
=> [performance] remove last of relational queries to instead rely on caches

internal/processing/workers/fromfediapi.go
>
Missed a nil pointer deref during refactoring a few PRs ago, this fixes that :)
closes https://github.com/superseriousbusiness/gotosocial/issues/2098
=> [bugfix] Populate `followRequest` before accessing `TargetAccount` ptr

internal/ap/normalize.go, internal/ap/normalize_test.go, internal/api/client/statuses/statuscreate_test.go, internal/processing/account/create.go, internal/processing/account/update.go, internal/processing/admin/domainblock.go, internal/processing/instance.go, internal/processing/media/update.go, internal/processing/status/create.go, internal/text/emojionly.go, internal/text/markdown.go, internal/text/markdown_test.go, internal/text/minify.go, internal/text/plain.go, internal/text/sanitize.go, internal/text/sanitize_test.go, internal/web/opengraph.go
>
This pull request updates our sanitization process to remove inline img tags, at least until we can find a nicer way of including them.
Also renames a couple functions that were not well named, and adds comments on the sanitizer linking to MDN docs about the various attributes and elements :)
closes https://github.com/superseriousbusiness/gotosocial/issues/2097
=> [bugfix] Use custom bluemonday policy to disallow inline `img` tags

internal/api/auth/callback.go
>
We were always using the string "client_id" to try to fetch the OIDC client application from the db :fireworks: 
closes https://github.com/superseriousbusiness/gotosocial/issues/2096
=> [bugfix] Fix using wrong key for clientID during oauth callback

internal/middleware/extraheaders.go, internal/middleware/middleware_test.go
>
This pull request updates our content-security-policy to add the instance's s3 endpoint as a source for images and media, if s3 is configured in non-proxying mode. 
=> [bugfix] Add s3 endpoint as image-src and media-src for CSP

.drone.yml, README.md, docs/getting_started/installation/metal.md, docs/getting_started/releases.md
>
This pull request adds an extra step to our snapshot process (triggered when a PR is merged into main) to publish binary tar.gz snapshots to s3.superseriousbusiness.org, so that folks don't have to build their own snapshots if they want to try running from current main.
This brings our binary snapshot process in line with the docker snapshot image process.
~~Draft right now, because I want to add a few things to the docs explaining how to download these snapshot binaries.~~
If this …
=> [feature] Add snapshot binary builds + uploads

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, docs/configuration/advanced.md, example/config.yaml, internal/config/config.go, internal/config/defaults.go, internal/config/flags.go, internal/config/helpers.gen.go, internal/middleware/contentsecuritypolicy.go, internal/middleware/extraheaders.go, internal/middleware/middleware_test.go, internal/storage/storage.go, test/envparsing.sh
>
This pull request updates our CSP construction logic to add extra URIs from config, and s3 URI from probed storage. This should fix cases where the S3 endpoint differs from the domain where images etc actually end up getting served from, while also adding flexibility for instance admins to specify their own URIs if they wish.
Tested this locally by connecting the testrig to an actual S3 bucket, and it works OK :)
Closes https://github.com/superseriousbusiness/gotosocial/issues/2123 …
=> [feature/bugfix] Probe S3 storage for CSP uri, add config flag for extra URIs

internal/cleaner/media.go, internal/db/bundb/media.go, internal/db/bundb/media_test.go, internal/db/bundb/migrations/20230821075342_attachment_cleanup_updates.go, internal/db/media.go
>
This pull request updates our uncacheing logic a little bit:
Replaces old index which included fields we aren't using anymore during the cleanup. New index includes only the used ones, as suggested by sqlite `.expert`. For SQLite, it is massively faster since it doesn't create a temporary index anymore. Seems to not make much difference for Postgres, which was fine anyway, but we should keep an eye on this.
When uncacheing remote media, treat headers/avatars and status attachments differently. Ie., don't let recent *account* fetch prevent *status attachment* uncaches, and vice …
=> [performance] Tweak media attachment cleanup; replace stale index

web/source/css/status.css
>
This pull request updates CSS for headings inside statuses, to ensure that they're sensibly sized. Previously, our h1 inside statuses was being overridden by normalization in base.css, and h5 was styled to be even smaller than body text, which is just a bit silly!
closes https://github.com/superseriousbusiness/gotosocial/issues/2150
=> [bugfix/frontend] Normalize header sizes

web/source/css/status.css
>
This pull request updates status CSS to make line height just a little bit bigger, so that wall-of-text statuses are a bit easier on the eyes.
Before:
After:
=> [chore/frontend] Make line-height a wee little bit bigger

internal/db/bundb/account.go, internal/db/bundb/db.go, internal/db/bundb/emoji.go, internal/db/bundb/list.go, internal/db/bundb/marker.go, internal/db/bundb/media.go, internal/db/bundb/status.go
Until now we have just been wrapping the bun database to add our own error processing hook, but we were forgetting the transactions! (agghhh!!!) Bun transactions are now properly wrapped to give our own error processing so that we may do nice, reasonable things like `if errors.Is(err, db.ErrAlreadyExists)` within transactions.
I desperately need to try adding SQLITE_BUSY retries into the modernc.org/sqlite package, and for the error processing, figuring out how to hook that in as a neater upstream fix to `uptrace/bun`... Because this wrapping situation is getting out of hand.
=> [bugfix] wrap bun.Tx to add our own error processing

internal/db/bundb/bundb.go
As the title says really! Moves the SQLite connection pragmas into the connection string, just to ensure that all our connection preferences are set on every created new connection, considering that it's a little unclear what data is shared across SQLite connections. These are set using the `_pragma` URI query key as specified in the `modernc.org/sqlite.Driver{}.Open()` documentation.
An example of a connection string with this:
`timestamp="01/09/2023 09:02:20.915" func=bundb.sqliteConn level=INFO msg="connected to SQLITE database with address file:/data/sqlite.db?_pragma=busy_timeout%28300000%29&_pragma=journal_mode%28WAL%29&_pragma=synchronous%28NORMAL%29&_pragma=cache_size%28-8192%29&_txlock=immediate"`
=> [bugfix] move SQLite pragmas into connection string

scripts/get_latest_snapshot.sh
>
This pull request adds a quick and fairly dirty bash script into the `scripts` directory that folks can use to pull the latest snapshot release tar.gz from our Minio S3 bucket.
I didn't advertise it anywhere in the docs because it's not something we should really 'recommend' to people, but we can at least point it to folks who regularly run snapshots and want a very slightly easier way of doing it.
If this is a documentation change, only the first checkbox must be filled (you can …
=> [chore] Add script for downloading latest snapshot tar.gz

internal/federation/dereferencing/thread.go
See title. Also some little refactoring to increase code reuse, reduce log string length and hopefully provide more useful information in the case of tracing.
=> [bugfix] fix checks for deref the same status descendants / ascendants

docs/advanced/security/firewall.md
This pull request add an example of regex for fail2ban, to make it easier for novices to configure it
This regex ignores failed API attempts, as it's not relevant
I don't know if it's also applicable to SSHGuard because I don't know it
That's explain why I didn't made a SSHGuard example too
=> [docs] add fail2ban example regex in the doc

internal/api/wellknown/webfinger/webfingerget_test.go, internal/util/namestring.go, internal/util/namestring_test.go
>
It's now possible to pass an Actor URI as the resource to query for when doing a webfinger query. The code now extracts the username and domain from the URI. The URI needs to be fully qualified, including having a scheme of http or https to be recognised as such.
The acct scheme is handled as we used to, including dealing with an erroneous leading @ on the username. We retain the ability to handle resources without a scheme by parsing them again with the acct scheme if the original parse failed. This can happen due to parsing ambiguities when dealing with a string like …
=> [feature] Support Actor URIs for webfinger queries

internal/paging/page_test.go
The paging test was incorrectly using a randomly generated limit which it was expecting to be > 0, but sometimes could be 0.
=> [bugfix] fix flakey paging test

internal/processing/workers/surfacetimeline.go, internal/visibility/home_timeline.go, internal/visibility/home_timeline_test.go
>
This pull request moves the check for reblogged status visibility out of `internal/processing/workers/surfacetimeline.go` and puts it in `internal/visibility/home_timeline.go`.
The latter is called not just for streaming of new statuses, but for building timelines by getting statuses out of the db, as well. This should help filter out unwanted reblogs, and also avoids splitting up status visibility logic across two very different packages.
closes https://github.com/superseriousbusiness/gotosocial/issues/2131
Please put an x inside each checkbox to indicate that you've read and …
=> [bugfix] Move `follow.show_reblogs` check further up to avoid showing unwanted reblogs in home timeline

docs/user_guide/settings.md, web/source/settings/style.css, web/source/settings/user/profile.js, web/source/settings/user/settings.js
>
This pull request adds the ability to set the 'discoverable' flag via the account settings panel.
A link to the docs is provided right next to the setting, to inform users about what the setting actually does.
As always, this setting defaults to 'false', no changes there.
Currently, the only thing that setting discoverable to 'true' really does is federate the flag to other instances, and update the robots meta tags for the profile to allow some scraping by search engines.
This has nothing to do with indexing of posts for search by Mastodon instances, since Mastodon uses a …
=> [frontend] Add `discoverable` flag to settings panel

internal/db/bundb/timeline.go, internal/processing/account/bookmarks.go, internal/processing/account/statuses.go, internal/processing/admin/report.go, internal/processing/timeline/public.go, internal/util/paging.go, internal/util/paging_test.go
>
This pull request fixes a bug where paging would stop when all items in a timeline response ended up being filtered out for various reasons (visibility, blocks, etc).
Basically, we were deriving paging headers properly, but then ignoring them in the PackagePageableResponse function when empty items were passed in.
As a fun little bonus, this PR also fixes paging for the public/local timeline to use minID properly. I don't think this was causing any real issues yet, but you never know.
All of the above is more or less just a quick fix 'for now' until we convert everything to the …
=> [bugfix] Fix paging for empty items

docs/api/swagger.yaml, internal/api/client/accounts/statuses.go
API Docs error: /api/v1/accounts/{id}/statuses
Query PinnedKey
Mastodon API Docs: pinned
GoToSocial API: pinned
GoToSocial API Docs: pinned_only
This pull request implements xyz or fixes abc.
closes #2250 
=> [docs]  statuses-query-pinned  #2250

web/source/settings/lib/query/admin/custom-emoji/index.ts
>
Error `TypeError: can't define array index property past the end of an array with non-writable length` was popping up in the console when using 'steal this look'.
Turns out I broke it.
So now I fixed it!
Explanation: we were returning an array which was being used in a react component *and then modified while the component was using it*, which is a big react no-no.
Fixed this by awaiting properly in the mutation function, so the returned array doesn't get modified again.
If this is …
=> [bugfix/frontend] Fix 'steal this look' emoji promise mapping

internal/db/bundb/errors.go, internal/db/bundb/errors_test.go
>
We were importing the wrong pgconn package in our error wrapping, which was causing pg errors to slip through without being wrapped. This fixes that by importing the correct package, and also adds some tests.
closes https://github.com/superseriousbusiness/gotosocial/issues/2271
=> [bugfix] Postgres error wrapping fix

internal/processing/timeline/public.go
>
Add accidentally-removed "local" param back to public timeline link header.
closes https://github.com/superseriousbusiness/gotosocial/issues/2253
=> [bugfix] Add missing "local" param in public timeline link headers

internal/cleaner/emoji_test.go, testrig/testmodels.go, web/source/settings/admin/emoji/remote/parse-from-toot.js, web/source/settings/lib/form/check-list.tsx, web/source/settings/lib/form/types.ts, web/source/settings/lib/query/admin/custom-emoji/index.ts, web/source/settings/redux/checklist.ts
>
I made a typo in patchRemoteEmojis that meant the emoji 'steal this look' thingy still wasn't working properly. This oughta fix it.
EDIT: it mostly fixes it but I'm still getting `TypeError: e is not iterable` when submitting the form after selecting some emojis to copy to local. The emojis are successfully copied though, so I assume the error is in the `onFinish` callback for the mutation somewhere...
EDIT2: Fixed the bug mentioned above, and found a new one: new patched emoji results were being added to the checklist state. The problem was that new patched emojis returned from …
=> [bugfix/frontend] fix typo and other oddness in patchRemoteEmojis

.drone.yml, .golangci.yml, CONTRIBUTING.md, go.mod, go.sum, internal/db/bundb/bundb.go
>
Bump go version from 1.20.x to 1.21.x.
This will let us use the fancy new Go language features, if we like.
Note: we were already building using go 1.21.x, so no difference there, we're just switching the language version properly now.
=> [chore] bump go version -> 1.21.x

web/source/settings/lib/form/get-form-mutations.ts, web/source/settings/lib/form/submit.ts, web/source/settings/lib/form/text.tsx, web/source/settings/lib/form/types.ts, web/source/settings/lib/query/query-modifiers.ts, web/source/settings/user/profile.js
>
When custom CSS is not enabled on an instance, submitting any custom CSS update (even if it's just an empty string) returns a 400 error since custom CSS is not allowed.
Previously, we were getting around this by just not generating a form field at all for custom CSS when it was disabled on the instance. When I refactored some of the frontend stuff, I made it so the form field was shown, but was not enabled and couldn't be updated by users. This causes empty `custom_css` to be sent along to the instance when doing profile updates, meaning the update always fails.
To get around …
=> [bugfix/frontend] Add `nosubmit` option to form fields; use it when instance custom CSS disabled

Dockerfile
>
- Update our go swagger version
- use go v1.21 when doing swagger generate inside docker container (I think @NyaaaWhatsUpDoc even warned me about this but I forgot)
- Use `go install` to add swagger since it can be a bit more reliable than downloading the binary: https://github.com/go-swagger/go-swagger/issues/2860
=> [chore] bump go swagger version in Docker build

web/source/settings/lib/query/admin/domain-permissions/export.ts, web/source/settings/lib/query/admin/domain-permissions/process.ts, web/source/settings/lib/types/domain-permission.ts
>
This pull request brings our csv importing / exporting in line with the format recognized by Mastodon import/export, and fixes a couple weird little issues around importing/exporting. Should work properly now.
=> [bugfix/frontend] Export/import CSV correctly

internal/ap/extract.go, internal/ap/extractattachments_test.go, internal/ap/interfaces.go
>
Honk provides both `name` and `summary` in their attachments. Unlike many other AP implementations, they actually use these correctly, so "name" is the name of the file, and "summary" is the image description. Previously, we were only checking the "name" field to parse image description, since this is what most other implementations use. This PR fixes this to check "summary" first and fall back to "name".
Closes https://github.com/superseriousbusiness/gotosocial/issues/2302
If this …
=> [bugfix] Extract description as `summary` first, fall back to `name`

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, docs/admin/media_caching.md, docs/admin/settings.md, docs/configuration/media.md, example/config.yaml, internal/api/wellknown/webfinger/webfingerget_test.go, internal/cleaner/cleaner.go, internal/config/config.go, internal/config/defaults.go, internal/config/flags.go, internal/config/helpers.gen.go, internal/gotosocial/gotosocial.go, internal/processing/admin/admin.go, internal/processing/admin/admin_test.go, internal/processing/processor.go, internal/processing/processor_test.go, internal/processing/workers/workers_test.go, mkdocs.yml, test/envparsing.sh, testrig/config.go, testrig/processor.go
>
This pull request implements customizable start time + interval period for media cleanup jobs.
Adds `media-cleanup-from` and `media-cleanup-every` config fields, which keep the current default values of `00:00:00` (midnight) and `86400000000000` or `24h` (24 hours).
These fields allow admins to run their cleanup at different times and rates. For example, say one wanted to run a cleanup every 3 days at 4.30am, one could set `media-cleanup-from` to `04:30:00` and `media-cleanup-every` to `72h`.
To make this work, instantiation of the cleaner has been pushed all the way back to the …
=> [feature] Customizable media cleaner schedule

internal/processing/polls/vote.go, internal/processing/workers/fromfediapi.go, internal/typeutils/internaltofrontend.go
=> [bugfix] fix poll vote count responses on client and fedi API vote creation

docs/api/swagger.yaml, internal/api/client/polls/polls_vote.go, internal/api/model/poll.go, internal/api/model/status.go, internal/typeutils/internaltofrontend.go
>
This pull request fixes up swagger docs for polls, and also ensures that the `voted` and `own_votes` fields of polls are always serialized when a user token is presented, even if the value are false/empty.
=> [bugfix/docs] Poll api fixups + swagger docs

internal/federation/dereferencing/account.go, internal/federation/federatingprotocol.go, internal/processing/fedi/common.go, internal/processing/fedi/user.go
>
This pull request fixes a bug where accounts that were suspended via the admin panel could become marked as unsuspended again on refresh of the account.
Bug only affected specifically-targeted accounts, not accounts that were blocked by a domain block action. All the account's relationships and posts and media and stuff were still deleted just fine by the side effects.
For good measure, add some early checks to bail fedi requests if a remote account was marked as suspended locally. …
=> [bugfix] Don't try to update suspended accounts

internal/api/auth/token_test.go, internal/api/client/accounts/accountdelete_test.go, internal/api/client/accounts/accountupdate_test.go, internal/api/client/admin/emojicreate_test.go, internal/api/client/admin/emojiupdate_test.go, internal/api/client/instance/instancepatch_test.go, internal/api/client/media/mediacreate_test.go, internal/api/client/media/mediaupdate_test.go, internal/api/client/polls/polls_test.go, internal/api/client/polls/polls_vote.go, internal/api/client/polls/polls_vote_test.go, internal/api/client/statuses/statuscreate.go, internal/api/model/poll.go, testrig/util.go
>
Unfortunately, some of our fave clients (pinafore, semaphore, derivatives thereof) submit some poll-related fields as strings when they ought to be integers. These clients aren't maintained anymore, so submitting fixes upstream is not useful. This hack allows those strings to work as well. This is technically compliant with the Mastodon API, though the Mastodon API is not documented as allowing this.
If this is a documentation change, only the first checkbox must be filled (you can …
=> [chore/bugfix/horror] Allow `expires_in` and poll choices to be parsed from strings

internal/api/activitypub.go, internal/api/auth.go, internal/api/client.go, internal/api/fileserver.go, internal/api/nodeinfo.go, internal/api/util/errorhandling.go, internal/api/wellknown.go, internal/gotosocial/gotosocial.go, internal/gtserror/withcode.go, internal/router/attach.go, internal/router/router.go, internal/router/timeout.go, internal/web/web.go, testrig/router.go
>
This pull request wraps HTTP requests (API, web, etc) in a handler that will time out requests after 10 minutes (if the request hasn't completed already). This should prevent very slow client requests from hanging around for too long in the server, taking up PRECIOUS MEMORY and so on.
Also does a few little chores:
- Deinterface router.
- Tidy up router functions a bit.
=> [feature/performance] Wrap incoming HTTP requests in timeout handler

internal/db/bundb/migrations/20231110142330_small_poll_table_tweaks.go, internal/db/bundb/poll.go, internal/db/bundb/poll_test.go
>
This pull request updates our db queries a little bit for polls:
- Don't bother checking for db.ErrNoEntries on delete, since this is never returned; use RowsAffected instead. You can never recover from an error inside a transaction, so checking for an ErrNoEntries and continuing would cause the next query to fail anyways.
- Fix choices slice return -- you can't do LIMIT on a Delete using bun, so bun doesn't know that only one row will be deleted, so you have to select into a slice of slices.
- Select fewer columns where possible (v. small performance tweak).
Please put an x …
=> [bugfix] Update poll delete/update db queries

internal/federation/authenticate.go, internal/federation/dereferencing/handshake.go, internal/federation/federatingprotocol.go, internal/processing/admin/domainkeysexpire.go, internal/processing/fedi/common.go, internal/processing/fedi/status.go, internal/processing/fedi/user.go
Refactors our very crucial .AuthenticateFederatedRequest() function to handle new instance / account dereferencing, along with suspension checks. This reduces the need for these checks (and possibility of them being missed) in other areas of the codebase.
=> [chore/security] refactor AuthenticateFederatedRequest() to handle account deref + suspension checks

internal/api/model/poll.go, internal/api/model/status.go, internal/router/template.go, internal/typeutils/internaltofrontend.go, testrig/testmodels.go, web/source/css/status.css, web/template/poll.tmpl, web/template/status.tmpl
>
This pull request adds a template + web view for rendering status polls in the frontend.
Produced HTML for a poll looks like this:
```html
<figure class="poll">
<figcaption class="poll-info">
<span class="poll-expiry">Poll closed&nbsp;Aug 28, 2021, 10:40</span>
<span class="total-votes">Total votes: 2</span>
</figcaption>
<ul class="poll-options">
<li class="poll-option">
<label aria-hidden="true" for="option-1" lang="en">50:50</label>
<meter aria-hidden="true" id="option-1" min="0" max="100" value="0">0&#37;</meter>
<div class="sr-only">Option 1:&nbsp;<span …
```
=> [feature] Poll web view

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, internal/api/metrics.go, internal/api/metrics/metrics.go, internal/web/web.go
>
The default prometheus handler we were using encodes using gzip if requested. However we were *also* enabling our gzip middleware, meaning things got double gzip encoded and therefore didn't work.
This PR fixes that by disabling compression on promhttp and using our own gzip middleware as well.
Also moves the metrics handling out of web and into its own API module, for consistency.
If this is a documentation change, only the first checkbox must be filled (you can delete the others …
=> [chore/bugfix] Fix double gzip on prometheus endpoint

docs/getting_started/index.md
=> [docs] Add docs about memory requirements and swap

internal/cache/gts.go, internal/db/bundb/emoji.go, internal/db/bundb/instance.go, internal/db/bundb/notification.go, internal/db/bundb/relationship_note.go, internal/db/bundb/status_test.go, internal/db/bundb/user.go, internal/db/emoji.go, internal/db/instance.go, internal/db/notification.go, internal/db/relationship.go, internal/db/user.go
>
This PR fixes the following scenario:
- Some of my statuses get cached after database calls.
- My account model is attached to those statuses.
- I update my profile picture.
- The statuses still show the old profile picture, on both the web view and via the API.
Essentially, what was happening in the above scenario is that the old account model was being kept on the cached statuses, and those statuses weren't being invalidated when the account model was updated.
There are two possible approaches to fixing this:
1. Invalidate all cache entries that contain a pointer to a given …
=> [bugfix] Don't copy ptr fields in caches

internal/db/bundb/migrations/20231128140847_remove_duplicate_indices.go
>
This PR drops a lot of duplicate indexes in cases where:
- a unique constraint for columns in the index already exists (so this index is a duplicate); OR --
- a covering index already exists for the indexed column
The PR also renames constraints that were misnamed in previous migrations (Postgres only).
closes https://github.com/superseriousbusiness/gotosocial/issues/2122
closes https://github.com/superseriousbusiness/gotosocial/issues/2017
If this is a documentation change, only …
=> [performance/postgres] Rename constraints, remove duplicate indexes

internal/db/bundb/migrations/20231128140847_remove_duplicate_indices.go, internal/db/bundb/migrations/20231130103643_fix_index_whoopsie.go
>
This pull request re-adds some indexes that were removed in a previous PR. Postgres query planner seemed likely to manage without those indexes, but sqlite doesn't like going without, so here we are!
Also while I'm doing penance for that previous broken PR, fixed the naming of some other indexes.
=> [chore] Re-add indexes, rename account actions indexes

internal/federation/dereferencing/announce.go, internal/federation/federatingdb/announce_test.go, internal/gtsmodel/status.go, internal/processing/common/status.go, internal/processing/fedi/status.go, internal/processing/status/boost.go, internal/processing/status/fave.go, internal/processing/workers/fromfediapi.go, internal/processing/workers/fromfediapi_test.go, internal/typeutils/astointernal.go, internal/typeutils/astointernal_test.go, internal/typeutils/internal.go, internal/typeutils/internaltoas_test.go, internal/typeutils/internaltofrontend.go, internal/web/thread.go
>
- ~~Use per-URI deref locks for Announce dereferences to avoid races.~~
- Use new `BoostOfURI` field on statuses for doing Announce derefs (new field not stored in the db).
- Ensure faves and boosts are redirected properly to top-level status when the fave or boost was created targeting the ID of a boost wrapper.
- Don't serve boost wrappers via the web UI or the fedi API.
- Use `Unretrievable` to do noop nicely when a boost target is on a blocked domain.
- Fail to serialize boost via the client API if BoostOfID is set but BoostOf is not (for whatever reason).
This is rather a …
=> [bugfix/chore] `Announce` reliability updates

docs/configuration/index.md, docs/getting_started/installation/container.md, docs/getting_started/installation/metal.md
* Change the instructions about how to create the initial configuration file
* Update the container instructions to push people towards using release tags
=> [docs] Change configuration creation instructions 

internal/config/gen/gen.go
The package was renamed from langs to language.
=> [bug] Fix an import statement in the gen template

internal/db/bundb/migrations/20231208152242_sqlite_analyze.go
See https://github.com/superseriousbusiness/gotosocial/issues/2425 for more details.
We may want to run VACUUM as well, but since this can take quite a long time (10-15 minutes-ish), it might be better not to, but instead tell folks to run it manually. I'm not entirely sure yet.
=> [chore] Run `ANALYZE` for SQLite after latest migrations

internal/processing/workers/surfacenotify.go
We'd set the wrong notification type for a voted-in poll ending; this fixes that!
https://docs.joinmastodon.org/methods/notifications/
=> [bugfix] Fix wrong notification type sent for poll end

internal/db/bundb/search.go, internal/db/bundb/search_test.go, internal/processing/search/accounts.go, internal/processing/search/get.go
>
This pull request tightens up our search logic a little:
- Don't use LOWER for SQLite `LIKE` searches. SQLite LIKE search is case-insensitive anyway, and LOWER is expensive. Postgres still uses LOWER.
- Passing a query string starting with `@` into the accounts search DB function will make it only look for accounts that *start with* the text after the `@`. This is a shitload faster than doing a full wildcard search, and is more suitable for an autocomplete-style search anyway. The leading `@` is stripped properly when doing a search like this.
- Searches that start with `@` will …
=> [bugfix] Narrow search scope for accounts starting with '@'; don't `LOWER` SQLite text searches

web/template/status.tmpl
Quick change to ensure that instead of just reading `en` for language, which is meaningless, screenreaders (at least, the Ubuntu default one I tested) will now read `language, engels left paren english right paren` for `Language: Engels (English)`, which is actually helpful! Also makes it so the published time is read nicely too.
=> [bugfix] Make screenreaders read out Language of posts properly

internal/cache/gts.go, internal/db/bundb/migrations/20231215115920_add_status_poll_index.go, internal/db/bundb/poll.go, internal/db/bundb/poll_test.go, internal/db/bundb/status.go, internal/db/poll.go, internal/db/status.go, internal/federation/dereferencing/status.go, internal/processing/common/status.go, internal/processing/fedi/status.go, internal/processing/polls/poll.go, internal/processing/status/bookmark.go, internal/processing/status/boost.go, internal/processing/status/fave.go, internal/processing/status/get.go, internal/processing/status/mute.go, internal/processing/status/pin.go
Adds an upToDate flag to the common processor target status fetching functions, which specifies whether to force a refresh of the given status. We use this to then force a refresh within the poll handler.
The dereferencer has also been updated to enforce a 5 minute cooldown on the force flag, so spamming the refresh button can't accidentally DOS another server, (or us acciddentally passing a force refresh flag elsewhere...)
This also updates the common processor functions to refresh the status synchronously instead of async when the flag is provided, which should help with issues of content "pop-in".
=> [bugfix] use a much shorter refresh limit for statuses with polls

ROADMAP.md, docs/faq.md
the docs' FAQ says that GTS lacks "muting conversations" and "polls", but this is no longer the case with the brand new v0.13.0 Spider Sloth 🕷️ 🎉 
note that maybe another of the missing features mentioned has also now been implemented and I don't know
edit: i also updated the roadmap to tick those 2 features
=> [docs]: Update FAQ and ROADMAP

internal/api/util/response.go, internal/middleware/ratelimit.go, internal/middleware/throttling.go, internal/middleware/throttling_test.go
Forgot I had these changes waiting around in the mountain that is my git stash >:D
Reduces the complexity of the throttling middleware to use a singular channel queue for the permitted executing requests logic, and simplifies the backlog to only use an atomically updated integer (we don't need anymore than this).
=> [performance] simpler throttling logic

internal/db/bundb/bundb.go
This ensures that at the end of migrations, we run ANALYZE if we're using SQLite. This should be relatively quick and guarantees that the table and index statistics have been updated. This helps to ensure the query planner makes better choices when it comes to picking which indexes are used when running queries.
=> [feature] Run ANALYZE after migrations on SQLite

internal/typeutils/internaltofrontend.go
In the case where the requesting user had voted in a poll, we would double count their votes towards the overall count of votes. This happens because we calculate a vote count of our own votes in case we can't see all the votes, but this isn't cleared before processing in the case where we _can_ see all the votes, resulting in a double count.
closes #2463
=> [bugfix] fix poll total vote double count

internal/api/client/admin/admin.go
actually allows the server routes to be populated without panic ....
=> [bugfix] :innocent:

internal/federation/dereferencing/account.go, internal/federation/dereferencing/status.go
- fixes issue of new statusUpToDate() checks skipping status edits made in < 5mins after creation (as noted + tracked down by @Sentynel in matrix, thank you!). now we only perform the up-to-date check if no incoming data is provided, i.e. if we need to make an outgoing dereference request.
- updates account dereferencing up-to-date logic to match that of statuses
- adds a check after all webfingering + dereferencing in the account dereferencer for an empty domain #2474 
the migration itself i'm thinking we write after christmas, as it will involve dropping accounts with NULL domain entries, which is VERY SCARY IN CASE WE DROP LOCAL USER ACCOUNTS. i'm thinking we perform a double check by parsing the account uris and checking the host field maybe??
=> [bugfix] misc dereferencer fixes

internal/cache/domain/domain.go, internal/cache/domain/domain_test.go, internal/db/bundb/domain_test.go
Turns out the children in the radix trie were being sorted in the wrong direction :woman_facepalming:
=> [bugfix] fix higher-level explicit domain rules causing issues with lower-level domain blocking

README.md, example/config.yaml, internal/config/testdata/test.yaml, internal/db/bundb/migrations/README.md, internal/db/bundb/statusbookmark_test.go, internal/db/bundb/statusfave_test.go, mkdocs.yml, web/source/css/_colors.css, web/source/css/about.css, web/source/css/base.css, web/source/css/index.css, web/source/css/page.css, web/source/css/profile.css, web/source/css/status.css, web/source/css/tag.css, web/source/css/thread.css
Update remaining copyright notices / license headers that used the 2021-2023 range.
=> [chore/docs] Replace specific year range of copyright notice

web/source/settings/index.js, web/source/settings/lib/form/array.ts, web/source/settings/lib/form/get-form-mutations.ts, web/source/settings/lib/form/index.ts, web/source/settings/lib/form/types.ts, web/source/settings/lib/query/user/index.ts, web/source/settings/lib/types/migration.ts, web/source/settings/style.css, web/source/settings/user/migration.tsx, web/source/settings/user/profile.tsx, web/source/settings/user/settings.tsx
>
This pull request adds a migration section to the user settings panel, allowing users to set and unset aliases, and to initiate a Move activity, using the API endpoints added in https://github.com/superseriousbusiness/gotosocial/pull/2518.
Along the way, it also does a bit more typescript conversion and tidying up, and adds a new input type for HookedForms: the Array input type. This is similar to the FieldArray input type, but presents just the values when parsed, not key/value pairings.
The documentation endpoints linked to in the new settings panel section are not yet …
=> [feature] Move + alias account via settings panel

internal/ap/resolve.go, internal/api/activitypub/users/inboxpost_test.go, internal/federation/federatingactor.go, internal/federation/federatingdb/reject.go, internal/federation/federatingdb/undo.go
We do this by dropping transient activities (those with missing ID property) instead of returning 400 bad request, since they are *technically* valid activitypub data.
Also some other misc fixes / cleanup i noticed while in the code
=> [chore] chore rationalise http return codes for activitypub handlers

docs/faq.md
Add a few things to the FAQ that are answers that were recently given to me or others or popped up in some past release notes to make them found more easily.
At this point, though, I wonder if we shouldn’t put the individual questions into `h3`s and whip up a couple of question categories (UI/UX, operational/warnings, federation, general(like the alpha question), …).
=> [docs] Add a few things to the FAQ.

docs/federation/federating_with_gotosocial.md, internal/federation/federatingactor.go, internal/federation/federatingactor_test.go
>
Update our inbox POST content negotiation to accept `charset=utf8` directive on application/activity+json content type requests.
This isn't really necessary according to the protocol but that's life!
This should allow Bookwyrm POST requests to our inboxes to succeed. See https://github.com/bookwyrm-social/bookwyrm/pull/2812#issuecomment-1865107260
Also added some docs on how to POST successfully to a GoToSocial inbox - https://gotosocial--2564.org.readthedocs.build/en/2564/federation/federating_with_gotosocial/#inbox
Please put an x inside each checkbox to indicate that you've …
=> [feature] Allow "charset=utf8" in incoming AP POST requests

internal/ap/resolve.go, internal/ap/resolve_test.go, internal/gtserror/error.go
>
This PR fixes an issue where searching for a URL that doesn't return valid AP JSON would return an Internal Server Error to the caller. Instead, failures to parse AP JSON from a dereference now return WrongType instead, which is checked for in the search processor.
Relates to https://github.com/superseriousbusiness/gotosocial/issues/2491, since that was triggering the bug, as threads.net doesn't return valid AP in response to our requests.
This could also be triggered just by putting something like "https://example.org" in the search bar. 
Please put an x inside each checkbox to …
=> [bugfix] Don't return Internal Server Error when searching for URIs that don't return AP JSON

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, internal/api/fileserver.go, internal/api/fileserver/fileserver.go, web/source/settings/admin/emoji/local/overview.js
>
This pull request serves the `emojis` part of the fileserver under a separate router group, applying separate rate-limiting (2 x configured rate limit). This should help with cases where someone has uploaded a few hundred custom emojis, and ends up getting rate-limited when using the emoji picker (which loads all emoji images at once, basically).
Also adds a warning to the emoji upload page recommending admins limit emoji use to ~ 300-400 custom emojis.
closes https://github.com/superseriousbusiness/gotosocial/issues/2537
Please put an x inside each checkbox to indicate that …
=> [feature] Ratelimit + serve emoji images on separate router group

docs/advanced/tracing.md
The Advanced docs section on Tracing shows a wrong option relating to tracing transport security, the actual option is `tracing-insecure-transport` instead of `tracing-insecure`. 
https://github.com/superseriousbusiness/gotosocial/blob/138cbe4d602838d0b4d431cb934d533cf5516ea9/internal/config/config.go#L141
=> [docs] Correct wrong tracing transport option

README.md, docs/faq.md, web/template/index_apps.tmpl
Updates Feditext links to point to the app's GitHub repo.
Fixes #2567
=> Update Feditext URL

docs/user_guide/posts.md
Add a section on media attachments to the user docs, including image description and Exif data sections, and a warning about mp4 geolocation data (see https://github.com/superseriousbusiness/gotosocial/issues/2577).
=> [docs] Add media attachments section to user docs

internal/api/util/response.go
These are meant to be the bytes representing an empty object and array in JSON: `{}` and `[]`. They are actually the strings `"{}"` and `"[]"`. This causes clients expecting an object or array to not be able to parse the response.
=> Fix EmptyJSONObject/EmptyJSONArray

internal/federation/dereferencing/account.go, internal/federation/dereferencing/status.go, internal/federation/dereferencing/thread.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/create_test.go, internal/visibility/home_timeline.go
- simplifies DereferenceStatusAncestors() -- as part of this it should also perform more self-correction in the case of setting / unsetting parent status IDs
- handle status acceptibility check even on status forwards
- update API of get{Account,Status}ByURI() to return error even if an old database model was returned, to allow caller to handle the error themselves for logging / further actions etc
- updates home timeline visibility checks to also check for threads that should be explicitly NOT visible
=> [bugfix] parent status replied to status not dereferenced sometimes

internal/processing/status/get.go, internal/processing/status/get_test.go
Topologically sort replies, moving self-replies to top of list. The topo sort is decent at producing runs of reply chains in the output, although it's probably possible to improve on that.
Fixes #2479
=> Improve context descendant sorting

internal/processing/account/block.go, internal/processing/common/account.go.go
closes #2595 
see for example of how it's happening: https://go.dev/play/p/8SMLbhbJ2sy
=> [bugfix] stop paged endpoints returning null for empty items

docs/federation/federating_with_gotosocial.md, internal/ap/interfaces.go, internal/ap/normalize.go, internal/ap/properties.go, internal/ap/serialize.go, internal/db/bundb/account.go, internal/typeutils/astointernal.go, internal/typeutils/astointernal_test.go, internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go, testrig/testmodels.go
>
This pull request implements serdes for incoming and outgoing movedTo and alsoKnownAs properties via the activitypub API. By extension, this means movedTo and alsoKnownAs URIs will be set in the database for remote AP accounts, though we don't yet do anything with these properties aside from store them.
It also renames the `getIRIs` utility function to `extractIRIs` to reflect that it can extract IRIs from a slice that contains either/both IRIs and Types. It adds a specific `getIRIs` function back in to get IRIs from a slice that the caller knows must contain only IRIs and not …
=> [feature] serdes for moved/also_known_as

internal/federation/authenticate.go, internal/federation/federatingdb/accept.go, internal/federation/federatingdb/announce.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/reject.go, internal/federation/federatingdb/undo.go
>
Close some gaps where remote accounts could theoretically deliver Activities to GtS inboxes imitating other accounts (Follow, Announce, Like, Block).
=> [bugfix] Ensure activities sender always = activities actor

internal/federation/dereferencing/account.go, internal/federation/dereferencing/emoji.go, internal/federation/dereferencing/status.go, internal/federation/dereferencing/util.go, internal/util/sync.go
`Move` will also require the v. nice little `doOnce` function we had in the dereferencer, so this PR just puts it in the util package in advance of that (to keep the `Move` PR simpler).
=> [chore] Move `DoOnce` func wrapper to util

internal/federation/dereferencing/account.go, internal/federation/dereferencing/dereferencer.go, internal/federation/dereferencing/status.go, internal/gtsmodel/status.go, internal/processing/common/account.go, internal/processing/common/status.go, internal/processing/fedi/status.go, internal/processing/polls/poll.go, internal/processing/status/bookmark.go, internal/processing/status/boost.go, internal/processing/status/fave.go, internal/processing/status/get.go, internal/processing/status/mute.go, internal/processing/status/pin.go, internal/processing/workers/fromfediapi.go
>
This pull request implements super-duper force refresh of accounts and statuses, by allowing callers to the dereferencing functions to specify what they consider to be "fresh enough" for their purposes, instead of a simple bool. 
This will be required for `Move`, which necessitates that we have a very up to date version of the target and origin accounts of a Move. I don't wanna lower the account/status force deref cooldown of 5 mins globally, so passing in a custom duration to the refresh functions (but providing consts for callers to use) seemed like a good way of doing things. …
=> [chore] Allow (internal) callers to set their own freshness window for Accounts + Statuses

cmd/gotosocial/main.go
This pull request makes GtS's version string compatible with SemVer by concatenating the VCS metadata with the version using a plus sign (SemVer's build tag separator) instead of a space. It relies on `main.Version` being set to a SemVer-compatible version, which should be the case for release and most development builds.
Fixes #1953
=> Make GtS reported version SemVer-compatible

internal/cache/cache.go, internal/cache/db.go, internal/cache/invalidate.go, internal/db/bundb/account.go, internal/db/bundb/drivers.go
should temporarily help with #1887 until my account status IDs PR is ready (will be post v0.14.0 release)
whilst i was here also ended up changing:
- fixing our database driver wrapping to include stmts (previously they were forgotten, though i'm not sure we actually use any)
- outlining `retryOnBusy()` to have a slow and path set of functions, allowing the fast path (case of just 1 try) to be inlined
- fix return of wrapped tx types on error
=> [performance] temporarily cache account status counts to reduce no. account counts

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, internal/metrics/metrics.go, internal/metrics/no_metrics.go
This pull request adds Prometheus metrics for instance user count, statuses count and federating instances count via Otel instruments.
closes #2569
=> [feature] Add metrics for instance user count, statuses count and federating instances count

internal/transport/controller.go
[RFC 9110][1] includes a definition for the format of a user-agent header:
```
User-Agent = product *( RWS ( product / comment ) )
product         = token ["/" product-version]
product-version = token
comment        = "(" *( ctext / quoted-pair / comment ) ")"
ctext          = HTAB / SP / %x21-27 / %x2A-5B / %x5D-7E / obs-text
```
An example given in the RFC: `User-Agent: CERN-LineMode/2.15 libwww/2.17b3`
The idea is typically start with the most important `product/version`, add a `(comment)` if necessary and then include any auxiliary products. However, the RFC warns against including too many auxiliary products as those can be unnecessarily revealing.
For automated systems (i.e not a browser), the common and recommended format is `<product></version> (+uri-for-contact)`, followed with …
=> [chore] Simplify the User-Agent string

internal/federation/federatingdb/accept.go, internal/federation/federatingdb/announce.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/delete.go, internal/federation/federatingdb/reject.go, internal/federation/federatingdb/undo.go, internal/federation/federatingdb/update.go, internal/federation/federatingdb/util.go
A little chore PR that comes out of the Move stuff I've been doing. PRing it separately here to avoid the Move PR becoming too big.
Just refactors extractFromCtx -> getActivityContext and simplifies the return type. No actual logic changes, but there might be in the Move PR.
=> [chore] refactor extractFromCtx a bit

internal/api/client/accounts/accountmove.go, internal/api/client/accounts/accounts.go, web/source/settings/user/migration.tsx
>
This pull request adds a warning to the migration user settings page that Move isn't actually implemented yet, and also comments out mounting the Move API endpoint. It still lets people set aliases on their accounts if they want though, since it might be useful to test that.
Since we decided to put Move back to 0.15.0 instead of 0.14.0, this will make the 0.14.0 release a bit easier to manage, and a bit less confusing for users. …
=> [chore] Disable Move API endpoints for now until Move is fully implemented in the backend

docs/faq.md, internal/federation/dereferencing/status.go, internal/federation/dereferencing/thread.go, internal/visibility/home_timeline.go, internal/visibility/public_timeline.go
>
Likely fix for https://github.com/superseriousbusiness/gotosocial/issues/2460.
Looks like on new status creates, we were passing the "barebones" status into the dereferenceThread function, which did not include the correct inReplyToURI values. This should fix it by passing in the properly dereferenced and populated status instead.
As a result of this fix, more followers-only posts were showing up in the timeline, even when the post they reply to is not visible. This PR fixes that too, by not assuming that 404 always means deleted when trying to deref a status. Many …
=> [bugfix] Fix dereferencing ancestors on new status create

internal/gtscontext/context.go, internal/transport/signing.go, internal/transport/transport.go
On outgoing `GET` requests that are signed (e.g. authorized fetch), if the initial request fails with `401`, try again, but _without_ the query parameters included in the HTTP signature.
This is primarily useful for compatibility with Mastodon; though hopefully this can be removed in the not-too-distant future, as they've started changing their behavior here.
See #894.
=> feat: add Mastodon-compatible HTTP signature fallback

internal/api/model/instancev1.go, internal/typeutils/internaltofrontend.go, web/template/page_header.tmpl
>
`with` in templates will skip if the `with` being `with`'d is a zero value. But we want zero values when rendering instance stats! So we can get around this by using a pointer instead :)
closes https://github.com/superseriousbusiness/gotosocial/issues/2588
=> [bugfix] Use ptr for instance stats entries to avoid skipping 0 values

web/source/css/base.css
Just a lil PR to remove the use of italics in block quotes. Italics make longer block quotes arduous to read, and also prevent italics inside the quote itself from appearing correctly.
Before:
With this PR:
=> [chore/frontend] Don't use italics for block quotes

docs/api/swagger.yaml, internal/api/client/followrequests/authorize_test.go, internal/api/client/followrequests/reject_test.go, internal/api/model/relationship.go, internal/db/bundb/relationship.go, internal/db/bundb/relationship_test.go, internal/gtsmodel/account.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
>
This pull request adds the `requested_by` field to relationships, showing if the target account has requested to follow you.
See: https://docs.joinmastodon.org/entities/Relationship/
closes https://github.com/superseriousbusiness/gotosocial/issues/2487
closes https://github.com/superseriousbusiness/gotosocial/issues/871
=> [feature] Add `requested_by` to relationship model

internal/api/client/streaming/stream.go, internal/processing/stream/delete.go, internal/processing/stream/notification.go, internal/processing/stream/notification_test.go, internal/processing/stream/open.go, internal/processing/stream/statusupdate.go, internal/processing/stream/statusupdate_test.go, internal/processing/stream/stream.go, internal/processing/stream/update.go, internal/processing/workers/fromclientapi_test.go, internal/processing/workers/fromfediapi_test.go, internal/processing/workers/surfacenotify.go, internal/processing/workers/surfacetimeline.go, internal/stream/stream.go
This fixes an issue I have noticed a few times on my own instance. It rewrites Stream{} to use much less mutex locking, and updates related code calling it.
=> [bugfix] fix possible mutex lockup during streaming code

web/source/css/index.css, web/source/css/page.css, web/source/settings/admin/settings/index.tsx, web/source/settings/style.css, web/template/page_header.tmpl
>
This pull request removes the HTML that forces images into a 100px x 100px box, and just uses css to resize the image instead.
I did the html trick in the first place to try to avoid flashes of unstyled content with massive images used as the instance avatar, but it just causes more headaches than it fixes. Rolled this back now to use a rem value that works for a variety of image dimensions. In future if we update the API we can set height/width using dimensions extracted from the avatar media attachment, but for now this is fine.
Also added a note to the settings panel that 1:1 …
=> [bugfix] Fix wide images being squished when used as instance avatar

internal/web/settings-panel.go, web/template/settings.tmpl
Tidies up a bit of cruft that I didn't catch in the previous big HTML template refactor. Now the template for the settings panel is actually called settings!
=> [chore] Rename frontend.tmpl to settings.tmpl, remove unused "lightgray" class

web/template/about.tmpl, web/template/index.tmpl, web/template/index_what_is_this.tmpl
>
This pull request adds a little "what is this" section to the index web page, with a very brief explanation of what the reader is actually looking at.
This should make it a bit less mysterious to people who open a GtS instance address to understand what it actually is.
Oh, and it also fixes a bug where the about page would say something like: "This instance has set the following rules: this instance has not set any rules" :') …
=> [feature] Add "what is this" section to index template

docs/configuration/media.md, docs/configuration/statuses.md, example/config.yaml, internal/api/client/statuses/statuscreate.go, internal/config/config.go, internal/config/defaults.go, internal/config/flags.go, internal/config/helpers.gen.go, test/envparsing.sh, testrig/config.go
>
This pull request removes some of the friction of using Mastodon clients on GtS by bringing some of our character counts more in line with Mastodon:
- Increase default image description char count from 500 => 1500 (the Mastodon default). There's no real reason we had such a limited default in the first place.
- Remove the statuses-cw-max-chars config option, and just add cw and body text together when checking that a status is within character limits. This is also closer to the Mastodon behavior, and so should cause fewer issues in clients (like Tusky, for example) which provide …
=> [chore] Increase default max image description to 1500 chars, collapse cw char count into status

docs/api/authentication.md, mkdocs.yml
>
This pull request adds the api authentication workflow to the documents and addresses #1135.
Closes: #1135
=> [docs] Add oauth token authentication workflow

example/apparmor/gotosocial, example/config.yaml
The current example configuration does not allow access to TMP directories, which is needed to process media attachments downloaded from other instances.
Additionally I modified some of the rules in the "not currently used" section to match the rules of the default paths and included some new rules suggested by `aa-logprof`
=> [bugfix] Allow access to TMP directories in example AppArmor config

docs/api/swagger.md, docs/faq.md, mkdocs.yml, web/source/settings/user/migration.tsx
Some small little docs updates:
- Make the "not implemented yet" warning on the migration panel more explicit.
- Remove the FAQ entry for the "not passed" warning since it's not relevant anymore.
- Update the API docs description, add warnings about filename (https://github.com/superseriousbusiness/gotosocial/issues/2641) and tip for authentication.
=> [chore/docs] Various little docs updates

docs/configuration/oidc.md, example/config.yaml, internal/api/auth/callback.go, internal/api/auth/callback_test.go, internal/config/config.go, internal/config/helpers.gen.go, test/envparsing.sh, testrig/config.go
This pull request implements checking roles for all OpenID users logging in against a list of allowed roles. If the list of roles is empty, then the check is skipped. Only one role has to match to pass.
Closes https://github.com/superseriousbusiness/gotosocial/issues/1915
Future: revalidate "admin" claim on login (the role may have changed); if user is part of admin group, bypass check.
=> [feature/oidc] Add support for very basic RBAC

internal/db/bundb/account.go, internal/db/bundb/account_test.go, internal/db/bundb/migrations/20240220204526_add_statuses_mentions_is_null_or_empty_idx.go, internal/db/bundb/util.go
This pull request excludes self-replies that mention other accounts when fetching an account's timeline with replies excluded. Normally, self-replies should be included, but it's possible to reply to one of your own replies to somebody else, and thus create a reply that mentions someone else but is included anyway, which looks weird. (I thought this was a Feditext client bug when I first noticed it.)
It doesn't specially handle the case where an account explicitly mentions themselves. (Most clients only include mentions for *other* accounts when replying to an account's own post.) Such posts will now be excluded from an account's timeline when replies are excluded. I could see a case for doing that either way (we could check that `mentions` contains a single entry that is the timeline …
=> [bugfix] Account timeline: exclude self-replies that mention other accounts

internal/db/bundb/migrations/20240220204526_add_statuses_mentions_is_null_or_empty_idx.go
Just add a little line about the potentially lengthy statuses index migration. Don't want people pressing ctrl-c thinking their instance has stopped doing anything.
=> [chore] add log line about lengthy reindex migration

internal/db/bundb/migrations/20240228113608_readd_statuses_account_id_id_idx.go
Re-add missing index. Removing it was causing heavy performance issues on SQLite (my bad) so let's add it back in and come back to it later.
The index is used for selecting "created_at" to get the last time an account posted. Eg:
```
SELECT \"status\".\"created_at\" FROM \"statuses\" AS \"status\" WHERE (\"status\".\"account_id\" = '01GRW75FF6W2CX5YE8054MT3FR') ORDER BY \"status\".\"id\" DESC LIMIT 1
```
=> [chore] re-add `statuses_account_id_id_idx` if removed

internal/log/syslog_test.go, internal/log/sysloglongunixgram_test.go
This pull request disables the test for long syslog messages over Unix datagram sockets on macOS, where it's known to hang the test runner. I suspect this is an implementation limit for macOS sockets. Given #493, which seems to cap the message size, I'm not sure this is an issue anything's going to hit in production. Also, we don't support macOS for production deployments anyway.
=> [bugfix] Disable the test for long syslog messages over Unix datagram sockets on macOS

internal/api/client/statuses/statuscreate_test.go, internal/processing/status/create.go
closes https://github.com/superseriousbusiness/gotosocial/issues/2701
=> [bugfix] unwrap boosts when checking in-reply-to status

docs/configuration/media.md, example/config.yaml, testrig/config.go
This switches the documentation to use human sizes, so 50MiB instead of an integer number of bytes. This makes it much easier to understand what values are set, and less likely to accidentally set the wrong value.
=> [docs] Use human sizes for size limitations

internal/tracing/tracing.go
The OpenTelemetry SDK is very strict about the schema version when the `Resource` is initialized.
Specifically, different schema versions _CANNOT_ be mixed, and since the default SDK resource (which is merged with the user-defined one) defines a schema URL, the `semconv` imports are really prone to being out-of-sync.
The best way to avoid this is to merge a _schemaless_ resource. This is fine...there's plenty of other ways to get `semconv` out of sync, and the core service attributes (e.g. `service.name`) should not ever change.
Additionally, any errors here are now propagated so that they'll be visible instead of silently swallowed.
=> [bugfix/tracing] fix broken tracing due to conflicting schema url

internal/ap/interfaces.go, internal/ap/normalize.go, internal/ap/normalize_test.go
>
Normalize/sanitize incoming PropertyValue fields on profiles. This wasn't an immediate vulnerability or anything like that, since we never display those fields from remotes on our web pages (and we have our own xss stuff in our content-security-policy headers), but you never know if it might cause some issue in a client that doesn't do its own sanitization.
=> [bugfix] Sanitize incoming PropertyValue fields

docs/api/swagger.yaml, internal/api/model/filterv1.go
Followup to #2698. Found while updating generated code in https://github.com/VyrCossont/slurp:
```
2024/03/06 09:24:23 validating spec https://raw.githubusercontent.com/superseriousbusiness/gotosocial/main/docs/api/swagger.yaml
2024/03/06 09:24:27 preprocessing spec with option:  minimal flattening
2024/03/06 09:24:27 building a plan for generation
2024/03/06 09:24:27 generation target ./
2024/03/06 09:24:27 planning definitions (found: 67)
2024/03/06 09:24:27 warning: validation minLength (value: 1) not compatible with type [array]. Skipped
2024/03/06 09:24:27 planning operations (found: 126)
2024/03/06 09:24:31 grouping operations into packages (packages: 27)
2024/03/06 09:24:31 operations for package packages "favourites" (found: 1)
2024/03/06 09:24:31 operations for package packages …
```
=> [chore] Fix a Swagger warning that only manifests during Go client code generation

docs/api/swagger.yaml, internal/api/client/filters/v1/filterpost.go, internal/api/client/filters/v1/filterput.go, internal/api/client/filters/v1/filtersget.go
This updates the Swagger spec to fix an incorrect type (getting filters returns an array of filters, not a single filter), and changes the way that filter contexts are serialized when creating or updating a filter (they should be passed as multiple parameters, but the default is apparently a single comma-separated parameter).
There are no code changes, just Swagger.
This is another followup patch to #2594 and #2698, and like #2729, I also found it while working on https://github.com/VyrCossont/slurp. Once this was patched and one bug in go-swagger itself go-swagger/go-swagger#2997 was worked around, `slurp` was able to import and export filters from both GtS and Mastodon instances, using a Swagger client generated from our own Swagger spec.
=> [docs/chore] Swagger fixes for filters

internal/db/bundb/errors.go
After our `modernc.org/sqlite` version bump v1.28.0 -> v1.29.2 (further narrowed to be changes in v1.29.0 -> v1.29.2) we started experiencing a regresion, in which canceling a context on an ongoing database query in the right way now causes an `Xsqlite_interrupt()` call to be made internally, which returns error code `SQLITE_INTERRUPT` on that connection's running query. Oddly, that then continually gets returned by all subsequent queries on that connection, leaving the instance in a broken state.
We still haven't narrowed this down to an SQLite library change revealing a bug on our end, or whether it's an SQLite library bug.
This is a quick workaround, which works as follows (text copied from matrix dev chat):
"okay i've found a workaround for now. so between v1.29.0 and v1.29.2 is that …
=> [bugfix] add workaround for Xsqlite_interrupt() permanently breaking connection

.goreleaser.yml
This pull request adds `{{ if .IsSnapshot }}` check to all snapshot tags and manifests in `.goreleaser.yml`.
With this change docker images with `snapshot` tag will not be produced unless `--snapshot` argument is explicitly set. So the `release` job in Drone CI will not overwrite `snapshot` tag.
closes #2737 
closes #2609 
=> [chore] seperate snapshot from release in goreleaser

internal/db/bundb/account.go, internal/db/bundb/account_test.go
>
We may not always have the MovedTo account stored in the database when an account's `MovedToURI` is set. It's nice if we do have it, since we can then convey that via the API too, but it's fine if we don't, and we don't need to error for it.
=> [bugfix] Don't error when populating MovedTo if account not found

internal/db/bundb/migrations/20240310120046_fix_empty_move_id.go, internal/gtsmodel/account.go
>
I introduced a bug where account `move_id` was being stored as a 26-character long whitespace string when using Postgres.
This PR fixes this by putting nullzero on the move_id field, and also adds a migration to correct the field for anyone who'd run on the latest Postgres snapshot while the issue was still present.
Reproduced the issue and tested the fix on local postgres-backed testrig.
If this is a documentation change, only the first checkbox must be filled (you can delete the …
=> [bugfix] Fix whitespace move_id issue

docs/api/swagger.yaml, internal/api/client/accounts/followers.go, internal/api/client/accounts/following.go, internal/api/client/accounts/statuses.go, internal/api/client/admin/reportsget.go, internal/api/client/reports/reportsget.go
Adds description of the `Link` header to Swagger docs for 5 endpoints that use it but which didn't already have that header in the response description. Also fixes a typo preventing correct docs generation for 1 of those endpoints.
Allows use of `Link` paging with Swagger clients. No code changes.
=> Swagger: add Link header to all endpoints that use it for paging

docs/api/swagger.yaml, internal/api/client/accounts/accountmove.go, internal/api/client/accounts/accounts.go, internal/processing/account/move.go, web/source/settings/user/migration.tsx
>
- Reattach move client API handler
- Update settings panel a little
- Return nicer error when trying to move to a different account than the one you've already moved to
=> [chore] Expose move endpoint again, small settings panel fixes

internal/processing/search/get.go
>
When searching for an unpermitted status, GtS will return 500 if the status is not permitted. This fixes that by including the error in the "semi-expected" error types when searching.
=> [bugfix] Don't return 500 when searching for unpermitted status

docs/admin/database_maintenance.md, internal/db/bundb/bundb.go, mkdocs.yml
>
~~The full ANAYLZE command we run for SQLite after each DB migration is not really necessary, and takes bloody ages (minutes and minutes on my 1cpu 1gb ram machine). This PR updates the post-migration ANALYZE command to use an analysis limit of 10000, which should be plenty (for comparison, we use 1000 for on-close callbacks).~~
Correction to the above: I've been messing about with running partial and full analyzes, and it turns out that running `PRAGMA anaylsis_limit=10000; ANALYZE;` actually doesn't cut it for the purposes of helping the query optimizer use the correct …
=> [docs] Add database maintenance section; update info message on ANALYZE run (sqlite)

docs/api/swagger.yaml, internal/api/client/accounts/relationships.go, internal/api/client/lists/listaccountsadd.go, internal/api/client/lists/listaccountsremove.go
These parameters should have names ending in `[]` and use `collectionFormat: multi` (pass multiple elements by repeating the param in the form data).
No code changes.
=> Swagger: correct names and formats for several array params

internal/validate/formvalidation_test.go
go 1.21.8 fixed some minor issues in net/mail that causes the test suite to fail for some mail validation cases. Although we're not on go 1.21.8 yet, make the test forward and backwards compatible.
See: https://github.com/golang/go/commit/263c059b09fdd40d9dd945f2ecb20c89ea28efe5
Running the test suite with go 1.21.8 leads to test failures like:
```
-- FAIL: TestValidationTestSuite (0.00s)
--- FAIL: TestValidationTestSuite/TestValidateEmail (0.00s)
formvalidation_test.go:147:
Error Trace:    /home/blake/src/gotosocial/internal/validate/formvalidation_test.go:147
Error:          Not equal:
expected: &errors.errorString{s:"mail: no angle-addr"}
actual  : &errors.errorString{s:"mail: missing word in phrase: mail: invalid string"}
Diff:
--- Expected
+++ Actual
@@ -1,3 +1,3 @@ …
```
=> [chore] Different error message for email validation from net/mail parsing on go 1.21.8 and above

internal/text/markdown.go, internal/text/plain.go, internal/text/plain_test.go
>
Update the goldmark link parser to use the regex we already had lying around :)
Closes https://github.com/superseriousbusiness/gotosocial/issues/2755
=> [bugfix] Parse links that contain non-ascii characters

internal/api/client/timelines/public.go, internal/processing/timeline/public.go, internal/processing/timeline/public_test.go, internal/processing/timeline/timeline_test.go
>
This pull request updates our public timeline querying to try to avoid the situation where all items from a db query get filtered out, which causes issues like https://github.com/superseriousbusiness/gotosocial/issues/2410 and https://github.com/superseriousbusiness/gotosocial/issues/2273.
Now:
- Always select a bit more than `limit` from the db when doing public timeline queries.
- Reattempt select (paging up or down) to try to get appropriate statuses if previous query resulted in all selected statuses being filtered out (limit 3 queries total).
This won't *completely* fix the …
=> [bugfix] Mitigate empty public/local timeline query pages

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, docs/advanced/healthchecks.md, docs/api/swagger.yaml, internal/api/health.go, internal/api/health/health.go, internal/api/health/live.go, internal/api/health/ready.go, internal/db/basic.go, internal/db/bundb/basic.go, mkdocs.yml
>
This pull request adds some simple health check endpoints, and documentation for how to configure a health check.
Closes https://github.com/superseriousbusiness/gotosocial/issues/2707
=> [feature] Add healthcheck endpoints `/livez` and `/readyz`

internal/processing/fedi/collections.go
>
Fix an error in serving the following collection, where we were taking the account of the follow, not the target account.
closes https://github.com/superseriousbusiness/gotosocial/issues/2786
=> [bugfix] Serve correct URI for AP following collection

internal/ap/extract.go, internal/ap/extractpubkey_test.go, internal/federation/authenticate.go, internal/timeline/get_test.go, internal/typeutils/astointernal.go
>
This pull request is the first part of a fix for https://github.com/superseriousbusiness/gotosocial/issues/1186.
At this point, it *just* adds some logic to try to parse bytes received from a dereference to a public key endpoint as both an Actor, and as a bare Public Key. There are no real logic changes aside from that.
As far as I know, nobody actually serves just the key at the main-key endpoint yet, but it's not a bad idea to get this merged early in the GtS codebase for forwards compatibility reasons. Ie., if we include this change in 0.15.0, and then in 0.16.0 or later …
=> [chore] Try to parse public key as both Actor + bare key

internal/db/bundb/migrations/20240402113305_nil_domain_fix.go
>
Adds a migration to update the domain of friendica service accounts that were inadvertently stored with a nil domain. 
closes https://github.com/superseriousbusiness/gotosocial/issues/2515
closes https://github.com/superseriousbusiness/gotosocial/issues/2474
=> [bugfix] Set domain for empty-domain Friendica accounts

internal/api/activitypub/users/inboxpost_test.go, internal/federation/federatingactor.go, internal/federation/federatingprotocol.go, internal/federation/federatingprotocol_test.go
updates the failed auth error handling on the post inbox route to better handle returned errors, previously we were masking a lot with just "not authenticated" which wasn't the most useful in the logs :D
=> [bugfix] improved authenticate post inbox error handling

internal/db/bundb/relationship.go, internal/federation/federatingdb/following_test.go
The id on the follows table is not a ULID, but a random ID. Sorting on them results in a completely random order. Instead, sort on created_at, which sould result in a stable and intended sort order.
Fixes: #2769
=> [bugfix] Sort follows chronologically

go.mod, go.sum, vendor/modernc.org/sqlite/AUTHORS, vendor/modernc.org/sqlite/CONTRIBUTORS, vendor/modernc.org/sqlite/Makefile, vendor/modernc.org/sqlite/README.md, vendor/modernc.org/sqlite/builder.json, vendor/modernc.org/sqlite/sqlite.go, vendor/modules.txt
See for changes: https://gitlab.com/NyaaaWhatsUpDoc/sqlite/-/commit/29a5812b7c37800d643eff7fc9686e61ad3112c8
This is a temporary fix for #2808 and #2774. This works by cutting out the possible concurrent access of a singullar sqlite3 db pointer with the "interruptOnDone()" goroutine. The downside now is that context handling will now **not** be immediate, it will instead have to check at the next sqlite3 step() for a canceled context. In practice though this shouldn't cause (us at least) any issues.
You can confirm this by triggering #2774 on a testrig instance (same methodology as with #2728) then attempting to shutdown the instance. It will hang on "database locked". Switching to this branch the issue will no longer be there. Switching to this branch you'll also notice that your …
=> [bugfix/workaround]replace modernc.org/sqlite-v1.29.5 with gitlab.com/NyaaaWhatsUpDoc/sqlite-v1.29.5-concurrency-workaround

internal/processing/account/follow.go, internal/processing/account/follow_test.go
>
We weren't passing local -> local follow (requests) back to the workers for side effect processing, which led to notifs not being created for local -> local follows. Fixes that!
Closes https://github.com/superseriousbusiness/gotosocial/issues/2813
=> [bugfix] Ensure side effects for local -> local follows get processed

docs/configuration/database.md, docs/getting_started/index.md
Just tidies up the deployment docs a bit, and adds a warning about oracle free tier volumes.
Preview: https://gotosocial--2821.org.readthedocs.build/en/2821/getting_started/
=> [docs] update deployment considerations docs with latest findings

internal/email/common.go, internal/email/email_test.go
>
This pull request adds MIME headers to our outgoing emails appropriate to the content-type and encoding that we use. This should prevent issues where non-ascii characters get mangled by some email providers, in cases where the email provider doesn't massage the email headers + contents to be readable (which is not something we should rely on).
=> [bugfix] Include MIME email headers to avoid mangling non-ascii text

docs/configuration/accounts.md, example/config.yaml, internal/config/defaults.go
>
I actually thought we already had this `false` by default but it was `true`, so this PR just fixes that!
=> [chore] Turn `accounts-registration-open` false by default

internal/api/client/statuses/statusboost_test.go, internal/typeutils/internaltofrontend.go, internal/typeutils/util.go
>
Following the Mastodon API we should be taking interaction counts from the boosted status, rather than generating them separately on the boost wrapper status, when serializing via the API.
This PR fixes that by serializing the wrapped reblogged status first, then just taking the interactions from that.
This also means fewer DB calls in total when serializing a boosted status, which is a nice bonus :)
MIGHT be a fix for https://github.com/superseriousbusiness/gotosocial/issues/2844 but i'm not sure.
Please put an x inside each checkbox to indicate that you've read and followed …
=> [bugfix] Fix minor API issue w/ boosted statuses

docs/api/swagger.yaml, internal/api/client/statuses/status.go, internal/api/client/statuses/statushistory.go, internal/api/client/statuses/statushistory_test.go, internal/api/model/status.go, internal/processing/status/get.go
>
This pull request implements a stub for the `/api/v1/statuses/{id}/history` endpoint, which just returns a single-length array of status edits with the current/latest revision. See https://docs.joinmastodon.org/entities/StatusEdit/ and https://docs.joinmastodon.org/methods/statuses/#history.
In future when we implement storing revisions/edit history we can flesh this endpoint out.
Should close https://github.com/superseriousbusiness/gotosocial/issues/1681
If this is a documentation …
=> [feature] Stub status history endpoint

internal/federation/federatingdb/delete.go
ensures that requestingAccount is always set, otherwise the new status count decrementer panics
=> [bugfix] nil panic when deleting status

docs/api/swagger.yaml, internal/api/client.go, internal/api/client/mutes/mutes.go, internal/api/client/mutes/mutesget.go
>
This pull request just stubs out the mutes endpoint to always return an empty array. Not being able to fetch mutes was causing issues for some clients, and we'll eventually implement it anyway so stubbing it now makes sense.
Should help with https://github.com/superseriousbusiness/gotosocial/issues/2845
=> [feature] Stub account mutes endpoint

docs/api/swagger.yaml, internal/api/client.go, internal/api/client/conversations/conversations.go, internal/api/client/conversations/conversationsget.go
>
This pull request stubs the /api/v1/conversations endpoint to always return an empty array (until we implement it properly).
=> [feature] Stub conversations endpoint

.drone.yml, Dockerfile, go.mod, internal/oauth/util.go
With Go 1.22 having been released at the start of February, it's now been a few months. No major issues have shown up, and the two point release since then have primarily been security fixes plus some general bug fixing.
This sets the required Go version to 1.22, as there's nothing in 1.22.1 or 1.22.2 that we would explicitly require. It sets the toolchain to the latest point release, to ensure we pick up any fixes from there when building releases etc.
=> [chore] Upgrade our Go version to 1.22

testrig/config.go
cmp.Or was introduced in Go 1.22 and picks the first value that's not the zero value for the type. For a string, the zero value is the empty string, which is what os.Getenv will return if the environment variable is not set. That then results in "error" being returned instead.
This allows loading an environment variable with a default without having to do the check and write out the conditional.
=> [chore] Update setting testrig loglevel

Dockerfile
=> [chore] update Docker container to use new go swagger hash

internal/processing/workers/fromclientapi_test.go, internal/processing/workers/fromfediapi_test.go, internal/processing/workers/workers_test.go
Update workers tests to ensure that each test gets its own fresh processor, so that they avoid using each others workers queues.
=> [chore] Fix conflict in workers tests

internal/api/activitypub/users/repliesget_test.go, internal/paging/boundary.go, internal/paging/page.go
Fix paging relative links so they use the correct cursoring parameter. Also updates the ASCII paging doc to explain this cursoring and make it clear.
=> [bugfix] paging rel links

README.md, docs/configuration/database.md
This updates the documentation to remove the last stray references to the copaganda Pi. It now uses the the term single-board computer. GtS can run fine on all kinds of SBCs and isn't limited to that one particular fruit version.
=> [docs] Remove last references to RPi

cmd/gotosocial/action/admin/account/account.go, cmd/gotosocial/action/admin/media/list.go, cmd/gotosocial/action/admin/media/prune/common.go
>
Along with https://github.com/superseriousbusiness/gotosocial/pull/2865, this should close https://github.com/superseriousbusiness/gotosocial/issues/2843 by removing remaining references to unused workers in CLI setup/teardown.
=> [bugfix/chore] Tidy up remaining references to workers in cmd

internal/processing/account/move.go, internal/processing/admin/accountapprove.go, internal/processing/admin/accountreject.go, internal/processing/status/pin.go, internal/processing/workers/fromclientapi.go, internal/processing/workers/fromfediapi.go, internal/processing/workers/surface.go, internal/processing/workers/surfaceemail.go, internal/processing/workers/surfacenotify.go, internal/processing/workers/surfacenotify_test.go, internal/processing/workers/surfacetimeline.go, internal/processing/workers/util.go, internal/processing/workers/workers.go, internal/processing/workers/workers_test.go, internal/state/state.go
>
This pull request adds some locks in the surfaceNotify functionality to ensure that multiple notifications aren't created for the same status. Previously it was possible to create multiple notifs if the function was called in parallel (see added tests, which fail without the fix).
Should close https://github.com/superseriousbusiness/gotosocial/issues/2858
Note: to test this in isolation I had to expose a few things in the surface package, and I renamed the AccountLocks thing to ProcessingLocks too. The actual fix itself is very small.
Here's how it looks now when you spam …
=> [bugfix] Lock when checking/creating notifs to avoid race

web/source/settings/lib/query/admin/index.ts, web/source/settings/lib/types/account.ts
>
Cheeky little PR to do optimistic updates when taking account moderation actions, to provide more immediate feedback to the admin. Now instead of clicking and having to refresh a few times while the backend does its things and marks the account as suspended / approved / rejected or whatever, the change is reflected immediately in the frontend redux cache state.
See: https://redux-toolkit.js.org/rtk-query/usage/manual-cache-updates#optimistic-updates
If this is a documentation …
=> [frontend] Do optimistic update when approving/rejecting/suspending account

internal/cache/db.go, internal/cache/size.go
previously some of the caches were ignored from cache size calculations!
=> [bugfix] fix cache size calculations

internal/cache/db.go, internal/db/bundb/filterkeyword.go, internal/gtsmodel/filter.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
=> [performance] cache v2 filter keyword regular expressions

internal/processing/workers/surfaceemail.go
Just updates the link used when emailing reports, to the new path used after the settings panel refactoring.
=> [chore] Fix report email link

docs/admin/settings.md, docs/api/swagger.yaml, docs/configuration/smtp.md, internal/api/client/admin/emailtest.go, internal/api/model/admin.go, internal/email/test.go, internal/processing/admin/email.go, web/source/settings/lib/query/admin/actions/index.ts, web/source/settings/lib/query/admin/index.ts, web/source/settings/views/admin/actions/email/index.tsx, web/source/settings/views/admin/actions/email/test.tsx, web/source/settings/views/admin/actions/keys/expireremote.tsx, web/source/settings/views/admin/actions/keys/index.tsx, web/source/settings/views/admin/actions/media/cleanup.tsx, web/source/settings/views/admin/menu.tsx, web/source/settings/views/admin/router.tsx, web/template/email_test.tmpl
>
This pull request adds a section to the admins settings panel to send a test email to a provided address, with an optional message (could be useful for testing language encoding etc).
closes https://github.com/superseriousbusiness/gotosocial/issues/2376
=> [feature/frontend] Let admins send test email to validate SMTP config

.goreleaser.yml
This PR makes wasmsqlite3 available to goreleaser, invoked as follows:
`WASMSQLITE3=1 goreleaser --clean --snapshot`
=> [chore] make wasm sqlite3 available to goreleaser via env var

internal/cache/db.go
Small bugfix to ensure we're not caching MovedTo account pointer
=> [chore/bugfix] Don't cache MovedTo account

cmd/gotosocial/action/server/server.go, cmd/gotosocial/action/testrig/testrig.go, docs/api/swagger.yaml, internal/api/client.go, internal/api/client/admin/admin.go, internal/api/client/admin/admin_test.go, internal/api/client/admin/debug_off.go, internal/api/client/admin/debug_on.go
>
This pull request adds `/api/v1/admin/debug/caches/clear` endpoint to sweep all in-memory caches down to 0.
Only enabled/exposed when DEBUG=1.
=> [feature] Debug admin endpoint to clear caches

scripts/build.sh
=> [docs]: Document build tag for WASM SQLite

internal/transport/delivery/delivery.go, internal/workers/worker_fn.go, internal/workers/worker_msg.go
On startup and shutdown of a worker, we log a message of the worker being started together with a textual representation of a memory address. Though this can be handy for developers to debug startup/shutdown sequencing issues of the workers, it's typically not very useful or informative for an admin. We can also output a lot of these (on my system I get 265 lines of these during startup).
This changes the messages from Info to Debug, to not print them under normal circumstances.
=> [chore] Make worker run startup messages debug output

docs/api/swagger.yaml, docs/user_guide/search.md, internal/api/client/search/searchget.go, internal/api/client/search/searchget_test.go, internal/api/model/search.go, internal/api/util/parsequery.go, internal/db/bundb/search.go, internal/db/bundb/search_test.go, internal/db/search.go, internal/processing/search/get.go, mkdocs.yml
This pull request implements Mastodon-compatible functionality for restricting a search to statuses authored by a specific account:
- [`account_id` parameter to search API](https://docs.joinmastodon.org/methods/search/#query-parameters)
- `from:localuser` or `from:remoteuser@domain` as an additional (or only) term in search query text, useful for the majority of clients which don't support `account_id` (also implemented in Mastodon, documented only in online help)
There are two main use cases:
- Find your most recent conversations with somebody else
- Find your own posts
=> [feature] Add from: search operator and account_id query param

internal/transport/delivery/delivery.go, internal/workers/worker_msg.go, internal/workers/workers.go
Logs the number of each worker kind started during init. As pointed out by @daenney the way we were doing it previously was overly verbose and kinda useless, so moving to debug logging was definitely an improvement, but this removes the per-worker logging and instead just uses simple per-worker-pool-type n-workers-started style logging
=> [feature] log worker startup counts

internal/db/bundb/filter.go
User reported a bug in chat where their home timeline was crashing while filtering due to a nil `Regexp`:
```
gotosocial_1  | timestamp="01/06/2024 15:19:54.432" func=server.init.func1.Logger.14.1 level=INFO latency="25.915262ms"userAgent="***" method=GET statusCode=200 path=/api/v1/timelines/home clientIP=x.x.x.x errors="Error #01: recovered panic: runtime error: invalid memory addresss or nil pointer dereference
" requestID=4v3p5n4f04001700hav0 msg="OK: wrote 23B"
gotosocial_1  | timestamp="01/06/2024 15:19:54.432" func=server.init.func1.Logger.14.1 level=ERROR stacktrace="()
/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:881
regexp.(*Regexp).doExecute()
/usr/local/go/src/regexp/exec.go:527
()
/usr/local/go/src/regexp/exec.go:514 …
```
=> Compile filter keyword regexps when touched through PutFilter or UpdateFilter

internal/federation/dereferencing/account.go, internal/federation/dereferencing/dereferencer.go, internal/federation/dereferencing/emoji.go, internal/federation/dereferencing/status.go
- removes the avatar / header deref maps as we now have per-uri status / account locks, (besides we don't actually set any database uniqueness limits on remote url so storing processing media per remote url could actually cause some unexpected weirdness in some places)
- adds separate emoji map mutex
=> [bugfix] concurrent map writes in dereferencer media processing maps

docs/api/swagger.yaml, internal/api/model/account.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
>
Don't nil emojis + fields on blocked accounts, use empty array instead as these fields are nillable (https://docs.joinmastodon.org/entities/Account/#fields).
Fixes an issue where some clients would fail on showing a blocked account.
=> [bugfix] Don't nil emojis + fields on blocked accounts

docs/federation/federating_with_gotosocial.md, internal/transport/signing.go
>
Throughout [the spec](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-12), `(created)` is used instead of `date` for constructing signatures. This PR switches to using that, which is already supported by the library we use anyway.
Tested with Mastodon, Misskey, Akkoma, Kristec, and other GtS instances, and it seems to work fine with all of those.
closes https://github.com/superseriousbusiness/gotosocial/issues/2857 …
=> [chore] Use `(created)` instead of `date` for outgoing HTTP signatures

web/source/package.json, web/source/settings/views/admin/http-header-permissions/create.tsx, web/source/settings/views/admin/http-header-permissions/detail.tsx, web/source/yarn.lock
>
Use RE2 syntax on frontend for validation of header permissions regexes.
=> [bugfix/frontend] Use re2 syntax for regex validation

docs/federation/federating_with_gotosocial.md, internal/transport/signing.go
Roll back `(created)`, see: https://github.com/superseriousbusiness/gotosocial/issues/2991
=> [chore] Roll back use of `(created)` pseudo-header pending #2991

internal/db/account.go, internal/db/bundb/account.go, internal/federation/dereferencing/announce.go, internal/processing/account/move.go, internal/processing/account/move_test.go, internal/processing/common/status.go, internal/processing/status/boost.go, internal/typeutils/internaltofrontend.go
fixes a possible recursion issue with moved accounts referrring back to the original account. adds a protection for boost wrapping statuses to make we're never allowing processing of boostOf-boostOf's
- fix possible recursion issue setting Moved account in type converter
- fix possible recursion issue setting Reblogged status in type converter
- add protections for accepting boost wrapping statuses as boost targets
- add protections for move account recursion loops (closed move chains)
=> [bugfix] boost and account recursion

internal/ap/activitystreams_test.go, internal/ap/collections.go, internal/api/activitypub/users/outboxget.go, internal/api/activitypub/users/outboxget_test.go, internal/db/account.go, internal/db/bundb/account.go, internal/db/bundb/admin.go, internal/federation/dereferencing/account.go, internal/processing/fedi/collections.go, internal/processing/fedi/common.go, internal/processing/fedi/status.go, internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go, testrig/testmodels.go
>
This pull request solves a bug introduced in 0.16.0-rc1 where account stats were fetched during the initial dereference attempt, leading to a potential recursive handshake loop where two GtS instances would fail to dereference each other.
The fix is to:
1. Only fetch stats asynchronously, and during a first dereference just return local stats (ie., 0 followers, 0 following, 0 statuses).
2. Serve bare stub endpoints for an Actor's collections (without even totalItems) if dereference is done during handshaking, just to get things moving along. This part isn't strictly necessary to …
=> [bugfix] Deref stats async, serve stub collections if handshaking

internal/processing/workers/fromfediapi_test.go
In https://github.com/superseriousbusiness/gotosocial/pull/2998 the FollowCreate function was changed to not create the follow immediately but to create the follow asynchronously, which was causing a test to run into a race. This PR fixes that by ensuring that the test waits until side effects are complete.
=> [chore] Update move test

cmd/gotosocial/action/server/server.go
The memlimit package started to log any error returned by automemlimit. This updates our implementation to call SetGoMemLimitWithOpts() instead which uses the same defaults as automemlimit except for being initialised with a noop logger.
We check the returned error for a particular substring, as when cgroups isn't available even when running on a Linux system that's not a problem. If it's anything but that error, we log it at the warning level so that admins can still diagnose other cgroup related issues.
Fixes #2983
=> [chore] Silence memlimit package

README.md, ROADMAP.md, docs/environment.yml, docs/faq.md, docs/index.md, mkdocs.yml
This PR updates our docs to drop the silly duplication we had between `README.md` and `docs/index.md`. Instead, `README.md` is now just imported (selectively) into `docs/index.md` so we don't have to keep maintaining two versions of essentially the same document. To achieve this without breaking stuff, relative links in `README.md` were changed into absolute links.
Also updates and rearranges various bits and bobs in the readme, and updates the roadmap a bit as well.
=> [docs] Rework README a bit, import into docs

docs/api/swagger.yaml, internal/api/client/filters/v2/filterpost.go, internal/api/client/filters/v2/filterpost_test.go, internal/api/client/filters/v2/filterput.go, internal/api/client/filters/v2/filterput_test.go, internal/api/model/filterv2.go, internal/processing/filters/v2/create.go, internal/processing/filters/v2/update.go
These filter API v2 features were cut late in development because the form encoding version is hard to implement correctly and because I thought no clients actually used `keywords_attributes`. Unfortunately, Phanpy does use `keywords_attributes`. Fortunately, it uses the JSON version.
=> [feature] filter API v2: restore keywords_attributes and statuses_attributes

docs/api/swagger.yaml, internal/api/client/notifications/notifications.go, internal/api/client/notifications/notifications_test.go, internal/api/client/notifications/notificationsget.go, internal/api/client/notifications/notificationsget_test.go, internal/db/bundb/notification.go, internal/db/bundb/notification_test.go, internal/db/notification.go, internal/processing/timeline/notification.go, internal/processing/workers/surfacenotify_test.go
Counterpart of `exclude_types[]`.
Also updates Swagger spec for `exclude_types[]` to use the correct param name and enumerate possible values.
Fixes #3003
=> [feature] Implement types[] param for notifications

internal/api/client/notifications/notifications.go, internal/api/client/notifications/notificationsget.go, internal/api/client/notifications/notificationsget_test.go, internal/db/bundb/notification.go, internal/db/notification.go, internal/processing/timeline/notification.go
>
We accidentally named the `types[]` parameter incorrectly in https://github.com/superseriousbusiness/gotosocial/pull/3009, this just fixes that by renaming `include_types[]` to `types[]`.
=> [bugfix] rename `include_types[]` to `types[]`

go.mod, go.sum, vendor/codeberg.org/gruf/go-mangler/README.md, vendor/codeberg.org/gruf/go-mangler/helpers.go, vendor/codeberg.org/gruf/go-mangler/load.go, vendor/codeberg.org/gruf/go-mangler/mangle.go, vendor/codeberg.org/gruf/go-mangler/manglers.go, vendor/codeberg.org/gruf/go-structr/cache.go, vendor/codeberg.org/gruf/go-structr/index.go, vendor/codeberg.org/gruf/go-structr/map.go, vendor/codeberg.org/gruf/go-structr/queue.go, vendor/codeberg.org/gruf/go-structr/queue_ctx.go, vendor/codeberg.org/gruf/go-structr/runtime.go, vendor/codeberg.org/gruf/go-structr/util.go, vendor/modules.txt
Updates [go-structr](https://codeberg.org/gruf/go-structr) and [go-mangler](https://codeberg.org/gruf/go-mangler) to no longer rely on [modern-go/reflect2](https://github.com/modern-go/reflect2), which come release of Go 1.23 with changes to how linkname works (now requires both sides of a linkage to confirm it), means we will no longer be reliant on weird build tags to revert to old linkname behaviour.
=> [chore] update go-structr and go-mangler to no longer rely on modern-go/reflect2

internal/email/common.go, internal/email/email_test.go, internal/email/noopsender.go, internal/email/sender.go
This should make spam filters more happy, as most of them grant some negative score for not having those headers. Also the Date is convenient for the user receiving the mail.
=> [bugfix] add Date and Message-ID headers for email

docs/advanced/host-account-domain.md
This pull request fixes the Traefik redirect regex issue in the [split domain documentation](https://docs.gotosocial.org/en/latest/advanced/host-account-domain/). The current regex won't keep the query string, e.g. `?resource=acct:example@example.org`, which would cause federation issues with other instances.
I've met the federation issues on my own instance. After checking Traefik logs (e.g. `GET /.well-known/webfinger?resource=acct:example@example.org 502`), I found out it's due to the redirection. And changed the regex which fixed the problem for me. Maybe some further checking of the regex would be better (I am really bad at regex :( …
=> [docs] traefik redirect regex documentation

test/envparsing.sh
We didn't have an envparsing.sh case for `advanced-header-filter-mode` aka `GTS_ADVANCED_HEADER_FILTER_MODE` so this PR just adds that in.
=> [chore] Add envparsing test for advanced-header-filter-mode

internal/cache/db.go
Fix a little typo in the instance cache copy function, which would cause already-populated instances to be returned.
=> [bugfix] Fix typo in instance cache copyF

web/source/settings/views/admin/emoji/local/detail.tsx
Found by @Sentynel, fixes the TODO on the emoji details form to actually use the instance's configured max size for emoji, like what was already implemented for new emoji uploads.
=> [fix] use instance configured emoji maxsize on emoji update validation

docs/getting_started/reverse_proxy/nginx.md
Since 1.25.1 the newer 'http2 on;' syntax should be used. The previous syntax still works, but throws warnings when testing the configuration with 'nginx -t'.
This also updates the certbot template to match what's currently generated. It removes ipv6only=on as that's the default on a listen directive binding on a wildcard IPv6 address.
=> [docs] Update how to enable http2 on nginx

internal/middleware/contentsecuritypolicy.go, internal/middleware/extraheaders.go
This sets a few basic security related headers, aside from the CSP which we already have.
I'm slowly going through https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html and figuring out what applies.
Each commit is a separate header + the why of it.
=> [feature] Set some security related headers

internal/processing/timeline/home_test.go, internal/processing/timeline/timeline_test.go, internal/timeline/get.go
The included tests weren't successful as regression tests for this bug, but describe behavior that works now and should continue to work in the future, so I'm leaving them in.
Reported by @tsmethurst. The symptom is the log message `db error while trying to prepare`, which occurs in three places, one of which already handles `ErrHideStatus`, and the other two of which I've added handling for in this patch.
=> [bugfix] Handle ErrHideStatus when preparing timeline statuses

internal/db/bundb/status.go
>
This pull request allows retrieving posts that reply to a parent status that isn't in the database, by ending the traversal below the missing parent. A missing parent post can happen for a few reasons: the calling user being blocked, a deleted post, or federation/remote server issues come to mind.
closes #2011
=> [bugfix] Don't throw error when parent statuses are missing (#2011)

internal/db/bundb/migrations/20240620074530_interaction_policy.go
This PR just adds some logging to the very long interaction policy migration, so that users know stuff is happening and they oughtn't be jumping the gun and pressing ctrl-c on it.
Looks like this:
=> [chore] add step-by-step logging to long migration

internal/processing/common/account.go, internal/processing/common/status.go
fixes media 404s sometimes, as currently the async refresh causes the original media files to get invalidated while the client is still requesting them
=> [bugfix] update common get target account / status doing refresh async

internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
Explicitly propagate `.Filtered` from an original status to its boosts in the type converter, the same way we explicitly propagate `ErrHideStatus`.
This changes one line of actual code. The tests either ensure that existing filter-matching behavior continues (see #3128) or that `.Filtered` is copied.
=> [bugfix] Explicitly propagate filter results from statuses to their boosts in API responses

internal/db/bundb/migrations/20240613091853_drop_unused_media_columns.go, internal/db/bundb/migrations/20240715204203_media_pipeline_improvements.go, internal/db/bundb/migrations/20240722222556_remove_boost_content.go, internal/typeutils/internaltofrontend_test.go
Just a chore PR to add some logging to some of the lengthy recent migrations, so admins know that stuff is actually happening and won't be tempted to press ctrl-c.
=> [chore] Add some log lines to recent migrations warning not to interrupt

internal/typeutils/internaltofrontend.go
This pull request fixes a type error when serializing a conversation's account list. This is only about the millionth time I've run into this problem; golang/go#63397 when?
Followup to #3013
Only affects DMs to yourself *and* clients that are strict about types. Semaphore and Phanpy apparently don't care.
=> Serialize empty conversation account list as empty list, not null

internal/transport/delivery/worker.go
Just brings worker start logging in line with how we log worker starts elsewhere (at debug level).
=> [chore] log delivery worker stop/start at debug level

internal/media/ffmpeg.go, internal/media/processingemoji.go, internal/media/processingmedia.go
Stops some weird issues with thumbnail generation losing orientation and color data, so far only seen with iPhone-taken images.
=> [bugfix] moves file rename to earlier in media pipeline so ffmpeg calls ALWAYS have a file extension

internal/media/ffmpeg.go, internal/media/manager_test.go, internal/media/processingmedia.go, internal/media/util.go
- takes into account rotation data when generating output thumbnail
- simplifies ffprobe output to only show the fields we actually need
=> [bugfix] take into account rotation when generating thumbnail

internal/federation/federatingprotocol.go, internal/gtsmodel/conversation.go, internal/media/processingmedia.go, internal/typeutils/internaltofrontend.go, internal/util/slices.go, internal/util/slices_test.go, internal/util/unique.go
got bored so decided to add some more useful utility functions. i know we're already doing some of the functionality provided by these in areas of the codebase so in time they can probably be updated to use these.
the advantage of these functions being that they're optimized to minimize number of `append()` type calls which allocate new slice lengths when needed. these functions try to allocate as much up-front as possible.
=> [chore] add some more slice related utility functions + remove duplicates

internal/media/ffmpeg.go
i would link to the ffprobe option for it but there isn't a specific link for `-read_interval` :p
=> [performance] limit ffprobe read time to at most 1s after start of file

internal/media/ffmpeg.go, internal/media/processingmedia.go, internal/media/util.go
>
This pull request updates the code that determines height + width, to take account of rotation data *before* doing any aspect ration calculations etc. 
=> [chore] Take account of rotation data when calculating full size image dimensions

internal/middleware/extraheaders.go, internal/web/robots.go
* Updates our robots.txt with upstream
* Add two headers that a number of AI crawlers respect as an opt-out of their crap
=> [feature] Beef up our AI opt-outs

web/source/css/profile.css
Noticed that it was fairly easy on a profile page with a reasonably long username + domain for the role badge to get lost in x-overflow cutoff. This PR updates our CSS for namerole to become even more compact on smaller screens, giving a higher chance of being able to read everything.
Normal width:
Tablet-ish width:
Phone-ish width:
Really skinny phone-ish width:
=> [chore/frontend] Update namerole rendering on skinny devices

cmd/gotosocial/action/server/server.go, docs/configuration/media.md, example/config.yaml, internal/config/config.go, internal/config/defaults.go, internal/config/helpers.gen.go, test/envparsing.sh
Add config variable for ffmpeg pool size, which dictates the number of ffmpeg and ffprobe instances to put in the instance pool.
=> [chore] Add `media-ffmpeg-pool-size` config var

internal/api/client/streaming/stream.go, internal/api/client/streaming/streaming_test.go
Chrome expects the selected Sec-Websocket-Protocol to be sent back on the WebSocket upgrade request (RFC6455 1.9).
This makes GTS live update on e.g. elk.zone with a Chrome-based browser.
Solution adapted from https://stackoverflow.com/questions/58417479/sec-websocket-protocol-issues
Fixes #2427.
=> [bugfix] send back Sec-Websocket-Protocol header for streaming WebSocket

internal/gtsmodel/mediaattachment.go, internal/media/ffmpeg.go, internal/media/processingmedia.go, web/source/frontend/index.js, web/template/status_attachments.tmpl
>
This pull request updates some of our media parsing logic to use `gifv` instead of `video` as the type label for short, soundless mp4 videos. This is in line with what Mastodon does, and maybe some others, but I haven't checked. The `gifv` type hints to clients that they should show the video as a looping gif, rather than a traditional video.
Also updates the frontend to autoplay gifvs (if prefers-reduced-motion isn't set to reduce), an example can be seen here: https://goblin.technology/@tobi/statuses/01J4EGXESJ7X0801YNE05CWWA6
Please put an x inside each checkbox to indicate …
=> [feature] Use gifv type for short soundless mp4 videos

docs/configuration/database.md, example/config.yaml, internal/config/config.go, internal/config/helpers.gen.go, internal/db/bundb/bundb.go, test/envparsing.sh
For https://github.com/superseriousbusiness/gotosocial/issues/3172
This PR implemented a new field in configuration called `db-url`. This allow user to defined their connection to database using DSN, so they can customize the database behavior as much as they want. For example, they can allow connection to DB with schema using the following URL:
```yaml
db-url: 'postgres://user:pass@localhost/db?search_path=gotosocial'
```
=> handle db-url

internal/messages/messages.go
Updates to use `streams.Serialize()` instead of `interface{ Serialize() (...) }`, the latter of which doesn't include the `@context` field
=> [bugfix] incorrect AP serialize function used serializing worker data

internal/ap/extract.go, internal/api/activitypub/users/userget_test.go, internal/federation/dereferencing/account.go, internal/federation/dereferencing/finger.go, internal/typeutils/astointernal.go, internal/typeutils/astointernal_test.go, internal/util/punycode.go
~~Marking this as draft for now as i'm not 100% sure how i feel about this fix. Both from a fedi API perspective, and the further complication it adds to our horribly complex (and needing refactoring... again) dereferencer.GetAccount() series of functions :p~~
closes #2961
=> [bugfix] relax missing preferred_username, instead using webfingered username

internal/federation/dereferencing/account.go, internal/federation/dereferencing/account_test.go, internal/federation/dereferencing/authenticate.go, internal/processing/workers/fromfediapi.go
A very quick change. It just ensures that on account refresh that the public keys do not change. It ensures that we don't accidentally end up changing the account's public key outside of `AuthenticateFederatedRequest()`.
Though exploring this in more detail, and filling my head once more with the intricasies of AP + http signatures has reminded me how the current implementation only protects against unauthorized GET requests. If a server doesn't sever ties before it goes dark, the domain lapses and someone else sets up a server on that domain, if they set-up a dummy account model that mirrors exactly what we expect (which is possible since there's no signature attached to an account model to verify that the GET request was *responded to* by the expected party), then we may end up sending …
=> [security] harden account update logic

go.mod, go.sum, vendor/codeberg.org/gruf/go-mangler/helpers.go, vendor/codeberg.org/gruf/go-structr/cache.go, vendor/codeberg.org/gruf/go-structr/index.go, vendor/codeberg.org/gruf/go-structr/item.go, vendor/codeberg.org/gruf/go-structr/key.go, vendor/codeberg.org/gruf/go-structr/queue.go, vendor/codeberg.org/gruf/go-structr/queue_ctx.go, vendor/codeberg.org/gruf/go-structr/runtime.go, vendor/modules.txt
Just does some shuffling of the `go-structr` struct fields to optimize memory alignment and minimise memory footprint. May / may not have much of an effect, but hey :p
=> [chore] update go-structr to v0.8.8

go.mod, go.sum, vendor/codeberg.org/gruf/go-fastcopy/copy.go, vendor/modules.txt
Updates go-fastcopy to v1.1.3 which removes reliance on go:linkname
=> [chore] update go-fastcopy to v1.1.3

internal/media/ffmpeg.go
Fixes `invalid orientation data` being returned if the image doesn't actually specify it (which is totally valid to do).
=> [bugfix] permit unspecified orientation data

internal/media/metadata.go, internal/media/probe.go, internal/media/processingemoji.go, internal/media/processingmedia.go
Updates our media pipeline probing logic to rely on Go code where possible for some types (only JPEG at the moment). This reduces the need for calls into WebAssembly which can be costly both in memory and processing-time.
=> [performance] use native Go code to probe JPEGs

web/source/css/base.css, web/source/css/status.css, web/source/settings/components/form/inputs.tsx, web/source/settings/style.css
>
This pull request fixes `<select>` appearance on Gnome Web aka Epiphany, which was rendering them as white blobs before, and also closes https://github.com/superseriousbusiness/gotosocial/issues/3170
=> [bugfix/frontend] Small safari + gnome web fixes

internal/processing/workers/fromfediapi.go
Forgot to actually insert pre-approved interaction requests stemming from the fedi API in https://github.com/superseriousbusiness/gotosocial/pull/3215, good lord.
=> [chore/bugfix] Fix missing insertion of preapproved interaction requests

internal/federation/dereferencing/status.go
>
Lil bugfix for a case where a remote status could be marked as pending approval even after being previously pre-approved.
=> [bugfix] Carry-over `ApprovedByURI` to avoid marking already-approved remote statuses as pending approval

cmd/gotosocial/action/server/server.go, internal/api/metrics/metrics.go, testrig/config.go
>
Update routing to *not* pass our gzip middleware to prometheus http endpoint, but let it do its own compression handling. Because of [this change](https://github.com/superseriousbusiness/gotosocial/pull/3210/files#diff-9b0fbb4e734fd51a74793baf89de863a2d1b56f02a713dd6e145a9a0b9eb79ceR438) in [this PR](https://github.com/superseriousbusiness/gotosocial/pull/3210), prometheus overwrites the `content-encoding` header to `identity` (ie., no compression) even if our gzip middleware compresses the body, which was confusing http clients (understandably). Rather than fighting prometheus …
=> [bugfix] Let prometheus client do its own compression handling

internal/federation/dereferencing/status.go
Further tweak on top of https://github.com/superseriousbusiness/gotosocial/pull/3231 because I realized there are cases where we might not have an `approvedBy` stored, but a remote status has had `approvedBy` added in the meantime, we should use the latter value then.
=> [chore] Tiny tweak to ApprovedByURI

internal/media/ffmpeg.go, internal/media/util.go
>
This pull request wraps access to files by ffmpeg and ffprobe in `allowFiles`, which implements `fs.FS` to allow only select permissions on in and out files.
=> [security] Implement `allowFiles` fs for better isolation of ffmpeg / ffprobe

internal/transport/deliver.go
Tiny chore PR to just close the copy of body used in SignDelivery (which is like 99% sure to be a no-op anyway).
=> [chore] Close copied request body in SignDelivery

internal/db/bundb/account.go, internal/db/bundb/application.go, internal/db/bundb/conversation.go, internal/db/bundb/emoji.go, internal/db/bundb/list.go, internal/db/bundb/media.go, internal/db/bundb/mention.go, internal/db/bundb/notification.go, internal/db/bundb/poll.go, internal/db/bundb/relationship_block.go, internal/db/bundb/relationship_follow.go, internal/db/bundb/relationship_follow_req.go, internal/db/bundb/relationship_mute.go, internal/db/bundb/status.go, internal/db/bundb/statusbookmark.go, internal/db/bundb/statusfave.go, internal/db/bundb/tag.go
>
This pull request updates our load uncached function to avoid making lots of calls that have `WHERE` params like `WHERE id IN (NULL)`, which always return 0 entries.
=> [chore/performance] Avoid unnecessary "uncached" queries

web/assets/themes/brutalist.css
>
This pull request adds a brutal (almost-)black + (almost-)white custom theme.
=> [feature/frontend] Add brutalist b&w theme

internal/db/bundb/bundb.go, internal/db/bundb/conversation.go
>
This pull request addresses an issue we've been having with runaway memory allocations causing stress on the garbage collector. For some reason, deleting temporary tables causes SQLite to flip out and keep allocating memory, which is then immediately cleaned up.
This PR fixes the issue by changing the way we delete temporary tables: for Postgres, we can just use `ON COMMIT DROP`, which causes the temp tables to be cleaned up when the transaction ends. For SQLite, we can adjust the max conn lifetime to 5 minutes to ensure that temp tables get closed when the connection is closed …
=> [bugfix] Fix temp table deletion causing runaway allocations

docs/api/swagger.yaml, internal/api/client/accounts/lists_test.go, internal/api/client/lists/listcreate.go, internal/api/client/lists/listupdate.go, internal/api/model/list.go, internal/db/bundb/migrations/20240903212842_add_exclusive_lists.go, internal/filter/visibility/home_timeline.go, internal/gtsmodel/list.go, internal/processing/list/create.go, internal/processing/list/get.go, internal/processing/list/update.go, internal/processing/workers/fromclientapi_test.go, internal/processing/workers/surfacetimeline.go, internal/typeutils/internaltofrontend.go, testrig/testmodels.go
This pull request implements Hometown-style exclusive lists, compatibly with vanilla Mastodon's current API.
Fixes #2616
=> [feature] Implement exclusive lists

internal/db/bundb/timeline.go, internal/db/bundb/timeline_test.go
>
Follow up to https://github.com/superseriousbusiness/gotosocial/pull/3280
This PR updates the home timeline db query so that entries from exclusive lists are ignored when building up the timeline for the first time. Should address https://github.com/superseriousbusiness/gotosocial/issues/2616#issuecomment-2340861928
=> [bugfix] Update home timeline query to ignore exclusive list entries

internal/typeutils/internaltofrontend.go
This doesn't change within the loop, so there's no point in repeating it. This should make filter processing faster in the common case where a user has more than one applicable filter.
Discovered while investigating #3128
=> [bugfix] Hoist filterable text field extraction out of loop

internal/federation/dereferencing/status.go, internal/federation/dereferencing/status_permitted.go
>
This pull request updates our permissivity checks in the dereferencer to store a pre-rejected interaction request for rejected replies, and to check if a status tries to reply to a previously-rejected reply. This should help to avoid situations where someone replies to a status, their reply is rejected, and then they reply *to their own reply*, which is allowed through, causing all sorts of mess.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3057 as this is the last part.
Please put an x inside each checkbox to indicate that you've read and followed it: `[ ]` …
=> [chore] Reject replies to rejected replies

internal/federation/federatingactor.go, internal/federation/federatingdb/undo.go, internal/typeutils/astointernal.go
>
This pull request does a bit of refactoring of `undo.go` in the federatingdb package, specifically to bring it in line with other more modern files in that package like `reject.go`.
**Thing 1**: Don't return 500 if we just can't get something because we never had it stored. This was happening frequently when Misskey and Friendica instances were sending us Undo's of Likes that we'd never processed, leading to annoying log messages like this: 
```
timestamp="16/09/2024 07:58:45.971" func=server.init.func1.Logger.13.1 level=ERROR latency="39.358876ms" userAgent="Friendica 'Yellow …
```
=> [chore] Refactor federatingDB.Undo, avoid 500 errors on Undo Like

internal/processing/workers/federate.go, internal/typeutils/internaltoas.go
Fix an issue where `id` property was not being set correctly on outgoing Accept + Reject for interactions :facepalm:
=> [bugfix] Ensure id set on outgoing Reject + Accept

internal/federation/federatingdb/accept.go, internal/federation/federatingdb/announce.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/delete.go, internal/federation/federatingdb/exists.go, internal/federation/federatingdb/get.go, internal/federation/federatingdb/move.go, internal/federation/federatingdb/owns.go, internal/federation/federatingdb/reject.go, internal/federation/federatingdb/undo.go, internal/federation/federatingdb/update.go, internal/federation/federatingdb/util.go, internal/log/log.go
also adds some nice new logging functions :3
=> [chore] improved federatingdb logging in cases of unknown iri / types

web/source/css/status.css, web/source/css/thread.css
Couple of cheeky tweaks to status styling:
- Make border to the left of indented statuses a little thicker.
- Put show more / show less button on separate line to avoid funky wrapping issues when the text changes.
=> [chore/frontend] Tweak status styling a little

docs/api/swagger.yaml, internal/api/client/interactionpolicies/updatedefaults.go, internal/api/client/statuses/statuscreate.go, internal/api/client/statuses/statuscreate_test.go, internal/api/model/status.go, internal/processing/status/create.go
>
This pull request implements setting interaction policy on a new status using the `interaction_policy` field.
Also updates the creates status tests, because my god, those were out of date.
=> [feature] Allow users to submit `interaction_policy` on new statuses

internal/middleware/headerfilter.go
Adds contextual error messages to log entries where requests have been blocked due to header filtering. This makes it much easier seeing what exactly is getting blocked specifically by the header filtering system. Also removes the currently unused stats being gathered on header filters, but leaves all the TODO messages / logic in place for integrating it with OTEL in the future.
=> [chore] header filter improvements

internal/cache/db.go, internal/cache/invalidate.go, internal/db/bundb/instance.go, internal/filter/visibility/status.go, internal/httpclient/client.go, internal/processing/common/account.go, internal/processing/common/status.go, internal/processing/status/context.go, internal/processing/workers/surfacetimeline.go
- adds caching for local instance count queries (e.g. statuses, users, known other instances)
- adds improved logging for status context fetching endpoint + consolidates some code
- ensures we don't end up logging ErrHideStatus as errors in the worker timelining code
- removes some unused httpclient code (an error type)
=> [chore] local instance count query caching, improved status context endpoint logging, don't log ErrHideStatus when timelining

internal/api/metrics/metrics.go, internal/api/metrics/no_metrics.go
I realized that the prometheus http server was still getting included in builds even with `nometrics`. This should fix that
=> [chore] add nometrics build tagging to metrics API endpoint

internal/media/ffmpeg.go
For example: https://godforsaken.website/@Shrigglepuss/113178575548564410
This also now supports having multiple video streams each with their own orientation / rotation data, which we accept, as long as all of them match.
=> [bugfix] add support for media with rotation contained in stream side data

internal/workers/workers.go
Given how little they're used, just reduces this number to instead = $GOMAXPROCS. Saves having idle goroutines always sitting around.
=> [chore] reduce number admin process workers

internal/gtserror/error.go, internal/media/util.go, internal/processing/common/media.go
So it turns out that doing an empty read to check for io.EOF only works with *some* readers.  This fixes that! And improves some of the errors we return to API callers when local media limits have been reached.
This is a partial fix for #3362 which encompasses 2 issues.
=> [bugfix] fix media limit reader check

docs/advanced/security/sandboxing.md, example/apparmor/gotosocial
Adds some additional permissions to the example AppArmor profile, to account for access to `/tmp` and `/dev/urandom` required by embedded ffmpeg.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3359
=> [chore] Update apparmor example file

internal/federation/dereferencing/status.go
We weren't carrying over the "PinnedAt" value from statuses when doing refreshes, which was causing pins to get dropped. This fixes that!
Closes https://github.com/superseriousbusiness/gotosocial/issues/3351
=> [bugfix] Carry-over "PinnedAt" when refreshing status

docs/configuration/smtp.md, example/config.yaml
>
Update our email docs to mention STARTTLS explicitly, recommend port 587, link to some handy docs explaining differences between different email ports, and remove the misleading TLS/SSL section.
Relates to https://github.com/superseriousbusiness/gotosocial/issues/3372
=> [docs] Update smtp docs to mention starttls + port 587

testrig/testmodels.go
The intention here should be to initialize a slice with a capacity of diff rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
=> [bugfix] fix slice init length

internal/db/sqlite/driver.go
See: https://www.sqlite.org/lang_analyze.html
In particular:
> The [PRAGMA optimize](https://www.sqlite.org/pragma.html#pragma_optimize) command is usually a no-op but it will occasionally run one or more ANALYZE subcommands on individual tables of the database if doing so will be useful to the query planner. Since SQLite version 3.46.0 (2024-05-23), the "PRAGMA optimize" command automatically limits the scope of ANALYZE subcommands so that the overall "PRAGMA optimize" command completes quickly even on enormous databases. There is no need to use [PRAGMA analysis_limit](https://www.sqlite.org/pragma.html#pragma_analysis_limit). This is the recommended way of running ANALYZE moving forward.
=> [performance] remove the sqlite pragma optimize analysis limit on connection close

docs/api/swagger.yaml, internal/api/model/conversation.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
>
This pull request updates our conversation conversion to include the requester's own account if no other accounts are involved in the convo, in-line with what the Masto API does (though this behavior doesn't seem to be documented afaict).
closes https://github.com/superseriousbusiness/gotosocial/issues/3385
=> [bugfix] Include own account in conversation when no other accounts involved

internal/typeutils/internaltofrontend.go
Check for nil Reply when serializing interaction requests (fix nil pointer when reply has been deleted but interaction request still exists).
=> [bugfix] Account for nil reply when serializing int req

docs/configuration/general.md, example/config.yaml
Puts a really loud warning on the "protocol" config option.
=> [docs] Make `protocol` config option really explicit

internal/federation/federatingactor.go
Check for malformed errors embedded inside error *first*, then check for gtserror.WithCode.
>
This pull request reorders error checking during PostInbox to check for any embedded malformed or actor missing errors *first*, then fall back to any gtserror.WithCode.
This accounts for cases where a malformed is embedded inside an 500 gtserror. In this case we care more about the embedded 400 as this is more informative for the caller.
closes https://github.com/superseriousbusiness/gotosocial/issues/3168
Please put an x inside each checkbox to indicate that you've read and followed it: …
=> [chore] Change order of error checking after PostInbox

docs/api/swagger.yaml, internal/api/client/statuses/statuscreate.go, internal/api/client/statuses/statuscreate_test.go, internal/gtserror/withcode.go
>
This PR updates status validation code to return 501 if a status is submitted using "scheduled_at", instead of just publishing the status as a normal, immediate status. The latter behavior was causing issues with clients: https://github.com/tuskyapp/Tusky/issues/4703
Also does a bit of gentle cleaning up in the status create file.
Relates to https://github.com/superseriousbusiness/gotosocial/issues/1006
If this is a documentation change, only the first checkbox must be filled (you …
=> [bugfix] Return 501 (not implemented) if user tries to schedule post

internal/filter/interaction/interactable.go
>
Fix a bug introduced by interaction policies in 0.17.0-rc1 where it was possible to try to boost a status from an instance that doesn't know about interaction policies, even when status should normally not be boostable. 
=> [bugfix] Only allow boosting post from non-interaction-policy-aware instance if public or unlisted

go.mod, go.sum, internal/media/ffmpeg/runner.go, internal/media/ffmpeg/wasm.go, vendor/codeberg.org/gruf/go-ffmpreg/embed/ffmpeg/lib.go, vendor/codeberg.org/gruf/go-ffmpreg/embed/ffprobe/lib.go, vendor/codeberg.org/gruf/go-ffmpreg/wasm/instance.go, vendor/github.com/tetratelabs/wazero/experimental/memory.go, vendor/github.com/tetratelabs/wazero/internal/descriptor/table.go, vendor/github.com/tetratelabs/wazero/internal/engine/interpreter/interpreter.go, vendor/github.com/tetratelabs/wazero/internal/engine/wazevo/module_engine.go, vendor/github.com/tetratelabs/wazero/internal/sysfs/dirfs_supported.go, vendor/github.com/tetratelabs/wazero/internal/sysfs/file.go, vendor/github.com/tetratelabs/wazero/internal/sysfs/osfile.go, vendor/github.com/tetratelabs/wazero/internal/wasm/engine.go, vendor/github.com/tetratelabs/wazero/internal/wasm/memory.go, vendor/github.com/tetratelabs/wazero/internal/wasm/store.go, vendor/github.com/tetratelabs/wazero/sys/stat.go, vendor/modules.txt
See: https://codeberg.org/gruf/go-ffmpreg/releases/tag/v0.3.1
This rebuilds the ffmpeg / ffprobe binaries with improved performance :)
=> [chore] update go-ffmpreg to v0.3.1

docs/federation/posts.md, internal/ap/activitystreams.go, internal/federation/dereferencing/status.go, internal/federation/dereferencing/status_permitted.go, internal/federation/federatingdb/accept.go, internal/gtsmodel/interaction.go, internal/processing/workers/fromfediapi.go, internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go
>
This pull request updates distribution of Accept activities for interactions on statuses, to send the Accept also to the accepter's followers, and CC it to public as well.
The PR also adds code to process incoming Accepts of interactions that target remote statuses.
The goal here is to ease interoperability with servers that don't yet know about interaction policies and therefore can't append the "approvedBy" field to statuses when sending them out. We can use the receipt of an Accept from an interaction-policy-aware instance to go and dereference the approved status from a …
=> [feature] Distribute Accepts to followers; process Accepts of remote interactions

internal/db/bundb/migrations/20240620074530_interaction_policy.go, internal/db/bundb/migrations/20241011115713_pending_approval_fix.go, internal/processing/status/create.go, internal/typeutils/astointernal.go
Fix an issue with the interaction policy migration where `pending_approval` did not have `NOT NULL` set on it, and write a migration to correct statuses and status_faves. Also ensure that this field is *always* set by adding some logic for it to the type converter.
Note, this PR *doesn't* bother completely undoing and redoing the previous migration by dropping and recreating the statuses  + status faves tables, because I'm not really keen on having folks who've run the RC having to do another massive migration. The `NOT NULL` is not actually that important as long as we remember to set it ourselves anyway.
If this is a documentation change, only the first checkbox must be filled (you can …
=> [bugfix] Ensure `pending_approval` set on statuses + status faves

internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go
Sending accept or reject of Likes on a popular post to all followers is likely to be pretty expensive and cause lots of network requests (similar to what happens now for a popular poll). This change makes it so we only cc Accept or Reject for boosts and replies.
=> [chore] Don't cc Accept of likes to followers

.drone.yml, .goreleaser.yml
Updates goreleaser to v2.3.2 in gotosocial-drone-build v0.6.2, and adds a release notes template and changelog categories to make my life a little bit easier!
=> [chore] Update goreleaser, add release notes template

.drone.yml, .goreleaser.yml, CONTRIBUTING.md
Quick little change to ignore previous RC tags when doing goreleaser releases.
=> [chore] goreleaser - use custom previous tag

.drone.yml, CONTRIBUTING.md
Busybox doesn't recognize `--reverse` in `sort` command, but `-r` works.
=> [chore/bugfix] goreleaser make previous_tag cmd busybox-compatible

.drone.yml, CONTRIBUTING.md
Just updates the goreleaser previous tag thingy to not bother with it during snapshots, as it's not important there, and also to exclude whatever current tag triggered the release, as we don't want to compare a tag to itself :facepalm:
=> [chore] Ensure current tag not set as `GORELEASER_PREVIOUS_TAG`

docs/federation/http_signatures.md
>
This pull request fixes a typo on [this](https://docs.gotosocial.org/en/latest/federation/http_signatures/) page of the documentation.
=> [docs] fix httpsig repo typo

Dockerfile, docs/configuration/index.md, docs/getting_started/installation/container.md, example/docker-compose/docker-compose.yaml, example/gotosocial.service
>
This pull request adds the optional `/gotosocial/.cache` volume in the Dockerfile, and documents usage of `GTS_WAZERO_COMPILATION_CACHE` to set the compilation cache dir, for both Docker and binary deployments (with systemd).
Closes https://github.com/superseriousbusiness/gotosocial/issues/3233
=> [chore/docs] Add `/gotosocial/.cache` to Docker container, document `GTS_WAZERO_COMPILATION_CACHE`

internal/db/bundb/bundb.go
This ensures that we don't cause any possible issues with having multiple connections open without WAL enabled.
=> [feature] for an sqlite database with journal mode != WAL, use maximum of 1 open connection

.goreleaser.yml, README.md, docs/getting_started/releases.md
This PR removes builds for OpenBSD added in https://github.com/superseriousbusiness/gotosocial/pull/3413, as testing on OpenBSD shows too many performance issues for "full" support currently.
Also adds some notes about 32-bit Linuxes (which also run with Wazero's "interpreter" mode) and FreeBSD, which runs in "compiled" mode (nice!) but also reportedly showed some issues with WASM SQLite.
The PR also adds a "supported platforms" table to the README.md with an explanation of which platforms we offer full, partial, and no support for.
=> [chore] Clarify supported platforms, add notes + docs

internal/db/sqlite/driver.go, internal/db/sqlite/driver_moderncsqlite3.go, internal/db/sqlite/errors.go, internal/db/sqlite/errors_moderncsqlite3.go, internal/media/ffmpeg/args.go, internal/media/ffmpeg/exec_nowasm.go, internal/media/ffmpeg/ffmpeg_nowasm.go, internal/media/ffmpeg/ffprobe.go, internal/media/ffmpeg/ffprobe_nowasm.go, internal/media/ffmpeg/runner.go, internal/media/ffmpeg/wasm.go, scripts/build.sh
This adds a `nowasm` build tag that allows building GoToSocial without any WebAssembly modules. This will instead rely on modernc.org/sqlite and locally installed versions of ffmpeg / ffprobe. It prints a warning on server start telling the user not to make any bug reports for media processing issues, and specifically warns them that it may be less secure is it enforces no version checks.
THIS IS AN OFFICIALLY UNSUPPORTED BUILD CONFIGURATION.
This probably needs updating with some improved documentation for this, not specifically to tell people about it, but to emphasise specifically how it is unsupported and we are not interested in bug reports produced by the products of these build changes, since we have no idea what their version of ffmpeg / ffprobe could be compiled with support for …
=> [feature/OFFICIALLY UNSUPPORTED] add nowasm build tag to disable building with WebAssembly

.goreleaser.yml
Should be the last bit of goreleaser changelog generation fuckery, I hope :crossed_fingers:
=> [chore] Hopefully final tweak to changelog generation

internal/db/sqlite/driver.go
this ensures `sql/db` has full access to all the methods available, (which in some cases, maybe not this one, can help improve performance)
=> [chore] updates exported interface types to match ncruces/go-sqlite3/driver types

example/apparmor/gotosocial
Drop the `owner` keyword from paths that we need to access but that are not owned by the gotosocial user.
=> [docs/bugfix] Fix access to /dev and /tmp in AppArmor profile

.gitattributes
* .go files are now tagged with diff=go for better diffs
* go.sum is tagged with generated which suppresses the diff
* go.sum is tagged with merge=ours to reduce merge conflicts
go.mod isn't tagged with generated since it's useful to see it on dependency bump PRs.
=> [chore] Set some additional git attributes

internal/api/client/streaming/stream.go
=> [chore] Fix loop issue in streaming 🤦

internal/db/bundb/filter_test.go, internal/db/bundb/migrations/20240126064004_add_filters.go, internal/db/bundb/migrations/20240126064004_add_filters/filter.go, internal/db/bundb/migrations/20241018151036_filter_unique_fix.go, internal/gtsmodel/filter.go
>
Adds a database migration to rework the unique constraint on filter titles so that it's unique with account id and not just unique full stop.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3445
=> [bugfix] Fix filter title unique constraint

internal/media/ffmpeg.go, internal/media/processingemoji.go, internal/media/processingmedia.go
Fixes an issue where a webm filetype (with correct video codec) without any audio codec might get mistakenly classified as an mkv. Also adds much improved logging in the case of unsupported data types.
=> [bugfix] support classifying correct video codec without audio as webm

docs/configuration/media.md, example/config.yaml, internal/api/client/instance/instancepatch_test.go, internal/config/config.go, internal/config/helpers.gen.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go, test/envparsing.sh
When left unset, defaults to local max size. The reason i didn't actually add local-image-max-size and local-video-max-size is in doing that it potentially opens us up for requiring local-audio-max-size, and potentially any other file types that we separate on in the future. It makes more sense to have a single local max size, and allow tweaking the frontend hinting that applications like Tusky use for autosizing.
It also updates the unused media limits (framerate, image / video dimensions) to just be the maximum possible int sizes. In case Tusky does try to limit based on those since we can support anything under the local max size.
closes #3449
=> [feature] add support for hinting via api/v_/instance preferred image / video max sizes

internal/api/client/accounts/mute.go, internal/api/client/filters/v1/validate.go, internal/api/client/filters/v2/filterpost.go, internal/api/client/filters/v2/filterput.go, internal/api/client/statuses/statuscreate.go, internal/api/util/parseform.go
>
This pull request puts our generous duration parsing (can be either float64 or string) into its own util function, and also ensures that empty form field string is interpreted as infinite duration, which closes https://github.com/superseriousbusiness/gotosocial/issues/3497
=> [bugfix] Fix setting immediate `expires_at` value on filter endpoints

internal/api/client/instance/instancepatch_test.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
=> [bugfix] sets the max value placeholders to MaxInt32 instead of MaxInt

internal/db/bundb/account.go, internal/db/bundb/application.go, internal/db/bundb/conversation.go, internal/db/bundb/emoji.go, internal/db/bundb/filter.go, internal/db/bundb/filterkeyword.go, internal/db/bundb/filterstatus.go, internal/db/bundb/interaction.go, internal/db/bundb/list.go, internal/db/bundb/media.go, internal/db/bundb/mention.go, internal/db/bundb/notification.go, internal/db/bundb/poll.go, internal/db/bundb/relationship_block.go, internal/db/bundb/relationship_follow.go, internal/db/bundb/relationship_follow_req.go, internal/db/bundb/relationship_mute.go, internal/db/bundb/status.go, internal/db/bundb/statusbookmark.go, internal/db/bundb/statusfave.go, internal/db/bundb/tag.go, internal/federation/federatingprotocol.go, internal/gtsmodel/conversation.go, internal/log/log.go, internal/processing/account/alias.go, internal/processing/status/create.go, internal/typeutils/internaltoas.go, internal/util/xslices/slices.go, internal/util/xslices/slices_test.go
- moves slice functions to separate internal/util/xslices package to fix an import cycle
- adds new xslices.AppendJust() and xslices.GrowJust() functions to grow a slice in similar manners to append() and slices.Grow() but ONLY by the necessary number of elements, not any extra as normally happens in those functions typically
- makes use of xslices.AppendJust() and xslices.GrowJust() in our log package
=> [performance] minimise log field allocations

go.mod, vendor/modules.txt
this allows our dependabot to keep notifying us on new library versions, but ultimately they won't do anything until we specifically unpin them by deleting our go.mod "replace" commands.
=> [chore] pin otel library versions

README.md
As a new visitor to the project on GitHub, what I really want to do is click around a server to see how it looks and feels compared with other fediverse implementations. Screenshots are great but not quite enough. I'm not sure whether it's intentional, but it takes a little effort to actually find a link to a real instance.
**Suggested change:** link to the project account near the top of the README
I'm aware that "improve readme!" PRs are a bit of a meme but in this case I'm serious. :)
=> [docs] Include link to a live instance in README

internal/api/client/instance/instancepatch_test.go, internal/db/bundb/instance.go, internal/db/bundb/instance_test.go, internal/typeutils/internaltofrontend_test.go
This pull request fixes a bug where private messages where counted in the public instance statistics potentially leaking dm information such as frequency or timing of dms
closes  #3504
=> [bugfix] post counters should not include direct messages

.drone.yml, .goreleaser.yml, Dockerfile, go.mod, go.sum, internal/db/bundb/bundb.go, internal/media/imaging.go, test/swagger.sh, vendor/github.com/go-swagger/go-swagger/codescan/schema.go, vendor/modules.txt
>
This pull request bumps the following:
- go v1.22 -> v1.23
- golangci-lint v1.57.2 -> v1.62.0 (and gosec linting)
- alpine v3.19.1 ->  v3.20
- gotosocial-drone-build v0.6.0 -> v0.7.0, which includes:
- docker buildx v0.11.2 -> v0.16.2
- goreleaser v1.25.1 -> v2.3.2
=> [chore] Bump tooling versions, bump go -> v1.23.0

internal/api/client/notifications/notificationsget.go, internal/db/bundb/notification.go, internal/db/bundb/notification_test.go, internal/db/notification.go, internal/processing/timeline/notification.go, internal/processing/workers/surfacenotify_test.go
closes #3548 
also updates the account notifications endpoint to use the new paging code :)
=> [bugfix] notification types missing from link header

internal/db/bundb/bundb.go
=> [performance] use new instance of bun.DB *after* migrations to reduce number of in-memory model schema

CONTRIBUTING.md, README.md, docs/faq.md, docs/getting_started/reverse_proxy/websocket.md, docs/locales/zh/faq.md, docs/locales/zh/getting_started/reverse_proxy/websocket.md, docs/locales/zh/repo/CONTRIBUTING.md, docs/locales/zh/repo/README.md, web/template/index_apps.tmpl
As discussed on chat earlier.
Neither Semaphore nor Pinafore are under active development, but Semaphore has archived its repository while Pinafore still gets occasional minor maintenance.
Enafore has newer features, but it has accessibility bugs affecting screen readers that prevent it from being recommended at this time.
Replace all mentions of Semaphore with Pinafore.
I've checked it manually; the new `index_apps.tmpl` is in use on https://hey.hagelb.org if you want to confirm the SVG looks good. Remaining matches for "semaphore" in the code are either comments, or mentioning …
=> Replace Semaphore recommendation with Pinafore.

web/assets/themes/blurple-auto.css, web/assets/themes/brutalist-auto.css, web/assets/themes/solarized-auto.css
Added auto-switching variants for themes that have both light and dark versions (blurple, brutalist, and solarized). These new variants use `prefers-color-scheme` media query to automatically switch between light and dark themes based on user's system preferences, as discussed in #1214 .
Each auto theme defaults to its dark version if `prefers-color-scheme` is not supported by the browser, while brutalist default to `brutalist.css`(the light version).
The auto-switching theme uses import to load the corresponding light/dark version themes. This way, in the future, they'll automatically follow the update, thus barely add any maintenance workload.
If this PR meets expectations and gets merged, the next step is to
- create a light version of the base CSS for GoToSocial
- add a theme switch …
=> [chore/themes] Add auto-switching themes for blurple/brutalist/solarized

.github/ISSUE_TEMPLATE/bug_frontend.yaml
It just came to my notice that GoToSocial uses the `[type/subtype]` style as a prefix for issue titles. Since we have a separate issue template for frontend issues, using a consistent `[bug/frontend]` prefix might help with searching and categorization.
=> [chore] Update frontend bug report issue title prefix

docs/user_guide/posts.md, internal/text/plain_test.go, internal/text/util.go
>
This pull request allows zero-width spaces (breaking and non-breaking) and pipe character to be used as hashtag boundaries, allowing partial-word hashtags.
Closes https://github.com/superseriousbusiness/gotosocial/issues/2489
=> [feature] Allow partial-word hashtags using non-breaking spaces

docs/admin/backup_and_restore.md
>
This pull request updates the documentation for backups using Borgmatic.  The commands for generating storage paths were missing the `--config-path` argument.
closes #3603 
=> [docs] Add missing --config-path arg in backup documentation

go.mod, go.sum, vendor/modules.txt
(this simply rebuilds our ffmpreg binary with the latest wasi-sdk release, nothing too interesting)
=> [chore] bump gruf/go-ffmpreg to v0.6.2

go.mod, go.sum, vendor/modules.txt
this simply rebuilds ffmpreg with latest libvpx and libwebp library versions
=> [chore] bump gruf/go-ffmpreg to v0.6.3

go.mod, go.sum, vendor/modules.txt
see: https://codeberg.org/gruf/go-ffmpreg/releases/tag/v0.6.4
=> [chore] update gruf/go-ffmpreg to v0.6.4

internal/web/about.go, internal/web/confirmemail.go, internal/web/domain-blocklist.go, internal/web/index.go, internal/web/profile.go, internal/web/settings-panel.go, internal/web/signup.go, internal/web/tag.go, internal/web/thread.go, web/template/page_stylesheets.tmpl
closes #3600
After making this modification to `page_stylesheets.tmpl`, all pages mentioned in #3600 can now load `/custom.css`. On the profile page, `/custom.css` still loads before `/@username/custom.css`, and it seems there’s no redundant import for pages like `/about` where `instanceCustomCSSPath` was loaded in `internal/web` beforehand. So I’m not entirely sure if we should remove the reference to `instanceCustomCSSPath` in `internal/web`.
Additionally, the changes in this PR use a hardcoded path for `/custom.css`. When updating `instanceCustomCSSPath` in the future, we'll also need to update the content in `page_stylesheets.tmpl`. Alternatively, we could consider changing `customCSS` to `customCSSPath` in the instance model, which would allow for unified referencing in the Go …
=> [bugfix] Load instance-wide custom css in page stylesheets template

docs/api/swagger.yaml, internal/api/client.go, internal/api/client/announcements/announcements.go, internal/api/client/announcements/announcementsget.go
This implements the [`/api/v1/announcements`](https://docs.joinmastodon.org/methods/announcements/#get) endpoint by simply returning an empty array. This indicates there are no instance announcements.
Some clients retrieve this endpoint and get surprised by a 404. It tends to be harmless, but results in some unnecessary logging when trying to debug other things.
=> [chore] Stub /api/v1/announcements implementation

internal/federation/dereferencing/status.go, internal/typeutils/astointernal.go, internal/typeutils/internaltofrontend.go
- ensures that edited_at is never set for boosts
- adds better handling of the updated_at field for remote statuses
sometime soon i'll make a PR that just drops the updated_at column and instead has an optional edited_at column. though for now this should make it behave a bit better for users currently on main, and the PR for dropping that column and adding a new one will be a monstrous migration that requires iterating the entire statuses table :')
=> [bugfix] small editing tweaks

internal/db/bundb/migrations/20250106165529_cleanup_dropped_edits.go
A migration that fixes the resulting data of a bug introduced with status edits, but fixed in #3636 
This finds all the dropped status edits with a status to relink to and reinserts it back into the status' list of edits.
This shouldn't do anything for anyone that has this migration run on the final release (as they won't have had the bug!), but it will fix up the databases of those running the snapshot currently :)
=> [bugfix] migration to cleanup dropped status edits

docs/configuration/instance.md, example/config.yaml, internal/cache/size.go, internal/db/bundb/migrations/20241022153016_domain_permission_subscriptions/domainpermissionsubscription.go, internal/db/bundb/migrations/20250119112746_domain_perm_sub_caching_tweaks.go, internal/gtsmodel/domainpermissionsubscription.go, internal/subscriptions/domainperms.go, internal/subscriptions/subscriptions_test.go, internal/transport/derefdomainpermlist.go, internal/transport/transport.go, testrig/transportcontroller.go
>
This pull request adds a LastModified column to domain permission subscriptions, which is used to store the `Last-Modified` header (if any) returned from a domain perm subscription fetch. This value is then transmitted as `If-Modified-Since` along with subsequent requests instead of the LastSuccessfulFetch value, as a more reliable way of ensuring that remotes can return 304 if nothing has changed.
(Also adds some docs I forgot to add before to the config.yaml example, oops.)
If …
=> [bugfix] Store LastModified for domain perm subs + send as `If-Modified-Since`

internal/cache/cache.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/db.go, internal/federation/federatingdb/exists.go, internal/federation/federator.go, internal/federation/transport.go
This adds a simple in-memory map that stores the IDs of activities that we have recently created, which allows us to partially implement Exists() and reduce the number of unnecessary calls to Create() during inbox forwarding. Unfortunately we can never return a definite answer in Exists(), since the **activity** JSONLD-ID doesn't necessarily match the stored **object**'s JSONLD-ID, which is the only part that we actually store in a lot of cases. So this provides a best-effort implementation to at least reduce unnecessary calls for recently handled activities.
In the future, I don't think we should strive to "fully" implement Exists(), instead focusing on removing our reliance on the go-fed code for federation logic.
Partially handles #1891
=> [performance] reduce InboxForward->Create calls by partially implementing Exists()

internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go
>
Just add the `published` prop on actors so remote instances know when an account was created. Or at least, when the account claims to have been created.
closes https://github.com/superseriousbusiness/gotosocial/issues/3546
=> [feature] Add `published` property to outgoing AP Actor representations

docs/api/ratelimiting.md, docs/configuration/general.md, docs/configuration/trusted_proxies.md, docs/getting_started/reverse_proxy/index.md, example/docker-compose/docker-compose.yaml, internal/api/util/template.go, mkdocs.yml, web/source/css/page.css, web/template/page_header.tmpl
>
This pull request adds a warning about `trusted-proxies` at the top of every GoToSocial web page if it looks as though the `trusted-proxies` value is incorrectly configured: 
The warning directs users to a new documentation page that provides a tl;dr of setting trusted proxies correctly.
To make this even more foolproof, the docker-compose.yaml file has also been updated to use a network with a specific address, and to trust the gateway of that address by default.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3443
Please put an x inside each checkbox to …
=> [feature] Add warning about `trusted-proxies` to make config easier

docs/federation/actors.md, internal/ap/activitystreams.go, internal/ap/ap_test.go, internal/ap/interfaces.go, internal/api/activitypub/users/inboxpost.go, internal/api/activitypub/users/inboxpost_test.go, internal/federation/federator_test.go, internal/processing/fedi/user.go, internal/processing/workers/federate.go, internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go, internal/typeutils/wrap.go, internal/typeutils/wrap_test.go, testrig/testmodels.go, testrig/transportcontroller.go
>
This pull request updates our account serialization logic to take account of the fact that bot accounts should be served as actor type service, not actor type person, so that remotes can properly mark them as bot.
closes https://github.com/superseriousbusiness/gotosocial/issues/3518
=> [feature] Serve bot accounts over AP as Service instead of Person

web/source/css/status.css, web/template/status_info.tmpl
Very small change to update the frontend templates to include an "edited at" for edited statuses.
=> [feature] show status edits on frontend

docs/api/swagger.yaml, internal/api/client/filters/v1/filterpost.go, internal/api/client/filters/v1/filterput.go, internal/api/client/filters/v2/filterpost.go, internal/api/client/filters/v2/filterput.go
…by moving enum list from the list type to the item type.
Reported by `@modulus:matrix.org` in chat, was small enough to skip opening an issue for.
=> Swagger: fix filter context params

internal/db/bundb/account.go, internal/db/bundb/migrations/20250126162825_top_level_mention_replies_fix.go
>
Update our "exclude_replies" db query for viewing statuses by a given account.
To support this, also drops + recreates `statuses_account_view_idx` with the index columns in the new order.
closes https://github.com/superseriousbusiness/gotosocial/issues/3687
=> [bugfix] Fix top-level posts with a mention being counted as replies when doing `exclude_replies`

cmd/gotosocial/action/server/server.go, docs/configuration/trusted_proxies.md, internal/api/util/template.go, internal/config/config.go, internal/config/gen/gen.go, internal/config/helpers.gen.go, internal/config/validate.go, internal/middleware/ratelimit.go, internal/middleware/ratelimit_test.go, test/envparsing.sh
>
This pull request adds a check to skip injecting the trusted-proxies warning if the clientIP address is in `advanced-rate-limit-exceptions`, to encourage people to add rate limit exceptions for their home networks, and to prevent annoying warnings when accessing one's own instance on one's own network, even though rate limiting is otherwise working correctly.
closes https://github.com/superseriousbusiness/gotosocial/issues/3690
Also updates config to store a parsed slice of exceptions, to avoid re-parsing them multiple times.
Please put an x inside each checkbox to indicate that …
=> [chore] skip `trusted-proxies` warning if ip excepted from rate limiting

internal/federation/authenticate.go, internal/federation/federatingdb/block.go, internal/federation/federatingdb/create.go, internal/federation/federatingdb/create_test.go, internal/federation/federatingdb/db.go, internal/federation/federatingdb/flag.go, internal/federation/federatingdb/follow.go, internal/federation/federatingdb/like.go, internal/federation/federatingdb/move.go, internal/federation/federatingdb/update.go, internal/federation/federatingprotocol.go, internal/federation/federator.go, internal/federation/transport.go, internal/gtserror/withcode.go
This is once again another part to https://github.com/superseriousbusiness/gotosocial/issues/1891.
It moves the type switch out of the federatingDB{}.Create() function and instead handles them as separate functions that we pass in FederatedCallbacks(). Also has some other minor refactoring (no logic changes), and adds some new gtserror functions that should collapse some of our common error wrapping logic down to one-liners.
=> [chore] remove type switch in Create() and instead move to FederatedCallbacks()

docs/api/authentication.md, docs/locales/zh/api/authentication.md
This is a change for GoToSocial's documentation and updates some `curl` command line options.
curl's `-X POST` option is not necessary and even considered bad behavior. Daniel, author of curl, explains why:
https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/
=> [docs] remove `-X POST` from curl commands

internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
=> [bugfix] check boosted account ID when performing usermute checks

internal/text/goldmark_parsers.go, internal/text/markdown_test.go, internal/text/normalize.go, internal/text/plain_test.go, internal/text/util.go
This pull request extends hashtag parsing to handle more non-Latin hashtags correctly.
Fixes #3618
=> Extend parser to handle more non-Latin hashtags

internal/router/router.go
>
Update the router to keep a reference to the letsencrypt server around, so it can be shut down nicely when the "main" server is shut down.
=> [bugfix] shut down LE server nicely

internal/webpush/realsender.go
webpush-go now supports sending `https://` as well as `mailto:` URLs for VAPID sub claims, so we can revert 464d920cfd9d6e362afdbe7ebdbf87f90fb50e0d now and save fetching the instance contact email or making up a dummy email if there wasn't one configured.
Tested on Safari, which was the only browser that cared about whether VAPID sub claims were even correctly formed.
=> [chore] Web Push: Use server URL for VAPID sub claim

internal/typeutils/internaltoas.go, internal/typeutils/internaltoas_test.go
>
This pull request sets the `target` field on outgoing Accepts or Rejects of interactions to the URI of the post that was interacted with, to make things a bit easier for remotes processing Accepts or Rejects.
https://github.com/superseriousbusiness/gotosocial/pull/3703 Should be updated to add this.
=> [chore] Add "target" uri to outgoing Accept + Reject messages

docs/configuration/instance.md, example/config.yaml, internal/api/client/instance/instanceget.go, internal/api/model/instance.go, internal/api/model/instancev1.go, internal/api/model/instancev2.go, internal/config/config.go, internal/config/flags.go, internal/config/helpers.gen.go, internal/processing/fedi/wellknown.go, internal/typeutils/converter.go, internal/typeutils/internaltofrontend.go, test/envparsing.sh
>
Adds a config option `instance-stats-randomize` to randomize user + post stats at `/api/v1|v2/instance` and `/nodeinfo/2.0` endpoints. Does not affect web views. Stats are re-randomized every hour thanks to the ttlcache.
=> [feature] Add `instance-stats-randomize` config option

docs/api/swagger.yaml, internal/api/client/statuses/statuscreate.go
This pull request makes it possible to post media with a generated Swagger client by fixing the param name and format.
It also fixes a similar issue with poll options. There may be other places in the codebase where we forgot to apply `collectionFormat: multi`, so keep an eye out. Without it, with multiple values for a param, you get `foo[]=AAA,BBB` when what a Mastodon-compatible API generally expects is instead `foo[]=AAA&foo[]=BBB`.
`uniqueItems: true` is useful as documentation but I'm not sure that generators actually care about it.
Discovered while working on `slurp`.
=> [bugfix] Swagger: fix media_ids[] param for creating statuses

internal/web/robots.go
>
This pull request mainly disallows the `/nodeinfo/` endpoint for scrapers (since they might already know where to look instead of asking the `/.well-known` endpoint) and those parsing the `/robots.txt` (basically complementing #3718).
=> [chore-adj] disallow /nodeinfo/ explicitly too while we're at it

internal/federation/federatingprotocol.go
Addresses https://github.com/superseriousbusiness/gotosocial/issues/3652 from GoToSocial's side by not panicking on an empty/null/unset `object` property on an incoming activity. I think the other part of the bug still needs to be fixed from Owncast's side but this is a good start :)
=> [bugfix] Don't panic on delivery of Activity with no `object`

internal/media/ffmpeg/exec_nowasm.go, internal/media/ffmpeg/ffmpeg.go, internal/media/ffmpeg/ffmpeg_nowasm.go, internal/media/ffmpeg/ffprobe.go, internal/media/ffmpeg/ffprobe_nowasm.go, internal/media/ffmpeg/wasm.go, scripts/build.sh
This specifically allows building without wasm ffmpeg, but still maintaining wasm sqlite. This may be useful on very memory-constrained devices e.g. routers since the ffmpeg compilation stage can take considerable memory, while still allowing them to use our first-choice in sqlite driver.
=> [feature] add more granularity to nowasm builds

docs/admin/robots.md, docs/api/swagger.yaml, docs/configuration/instance.md, example/config.yaml, internal/api/client/instance/instanceget.go, internal/api/model/well-known.go, internal/api/nodeinfo.go, internal/api/nodeinfo/nodeinfo.go, internal/api/nodeinfo/nodeinfoget.go, internal/config/config.go, internal/config/const.go, internal/config/flags.go, internal/config/helpers.gen.go, internal/config/validate.go, internal/processing/fedi/wellknown.go, internal/typeutils/internaltofrontend.go, internal/web/robots.go, test/envparsing.sh
>
This pull request removes `instance-stats-randomize` and instead adds `instance-stats-mode`, which allows admins to better configure if and how their instance should serve stats.
From the docs:
```yaml
#
#
#
#
#
#
instance-stats-mode: ""
```
In the process I also implemented the 2.1 version of the nodeinfo schema, which adds links for instance repository and instance homepage :) Because what the hell!
Closes https://github.com/superseriousbusiness/gotosocial/issues/3723
If this is a …
=> [feature] Change `instance-stats-randomize` to `instance-stats-mode` with multiple options; implement nodeinfo 2.1

CONTRIBUTING.md, docs/api/swagger.yaml, internal/api/client/admin/accountsgetv2_test.go, internal/api/client/admin/reportsget_test.go, internal/api/client/followrequests/get_test.go, internal/api/client/instance/instancepatch_test.go, internal/api/client/mutes/mutesget_test.go, internal/api/client/reports/reportget_test.go, internal/api/client/reports/reportsget_test.go, internal/api/client/statuses/statushistory_test.go, internal/api/client/statuses/statusmute_test.go, internal/api/model/account.go, internal/processing/stream/notification_test.go, internal/processing/stream/statusupdate_test.go, internal/typeutils/internaltofrontend.go, internal/typeutils/internaltofrontend_test.go
Not directly related to https://github.com/superseriousbusiness/gotosocial/issues/2619, this patch adds the `group` parameter to GoToSocial's account.go model.
The `Account` entity in the [Mastodon Spec](https://docs.joinmastodon.org/entities/Account/#group) was updated in release [3.1.0](https://github.com/mastodon/mastodon/releases/tag/v3.1.0) (February 2020) with a new mandatory parameter - `group` - as part of the feature for adding group actors.
GoToSocial doesn't currently implement the Group feature, but the spec requires the parameter and clients like [Tooty](https://github.com/n1k0/tooty) throw [an error](https://github.com/n1k0/tooty/issues/256) when the parameter isn't present in API responses from GoToSocial.
Tooty is a single-page app promoted on the …
=> [bug] Add missing `group` property to the Account model

web/assets/themes/blurple-light.css, web/assets/themes/brutalist-dark.css, web/assets/themes/midnight-trip.css, web/assets/themes/rain-forest.css, web/assets/themes/soft.css, web/source/css/_colors.css, web/source/css/index.css, web/source/css/profile.css
closes #1214
The PR mainly adds a light mode base color scheme to GoToSocial and enables the color theme to follow the client's `prefers-color-theme` setting.
When selecting the light mode base color scheme, my primary consideration was to maintain the contrast requirements of the original dark mode scheme. This results in some colors appearing darker. In some cases, keeping the same contrast means some colors might become too dark and less noticeable. In such instances, the contrast limits are slightly relaxed, but all contrast requirements remain above 4.5.
Additionally:
1. The gray shades for the background are reduced step by step with consistent offsets and are pure gray.
2. The variables `white1` and `white2` in light mode are actually black (`black[12]`). To reuse existing styles, …
=> [feature/frontend] add light mode color scheme of base css, adapt to prefers-color-scheme

web/source/css/status.css, web/template/status_info.tmpl
Tweak the edited label on web rendering of statuses a bit:
Closes https://github.com/superseriousbusiness/gotosocial/issues/3753
=> [chore/frontend] Tweak display of "edited" in web UI a bit

internal/processing/user/create_test.go, internal/processing/user/user.go, internal/processing/user/user_test.go
>
Lil fix + new test for creating an account by POSTing to the accounts endpoint.
Following command on the testrig:
```bash
curl -H 'content-type: application/json' -H 'authorization: Bearer ZTK1MWMWZDGTMGMXOS0ZY2UXLWI5ZWETMWEZYZZIYTLHMZI4' -d '{"username":"xk063c2xa3insqw3n4nj_sb_persona","email":"xk063c2xa3insqw3n4nj_sb_persona@personas.stringbeanradio.com","password":"20 char long mix of upper lower special and digits","reason":"a long enough explanation of why I am doing api calls","agreement":true,"locale":"en-US"}' localhost:8080/api/v1/accounts
```
Now returns expected …
=> [bugfix] Fix POST to create account endpoint

internal/api/auth/callback.go, web/template/finalize.tmpl
Updates the OIDC callback handler to suggest a lowercase username when registering an account via OIDC, to try to avoid suggesting usernames that aren't valid in any case.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3770
Relates to https://github.com/superseriousbusiness/gotosocial/issues/1813
=> [bugfix] Suggest lowercase username when creating via OIDC

internal/db/bundb/migrations/20241121121623_enum_strings_to_ints.go, internal/db/bundb/migrations/util.go
This improves our shared enum migration function to use a singular update query that handles all possible variations using a CASE statement (thank you for the suggestion @mirabilos !). I probably should have gone with this approach first but our ORM doesn't expose CASE logic so it hadn't initially jumped to mind. The ups-and-downs of ORMs, eh!
I ran this on our test suite (which isn't always the best test of migrations) with both SQLite and Postgres just fine. And I had an old backup of my own database which I was able to use to confirm in a production-like environment that this definitely works on SQLite. Obviously if anyone has an old backup of some Postgres data to test this against feel free to let us know and we can wait for a test on that!
=> [performance] improved enum migrations

docs/api/swagger.yaml, docs/configuration/instance.md, example/config.yaml, internal/api/client/statuses/statuscreate.go, internal/api/client/statuses/statuscreate_test.go, internal/api/model/status.go, internal/config/config.go, internal/config/defaults.go, internal/config/flags.go, internal/config/helpers.gen.go, internal/federation/dereferencing/instance_test.go, internal/gtsmodel/status.go, internal/processing/status/create.go, internal/processing/status/create_test.go, internal/processing/workers/fromclientapi.go, internal/processing/workers/fromclientapi_test.go, test/envparsing.sh, testrig/config.go
This pull request overloads `scheduled_at` to allow creating statuses with creation times and ULIDs backdated to a _previous_ time in `scheduled_at`, with the following caveats:
- Backfilled statuses aren't inserted into home or list timelines on the instance, and don't generate notifications
- Backfilled statuses aren't pushed to other instances through federation (but may be federated normally later through boosts, searches, etc.)
- Backfilled statuses may only mention or reply to the account creating them
- Backfilled statuses can't contain polls
This feature is intended to allow external tools to import statuses from previous instances. The only difference between a backfilled status vs. simply reposting the same text and attachments as the original post is that backfilled statuses …
=> [feature] Implement backfilling statuses thru scheduled_at

internal/db/bundb/migrations/20241121121623_enum_strings_to_ints.go, internal/db/bundb/migrations/util.go
Tested on both sqlite and postgres and it seems to work on both :)
=> [chore/performance] Batch migration queries

internal/db/bundb/poll.go, internal/db/poll.go, internal/federation/federatingdb/create.go, internal/gtsmodel/poll.go, internal/processing/polls/vote.go, internal/processing/workers/fromfediapi.go
Post v0.18.0, we need to handle poll vote deletes (just realised we don't have those...), and handle this same behaviour of multiple separate votes in a multi-choice poll via the client API too.
=> [bugfix] update fedi api to support multiple separate votes in same multi-choice poll

internal/api/robots.go, internal/api/robots/robots.go, internal/api/util/robots.go
Small update to use `no-cache` in the `Cache-Control` header returned from robots.txt, and provide (and parse) an ETag, to ensure crawlers can use the most up-to-date version of the robots.txt file. Relates to the potential caching issue described in https://github.com/fedidb/issues/issues/46.
=> [feature] Use ETag for robots.txt to prevent mishaps

web/source/settings/views/moderation/domain-permissions/excludes/common.tsx
>
This pull request fixes a tiny typo I spotted on the Domain Permissions Excludes page.
"auomatically" is now "automatically"
=> Fix typo in common.tsx

docs/getting_started/installation/container.md
The documentation explains that the release tag is in the format of `vX.Y.Z` for container images. This does not appear to be correct when looking at the image tags in dockerhub. It seems the `v` prefix has been dropped at some point, or was never in place.
=> [docs] correct docker version format

Dockerfile
We were building the swagger docs once in goreleaser and once inside the docker container, not necessary!
=> [chore] Remove duplicate swagger docs build in Dockerfile

web/source/frontend/index.js, web/template/status_info.tmpl, web/template/status_poll.tmpl
>
This PR makes a workaround to display timestamps in the user's local timezone:
Precise timestamps (containing hours and minutes) now converted to user's local time using browser's toLocaleString(), while vague timestamps (e.g. "Dec, 2024") are unchanged
Currently, the `timestampPrecise` in the Template has been removed because there's no need to return the server's local time right now. However, the corresponding field in `template.go` is still retained because I'm not sure if we might need it elsewhere.
~~The time format that users actually use might differ from the originally …
=> [chore/frontend] use localized time string in status & poll info page

web/template/profile.tmpl, web/template/status.tmpl, web/template/status_attributes.tmpl, web/template/status_header.tmpl, web/template/status_info.tmpl
Signed-off-by: Luca Matei Pintilie <luca@lucamatei.com>
Adds microfrontends documentation, as described in #2959
Currently running here as well for easy inspection
https://activitypub.lucamatei.com/@luca
Some notes:
- the main h-card contains the h-feed(s). Maybe unfortunate, but it's
the easy way to get the bio in that h-card
- First gotosocial PR, so I may have missed some stuff.
- I do not believe tests or documentation is necessary for this change,
as it's only markup and hidden from users.
=> [feature] add microformat support

go.mod, go.sum, vendor/modules.txt
see: https://codeberg.org/gruf/go-ffmpreg/releases/tag/v0.6.6
=> [chore] bumps go-ffmpreg to v0.6.6

internal/federation/dereferencing/emoji.go, internal/federation/dereferencing/media.go
Previously when additional info was provided, this was skipped being checked over if the force flag was already set, but we actually need to iterate over this information since the additional info isn't actually later passed anywhere.
This should (hopefully!) fix https://github.com/superseriousbusiness/gotosocial/issues/2851
=> [bugfix] fix refreshed additional media info being ignored

web/template/email_signup_approved.tmpl
I just randomly noticed that the link of the email template (for when one's account got approved) didn't point to the correct section on the main page anymore since that got moved to a separate page. This tiny pull request addresses that.
>
This pull request changes the "Sign-Up Approved" email template to point from gts-instance.example.com#apps to gts-instance.example.com/login#apps since the known-working apps section had been moved to the Login page.
If this is a documentation …
=> [chore] align email template with new, separate /login page

internal/db/bundb/instance.go, internal/db/bundb/migrations/20250310094108_statuses_count_query_optimize.go, internal/db/bundb/timeline.go, internal/db/bundb/timeline_test.go
>
Queries for counting local statuses and for fetching the local timeline have been annoyingly slow lately so I did some optimization. Count and timeline queries can now both use the updated `statuses_local_idx`, which should make things a lot faster.
Tested on both SQLite and Postgres. Postgres doesn't seem to use `statuses_local_idx` for local timeline queries in my testing, as it prefers to use `statuses_public_timeline_idx` and then filter local, but SQLite does, and both drivers use `statuses_local_idx` for the count query.
SQLite:
```
sqlite> CREATE INDEX IF NOT EXISTS …
```
=> [performance] Optimize local timeline + local status count queries

README.md, internal/media/ffmpeg/wasm.go
Also updates the supported platforms section of our README to note that all arm64 CPUs should be supported and that LSE isn't required (since we currently don't rely on threads).
=> [chore] add warning message when wazero compiler not supported

CONTRIBUTING.md
Just updates our contributing.md with better swagger docs command and up-to-date info (ie., don't need to install swagger anymore, as it's vendored).
Closes https://github.com/superseriousbusiness/gotosocial/issues/3893
=> [docs] Update swagger docs command

web/template/profile.tmpl
Just tweaks the "Nothing here!" here message to differentiate between reaching the last page, when paging, and the possibility that the user hasn't written any public posts or hides public posts.
=> [chore] Tweak "nothing here!" message

web/source/css/status.css, web/template/status_info.tmpl
>
Adds a visibility icon + alt text for posts, underlines date published, removes parenthesis around edited at.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3899
=> [feature/frontend] Add visibility icon for posts

internal/db/bundb/migrations/20250318093828_statuses_public_timeline_reindex.go, internal/db/bundb/timeline.go
The public timeline query was getting really slow because we kept adding more query parameters to it without really paying attention to their ordering, or updating index. This fixes that by removing the old index, creating a new index, and putting query parameters in a more deliberate order.
sqlite: 
```
sqlite> explain query plan SELECT "status"."id" FROM "statuses" AS "status" WHERE ("status"."visibility" = 2) AND ("status"."boost_of_id" IS NULL) AND ("status"."pending_approval" = FALSE) AND ("status"."id" < '01JPPWJGNR4568JRJ5ZAZP3RV7') ORDER BY "status"."id" DESC LIMIT 20;
QUERY PLAN
`--SEARCH status USING COVERING INDEX statuses_public_timeline_idx (visibility=? AND boost_of_id=? AND pending_approval=? AND id<?)
```
postgres (as usual it's doing its own thing but it seems fine):
``` …
```
=> [performance] reindex public timeline + tinker with query a bit

internal/cache/cache.go
If the maintenance router couldn't be started, the call to stop caches would trigger a nil pointer exception, masking useful errors.
=> [bugfix] Avoid nil ptr if maintenance router can't be started

internal/subscriptions/domainperms.go, internal/subscriptions/subscriptions_test.go, testrig/transportcontroller.go
I wrote a bug! I fixed the bug! In update statements during adoption obfuscate was being set to nil :facepalm: Which the db rejected ofc. Now it defaults to false properly in UPDATE statements.
Closes https://github.com/superseriousbusiness/gotosocial/issues/3909
=> [bugfix] Fix set obfuscate = null error in adoptPerm

.goreleaser.yml
Adds a bunch more labels to docker build (https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys)
```json
{
[... blah blah blah ...],
"Labels": {
"org.opencontainers.image.authors": "GoToSocial Authors",
"org.opencontainers.image.created": "2025-03-23T10:19:01Z",
"org.opencontainers.image.description": "Fast, fun, small ActivityPub server.",
"org.opencontainers.image.documentation": "https://docs.gotosocial.org/en/latest/getting_started/installation/container/",
"org.opencontainers.image.licenses": "AGPL-3.0-or-later",
"org.opencontainers.image.revision": "b141d93a6aa64f40b18558525ed80ba492b11694",
"org.opencontainers.image.source": "https://github.com/superseriousbusiness/gotosocial",
"org.opencontainers.image.title": "GoToSocial", …
```
=> [chore] Add extra `org.opencontainers.image` labels to docker build

go.mod, go.sum, vendor/modules.txt
this just rebuilds ffmpreg with the latest version of binaryen's wasmopt (web assembly optimizer)
=> [chore] bump ffmpreg to v0.6.7

docs/api/swagger.yaml, internal/api/client/statuses/statusedit.go
The "Edit status" operation is incorrectly listed under `/api/v1/statuses` whereas it actually requires an `{id}` route param.
closes #3910
=> Fix Swagger URL for the "edit status" operation

web/assets/themes/ecks-pee.css
Most browsers just take the second src line and they're fine, but Tor has trouble displaying the woff version on Linux. With two separate lines it doesn't fall back correctly.
closes #3946
Not sure how to add a test to an issue that only shows up in Tor on Linux.
It's CSS only, so these aren't really applicable
=> Fix Atkinson Hyperlegible font embedding on Ecks Pee theme.

internal/email/common.go, internal/util/time.go
Closes https://github.com/superseriousbusiness/gotosocial/issues/3971
=> [bugfix] Change email `Date` header to use RFC2822

web/source/css/_colors.css, web/source/css/_media-wrapper.css, web/source/css/_profile-header.css, web/source/css/base.css, web/source/css/status.css, web/source/frontend/index.js, web/source/settings/components/form/inputs.tsx, web/source/settings/components/status.tsx, web/source/settings/components/username-lozenge.tsx, web/source/settings/lib/form/file.tsx, web/source/settings/style.css, web/source/settings/views/admin/http-header-permissions/overview.tsx, web/source/settings/views/moderation/domain-permissions/drafts/index.tsx, web/source/settings/views/moderation/domain-permissions/excludes/index.tsx, web/source/settings/views/moderation/domain-permissions/form.tsx, web/source/settings/views/moderation/domain-permissions/subscriptions/common.tsx, web/source/settings/views/moderation/reports/search.tsx, web/source/settings/views/user/applications/search.tsx, web/source/settings/views/user/export-import/export.tsx, web/source/settings/views/user/interactions/search.tsx, web/source/settings/views/user/profile/profile.tsx, web/template/login_button.tmpl, web/template/status.tmpl, web/template/status_attachment.tmpl
>
Fixes a couple issues with focused elements not being properly visible. They're now shown clearly when tabbing through.
This isn't *perfect* since there's still some issues with `<details>` not being focusable, but it does work and everything is usable with a keyboard afaict.
~~Still a draft because I need to poke at some other elements as well before I'll be happy with this, particularly media links and content warning `<details>` elements.~~
closes https://github.com/superseriousbusiness/gotosocial/issues/3938
closes https://github.com/superseriousbusiness/gotosocial/issues/393 …
=> [bugfix] Fix a couple accessibility issues with `:focus` elements

web/source/css/_profile-header.css, web/template/profile_header.tmpl, web/template/status_attachment.tmpl
Some little tweaks to the frontend to not set alt text on links, not set title on images, and render header (if set) in a nice clickable photoswipe slide so it can be viewed full size.
=> [chore] render avatar in photoswipe slide, remove repeated alt text

docs/configuration/database.md
On [Postgres Document](https://www.postgresql.org/docs/current/ddl-schemas.html#:~:text=A%20user%20can%20also%20be%20allowed%20to%20create%20objects%20in%20someone%20else's%20schema.%20To%20allow%20that%2C%20the%20CREATE%20privilege%20on%20the%20schema%20needs%20to%20be%20granted.%20In%20databases%20upgraded%20from%20PostgreSQL%2014%20or%20earlier%2C%20everyone%20has%20that%20privilege%20on%20the%20schema%20public.%20Some%20usage%20patterns%20call%20for%20revoking%20that%20privilege:):
> A user can also be allowed to create objects in someone else's schema. To allow that, the CREATE privilege on the schema needs to be granted. In databases upgraded from PostgreSQL 14 or earlier, everyone has that privilege on the schema public. Some [usage …
=> add instruction about postgres permission

docs/advanced/builds/nowasm.md
I think an easy way to know if we have t use the standard or ‘nowasm’ builds would be handy and help people to not use the standard builds on uncompatible hardware
=> [docs] add a command to test the server compatibility with GTS

cmd/gotosocial/action/admin/account/account.go
Every time I reset the password, I assume that something went wrong, because I forget that the server will not pick up on the reset password until it's been restarted according to the docs:
https://docs.gotosocial.org/en/latest/admin/cli/#gotosocial-admin-account-password
A reminder here would help reduce confusion.
=> Remind the user that password resets don't work without restarting.

internal/gtsmodel/status.go
Prevents a possible panic during attempted wipeStatus(). (as i have seen on my own instance a few times)
=> [bugfix] don't panic on non-fully populated status edits

web/source/frontend/index.js, web/template/status_attributes.tmpl
Reuse a formatter as described here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
And fixes a tiny little aria label issue.
=> [chore/performance] Reuse Intl.DateTimeFormat for formatting times

.goreleaser.yml
Skip building and pushing docker containers to `latest` tag when doing prereleases.
=> [chore] Don't push `latest` Docker image on prerelease

internal/api/model/status.go, internal/typeutils/internaltofrontend.go, web/assets/themes/ecks-pee.css, web/assets/themes/midnight-trip.css, web/assets/themes/moonlight-hunt.css, web/assets/themes/soft.css, web/source/css/_media-wrapper.css, web/source/css/status.css, web/source/css/thread.css, web/source/frontend/index.js, web/source/settings/components/status.tsx, web/template/status.tmpl, web/template/status_info.tmpl, web/template/thread.tmpl
This PR revamps the status info bar a bit to unclutter it, which was causing wrapping on small screens and looked a bit poo. Now instead there's a little info thingy that people can tap/click in the bottom right, which will show language, likes, boosts, replies, and edit history. One exception: if a status has replies, the "replies" icon will be shown on the "main" status info bar so that folks can know at a glance whether clicking on a status to open the thread might show them some replies.
Along the way there's a bit of CSS + html tweaking to make the z-indexes more consistent, and remove the "status-link" href that was covering the whole status and causing many a misclick. Instead, you now click on the date specifically to open the status thread.
Some screenshots:
=> [feature/frontend] Hide "engagement" stats, edits, and other info under a little drop down to unclutter status info bar

internal/api/auth/authorize.go, internal/api/auth/revoke.go, internal/api/auth/signin.go, internal/api/model/oauth.go, web/source/settings/lib/query/login/index.ts, web/source/settings/lib/query/user/applications.ts
We weren't properly parsing +-separated scope in url query params at GETs to the /oauth/authorize endpoint. This fixes that with a cheeky strings.ReplaceAll call, so that the endpoint can accept either a space-separated *or* a +-separated `scope` param. Also changes the settings panel to use the proper +-separated scope entry for logging in and requesting tokens for managed applications. *Also* fixes some `validate` versus `binding` tag confusion (a mistake made by yours truly!!).
Closes https://github.com/superseriousbusiness/gotosocial/issues/4023
=> [bugfix] Fix '+'-separated scopes not being recognized

web/template/index_what_is_this.tmpl
Adjust our server picker recommendations list to avoid crawlers and prioritize opt-in / hand-picked lists.
=> [chore/frontend] rejig server picker recommendations

docs/configuration/database.md
the docs don't mention that the `GRANT CREATE ON SCHEMA public TO gotosocial;` command must be run in a posgres shell that's connected to the database, unlike the other setup commands on this page
=> Mention where to run the command to grant CREATE permissions
